### ISSUE TITLE
 increase the max-width of clinical submission modal

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1000]
Currently have to scroll to see whole summary in summary modal 
please increase the max-width of this modal
![image](https://user-images.githubusercontent.com/15824252/72463679-c9048380-37a1-11ea-9076-a3d558157bfd.png)

**Comment by kcullion** [comment]
@ciaranschutte this looks good thanks. we may revisit this to design for lack of horizontal scrollbar
