### ISSUE TITLE
Static UI: Dashboard Donor Data Summary Card

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1019]
big table at bottom 
**Zeplin** https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5deeac22f471a10775935a47 

Scop for static UI is
- layout the table (all headers)
- if double header is too hard to do, we can save that for later
- focus on clinical fields on left

**Comment by wajiha-oicr** [comment]
Zepplin link?

**Comment by rosibaj** [comment]
@wajiha-oicr ticket updated above.  if you have any qyestions about getting started talk to @hlminh2000!

**Comment by wajiha-oicr** [comment]
@rosibaj, I'm wondering about the `Samples` and `Raw Reads` fields...

I see values like '1N' alongside '1T'. Are those paired values, or independent from each other?

**Comment by rosibaj** [comment]
They are independent data pieces, but usually makes sense to present together. the # comes from the clinical system and is a count of normal (N) or Tumour (T) samples.

All table columns are explained here:
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs

**Comment by kcullion** [comment]
@rosibaj as discussed with @wajiha-oicr. At this stage, we will not split the Samples and Raw Reads cells into two cells as it's quite complicated, especially with the column filter being for both portions of the cell.
For now, this is what Wajiha will build, as it communicates the same thing as the cells split into two.
<img width="104" alt="Screen Shot 2020-03-03 at 2 28 35 PM" src="https://user-images.githubusercontent.com/18424138/75811990-6ec47f80-5d5b-11ea-9a5b-4161138f958e.png">

**Comment by rosibaj** [comment]
@wajiha-oicr this looks great! no feedback for now.

**Comment by kcullion** [comment]
looks awesome @wajiha-oicr !

**Comment by wajiha-oicr** [comment]
> looks awesome @wajiha-oicr !

props to you for the lovely looking design !

**Comment by kcullion** [comment]
awe thanks @wajiha-oicr !

**Comment by rosibaj** [comment]
tested on prod - static ui is not visible atm!
