### ISSUE TITLE
Dashboard Architecture, State, & Sequence Diagrams 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1021]
We need to update the technical specifications with the architecture for the dashboard. There are three components to spec out before starting development:
- [ ] **Architecture Diagram**  including ES, The Aggregtor Service (New), Kafka, Clinical, Rollcall, Song, Workflows 
- [ ] **State diagram** to describe the path from the user submitting through the architecture and the different STATE of the system for the user as this goes from action to action 
- [ ] **Sequence Diagram** of data as it gets submitted, updated, and transferred between different services.
some events to consider:
- donor registration 
- clinical data submission 
- song analysis publication 

All of these can be placed on the dashboard wiki:
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-ArchitectureDiagram

**Comment by hlminh2000** [comment]
I've put together one diagram that should capture all the requirements here: https://drive.google.com/open?id=1-AQ4sXN_2YidLw5xxTos9NS8s8n_m2C2 (Accessible with oicr gmail)
