### ISSUE TITLE
🐛 Save Button not being disabled after clicking when editing profile.

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1025]
## Describe the bug
As a DCC Member, once I navigate to any programs profile and make edits the button should be enabled, and when I click Save", the button should go back to disabled. 
Instead, the button does not go back to disabled and I can press it multiple times.
## Steps To Reproduce
Steps to reproduce the behaviour:
1. Navigate to any programs profile.
![image](https://user-images.githubusercontent.com/34698315/73213609-7a9aa180-411e-11ea-8fd6-44b63a733a1b.png)
2. Update/change one of the check boxes in `Processing Regions`
![image](https://user-images.githubusercontent.com/34698315/73213740-b7ff2f00-411e-11ea-9812-2940f10ed301.png)

3. Click "Save",
![image](https://user-images.githubusercontent.com/34698315/73213713-a9187c80-411e-11ea-8f5b-d0510e06f953.png)

4.Click save again and again, watch all the toasts
![image](https://user-images.githubusercontent.com/34698315/73213828-f268cc00-411e-11ea-8e22-6b020d4ebbe9.png)

## Expected behaviour
Once I click "Save", the Save button should be disabled and the program should be successfully updated. until I edit another field.

**Comment by rosibaj** [comment]
tested on QA - it looks like this is working correctly now!
