### ISSUE TITLE
🐛 "errors" in Error Notification is always plural

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1040]
## Describe the bug
Error notifications say "x errors..." even when there is only 1 error, i.e. it will say "1 errors found in..."

## Steps To Reproduce
Submit a .tsv file with a single incorrect field to submit clinical data or register samples.

**Comment by rosibaj** [comment]
@hlminh2000 is this deployed to qa?

**Comment by hlminh2000** [comment]
@rosibaj yes! version 1.8.11 as tagged :)

**Comment by rosibaj** [comment]
lgtm - thanks @P-Saha !!!
