### ISSUE TITLE
Integrate Refresh Token to Platform 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1042]
- [ ]  Make the correct changes to register the correct token initializing patterns in the app. Refresh tokens should last 3 hours, JWT 30 minutes
- [ ] When the JWT is expired, check for the refresh token.  Update the cookie and retry request.  if that fails, then logout.

**Comment by anncatton** [comment]
The polling on program dashboard is going to be modified here https://github.com/icgc-argo/platform-ui/issues/1339 to prevent perpetual refresh
