### ISSUE TITLE
🐛 When validating a submission, if the file is wrong it should take me to its tab

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1044]
## Describe the bug
When validating a submission, if a file or files are wrong it should take me to the first incorrect file's tab, similar to how upload file works. Currently, I stay on the current file tab I was on when I pressed validate.

## Steps To Reproduce
Navigate to a program
Register samples for that program
Navigate to program's submit clinical data page
Click on a file tab that you will not submit data for
Submit a file that has correct schema but does not follow constraints, eg. a donor that hasn't been registered, this file should not be one that you are on the tab for currently.

## Expected behaviour
I should be taken to the tab that has the first incorrect file, i.e. if Follow Up has an error I should be taken to it's tab, or a different tab that has an error.

**Comment by kcullion** [comment]
@rosibaj I tested this, looks good to me!
