### ISSUE TITLE
Register Samples table: start the rows at #2 like in clinical

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1047]
To be consistent with clinical submission, let's renumber these starting at 2 too.
![Screen Shot 2020-01-29 at 1.37.56 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/e2235897-13ff-4262-aa77-9c8cbfed3e0f)

**Comment by kcullion** [comment]
@rosibaj to be more clear, should we do what we do in the error table, and name this column to "Line #" instead of just #? (in register samples and clinical submission tables)
I know it's longer, but it's clearer that it's a file line number reference. 
<img width="270" alt="Screen Shot 2020-01-30 at 11 45 28 AM" src="https://user-images.githubusercontent.com/18424138/73470556-119d6e80-4356-11ea-955b-f2f7259a4a41.png">

**Comment by rosibaj** [comment]
@hlminh2000 Can you also rename based on @kcullion suggestion and let us see how much it impacts the ui?

**Comment by rosibaj** [comment]
Tested in qa environment
- line numbers now starts at 2
- header has been renamed to Line #

Thanks for the work @hlminh2000 !!
