### ISSUE TITLE
🐛 bugs for clinical submission updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1048]
## Describe the bug
Clinical submission section: I upload, validate, sign off some clinical files. But then when I upload those exact files again, I see that they have updates to be approved. I haven't updated any data.
![Screen Shot 2020-01-29 at 2 17 33 PM](https://user-images.githubusercontent.com/18424138/73389426-202a4e00-42a2-11ea-85c0-de43ac6cd304.png)

- [ ] I also noticed when I did change a donor from alive to dead and added the cause_of_death value, it says the old value and new value are the same.

<img width="1060" alt="Screen Shot 2020-01-29 at 3 06 56 PM" src="https://user-images.githubusercontent.com/18424138/73393052-02acb280-42a9-11ea-961c-caba6437dc15.png">

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to Clinical submission section
2. Upload files, validate and sign off (no updates)
3. Now try to upload those exact same files again - I get that I've made updates to data
4. The submission will need to be approved by DCC but it's not necessary

## Expected behaviour
When I upload those exact files, I should see the grey star for each row as there has been no updates. Also the updates should appear correctly (the blank values should not register as updates)

**Comment by blabadi** [comment]
note: This is a backend issue, the PR is in argo-clinical
