### ISSUE TITLE
Error text changes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1049]
- [ ] Please change this wording to "# new registered sample(s) "
![Screen Shot 2020-01-29 at 2 27 19 PM](https://user-images.githubusercontent.com/18424138/73390843-ea3a9900-42a4-11ea-9146-7077f02bb7b4.png)

**Comment by wajiha-oicr** [comment]
@kcullion , alternatively, we can make the word alternate between `have` and `has`. There's already logic in place that makes the the word alternative between `sample` or `samples` when just 1 was registered, so extending that that would be easy.

Let me know what you think!

**Comment by kcullion** [comment]
@wajiha-oicr thanks for pointing that out. I think @rosibaj and I compared it to another toast message and that's how we did that one. So we can keep it general like the ticket states.

**Comment by wajiha-oicr** [comment]
So it should **always** say `# new registered sample(s)` right?

The ticket says "for when a user just registers just 1", but the text kind of insinuates it's a message for all cases.

**Comment by kcullion** [comment]
@wajiha-oicr yes that's right. So it could be 
1 new registered sample(s)
3 new registered sample(s)

in your description above does that mean you can add or remove the s at the end?
like 
1 new registered sample
3 new registered samples

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr yes that's right. So it could be
> 1 new registered sample(s)
> 3 new registered sample(s)
> 
> in your description above does that mean you can add or remove the s at the end?
> like
> 1 new registered sample
> 3 new registered samples

@kcullion, yup the plural/ singular case can easily be applied conditionally.

So I'll change the message to not end with `(s)` and instead apply the `s` to the word `sample` conditionally, as you have it written

**Comment by kcullion** [comment]
@wajiha-oicr that'd be great thanks!
So 
1 new registered sample
3 new registered samples

**Comment by kcullion** [comment]
looks great to me on QA. Thanks @wajiha-oicr !

**Comment by rosibaj** [comment]
verified on prod - lgtm
