### ISSUE TITLE
🐛 Toast bug: submission sign off without updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1051]
## Describe the bug
When I submit clinical data, and sign off the submission, the toast quickly flashes on screen then the user is redirected to the dashboard (without the toast)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to Clinical Submission
2. Upload files 
3. Validate and Sign off
4. See the toast flash then redirect to the dashboard

## Expected behaviour
This confirmation should work as it does for registering samples. I can't even read the success toast.  The order should be:
1. Go to Clinical Submission
2. Upload files 
3. Validate and Sign off
3. See the dna loader
4. redirect to dashboard and see toast

**Comment by rosibaj** [comment]
@kcullion do you mind testing this one please?

**Comment by kcullion** [comment]
@rosibaj @wajiha-oicr this works for me! well done
