### ISSUE TITLE
🐛 Modal issues in add user

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1054]
![image](https://user-images.githubusercontent.com/15824252/73398885-448f2600-42b4-11ea-91ac-1ddc58af713d.png)

## Expected behaviour
The dropdown should drop below the edge of the modal, and should not cause a scrollbar to appear.

## Solution 
fix the modal height to be a little latter or fix the modal overflow.

**Comment by rosibaj** [comment]
Noticed a couple more issues:

- [ ] The dropdown does not close when i click away.
![image](https://user-images.githubusercontent.com/15824252/73715697-d77bf600-46e2-11ea-9e66-27179f8e9d8a.png)

- [ ] On a smaller screen, when I add more users the modal should scroll, and always have the buttons visible (cc @kcullion pls add any more details)

**Comment by kcullion** [comment]
@rosibaj yes I think the modal needs to be scrollable so the user can access the bottom buttons. We can fix them and create a fixed height for the modal, or we can just allow the user to scroll the full modal.

I saw something else - should we add to another ticket?

I tried adding 4 users (different names, different roles, but same email address).
The success notices says this, but it only added one of my users

![Screen Shot 2020-02-04 at 11 02 14 AM](https://user-images.githubusercontent.com/18424138/73762364-1be8af80-473e-11ea-8bbe-f73cd6db3efa.png)

**Comment by P-Saha** [comment]
The issue with the dropdown not closing occurs with every <Select> Tag in the code. This for example also occurs when creating a program and clicking the choose role drop down and clicking away. Will lump that in within this ticket's scope.

**Comment by rosibaj** [comment]
Still seeing a couple issues: 
![image](https://user-images.githubusercontent.com/15824252/75073536-a0ba2400-54c7-11ea-9702-f65b2eacfd8b.png)

**Comment by P-Saha** [comment]
This is a more difficult issue to fix than it seems. Should be made into a new ticket at the recommendation of @hlminh2000.

**Comment by rosibaj** [comment]
thanks @P-Saha I will make into a new ticket - we can close this one for now then.
