### ISSUE TITLE
File order - Clinical tab, dictionary, or elsewhere

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1055]
The order that files are displayed in should be consistent across all sites.  For example, this is the order in the clinical submission system right now, but that order is not correct. 
![Screen Shot 2020-01-29 at 4 37 41 PM](https://user-images.githubusercontent.com/18424138/73399773-d8152680-42b5-11ea-8dd0-955041cfd661.png)
The order of files should be as follows: 
- Donor
- Specimen
- Primary Diagnosis 
- Treatment
- Chemotherapy
- Hormone Therapy
- Radiation
- Follow Up

The places that this order are seen should all be consistent:
- [x] Data dictionary table view
- [x] Clinical Submissions tabs 
- [x] Template dropdown (dictionary and submission pages)

**Comment by rosibaj** [comment]
lgtm thanks @anncatton
