### ISSUE TITLE
🐛 Icons in  disabled button state should be white, not colored. 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1065]
## Describe the bug
Icons in  disabled button state should be white, not colored. 
![image](https://user-images.githubusercontent.com/15824252/73564258-2a2c8800-442d-11ea-9ee2-7202542a2968.png)

## Steps To Reproduce
1. disable the submission system using the lock config
2. look at the upload button on https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/PRE-PAN-GB/clinical-submission?tab=hormone_therapy

**Comment by wajiha-oicr** [comment]
@rosibaj  any idea how to get to this state in dev/qa?

I was able to confirm the change locally by spoofing the disabled state, but in dev I can't quite get any program in the 'locked submission' state.

**Comment by rosibaj** [comment]
@wajiha-oicr yes, there is an endpoint in clinical to do this: 
```
curl --location --request PATCH '{{CLINICAL_URL}}/submission/configs/submission-disabled' \
--header 'Content-Type: application/json' \
--data-raw '{
  "submissionDisabled": true
}'
```

https://clinical.dev.argo.cancercollaboratory.org/api-docs/#/Submission%20Configurations/patch_submission_configs_submission_disabled

**Comment by rosibaj** [comment]
@wajiha-oicr was this deployed to QA environment?  I still see this:
![image](https://user-images.githubusercontent.com/15824252/75070466-3e5e2500-54c1-11ea-970a-4aff2cc0a5e6.png)

**Comment by wajiha-oicr** [comment]
Oh sorry. I didn't realize it but I think the deploy to QA went south. I'll move the ticket back!

**Comment by wajiha-oicr** [comment]
@rosibaj re-ran the deploy and the change should be there now!

**Comment by rosibaj** [comment]
@wajiha-oicr still seeing the same thing:
![image](https://user-images.githubusercontent.com/15824252/75168212-8618c280-56f4-11ea-8ab0-bddbf118d419.png)

**Comment by rosibaj** [comment]
@wajiha-oicr i see the issue - it is still happening on the `sample registration` page, but NOT on the `clinical submission` page

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr i see the issue - it is still happening on the `sample registration` page, but NOT on the `clinical submission` page

Ahh okay, I didn't realize it was for both buttons! I'll put up another PR for the other button too.

**Comment by wajiha-oicr** [comment]
@rosibaj besides submit clinical data and register samples, is there anywhere else this change needs to go?

**Comment by rosibaj** [comment]
@wajiha-oicr nope! just that spot.

**Comment by rosibaj** [comment]
this looks great thanks @wajiha-oicr !
