### ISSUE TITLE
🐛 Edit user, clicking the same role enables save button.

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1067]
## Describe the bug
When I edit a user and click the drop down and select the same role as the user was previously, this enables the save button even though nothing has changed.

## Steps To Reproduce
Go to manage program
Go to edit user modal
Click role dropdown and select the same role as previously

**Comment by rosibaj** [comment]
tested on qa- is working as expected now.  Thanks @anncatton !!
