### ISSUE TITLE
🐛 Click Program link from program page - flash on page

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1068]
## Describe the bug
From the program page: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program
When I click on a program name it takes me to the dashboard, then I see the loader flash quickly. 

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program
2. Click on a program name link
3. See a flash on the page

## Expected behaviour
I think it's trying to use the loader like the other links on this page (manage user and manage program icons) but it's not implemented fully. There should be no flash, but rather the usual dna loader.

**Comment by rosibaj** [comment]
flash is fixed now thanks @wajiha-oicr !
