### ISSUE TITLE
Update links for Documentation and DACO access

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1069]
We have the url for the docs site: https://docs.icgc-argo.org/
Please update the following links (using the link component):

**Beta landing page callout**
- [x] "manage a program" links to: https://docs.icgc-argo.org/docs/managing-program-access/
- [x] "register samples" links to: https://docs.icgc-argo.org/docs/registering-samples
- [x] "submit clinical data" links to: https://docs.icgc-argo.org/docs/submitting-clinical-data

**Footer**
- [x] Link "Documentation" to https://docs.icgc-argo.org/
![Screen Shot 2020-02-04 at 11 34 05 AM](https://user-images.githubusercontent.com/18424138/73765252-46d50280-4742-11ea-9fcf-e62f7de05423.png)

**Email invite:** 
- [x] open email in browser link should open the html email in the browser
- [x] "DACO approval" should link to: https://icgc.org/daco
- [x] "check out our documentation" in body copy link to: https://docs.icgc-argo.org/
- [x] "The ARGO Data Platform team" should link to https://platform.icgc-argo.org/
- [x] Email footer: "Contact" should link to: https://platform.icgc-argo.org/contact
- [x] Email footer: "Documentation" should link to: https://docs.icgc-argo.org/
- [x] Email footer: "Privacy Policy" should link to:  https://platform.icgc-argo.org/privacy 
![Screen Shot 2020-02-04 at 11 48 18 AM](https://user-images.githubusercontent.com/18424138/73766607-4178b780-4744-11ea-92ac-f312e61bcade.png)

**Program Dashboard Links**
**Empty state**
- [x] Completed Core Clinical Data empty card - link to https://docs.icgc-argo.org/docs/submitting-clinical-data  
- [x] Molecular Data Summary empty card - link to https://docs.icgc-argo.org/docs/submitting-molecular-data  
- [x] Donor Data Summary empty card - link to https://docs.icgc-argo.org/docs/submitted-data 
- [x] HELP link on right side of titlebar: https://docs.icgc-argo.org/docs/submitted-data
![Screen Shot 2020-02-04 at 2 14 58 PM](https://user-images.githubusercontent.com/18424138/73778205-ce2d7080-4758-11ea-8b7c-6a7b1518e46e.png)

**Register samples links**
- [x] In step one the "Data Dictionary" link should go to https://docs.icgc-argo.org/dictionary
![Screen Shot 2020-02-04 at 11 50 45 AM](https://user-images.githubusercontent.com/18424138/73766930-bba93c00-4744-11ea-8334-be8be3117df9.png)
- [x] HELP link in top right titlebar should link to https://docs.icgc-argo.org/docs/registering-samples 

**Submit Clinical Data links**
- [x] In step one the words "Data Dictionary" SHOULD BE A LINK, and should go to https://docs.icgc-argo.org/dictionary
![Screen Shot 2020-02-04 at 11 57 37 AM](https://user-images.githubusercontent.com/18424138/73767590-a54fb000-4745-11ea-9268-1f7d268aba41.png)
- [x] HELP link SHOULD BE ADDED in the right of the titlebar, and should link to https://docs.icgc-argo.org/docs/submitting-clinical-data 
![Screen Shot 2020-02-04 at 11 59 26 AM](https://user-images.githubusercontent.com/18424138/73767783-ea73e200-4745-11ea-8a80-ddce1e572432.png)

**User Profile page**
- [x] Token card: link "HOW TO USE YOUR TOKEN WITH ICGC ARGO TOOLS ›" to https://docs.icgc-argo.org/docs/user-profile-and-api-token
- [x] When user has no daco access "Apply for DACO access" should link to: https://icgc.org/daco
![Screen Shot 2020-02-04 at 12 16 40 PM](https://user-images.githubusercontent.com/18424138/73769215-48092e00-4748-11ea-9256-45a6e5dc251c.png)

**401 and 404 pages**
- [x] "Documentation" should link to  https://docs.icgc-argo.org/ and "Home" should link to the landing page
example
![Screen Shot 2020-02-04 at 12 20 14 PM](https://user-images.githubusercontent.com/18424138/73769504-c49c0c80-4748-11ea-807e-84c19f589f6a.png)

**Maintenance page**
- [x] "Contact Us" should link to  /contact and "Home" should link to the landing page
![Screen Shot 2020-02-27 at 4 18 45 PM](https://user-images.githubusercontent.com/18424138/75487716-f46fb600-597c-11ea-9372-c92431028f40.png)

**Notifications** 
- [x] Welcome to program notification: 3 Links 
Data submission:https://docs.icgc-argo.org/docs/submission-overview
Data Access:https://docs.icgc-argo.org/docs/managing-program-access
Program Management: https://docs.icgc-argo.org/docs/data-access
![Screen Shot 2020-02-24 at 5 23 16 PM](https://user-images.githubusercontent.com/18424138/75196646-6dc39a80-572a-11ea-8d1e-3e2bf3d4e8de.png)

- [x] Registration success - link "Contact DCC" to /contact page
![Screen Shot 2020-02-04 at 12 09 15 PM](https://user-images.githubusercontent.com/18424138/73768583-41c68200-4747-11ea-8686-7536892ac451.png)

**Contact Page**

- [x] For the first two sections, please copy the same content and links from the docs landing page: https://docs.icgc-argo.org/ 

![Screen Shot 2020-02-24 at 5 20 15 PM](https://user-images.githubusercontent.com/18424138/75196468-06a5e600-572a-11ea-8f77-e77f2ef12d85.png)

![Screen Shot 2020-02-24 at 5 16 43 PM](https://user-images.githubusercontent.com/18424138/75196200-81223600-5729-11ea-8eab-9c0083d4a3e0.png)

**Comment by rosibaj** [comment]
Add all ids links here as well for future testing : https://github.com/icgc-argo/e2e-test/issues/32

**Comment by akachru-github** [comment]
@P-Saha , this ticket is now a requirement for beta next week. Let's remain focused on this before any other work. We will attempt to promote as a hotfix to production.

**Comment by P-Saha** [comment]
@akachru-github Understood!

**Comment by P-Saha** [comment]
@kcullion Do we want to open any links on a new page rather than on the same page for any of these links?

**Comment by kcullion** [comment]
@P-Saha yes let's open the links to the external sites (daco or docs site) in a new window. For any internal links (like the contact us links) just open within the same window.  Make sense?

**Comment by P-Saha** [comment]
@kcullion Sounds good!

**Comment by kcullion** [comment]
@P-Saha to fix:
- [ ] all links should be using the default style from the UI kit (eg. maintenance page)
- [ ] Documentation link in footer can open in a new window to be consistent with the other docs links

**Comment by kcullion** [comment]
looks great @P-Saha thanks!

**Comment by kcullion** [comment]
looks good in prod!
