### ISSUE TITLE
🐛 DACO access is not correct on production 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1071]
![image](https://user-images.githubusercontent.com/15824252/73765452-8f8cbb80-4742-11ea-8e23-eb8130148659.png)

- the groups were renamed in prod:
{
  "limit": 20,
  "offset": 0,
  "count": 2,
  "resultSet": [
    {
      "id": "-------",
      "name": "DACO-CLOUD",
      "description": null,
      "status": "APPROVED"
    },
    {
      "id": "-------b",
      "name": "DACO",
      "description": null,
      "status": "APPROVED"
    }
  ]
}

**Comment by rosibaj** [comment]
- check gateway first to make sure information is returned correctly 
- if it is the gateway, then check the caching first 
- if not those, then have fun finding it!

**Comment by anncatton** [comment]
Checked with @joneubank, this works for his account on prod. Can you retest @rosibaj with your daco-approved account?

**Comment by joneubank** [comment]
Checking the code/logic it seems like it should work correctly as is. Need confirmation that this is still an issue and a way to reproduce.

**Comment by anncatton** [comment]
Display was failing due to a groups request to ego that was admin-scoped. Will add a DACO-specific permission instead of relying on groups.

**Comment by rosibaj** [comment]
Tested on QA - i made my user (rosi.bajari) which is in DACO group USER in ego.  I was able to successfully login to the QA platform and see the green checkmark on DACO access. 

lgtm @anncatton !

**Comment by rosibaj** [comment]
Tested on production - my DACO access is now correctly visible on the production environment for accounts with/without DACO access..
