### ISSUE TITLE
🐛 Toast disappears immediately when redirected to program dashboard after clinical submission signoff

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1079]
## Describe the bug
When signing off on clinical submission with no updates, the toast appears and then immediately disappears when getting redirected to the dashboard.

## Steps To Reproduce
Sign off clinical data with no updates.

## Expected behaviour
Toasts should persist above page switching. (preferred)
OR 
Toast should pop in after getting redirected to program dashboard.

**Comment by rosibaj** [comment]
Verified on dev environment - this bug is no longer happening 

https://drive.google.com/file/d/1tRmbpGPrH5lBkgywzqSaX-xrjMTkLoeJ/view
