### ISSUE TITLE
🐛 Clinical Submission progress bar goes off the page.

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-ui#1080]
## Describe the bug
See photo
<img width="383" alt="Screen Shot 2020-02-07 at 10 54 34 AM" src="https://user-images.githubusercontent.com/19506039/74044749-92cdb480-4999-11ea-85af-381c6d7f431b.png">

## Steps To Reproduce
Go to dashboard while having clinical submission pending approval.
- @kcullion has a mockup - the bar title spans two lines always so there's more room for the progress bars 
- fix the font size and the size of the progress bar according to the zeplin https://zpl.io/V4dd110

**Comment by rosibaj** [comment]
@kcullion i also think maybe this was fixed - could you reverify this one?

**Comment by kcullion** [comment]
@rosibaj yep! I think this was fixed as part of another ticket

**Comment by rosibaj** [comment]
amazing thanks!
