### ISSUE TITLE
Landing page updates for Beta Testing

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1082]
- [ ] Add a warning to the page to notify this is closed for beta testing
- [ ] Revise the title of the page to "Welcome to the ICGC ARGO Data Platform"
- [ ] Revise the copy in the "Get started with Data Submission" callout so it's geared towards Beta testers

zeplin:https://zpl.io/V11k0G4

![Screen Shot 2020-02-11 at 4 44 05 PM](https://user-images.githubusercontent.com/18424138/74282206-bec89d00-4ced-11ea-9335-7b81b0668ab9.png)

**Comment by P-Saha** [comment]
@kcullion Should I keep the old changes commented for use after beta testing is over?

**Comment by kcullion** [comment]
@P-Saha I think it's ok to remove. We will have to change this landing page soon anyway. Thanks!

**Comment by kcullion** [comment]
As discussed with @P-Saha 
1. please include the urls for the documentation links within the callout
2. move the banner up 20px so it doesn't cover the logo on a laptop resolution

![](https://files.slack.com/files-pri/T033B0H01-FU41ZRA8J/screen_shot_2020-02-25_at_4.09.08_pm.png)

**Comment by hlminh2000** [comment]
@kcullion @rosibaj we quite a few links scattered around that need to be hooked up. I believe we have a ticket for that, can you confirm? This isn't really part of this ticket's scope...

**Comment by kcullion** [comment]
@hlminh2000 yes we do: https://github.com/icgc-argo/platform-ui/issues/1069
@P-Saha  was in there so thought it would be easiest if he just did that update at the same time. Let me know if I need to add this to the other ticket

**Comment by hlminh2000** [comment]
Some of the work for the links isn't page specific so it's easier to keep track separately to avoid blocking this ticket :)

sorry I didn't notice the original ticket scope earlier when you asked @kcullion

**Comment by kcullion** [comment]
thanks @hlminh2000 - I think Priyonto said he made the changes
