### ISSUE TITLE
API key not showing in UI

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#1108]
On the `/user` page, the API key is not showing even though it's available.
How do we know it's available? The following query from the page is returning data fine:
```
query PROFILE {
  self {
    isDacoApproved
    apiKey {
      exp
      error
      key
      __typename
    }
    __typename
  }
}
```
![Screen Shot 2020-02-24 at 10.48.51 AM.png](https://images.zenhubusercontent.com/5a69f6494b5806bc2bc447b7/30bc3764-f2d1-4bff-af13-b534861ac7f6)

## Expected behaviour
The token should show when you generate a new one, refresh the page, or login.

**Comment by kcullion** [comment]
@anncatton this looks good to me. @rosibaj I'll keep it in this column for you to test too

**Comment by kcullion** [comment]
tested in prod, looks good!

**Comment by rosibaj** [comment]
tested in prod can see the token all the tiem now.  lgtm thanks @anncatton !
