### ISSUE TITLE
Collaborators: remove links to register and submit data

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1110]
Can we remove the links for this card **ONLY for collaborators**? Since they don't have access to those sections, the links lead to the error page. 

![Screen Shot 2020-02-24 at 11 25 06 AM](https://user-images.githubusercontent.com/18424138/75170588-57045000-56f8-11ea-8ff8-75ce84bfd4df.png)

Then when I click "reload this page" from that error page I am taken to an "Internal Server Error" page and can't use the back button. 
![Screen Shot 2020-02-24 at 11 25 37 AM](https://user-images.githubusercontent.com/18424138/75170635-66839900-56f8-11ea-8be9-d0277a08a279.png)

**Comment by kcullion** [comment]
@wajiha-oicr yes, basically the card would not link anywhere for Collaborators because they can't submit or register data...so it would look like this:
<img width="387" alt="Screen Shot 2020-02-28 at 9 04 58 AM" src="https://user-images.githubusercontent.com/18424138/75555055-82917e00-5a09-11ea-9d86-ac3121fca76f.png">

**Comment by wajiha-oicr** [comment]
@kcullion Do you know how can I make an account with collaborator status? I'd like to be able to test this in dev, but my account isn't a collaborator.

**Comment by kcullion** [comment]
@wajiha-oicr yes you can, just go a a program, add user - and specify your role as "collaborator" in the user form

**Comment by wajiha-oicr** [comment]
and an email should be sent out if you do that? I tried adding collaborator users but I'm not seeming to get invitation emails in my inbox

**Comment by kcullion** [comment]
@wajiha-oicr you may still have to go through mailhog to access the email and click the join button. I'll slack you

**Comment by kcullion** [comment]
@wajiha-oicr the link removal is working. But I noticed, when I have a registration/submission in progress I see it within the data submitter role but not the collaborator role.
Data submitter
<img width="722" alt="Screen Shot 2020-03-04 at 8 19 48 AM" src="https://user-images.githubusercontent.com/18424138/75883623-4c7d4100-5df1-11ea-8a36-374e8084275c.png">

Collaborator
<img width="424" alt="Screen Shot 2020-03-04 at 8 19 09 AM" src="https://user-images.githubusercontent.com/18424138/75883639-543ce580-5df1-11ea-8ea9-3850e81979e3.png">

**Comment by wajiha-oicr** [comment]
@kcullion that might be its own separate issue. the link is quite separate from the data that feeds into those progress bars.

**Comment by kcullion** [comment]
@wajiha-oicr that's what I was going to ask. I'll make a separate issue and move this one. Thanks

**Comment by kcullion** [comment]
tested in production, looks good!

**Comment by rosibaj** [comment]
lgtm - links are removed for collaborators.
