### ISSUE TITLE
Modal issues in new user 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1111]
Continuation of #1054 

![image](https://user-images.githubusercontent.com/15824252/75180790-e9adea80-570a-11ea-912f-bc53aa99cf66.png)

**Comment by kcullion** [comment]
tested, looks great @anncatton

**Comment by kcullion** [comment]
looks good in prod!

**Comment by rosibaj** [comment]
tested in prod lgtm!
