### ISSUE TITLE
🐛 Invalid ... icon not showing in side bar sometimes

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1116]
![image](https://user-images.githubusercontent.com/15824252/75194928-05bf8500-5727-11ea-83a9-ee9ce828f959.png)

## Expected behaviour
When a submission has been marked `invaid` it shows correctly in the top status bar, but not in the side bar.

**Comment by kcullion** [comment]
I see the "!" icon in the sidebar now, thanks Ann.

@rosibaj I just noticed, in other cases we have the user land on the first tab with the errors. Here they are landing on the Chemo tab, but it's not the one with the errors. Should we fix this along with this ticket?
