### ISSUE TITLE
🐛 The "All Programs" Table seems to render n-1 rows

### ISSUE THREAD

**Issue by wajiha-oicr** [icgc-argo/platform-ui#1126]
## Describe the bug
![image](https://user-images.githubusercontent.com/59613607/75289334-1259e100-57ec-11ea-9dcc-0fde6c6af210.png)

Despite the fact that the table is being passed the correct `data` object that contains all the rows, it seems like the table always renders (number of rows -1).

Another observation I noticed is that if there are >2 programs, you can see that the missing row is just the last one in the list. Change the sort order and the first one in the list goes missing.

![image](https://user-images.githubusercontent.com/59613607/75289780-091d4400-57ed-11ea-859b-324162774a96.png)

![image](https://user-images.githubusercontent.com/59613607/75289942-5c8f9200-57ed-11ea-88f8-722fe4c68f98.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to the 'All programs' tab
2. Observe that the number of programs doesn't match with how many results the table shows

## Expected behaviour
The table should render all the rows.

**Comment by kcullion** [comment]
Working in qa. Thanks @jaserud

**Comment by kcullion** [comment]
trested in Prod...looks good!

**Comment by rosibaj** [comment]
tested in prod - lgtm!
