### ISSUE TITLE
🐛 Add User dropdown default

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1131]
## Describe the bug
When adding a user the role defaults to "Collaborator". A program admin may not change this, and it seems arbitrary to land on collaborator. 
![Screen Shot 2020-02-26 at 4 46 34 PM](https://user-images.githubusercontent.com/18424138/75391203-9cbb4700-58b7-11ea-9f25-855b91607b5c.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to Manage program for a program
2. Click on add user
3. modal appears with Collaborator specified for the user

## Expected behaviour
Let's make the the user choose the role. Use  the dropdown component and default to "Select an option" like:
<img width="712" alt="Screen Shot 2020-02-26 at 3 29 17 PM" src="https://user-images.githubusercontent.com/18424138/75391279-bfe5f680-58b7-11ea-9e99-23f4a5cbf850.png">

This will mean we need an error if this isn't filled in:
"Role is a required field."

**Comment by kcullion** [comment]
@anncatton just a small bug when I click on the dropdown, don't select an option, then click away I get this error
<img width="412" alt="Screen Shot 2020-03-02 at 10 24 13 AM" src="https://user-images.githubusercontent.com/18424138/75690269-88d56380-5c70-11ea-9253-4c77484105d1.png">

**Comment by kcullion** [comment]
looks good @anncatton thanks!

**Comment by kcullion** [comment]
tested in Production..looks great!

**Comment by rosibaj** [comment]
verified in production
