### ISSUE TITLE
Data Hookup - Gateway to Dashboard 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1132]
- we have the table #1019 
- we have the gateway https://github.com/icgc-argo/platform-api/issues/133
transform the gateway data shape to the expected table state.

**Comment by jaserud** [comment]
currently the table only shows 20 donors. The queries need to be updated to make use of pagination, sort, and filter from gateway: https://github.com/icgc-argo/platform-ui/issues/1287

**Comment by rosibaj** [comment]
table looks great! Data is flowing in correctly thanks @jaserud

**Comment by rosibaj** [comment]
verified on prod dashboard
