### ISSUE TITLE
API Token note: copy change

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1135]
On the profile + token page, please update the current note to read as a list with two bullet points:
<img width="667" alt="Screen Shot 2020-02-27 at 11 17 09 AM" src="https://user-images.githubusercontent.com/18424138/75476135-101c9180-5968-11ea-9fac-04b9059bd35b.png">

- [ ] Adding the bottom bullet point:
When you generate a new token, all previous tokens become invalid.

- [ ] And removing the "Please note" from the first bullet point

**Comment by kcullion** [comment]
looks great @anncatton !

**Comment by kcullion** [comment]
tested and looks good in prod

**Comment by rosibaj** [comment]
tested and looks good in prod
