### ISSUE TITLE
Invalid Submission Errors: tab should land on first reported error

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1154]
When the submission is invalid (because of dictionary changes), going to the clinical submission section should land on the first tab with reported errors. Currently it lands on the first tab (chemotherapy). This is what we have consistently been doing in other error scenarios.

<img width="1269" alt="Screen Shot 2020-03-02 at 2 05 31 PM" src="https://user-images.githubusercontent.com/18424138/75708690-4a9b6c80-5c8f-11ea-9a20-644afd9f6a13.png">

**Comment by wajiha-oicr** [comment]
found some odd caching behaviour, moving back to in progress

**Comment by kcullion** [comment]
@wajiha-oicr as we discussed in slack, I'm just seeing that the error icon is missing when uploading a failed file in some programs (it happened in KIMC-CA and LUCA-KR

<img width="706" alt="Screen Shot 2020-03-20 at 2 02 05 PM" src="https://user-images.githubusercontent.com/18424138/77197964-76ef1f80-6abc-11ea-8b50-1f7e796b6004.png">

**Comment by wajiha-oicr** [comment]
@kcullion I think I've found out how to recreate the error consistently.

The error state **does not** show up in the side tab if the first file you upload is an invalid file. 
It **will** show up if you upload a file in a clinical submission that already has 1+ valid files uploaded uploaded.

**Comment by kcullion** [comment]
@wajiha-oicr interesting.always that n+1 error eh.  Do you want to try and tackle this bug? Or shall we make a new ticket?

**Comment by wajiha-oicr** [comment]
Don't think another ticket is needed, I think I was able to find a fix for this which I also just tacked onto this ticket for convenience's sake.

**Comment by wajiha-oicr** [comment]
@kcullion the side menu bug's fix is in QA now, ready to be tested

**Comment by rosibaj** [comment]
tested on qa - i can see the invalid tab being selected 
- when i have only error files
- when i have 1 or more than 1 good files 

i see teh correct status in the side bar, and the table. 

@kcullion can you give this one a final test as well please?

**Comment by kcullion** [comment]
@rosibaj @wajiha-oicr I now see the error icon in the sidebar. Thanks!!

**Comment by rosibaj** [comment]
tested on prod - priority is being determined correctly on clinical tabs.  
lgtm.
