### ISSUE TITLE
🐛 DCC updates: old and new values are not correct

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1162]
## Describe the bug
(in QA and Production)
DCC locked submission for approval: the updated rows are still incorrect. 
<img width="1151" alt="Screen Shot 2020-03-03 at 1 42 10 PM" src="https://user-images.githubusercontent.com/18424138/75808275-d3301080-5d54-11ea-9124-5b9db301a4da.png">

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Submit a clinical file
2. make an update to submitted data and upload the file with that change
3. DCC needs to approve this update. Login as DCC and view that submission
4. Look at the updated rows - old and new values

## Expected behaviour

- [ ] In this case, my reason for deceased, and survival time should not be in the old value row. 

- [ ] I also removed the "Yes" for prior_malignancy. This shows up as updated but appears in the middle of the cell - so I can't tell if it's the old or new value. It should appear on the same line as the old values

**Comment by hlminh2000** [comment]
Recreate on dev:
- submit this file on program `MINH-CA`: https://drive.google.com/open?id=1r5qTHmUJNBmZO_Z0H1_c6WgImmbyoG7r
- submit this file on same program: https://drive.google.com/open?id=1pWei0wUeyrJYM73ZeVjjrD3TVt4jFgW4

**Comment by kcullion** [comment]
I tested this on QA with a donor file. Seems to be good now! Thanks @hlminh2000

**Comment by kcullion** [comment]
@hlminh2000 as per slack, I found that prior_malignancy field acting up.  Try different things with it. Uploaded files 
https://drive.google.com/drive/u/0/folders/1Iro7u44GAoIcSCa0LDe7nZGjE9wygH1J
https://drive.google.com/drive/u/0/folders/1Iro7u44GAoIcSCa0LDe7nZGjE9wygH1J
https://drive.google.com/drive/u/0/folders/1Iro7u44GAoIcSCa0LDe7nZGjE9wygH1J

(change ids maybe)

**Comment by kcullion** [comment]
Also @hlminh2000 in this case, I didn't change prior_malignancy or age_at_prior_malignancy for KIM-39. So these cells shouldn't be shaded for that donor
<img width="1238" alt="Screen Shot 2020-03-17 at 10 47 05 AM" src="https://user-images.githubusercontent.com/18424138/76868149-de973780-683c-11ea-857c-f313acb9dbc4.png">

**Comment by hlminh2000** [comment]
@kcullion thanks for the testing files :) problem fixed!

**Comment by kcullion** [comment]
@hlminh2000 I tested with a new file and I'm still noticing the new values vertically centering within the two cells:
<img width="521" alt="Screen Shot 2020-03-20 at 4 27 13 PM" src="https://user-images.githubusercontent.com/18424138/77203978-2251a180-6ac8-11ea-935e-2fa91aeda759.png">
The new test files can be found in on the google drive: Icgc-argo/testing files/Platformui-1162/

**Comment by hlminh2000** [comment]
@kcullion thanks so much for the test again! Updated! was a very subtle css issue...

**Comment by kcullion** [comment]
@hlminh2000 @rosibaj  I've tested this with a couple files and it seems to be fixed now!!! Thanks :)
