### ISSUE TITLE
🐛 Clinical submission is Reporting updates to data that I didn't change

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1166]
## Describe the bug
Uploading the same treatment file for a second time, reports that I made updates to the data.
(happening in QA and Production)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. After registering a donor, upload a treatment + chemo file. The treatment file should have one row for a donor for chemo treatment and one for Ablation for the same donor. Both are primary treatments
So like

RAWR-CA	Kim-01	TRE-01	Chemotherapy		Yes	43	444	Concurrent	Disease progression
RAWR-CA	Kim-01	TRE-02	Ablation		Yes	22	223	Concurrent	Disease progression

2. upload this file with a corresponding chemo file

RAWR-CA	Kim-01	TRE-01	Need list	mg/m²	22

3. Sign off and submit
4. Upload that exact same treatment file again. It is saying that I updated the second row, but I didn't. 
<img width="945" alt="Screen Shot 2020-03-03 at 2 01 00 PM" src="https://user-images.githubusercontent.com/18424138/75809858-6ec28080-5d57-11ea-911c-237a7f2b6fbc.png">

5. This is the change that is being reported to dcc
<img width="1353" alt="Screen Shot 2020-03-03 at 2 02 55 PM" src="https://user-images.githubusercontent.com/18424138/75810066-d678cb80-5d57-11ea-9a5b-9400c66e6834.png">

## Expected behaviour
Files that I upload twice with no changes, should not report updates for DCC to approve.

@rosibaj is this because I can only have one primary treatment and I said Yes for both treatments for this donor?

**Comment by kcullion** [comment]
@rosibaj I tested this again and it doesn't seem to be happening anymore, probably from what @hlminh2000 fixed in 1162. Closing

**Comment by rosibaj** [comment]
thanks @kcullion ! i thought htis one was probably a duplicate!
