### ISSUE TITLE
🐛 Submission not refreshing when DCC approves

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1167]
## Describe the bug
DCC has to refresh the browser in order to see that the program submission has been approved and reset.

This submission has been approved, but the lock is still there...and the submission still appears locked for approval
<img width="286" alt="Screen Shot 2020-03-03 at 3 46 44 PM" src="https://user-images.githubusercontent.com/18424138/75819653-11cfc600-5d69-11ea-8169-50dc2689223e.png">

## Steps To Reproduce

Steps to reproduce the behaviour:
1. As DCC, approve a submission that has updates
2. You are taken to the DCC dashboard with the success toast 
3. Go back to that program section, the submission section still appears locked for approval
4. You have to refresh the browser in order for the submission to be reset 

## Expected behaviour
The submission should refresh upon approval. Similar to the program member behaviour

**Comment by anncatton** [comment]
@rosibaj @kcullion when you test this, can you verify that the submission state goes from validated to pending approval properly? This happened when I was testing in dev/qa but I cannot reproduce

**Comment by kcullion** [comment]
@anncatton I thought this bug was for when the submission was going from pending approval to approved and blank submission.

**Comment by anncatton** [comment]
Correct. But you still have to go through all the steps to test, and I noticed once or twice that the state did not update to `pending approval` (show the Approve button) properly. But I couldn't reproduce after.

**Comment by kcullion** [comment]
@anncatton I tested this and everything seems to be working as expected with the submission state and the refresh. thanks

**Comment by rosibaj** [comment]
@anncatton ive tested a few times and im not able to any issues with the approve button not appearing on qa. 

this lgtm! I will move for release.  thanks @anncatton !
