### ISSUE TITLE
🐛 Beta testing banner covers some of the buttons

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-ui#1183]
## Describe the bug
It seems the banner for beta testing is cover the buttons in the top left corner. This only occurs on the home page.

## Steps To Reproduce
Two examples:
1. Can't press `logout` here
![image](https://user-images.githubusercontent.com/34698315/75928843-444af300-5e3d-11ea-982b-1d44837e21a7.png)
2. Can't press `login` button here
![image](https://user-images.githubusercontent.com/34698315/75928952-7bb99f80-5e3d-11ea-840f-500ff6c50129.png)

## Expected behaviour
Probably want to be able to click those

**Comment by akachru-github** [comment]
@kcullion did we decide this a hotfix ticket?

**Comment by kcullion** [comment]
I think @hlminh2000 was going to do this as a hotfix

**Comment by akachru-github** [comment]
In that case, marked this as high priority in zenhub.

**Comment by hlminh2000** [comment]
going to deploy as hotfix now :) thanks!

**Comment by kcullion** [comment]
looks good @hlminh2000  thanks!

**Comment by kcullion** [comment]
looks good in production!

**Comment by rosibaj** [comment]
verified on production environemnt - i can login/logout and navigate to profile pag.
