### ISSUE TITLE
Fix links to dictionary

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1198]
These links should link to the dictionary table and use the correct UI kit link style

- [ ] when submission is invalid because of dictionary changes:

<img width="1326" alt="Screen Shot 2020-03-06 at 10 10 41 AM" src="https://user-images.githubusercontent.com/18424138/76096367-fac0ec00-5f93-11ea-86b4-e0828fe71301.png">

EXAMPLE OF NOTIFICATION HAPPENING:
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/RAWR-CA/clinical-submission?tab=primary_diagnosis

**Comment by wajiha-oicr** [comment]
Hi, I can recreate the link leading to the wrong place, but the link style looks okay to me...
![image](https://user-images.githubusercontent.com/59613607/78148979-7aab6c00-7403-11ea-9566-a036fb862ada.png)

Is there something I'm missing about the style?

**Comment by kcullion** [comment]
@wajiha-oicr I forget where I saw that. But sometimes when the link is blue it means the link isn't using the UI link component. @P-Saha had to format the links to use the component so it used the right styles. Priyonto, maybe you fixed this styling already?
