### ISSUE TITLE
Case insensitivity when comparing email addresses

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#1207]
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/b6fa4e07-1d6d-45cc-ad37-14824e211914)

**Comment by rosibaj** [comment]
@P-Saha this looks good now!  thank you!

**Comment by rosibaj** [comment]
tested on production - case sensitivity in email add is no longer visible.
