### ISSUE TITLE
🐛 Cannot add new institutions.

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1221]
## Describe the bug
Cannot add new institutions on production:
https://drive.google.com/file/d/1rXiW5iqT-q87l_c2w9AYpeOmbH5zxDL2/view 

Cannot add new institution on QA:
https://drive.google.com/file/d/1ct7Pcvyc_spyq2XHZyObnEdrlMX_1xWI/view
## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to any program
2. Erase all institutions and add a new institution
3. Scroll down to click save.  you will see a success toast.
4. Refresh the page.  you will see that your changes have not actually taken effect. 

## Expected behaviour
I should be able to add institutions.

**Comment by jaserud** [comment]
closing because ticket is moved to program service: https://github.com/icgc-argo/program-service/issues/318. Content of ticket is exactly the same
