### ISSUE TITLE
Success Toasts: Text change for dashboard updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1222]
In order to notify the user that the dashboard data will update, we will add a sentence to both toasts:

- [ ] Success when user registers samples. The copy becomes 

**2 new registered samples**
You will see the updates on your dashboard shortly. If you have any changes to this registered sample data, please contact the DCC.

- [ ] Success when user submits clinical data. The copy becomes 

**Successful Clinical Submission!**
Your clinical data has been submitted. You will see the updates on your dashboard shortly.

<img width="490" alt="Screen Shot 2020-03-17 at 11 55 59 AM" src="https://user-images.githubusercontent.com/18424138/76874966-49993c00-6846-11ea-9da0-76d64b9fe0fb.png">

**Comment by rosibaj** [comment]
tested on qa- lgtm thanks @P-Saha
