### ISSUE TITLE
Footer: fix links breaking onto two lines

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1227]
The footer links don't need to break onto two lines, until there's at least 100px between the copy on the left and the links on the right.

<img width="955" alt="Screen Shot 2020-03-17 at 3 46 15 PM" src="https://user-images.githubusercontent.com/18424138/76895500-837a3a80-6866-11ea-86ac-18a3ef8a7a2b.png">

**Comment by rosibaj** [comment]
lgtm thanks @P-Saha !

**Comment by rosibaj** [comment]
verified on prod! lgtm!
