### ISSUE TITLE
Dashboard card styling updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1243]
- [x] For Program Workspace Status: so the progress bars fit consistently, please break the labels onto two lines and use the "caption" font style which has font-size:11px

<img width="424" alt="Screen Shot 2020-03-20 at 3 33 07 PM" src="https://user-images.githubusercontent.com/18424138/77199994-1e218600-6ac0-11ea-92e4-0355d1f57678.png">

- [x] For Donor Release Summary, put the "committed donor number" below with the "Committed" label.  and also use font-size:11px, bold for that number
<img width="384" alt="Screen Shot 2020-03-20 at 3 49 04 PM" src="https://user-images.githubusercontent.com/18424138/77201143-5cb84000-6ac2-11ea-9de7-4b24ec1b37db.png">

**Comment by wajiha-oicr** [comment]
Hi @kcullion,

These changes are in dev, the text for the workplace status card is less wide.
<img width="389" alt="in dev" src="https://user-images.githubusercontent.com/59613607/77767948-2cb7f200-7018-11ea-91fe-bb5f0df04a8b.png">.

However, I think the entire purpose of this change was to stop the progress bar from getting cramped, especially when getting to the locked state. Despite the changes, there's still an overlap. 

<img width="388" alt="bar" src="https://user-images.githubusercontent.com/59613607/77768326-b5369280-7018-11ea-9e20-01eb74fb88db.png">

I noticed the pending approval bar has a custom width of 100px. I guess that was done to get the text all on one line (not sure)? By reducing that fixed width to ~75px, everything seems to fit. 

<img width="392" alt="width edit" src="https://user-images.githubusercontent.com/59613607/77768446-e0b97d00-7018-11ea-9536-f035d77e8986.png">

Let me know if I should modify the width, or if you have other design suggestions.

**Comment by kcullion** [comment]
@wajiha-oicr this looks great thanks! Will this just happen for the dashboard card? Like on the actual submission, the "pending approval" item can span one line in that top bar.

**Comment by wajiha-oicr** [comment]
@kcullion yes it's a custom width for the dashboard card

**Comment by kcullion** [comment]
@wajiha-oicr ok please  do what you're suggesting! Thanks :)

**Comment by wajiha-oicr** [comment]
@kcullion you can test this change in QA now. MINH-CA is a program in the pending approval state so you can check there especially.

**Comment by kcullion** [comment]
Both of these updates look great! thanks @wajiha-oicr 
@rosibaj I'll leave this ticket for you to have a look

**Comment by rosibaj** [comment]
lgtm - thanks @wajiha-oicr @kcullion
