### ISSUE TITLE
Update links for the footer to link to icgc-argo.org

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1257]
Footer links:
- remove the /privacy page and instead link "Privacy Policy" to: https://www.icgc-argo.org/page/2/privacy 
- link Terms and Conditions to: https://www.icgc-argo.org/page/1/terms-and-conditions
- link Publication Policy to: https://www.icgc-argo.org/page/77/e3-publication-policy

(all links will open in a new tab)

**Comment by kcullion** [comment]
@anncatton @rosibaj this one looks good to me!

**Comment by rosibaj** [comment]
lgtm thanks @anncatton

**Comment by rosibaj** [comment]
verified on prod
