### ISSUE TITLE
Beta-Feedback: No validation error on incorrectly formatted TSV file 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1264]
## Detailed Description
- A beta user submitted this tsv file: 
https://drive.google.com/drive/u/1/folders/1Dh7Wcly50kmRnEz184kpKM14GQzMUbCg
- Nothing at all happened on the UI. 
- When i uploaded the file, I can see these errors:
```
{errors: [{message: "", locations: [], path: ["uploadClinicalRegistration"],…}], data: null,…}
errors: [{message: "", locations: [], path: ["uploadClinicalRegistration"],…}]
0: {message: "", locations: [], path: ["uploadClinicalRegistration"],…}
message: ""
locations: []
path: ["uploadClinicalRegistration"]
0: "uploadClinicalRegistration"
extensions: {code: "INTERNAL_SERVER_ERROR", exception: {,…}}
code: "INTERNAL_SERVER_ERROR"
exception: {,…}
data: null
extensions: {tracing: {version: 1, startTime: "2020-03-25T19:42:45.669Z", endTime: "2020-03-25T19:42:45.712Z",…}}
tracing: {version: 1, startTime: "2020-03-25T19:42:45.669Z", endTime: "2020-03-25T19:42:45.712Z",…}
```

Something about this file is just totally had an issue. (looks like they put their values where the column headers used to be - so they have a mixture of column headers and values in the first row)

## Steps to Reproduce 
1.  Upload the attached file to any programs sample registration

## Expected Behaviour
The UI should show this error: 

```
Failed to upload: file name
This file is formatted incorrectly. Please retain the template format with the correct headers in the first row.

```

<img width="999" alt="Screen Shot 2020-03-25 at 4 43 59 PM" src="https://user-images.githubusercontent.com/18424138/77583665-db90ec80-6eb7-11ea-896f-4b4cb19bc6ed.png">

**Comment by jaserud** [comment]
I'm closing this because it is replaced by this one: https://github.com/icgc-argo/argo-clinical/issues/455. They are the exact same just moved to `clinical` repo
