### ISSUE TITLE
Static UI: File Repository Table 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1265]
spec: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=File+Repository+Specification

**Logged out**
![image](https://user-images.githubusercontent.com/15824252/77594569-40a30d00-6ecd-11ea-8de6-13f099c6cc2c.png)

**Logged in**
![image](https://user-images.githubusercontent.com/15824252/77594762-c1fa9f80-6ecd-11ea-8126-71e7ba4c79cd.png)

Please note 
- that the sort has been changed on the table to be a bar not the up/down icons
- there are 2 icons for the last column, locked and download 

**Zeplin link** 
https://zpl.io/VQ8Xql4
Tooltips: https://zpl.io/VQ8Xql4
Include:
- [x] Table dispaly
- [x] Download buttons
- [x] Pagination 
- [x] Checkboxes component exists ; just track which checkboxes are selected but do not pipe into download. (use select table component)
- [x] for the state capture (select all) make sure it is captured separately.
- [x] tooltips for action column (logged out and logged in versions)
- [x] tooltips for Program column (showing full program name)

**Comment by wajiha-oicr** [comment]
@kcullion just curious, is the upper/lower bar replacement for sort going to be a change you'd like for all tables? or just for this one in particular?

**Comment by rosibaj** [comment]
@wajiha-oicr its a replacement for all tables.

**Comment by kcullion** [comment]
Yeah @wajiha-oicr it's for the table component - because eventually we will have a filter in the spot where the up/down arrows are

**Comment by wajiha-oicr** [comment]
thanks guys!

**Comment by wajiha-oicr** [comment]
https://argo-ui-storybook.netlify.com/?path=/story/components-pages-file-repository-filetable--basic

This is the version of this being in "qa"

**Comment by kcullion** [comment]
@wajiha-oicr this looks awesome!
Question, can we have a default sort (so the blue stroke at the top would be on that column)? I think in this case it would be on File ID. Maybe that's not set in storybook though.

We also had the count look like: 1-20 of 11,350 files (depending on how many files they are viewing at once)

**Comment by rosibaj** [comment]
@kcullion Question, but whats the value of this sort?

**Comment by kcullion** [comment]
@rosibaj that's what current ICGC did. Would you rather a different default sort?

**Comment by rosibaj** [comment]
I think that's an API level sort, not a frontend sort

**Comment by wajiha-oicr** [comment]
Hi Kim, sorry I forgot to mention this but the count that says 1-20 of 11,350 requires info from the pagination, which I believe is still partially 'under construction'. So I think displaying it in that manner may be blocked until then.

**Comment by kcullion** [comment]
@wajiha-oicr ok sounds good!

**Comment by rosibaj** [comment]
@wajiha-oicr i see this at the bottom: 
![image](https://user-images.githubusercontent.com/15824252/78717114-19e1cf00-78ee-11ea-9217-38bab6a343e5.png)

**Comment by wajiha-oicr** [comment]
Yeah I have that there as a temporary place to show which files have been selected. It's meant for demonstration purposes (i.e. intended to be removed during implementation). 

If you select and unselect files that array should be keeping track.

**Comment by wajiha-oicr** [comment]
If it's preferred not to be there I can just remove it :) 
![image](https://user-images.githubusercontent.com/59613607/78717361-79d87580-78ee-11ea-8147-c9a96627f889.png)

**Comment by rosibaj** [comment]
well lgtm!!!!
