### ISSUE TITLE
Static UI: File Repo Charts 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1266]
- [x]  Pick a charting library or build yourself? pls decide!
- [ ] Implement the bar chart graph card in storybook first. 
- [ ] tooltips for charts

![image](https://user-images.githubusercontent.com/15824252/77594388-ca9ea600-6ecc-11ea-81ce-7276531bead9.png)

**Zeplin Link**
https://zpl.io/VxeZeyR
Tooltips: https://zpl.io/VQ8Xql4

Specs: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=File+Repository+Specification

**Comment by anncatton** [comment]
The arrow style for the tooltips was added to the global tooltip, arrow position should adjust according to tooltip position.

**Comment by rosibaj** [comment]
lgtm!!! Thanks @anncatton !!!

**Comment by rosibaj** [comment]
confirmed hidden in prod.
