### ISSUE TITLE
Static UI: Facet Search Components

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1267]
- [ ] https://dcc.icgc.org/repositories?files=%7B%22from%22:1,%22size%22:25%7D 
This is an example of all the interactions listed. 
- [ ] Implement the facet component in the  storybook:
![image](https://user-images.githubusercontent.com/15824252/77610653-ac9b6a80-6ef9-11ea-9b1c-4a9bc6018c81.png)

**Comment by wajiha-oicr** [comment]
Facet story 
https://argo-ui-storybook.netlify.app/?path=/story/uikit-facet--basic

Integer Field display stpry
https://argo-ui-storybook.netlify.app/?path=/story/uikit-integerfielddisplay--basic

**Comment by kcullion** [comment]
Looking good @wajiha-oicr. Some feedback
- [ ] Can you make the top and bottom padding the same for the grey count bubbles and the list items (shows on hover)
<img width="662" alt="Screen Shot 2020-04-20 at 1 39 19 PM" src="https://user-images.githubusercontent.com/18424138/79782619-60cbbd80-830d-11ea-92e9-8d16294e97b2.png">

- [ ] Semantically, I don't think the list items should be <h4> elements as the browser will read them as headings for blind readers. They should probably be list items
- [ ] Can you use the font-sizes and colours from the mock.
<img width="668" alt="Screen Shot 2020-04-20 at 1 50 54 PM" src="https://user-images.githubusercontent.com/18424138/79783007-f9fad400-830d-11ea-988a-75b24cf4d242.png">
- [ ] tighten up the spaces between the list item like the mock - we are going to want to try to show as many facets at once as we can
