### ISSUE TITLE
Static UI: Page Initialization for File Repo

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1268]
- [ ] Create the file repository page in the application 
![image](https://user-images.githubusercontent.com/15824252/77594520-1c473080-6ecd-11ea-9c0d-7a0ff96e1bd6.png)
- [ ] Make sure it is hidden behind feature flag 
- [ ]  Add table, facets, and chart components from storybook

**Comment by anncatton** [comment]
@rosibaj Feature flag is currently disabled in QA to test it is working properly, will enable once that's verified.
* manually test `/repository` route to ensure there is a 404

**Comment by rosibaj** [comment]
@anncatton i do not see this in qa 
![image](https://user-images.githubusercontent.com/15824252/80017723-05cbcf00-84a3-11ea-896f-33bbe6368c7c.png)
