### ISSUE TITLE
Static UI: Summary Chart

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1269]
![image](https://user-images.githubusercontent.com/15824252/77662630-80f89e80-6f52-11ea-9c79-883b1a930825.png)

- add to storybook
- don't worry about exact data; just make the component take a list of key/value pairs and display those in the order provided (arrya of objects each object with value + number)
- 2 column list where each is approximate the same height

@rosibaj please add a list of fields here

**Comment by P-Saha** [comment]
https://argo-ui-storybook.netlify.app/?path=/story/components-pages-submission-system-donor-donordatatable--basic

**Comment by kcullion** [comment]
@P-Saha looks good, here's some feedback:

- [ ] use subtitle2 for the header (this may decrease space above and below the header - if not, please minimize that space a bit)
- [ ] Make space in between the tables equal to the left and right card padding 

<img width="874" alt="Screen Shot 2020-04-21 at 10 15 03 AM" src="https://user-images.githubusercontent.com/18424138/79876657-51a24980-83b9-11ea-82f4-3e5f36085d5b.png">

**Comment by kcullion** [comment]
@P-Saha so the headings of these cards can be `h2`. Like that semantic article I sent. this page would be set up like 
`h1 `Donor id` /h1`
     `h2` Summary `/h2`
     `h2` Available Files `/h2`
            `h3`DATA TYPES`/h3`
            `h3`EXPERIMENTAL STRATEGIES`/h3`
   `h2` Clinical Timeline `/h2`
           `h3`Primary Diagnose`/h3`
etc

**Comment by kcullion** [comment]
@rosibaj @P-Saha this looks good to me. Thanks for the fixes!
