### ISSUE TITLE
Static UI: Donor Summary Card

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1271]
- [ ] Implement the Donor Summary Card in story book
![image](https://user-images.githubusercontent.com/15824252/77610105-2fbbc100-6ef8-11ea-903b-73593d2e89d9.png)

These stats should be the same as available on the Dashboard summary.
**Zeplin Link:**
Less data has been submitted: https://zpl.io/be0Rg7N
More data has been submitted: https://zpl.io/V1n0ZJm

**Comment by P-Saha** [comment]
https://argo-ui-storybook.netlify.app/?path=/story/components-pages-submission-system-donor-donorsummarystats--basic

**Comment by kcullion** [comment]
Thanks @P-Saha we started a feedback ticket for next spring: https://github.com/icgc-argo/platform-ui/issues/1349
