### ISSUE TITLE
Static UI: Donor Clinical Display

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1272]
Create the field Donor Clinical Timeline Display in storybook:

![image](https://user-images.githubusercontent.com/15824252/77610841-39debf00-6efa-11ea-9000-024750d3b6b1.png)

Note for timeline checkbox filters.  Just use the singular version of these words. Eg:
1 Primary Diagnosis   1 Specimen    2 Treatment     3 Follow up
(the mockups will show a combination of singular and plural)
<img width="556" alt="Screen Shot 2020-03-26 at 2 11 10 PM" src="https://user-images.githubusercontent.com/18424138/77682607-9d560480-6f6d-11ea-9970-5bbaf8eaab35.png">

**Zeplin Links:**
Empty (no clinical timeline data submitted yet): https://zpl.io/be0RYkB
Primary Diagnosis Tab: https://zpl.io/V1n0ZJm
Specimen tab: https://zpl.io/anRDrKO
Treatment tab: https://zpl.io/VY4OJBn
Followup tab: https://zpl.io/bAyMGZq

**Comment by ciaranschutte** [comment]
- [ ] table
- [ ] samples
- [ ] no data
- [ ] invalid header
- [ ] invalid tab

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion in storybook

**Comment by rosibaj** [comment]
@ciaranschutte can you please add a version label tag to this ticket? Cannot release it till added.
