### ISSUE TITLE
Update donor submission summary table query variables to use es features

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-ui#1287]
since gateway has been connected to elastic search: https://github.com/icgc-argo/platform-api/issues/168, we need to update UI donor data submission queries to use pagination, sort and filter options

## Detailed Description
- Ordered data by default by last updated
- The query needs to be updated to use the query variables. 
- Make any required UI updates

**Comment by jaserud** [comment]
I misspoke filters is not yet ready in the gateway. There is a `fitlers` variable but doesn't do anything right now. Added ticket in gateway to implement it: https://github.com/icgc-argo/platform-api/issues/190

**Comment by kcullion** [comment]
@jaserud when I register samples I notice when the donor table refreshes to show the newly registered samples, the card title flashes from grey to blue. Like for a few seconds after it refreshes it keeps changing colours.

Also, are we using the same loader when this table does refresh? Would that be for a new ticket?

**Comment by jaserud** [comment]
@kcullion I see what your talking about with, looks like some weird polling behavior. This didn't happen when I worked on it so looks like something was merged that broke it :disappointed:, will take a look.
