### ISSUE TITLE
🐛 Fix Column Sorting on Summary Donor Table for Core & Extended Fields

### ISSUE THREAD

**Issue by wajiha-oicr** [icgc-argo/platform-ui#1292]
## Describe the bug
- The column sorting for the core and extended fields doesn't seem to be correctly sorting the numbers in ascending/descending order

## Steps To Reproduce
Go to a donor summary table and click on the column headers for core or extended fields and observe that there seems to be a random sort

## Expected behaviour
- Within the table, the column cell's 'accessor' property is still using the old 'dummy' property names (`coreFields` and `extendedFields`). It needs to be updated to the newly created property names (`submittedCoreDataPercent` and `submittedExtendedDataPercent`) that were added during the data hookup step.

**Comment by wajiha-oicr** [comment]
@rosibaj I think the fix for this is straightforward (written in description). I can bundle it with my file repository table ticket when it's ready, or it could be done as a separate PR.

**Comment by rosibaj** [comment]
@wajiha-oicr added to sprint - as this is one a different page, please do it as a separate PR to make testing easier.

**Comment by rosibaj** [comment]
tested on QA - i see the sort correctly wokring now.  thanks @wajiha-oicr !
