### ISSUE TITLE
Static UI Dashboard: Donor table download buttons

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1300]
We need to implement 3 buttons on the donor table:
Zeplin: https://zpl.io/V4dd110
- [ ] Download All Clinical Data
- [ ] Download Missing Data (contains all donors and only what fields they are missing)
- [ ] Download Summary Table (just the data from the table)

<img width="480" alt="Screen Shot 2020-04-03 at 10 15 25 AM" src="https://user-images.githubusercontent.com/18424138/78370017-10760100-7594-11ea-8ac9-f86fc3596adb.png">

**Comment by kcullion** [comment]
@P-Saha looks good! They should just be right justified with the table
<img width="1225" alt="dashboard buttons" src="https://user-images.githubusercontent.com/18424138/80018783-9060fe00-84a4-11ea-9d59-5de0da7c1369.png">

**Comment by kcullion** [comment]
@P-Saha @rosibaj the buttons look good on QA now. Thanks!

**Comment by rosibaj** [comment]
@hlminh2000 @P-Saha if this is onqa can i please have the lablel/tag version applied to this ticket?

**Comment by P-Saha** [comment]
@rosibaj This ticket was in `1.12.1`, I labeled it as `1.12.0`

**Comment by rosibaj** [comment]
thanks @P-Saha !!!!!!!
