### ISSUE TITLE
Update Upload and Download Icon

### ISSUE THREAD

**Issue by wajiha-oicr** [icgc-argo/platform-ui#1314]
- The UiKit upload and download icon needs to be updated to the svgs @kcullion  used in the mockups( [see icon under manifest](https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5e39c770cf1cdf8f1abe4097))

- the dashboard icons need to be purple

**Comment by rosibaj** [comment]
@wajiha-oicr can we get this released to QA before sprint end?

**Comment by wajiha-oicr** [comment]
the release PR is up https://github.com/icgc-argo/platform-ui/pull/1315

waiting for approval from @hlminh2000

**Comment by kcullion** [comment]
This looks good to me @wajiha-oicr and @rosibaj ...I'll move it over :)
