### ISSUE TITLE
Static UI: Homepage

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1321]
Build the UI for the homepage. Zeplin: https://zpl.io/2yZk3dG

- [ ] Banner: hardcode the stats for now 
links: 
**Browse the data** will eventually link to the File Repository (open in a same window)
**About ICGC ARGO** links to https://www.icgc-argo.org/ (open in a new window)

- [ ] 3 data callouts
links all go to documentation (open in new windows)
**How to Apply** links to https://docs.icgc-argo.org/docs/data-access
**How to Download** links to https://docs.icgc-argo.org/docs/data-download
**About our Workflows** links to https://docs.icgc-argo.org/docs/dna-pipeline

- [ ] News - this will need to be updatable (ask @hlminh2000)
content is placeholder but for now just link "Contact us" to /contact 

- [ ] Resources boxes
Links (open in new windows)
**Publications Guidelines** links to: https://docs.icgc-argo.org/docs/publication-guidelines (page isn't on production yet)
**Release Notes** links to https://docs.icgc-argo.org/docs/data-release-notes (page isn't on production yet)
**Programmatic APIs** - no link yet
**ICGC 25K Data Portal** link to https://dcc.icgc.org/
**Data Submission** link to https://docs.icgc-argo.org/docs/submission-overview
**Documentation** link to https://docs.icgc-argo.org/

- [ ] Overture callout
the logo and copy link will open in a new window: overture.bio

**Assets (sent over slack)** 
- [ ] All of the icons should be available in zeplin, but let Kim know if there's any missing. The banners may not be the perfect size, so I can redo those if you need it.
- [ ] The latest news box can grow taller, so I made the image fade into the primary colour #151C3D so you can set that as the background colour of that box (position: top)
- [ ] The world banner is also meant to blend into the top nav bar. so you can try position:bottom with that same background colour #151C3D
- [ ] a light stroke was added to distinguish the navbar - maybe you can put that on the top of the banner container

**Comment by wajiha-oicr** [comment]
@kcullion for the resource boxes, which part of the component did you want to behave as the actual link? the entire box? the title? the chevron?

**Comment by kcullion** [comment]
@wajiha-oicr can you make the entire box a link? Larger hit area is always my preference :)

**Comment by wajiha-oicr** [comment]
thanks for clarifying :)

**Comment by kcullion** [comment]
Thank you for checking! Also, @wajiha-oicr  I put a hover state for the box in the zeplin mock (see first box): https://zpl.io/2yZk3dG

**Comment by wajiha-oicr** [comment]
This is in QA but hidden behind a feature flag.

(visible in dev for sneaky peeks though https://platform-ui.dev.argo.cancercollaboratory.org/)

**Comment by kcullion** [comment]
you so great @wajiha-oicr!! should we hold off on reviewing if it's a feature flag?

**Comment by wajiha-oicr** [comment]
@rosibaj thoughts?

**Comment by rosibaj** [comment]
@wajiha-oicr can we please turn feature flag OFF in QA so we can provide feedback.  it should be ON in production .

**Comment by rosibaj** [comment]
confirmed hidden on prod
