### ISSUE TITLE
Dashboard: hook up committed donors

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1323]
- [ ] each program sets a committed # of donors in the "Create a program" form. That number should show here
<img width="404" alt="committed-donors" src="https://user-images.githubusercontent.com/18424138/78930095-82a58480-7a71-11ea-842b-e0c7b1e987f7.png">

**Comment by rosibaj** [comment]
tested on qa - lgtm thanks @P-Saha !!

**Comment by rosibaj** [comment]
confirmed on prod
