### ISSUE TITLE
Contact page UI fixes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1326]
Just the bottom feedback from this ticket: https://github.com/icgc-argo/platform-ui/issues/336

- [x] change` "Data or Analysis Query" in the dropdown to "Data or Analysis Inquiry" to be consistent with the service desk topics.

- [x] it doesn't seem like there is a margin between these two columns. Eg. at this screenwidth:
can you add 50px margin between columns (or padding within the left content area - it's better if that gets a little smaller than the form side)

<img width="737" alt="77570720-9e6e2f80-6ea2-11ea-8f89-2ee7dd2910f4" src="https://user-images.githubusercontent.com/18424138/78938690-a7552880-7a80-11ea-884c-2b900d194178.png">

**Comment by rosibaj** [comment]
tesed on qa - lgtm thanks @P-Saha!!!

**Comment by rosibaj** [comment]
confirmed on prod
