### ISSUE TITLE
Static UI: Facet Search Component FEEDBACK

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1340]
Feedback for this ticket: https://github.com/icgc-argo/platform-ui/issues/1267

**Basic Facet**
- [x] Can you make the top and bottom padding the same for the grey count bubbles and the list items (shows on hover)
<img width="662" alt="Screen Shot 2020-04-20 at 1 39 19 PM" src="https://user-images.githubusercontent.com/18424138/79782619-60cbbd80-830d-11ea-92e9-8d16294e97b2.png">

- [x] By default, the order is based on the number in the grey bubble. So from highest count to lowest. 

- [x] Semantically, I don't think the list items should be h4 elements as the browser will read them as headings for screen readers. They should probably be list items
- [x] Can you use the font-sizes and colours from the mock. (same goes for integer field display)
<img width="668" alt="Screen Shot 2020-04-20 at 1 50 54 PM" src="https://user-images.githubusercontent.com/18424138/79783007-f9fad400-830d-11ea-988a-75b24cf4d242.png">

- [x] tighten up the spaces between the list item like the mock - we are going to want to try to show as many facets at once as we can
- [x] Also tighten up the primary facet heading item so it's 36px height. (same goes for integer field display)
<img width="358" alt="Screen Shot 2020-04-20 at 3 23 27 PM" src="https://user-images.githubusercontent.com/18424138/79791191-e9048f80-831a-11ea-8edc-fe013fbd8754.png">
 

- [x] Add a label for "# files" above the grey boxes (typography style is caption, dark grey)
<img width="262" alt="2020-04-23_1004" src="https://user-images.githubusercontent.com/18424138/80108029-da4fef80-8549-11ea-8cfa-7df90cb0bf3f.png">

- [x] Search box - use this component (so font isn't bolded): https://argo-ui-storybook.netlify.app/?path=/story/uikit-form-input--with-icon
- [x] Search box - make the top and bottom padding a bit smaller so it's about the same size as the header button (same goes for integer field display):
<img width="329" alt="Screen Shot 2020-04-20 at 1 57 05 PM" src="https://user-images.githubusercontent.com/18424138/79783692-0c294200-830f-11ea-9abe-623026fc1d76.png">

- [x] The checkboxes look a bit big - my mock has them 12px x12px and these are 17x17.  Are we able to make a smaller version of the checkbox component for this (like the sm/lg versions of the input box)?

- [x] Select behaviour: decided to leave as. But change the way the Select all works when searching. Regarding select all: search for "abc", select all.  search again for "def", select all.  All terms matching "abc" and "def" should stay selected

- [x] When you do just press select all - can the options just stay in the original order and not reorder? If they are all selected, technically they are still pinned at the top in their original order

- [x] When facet title spans on two lines, it should still be left justified.
<img width="214" alt="Screen Shot 2020-04-24 at 11 12 57 AM" src="https://user-images.githubusercontent.com/18424138/80228160-aabde780-861c-11ea-8b6b-5b6e060024ff.png">

- [x] Search behaviour...when a user searches the list of facet values, hide the "# more" link as it doesn't actually show more.
<img width="227" alt="facet-search" src="https://user-images.githubusercontent.com/18424138/80229124-f9b84c80-861d-11ea-86b8-819e548070ab.png">

**Integer field display:**
- [x] single borders and input values not bolded
<img width="660" alt="Screen Shot 2020-04-20 at 2 43 34 PM" src="https://user-images.githubusercontent.com/18424138/79787714-7218c800-8315-11ea-8645-36aacfb7af77.png">

- [x] implement the blue focus border (like when search box is activated) when user selects the min or the max input fields to type in
<img width="173" alt="Screen Shot 2020-04-20 at 2 46 28 PM" src="https://user-images.githubusercontent.com/18424138/79787949-d89de600-8315-11ea-96b3-b5b215d938cf.png">

- [x] From Christina: Allow for entering decimals in the min and max textfields

Storybook:
- [x] Put both facet components under "Facet" category in storybook
- [x] Apply the right font for "Min |Max" in this component: https://argo-ui-storybook.netlify.app/?path=/story/uikit-numberrangefield--basic

**Comment by kcullion** [comment]
Thanks for all the updates @wajiha-oicr 
Just noticed a couple more things:

- [ ] Is it possible to have the "invalid input" on one line?
<img width="238" alt="Screen Shot 2020-05-01 at 10 43 29 AM" src="https://user-images.githubusercontent.com/18424138/80814226-7a84c480-8b99-11ea-9f1c-b397c8b1d05a.png">

- [ ] When I select facet values, they reorder to the top. Then I press "select all", then "deselect all" - the facet values should go back to the original order (ordered by max # files) - see icgc for what I mean

**Comment by rosibaj** [comment]
@wajiha-oicr great job :) Facet display is looking real good!
