### ISSUE TITLE
Static UI: Donor Summary Card FEEDBACK

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1349]
**Pipe component**. Please change at this level: https://argo-ui-storybook.netlify.app/?path=/story/uikit-pipe--basic
- [x]  pipes are using the wrong font. Please change in the pipe component level
- [x]  For divider line between pipe section - please change margin-right: 2px; to margin-right: 1px.

**Donor Summary Card**
- [x] Change "Raw Reads Submitted" to "Submitted Raw Reads" to be consistent with "Registered Samples" wording
- [x] try to get "Core Clinical Data Completeness" and "Extended Data Completeness" on two lines. If you can't, we should at least use these labels "Core Data Completeness" and "Extended Data Completeness"
- [ ] Each stat box can be spaced out better for content within to fit better. Ideally text will stay on 2 lines and it seems there's room for that if you minimize room between stat boxes.  Please try these fixes
<img width="1219" alt="Screen Shot 2020-04-21 at 1 21 52 PM" src="https://user-images.githubusercontent.com/18424138/79894287-38a69200-83d3-11ea-8c16-8510e85f63c4.png">
- [x] Each stat numbers is an `h2` element, but these aren't headings on the page. Semantically screen readers will scan this page and read all of these as headings. Please change them to `span` elements (it should be doable using the as prop, as in `Typograph as="span" ...`)
<img width="1083" alt="use-spans" src="https://user-images.githubusercontent.com/18424138/79895378-ccc52900-83d4-11ea-95a4-519a910b0f2f.png">

**Comment by kcullion** [comment]
@rosibaj this looks good. Let's review when implemented on entire page

**Comment by rosibaj** [comment]
@hlminh2000 does this ticket have a tag?  I cannot add it to release until it has a ui tag label.

**Comment by hlminh2000** [comment]
@rosibaj tag added

**Comment by rosibaj** [comment]
thanks @hlminh2000 !
