### ISSUE TITLE
Update Footer text + commit link

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1352]
Foot in the platform needs to be confirmed. 
![Screen Shot 2020-04-21 at 12.17.26 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/62b80b23-1cac-49e1-9f78-cb0e83f5ba70)

- [ ] Update the copyright text to 2020 because 2019 is bad luck (also, because we are publishing the Platform in 2020).
- [ ] Add the tag version to the gateway-api
- [ ] Update the footer to read the new version from the gateway instead of this placeholder value.  We `do not` need to include the commit hash in the mockup above

**Comment by rosibaj** [comment]
confirmed on prod
