### ISSUE TITLE
🐛 Dashboard: Donors with Released Files bar is full at zero

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1364]
## Describe the bug
Some programs like CYUNG-CA and HELLO-GB have the Donors with Released Files bar full. 
<img width="205" alt="Screen Shot 2020-04-22 at 10 01 21 AM" src="https://user-images.githubusercontent.com/18424138/79991687-95ac5180-8480-11ea-8c2e-d78a2e17fbf3.png">

## Expected behaviour
This should be grey as the count is at zero.

**Comment by kcullion** [comment]
@anncatton @rosibaj this looks good to me on QA!

**Comment by rosibaj** [comment]
@hlminh2000 @P-Saha if this is onqa can i please have the lablel/tag version applied to this ticket?

**Comment by rosibaj** [comment]
confirmed on prod
