### ISSUE TITLE
Static UI: Homepage Feedback

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1369]
- [x] Replace banner and news images with smaller versions Kim sent
- [x] Can you put the top border on the bottom of the nav bar instead of the top of the banner. My bad - but I think it looks weird that the border doesn't stay on the navbar if the top nav is sticky
- [x] The file repo link is working. Can you link the "Browse the data" button to it
- [x] can you make the top and bottom padding here 10px instead of 20px
<img width="568" alt="Screen Shot 2020-04-24 at 10 06 20 AM" src="https://user-images.githubusercontent.com/18424138/80221424-43e80080-8613-11ea-956f-57374b0db357.png">

- [ ] can you minimize the space between the two rows of bottom callouts a bit, like approx 30px space
<img width="623" alt="Screen Shot 2020-04-24 at 10 08 02 AM" src="https://user-images.githubusercontent.com/18424138/80221639-94f7f480-8613-11ea-8446-640bb81c9623.png">

- [x] In terms of html, can you use less headings for the elements and just style using the "as" prop, as in `Typograph as="span" ... (ask Minh if need be)
<img width="948" alt="Screen Shot 2020-04-24 at 9 56 40 AM" src="https://user-images.githubusercontent.com/18424138/80220493-eb643380-8611-11ea-9db4-7fab5bf22a05.png">
<img width="893" alt="Screen Shot 2020-04-24 at 9 56 06 AM" src="https://user-images.githubusercontent.com/18424138/80220534-fe770380-8611-11ea-8fce-2406f360fe89.png">

**Comment by wajiha-oicr** [comment]
I believe I have gotten a fix for the inconsistent padding, (https://github.com/icgc-argo/platform-ui/issues/1370) I have a PR up for that just as an fyi

**Comment by kcullion** [comment]
@wajiha-oicr @rosibaj this looks good to me!

**Comment by rosibaj** [comment]
@wajiha-oicr is this still feature flagged? We can remove the feature flag now as beta testing is completed.

**Comment by wajiha-oicr** [comment]
yes, I can remove the feature flag in a new change

**Comment by wajiha-oicr** [comment]
https://github.com/icgc-argo/platform-ui/issues/1429
