### ISSUE TITLE
🐛 Inconsistent padding on the homepage

### ISSUE THREAD

**Issue by wajiha-oicr** [icgc-argo/platform-ui#1370]
## Describe the bug
Occasionally, the homepage will render with different padding styles

## Steps To Reproduce
- go to the homepage, navigate to another page within the site, navigate back again
- rinse and repeat, padding is showing up differently upon different page loads

## Expected behaviour
Padding should remain consistent

**Comment by kcullion** [comment]
Looks good on QA, thanks @wajiha-oicr
