### ISSUE TITLE
🐛 File Repo tooltip causing a second scrollbar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1381]
## Describe the bug
In the file repo, when I hover over the lock in the far right column of the table, the tooltip appears but it creates a second scrollbar and jumping behaviour
<img width="227" alt="Screen Shot 2020-04-24 at 10 43 08 AM" src="https://user-images.githubusercontent.com/18424138/80225177-b6a7aa80-8618-11ea-86c7-d4cc320b2444.png">

This happens when logged in too
<img width="301" alt="Screen Shot 2020-04-24 at 10 50 29 AM" src="https://user-images.githubusercontent.com/18424138/80225743-772d8e00-8619-11ea-8337-a22c1d0f587a.png">

## Expected behaviour
The tooltip can span onto two lines if needed so it isn't so long

**Comment by rosibaj** [comment]
@kcullion i think this is the bug i experiences that i asked you and ann about ( but i couldnt figure out what was happenin!

**Comment by kcullion** [comment]
@rosibaj oh yes! it's a weird jumpy behaviour

**Comment by rosibaj** [comment]
lgtm 
- no more double scrollbar
- no more weird falshing on toolup

looks great thanks @anncatton !
