### ISSUE TITLE
File Repository: Chart updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1397]
After our demo feedback, we made some changes to the File repo charts to make them fill the space better, and separated the stats into it's own bar as they weren't necessarily related to the charts.

Please make the following UI updates: Zeplin: https://zpl.io/Vk6MGxg
- [ ] Remove stats
- [ ] Add chart title
- [ ] Add x-axis and y-axis lines with the labels
- [ ] bars go all the way to the bottom of the x-axis line, only rounded at top
- [ ] chart fills full space. the bars get wider when there aren't as many
- [ ] tooltips haven't changed, but here's the mock in case: https://zpl.io/aNQOmQZ

<img width="1165" alt="Screen Shot 2020-04-28 at 10 08 10 AM" src="https://user-images.githubusercontent.com/18424138/80497254-32b33280-8938-11ea-8c3b-9353b8d9a1d5.png">

**Comment by kcullion** [comment]
Looks great @anncatton! Just a couple small things
- [ ] for consistency with the page, can you capitalize the titles like: 
Files by Data Type, Files by Primary Site, Files by Program

- [ ] Tooltips, can you add the word "files" after the numbers (all charts)
<img width="188" alt="Screen Shot 2020-05-01 at 11 23 45 AM" src="https://user-images.githubusercontent.com/18424138/80816831-3ea02e00-8b9e-11ea-9d3d-4ee7195e99d0.png">

**Comment by kcullion** [comment]
looks great, thanks @anncatton !

**Comment by rosibaj** [comment]
@anncatton can you please add the tag label to this ticket?
