### ISSUE TITLE
File Repository: Implement stat bar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1398]
The stats have been removed from the charts and put into a stat card.

Some of the icons can be found in storybook, please add the missing ones here too: https://argo-ui-storybook.netlify.app/?path=/story/uikit-icon--all-icons

Zeplin: https://zpl.io/Vk6MGxg

<img width="1161" alt="Screen Shot 2020-04-28 at 10 26 29 AM" src="https://user-images.githubusercontent.com/18424138/80499391-eb7a7100-893a-11ea-9c8c-24dd7e7b95fd.png">

**Comment by kcullion** [comment]
awesome @anncatton !
can you just make all icons (except primary sites) smaller - width:16px;
<img width="1183" alt="2020-05-01_1130" src="https://user-images.githubusercontent.com/18424138/80817583-b458c980-8b9f-11ea-8c3a-063bcb2d72de.png">

**Comment by kcullion** [comment]
looks great, thanks @anncatton

**Comment by rosibaj** [comment]
@anncatton can you please add the ui tag label to this ticket  before i can move it into the release?
