### ISSUE TITLE
Static UI: DCC Team page

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1400]
Build the DCC team page
zeplin: https://zpl.io/bA1wxXB

- Ask Kim for the banner image
- The styles are similar to the privacy page that was built but not used, in case you can reuse any of that. 
- Title bar component: https://argo-ui-storybook.netlify.app/?path=/story/uikit-titleborder--fixed-width

**Comment by rosibaj** [comment]
@ciaranschutte can i please get Kevin Hartmann moved to alumni?

**Comment by kcullion** [comment]
@ciaranschutte can you also make the background white instead of light grey?

**Comment by kcullion** [comment]
looks good @ciaranschutte, thanks

**Comment by rosibaj** [comment]
verified on production deplpy! thanks @ciaranschutte !
