### ISSUE TITLE
Hide Dashboard buttons for now

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1401]
![image](https://user-images.githubusercontent.com/15824252/80631634-05dc4980-8a24-11ea-939d-10b12194c8af.png)

**Comment by wajiha-oicr** [comment]
@rosibaj @hlminh2000 is this significant enough to hide behind a feature flag? This is small so I was just thinking of removing the buttons altogether and then using the file history to grab the code again when we're ready for the buttons?

Or just comment it out?

**Comment by rosibaj** [comment]
Comment out? Feature flag seems overkill. @hlminh2000 ?

**Comment by hlminh2000** [comment]
yeah just comment out :)

**Comment by rosibaj** [comment]
verified in production
