### ISSUE TITLE
Dashboard: Coming soon for chart cards

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1425]
Can you change the "No data found." text to "Coming Soon." for these two cards
<img width="831" alt="2020-05-04_1342" src="https://user-images.githubusercontent.com/18424138/80995988-1e29db00-8e0d-11ea-8229-d790c5ce942c.png">

**Comment by rosibaj** [comment]
lgtm thanks @wajiha-oicr !

**Comment by rosibaj** [comment]
confirmed on production
