### ISSUE TITLE
Homepage: Content updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1427]
Just a few updates to the homepage when we know the final content. 

- [x] implement top and bottom padding to the parent container of the bottom 6 callouts so that the background globe is a bit more visible

- [x] hide this button for release day
<img width="1086" alt="2020-05-28_1608" src="https://user-images.githubusercontent.com/18424138/83189458-1e14b680-a0ff-11ea-8f67-99c0dc51829f.png">

- [x] Please  hide this section for release day
<img width="1256" alt="Screen Shot 2020-05-04 at 2 23 52 PM" src="https://user-images.githubusercontent.com/18424138/80999586-e9b91d80-8e12-11ea-8f8b-002b7ffb4b45.png">

- [x] Update latest news - just one sentence and keep the bottom sentence (If you have feature suggestions, feedback, or want to report a bug, please contact us.)

**Announcement**: We are excited to announce the soft launch of the ARGO Data Platform. The team is working hard to roll out features such as clinical data submission and the file repository for browsing and downloading data. Check back soon for updates!

Link updates have been moved to: https://github.com/icgc-argo/platform-ui/issues/1506

# From Minh:
- The button hiding should be done by hooking into the `FEATURE_REPOSITORY_ENABLED` feature flag
- The content stats section hiding can be hooked into a `FEATURE_LANDING_PAGE_STATS_ENABLED` feature flag

**Comment by wajiha-oicr** [comment]
is this still blocked by the news updates?

**Comment by kcullion** [comment]
@wajiha-oicr I think this is an important to get done for launch... @rosibaj maybe we can write a news blurb that is a message like what Christina just said - more of a "coming soon" warning?

**Comment by rosibaj** [comment]
**Announcement**: We are excited to announce the soft launch of the ARGO Data Platform, the next step from the ICGC 25K Data Portal (link). Our team is working hard to roll out the first release of Clinical Dat Submission, including features such as clinical data submission and the file repository for browsing and downloading molecular data. Check back soon for updates!

**Comment by kcullion** [comment]
here's a zeplin link too: https://zpl.io/2yZk3dG

**Comment by kcullion** [comment]
Thanks @wajiha-oicr 
For the news block, I saw some weird formatting - like using times new roman. Then I refreshed and it looked better but when I refresh or go back to the homepage, I see that wrong font for a split second. Is the font applied to this block differently?

**Comment by kcullion** [comment]
can't seem to recreate the font thing. So this looks good to me!

**Comment by rosibaj** [comment]
lgtm! thanks @wajiha-oicr !!

**Comment by rosibaj** [comment]
Confirmed on production 
- link to file repo hidden
- announcement is there! 

thanks @wajiha-oicr !
