### ISSUE TITLE
🐛 Redirecting to old login page

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1428]
## Describe the bug
When logging out from certain program pages, the user is redirected to the old login page or is stuck on the loader.

## Steps To Reproduce
For example, go to to CYUNG-CA dashboard and log out. The page is frozen with the dna loader

Or go to RAWR-CA dashboard and log out. User is quickly redirected to old login page https://platform-ui.qa.argo.cancercollaboratory.org/login?redirect=/submission/program

## Expected behaviour
They should be redirected to the new homepage (never to this login page)

**Comment by anncatton** [comment]
Looks like this is partially linked to #1357

**Comment by rosibaj** [comment]
@anncatton if you find both are related, we can pull both in.

**Comment by anncatton** [comment]
I don't think the issues are related, I think this ticket might be describing 2 separate issues. @hlminh2000 pointed out the loader issue recently.

**Comment by hlminh2000** [comment]
yeah I think they're separate...

**Comment by anncatton** [comment]
The PR for this does not entirely fix the endless loader issue, that will be addressed in https://github.com/icgc-argo/platform-ui/issues/1357

**Comment by rosibaj** [comment]
@anncatton if i click the link in the ticket i still get sent to the old page...

**Comment by rosibaj** [comment]
confirmed on prod logout goes to homepage
