### ISSUE TITLE
Integrate Arranger query bar

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1430]
Integrate Arranger filter bar into the ARGO UI

- arranger has a SqonView (or something like that) that renders the sqon visually, it can be pulled in for this. The arranger package is @arranger/components
- make a component that uses that component, do all the styling and what not to match argo
- use storybook, with a sample sqon

**Comment by anncatton** [comment]
Empty filters view is visible on File Repository page, with filters is available on Storybook

**Comment by rosibaj** [comment]
@anncatton can you please label the ocrrect version tag here?
