### ISSUE TITLE
Dashboard: Donor table, remove links for now

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1431]
For the release, we won't have donor page...let's remove these links on the ids for now.

<img width="561" alt="2020-05-04_1553" src="https://user-images.githubusercontent.com/18424138/81007526-62be7200-8e1f-11ea-81b0-314a01edcb84.png">

**Comment by rosibaj** [comment]
tested on dev - lgtm.  @ciaranschutte can we please move to qa?

**Comment by rosibaj** [comment]
nvm i see it is tagged now but not moved on board. moving this.

**Comment by rosibaj** [comment]
verified on prod
