### ISSUE TITLE
User Profile: update links

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1442]
On the user profile page,  /user

- [ ] Please link  HOW TO USE YOUR API TOKEN WITH ICGC ARGO TOOLS › to https://docs.icgc-argo.org/docs/data-download

- [ ] Please link "view files" to the file repository page /repository

<img width="1538" alt="2020-05-05_1508" src="https://user-images.githubusercontent.com/18424138/81105668-47686b00-8ee2-11ea-8b58-d35ddb0b18e1.png">

**Comment by rosibaj** [comment]
amazing.  thanks @wajiha-oicr !

**Comment by rosibaj** [comment]
confirmed on prod
