### ISSUE TITLE
Move Maintenance page outside Kubernetes deployment

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1452]
## Detailed Description
Right now the maintenance page that exists: https://platform-ui.qa.argo.cancercollaboratory.org/maintenance is served from the kubernetes pod.   In the case of an actual maintence/issue, this page is not reachable. 
We need to: 
- [ ] Make sure this is a static html/css page
- [ ] Make sure the static page can be served from F5 or nginx (confirm with IT which one)

## Implementation
- Create a static export from the UI repo using `next export`

**Comment by hlminh2000** [comment]
I've created some scripts to export the static maintenance page from the UI repo. A sample view of this can be found at: https://argo-maintenance.netlify.app/ (this is public, hosted with a manual upload for demo only)

The static bundle has also been uploaded here: https://drive.google.com/open?id=1K-y53Os_6Dq3chB6-l9bp1hJYgyOcLX5

**Comment by rosibaj** [comment]
@hlminh2000 page looks great!

**Comment by hlminh2000** [comment]
once code is approved and merged, here's the next step: https://github.com/icgc-argo/platform-ui/pull/1465

**Comment by hlminh2000** [comment]
This ticket should not affect any existing stuff, so as long as there is no resulting break to UI, it's good to go. Hosting of the actual site will be part of above mentioned ticket.

**Comment by rosibaj** [comment]
UI looks good to me so I will close this ticket.  Noted the above tracking ticket and has been added to sprint.
