### ISSUE TITLE
Dashboard: Donor table update - implement loader

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1455]
When I register samples or submit clinical data - when the donor dashboard updates I see:

Before update: I see my list of donors
During update: donor table changes to the empty state
<img width="1322" alt="Screen Shot 2020-05-11 at 10 49 32 AM" src="https://user-images.githubusercontent.com/18424138/81577232-2fc43300-9377-11ea-86dc-ae30690cd445.png">
When updated: donor table loads with list of donors and their updates
<img width="1333" alt="Screen Shot 2020-05-11 at 10 49 37 AM" src="https://user-images.githubusercontent.com/18424138/81577301-410d3f80-9377-11ea-8eda-ec8537b4f3dd.png">

Can you implement the dna loader instead of switching to the empty state. The user should see the old table, with loader on top and then the new table content loads in when ready.

**Comment by jaserud** [comment]
Currently the only thing that seems to be causing this is https://github.com/overture-stack/rollcall/issues/35

**Comment by jaserud** [comment]
Previously I could consistently create the flash to empty state and back by registering new samples and submitting clinical data quickly after one another (basically increase the chances that a poll would hit while the previous index is unreleased and the new one hasn't released)

Latest rollcall release 2.3.0(https://github.com/overture-stack/rollcall/pull/38) seems to have fixed this issue as I can't make it happen anymore. Let mew know if some other series of actions produces the issue.

**Comment by rosibaj** [comment]
@kcullion can you help me test out this issue to see if you can make it happen?

**Comment by kcullion** [comment]
sure I will have a look on QA right now

**Comment by kcullion** [comment]
@rosibaj @jaserud I tested a sample registration file and a donor file upload and I didn't see the blank table on the dashboard. 
Question - do you think we should display the dna loader over the table until the values are updated? Like don't show the old values at all?

**Comment by jaserud** [comment]
@kcullion originally I was thinking of doing that too. But after some thought, I realised a 30 sec loader might be a bit inconvenient. It would mean you have to wait 30 secs to see your dashboard even if you made no updates.

**Comment by kcullion** [comment]
@jaserud yeah that wouldn't be ideal, so yes, we shall leave this :) Thanks!
