### ISSUE TITLE
Dashboard: Table header label change

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1456]
The heading "core fields" is a bit misleading with the way the core completeness is calculated. 
For example, if one core field is added, the calculation goes down by 20%. 

For clarity and to be consistent with the documentation, let's change the heading from "Core Fields" to "Core Completeness"

![2020-05-13_1039.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/b9677a40-183e-4665-bdf8-f8b24cff5c17)

**Comment by jaserud** [comment]
@kcullion can we call it `Core Completion` for consistency, that's what we call it in clinical.

**Comment by kcullion** [comment]
Thanks @jaserud ..we've been calling it core completeness in the docs site: https://docs.qa.argo.cancercollaboratory.org/docs/clinical-data-validation-rules

Does the user see what is in clinical ever? @rosibaj should we change all the docs references to completion?

**Comment by jaserud** [comment]
hmm, User will only see this if they use the back end api and even then they won't see a percentage, they see a breakdown. I was just thinking out loud. I think it makes sense to follow whats in the docs so I'll leave it.

**Comment by kcullion** [comment]
@jaserud completion is a tiny bit shorter, so I lean towards that. Trying to decide which word I like better. I'm a bit indifferent on it - it won't be hard to change in the docs. So let's let @rosibaj decide! haha

**Comment by kcullion** [comment]
Decision: for this header we will use Completion, because "completeness" suggests the donor should be 100%. 
In the docs I have changed some instances of completeness to completion - when we are not talking about being at 100%

**Comment by kcullion** [comment]
Looks good to me! Thanks @jaserud

**Comment by rosibaj** [comment]
LGTM THANKS @jaserud !

**Comment by rosibaj** [comment]
confirmed on production
