### ISSUE TITLE
🐛 Can only see 20 rows on clinical files

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1471]
![image](https://user-images.githubusercontent.com/15824252/82610425-5743a880-9b8c-11ea-88e1-6b94440448ea.png)

**Comment by rosibaj** [comment]
@ciaranschutte one small issue: 
![image](https://user-images.githubusercontent.com/15824252/83469004-75db5680-a44c-11ea-9000-ce3c8502a0c4.png)

**Comment by ciaranschutte** [comment]
on it
