### ISSUE TITLE
Unclear Behaviour while validating

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1474]
When uploading files, could the spinner actually says "Validating"?  It's not clear that validation takes place during the upload step. It seems like upload takes long 

- [ ] when user uploads files, the state of the button would change to the animated loader icon + the label "Validating files"
<img width="272" alt="Screen Shot 2020-08-18 at 1 34 56 PM" src="https://user-images.githubusercontent.com/18424138/90546303-dc246b00-e157-11ea-9821-3f35641802d4.png">

- [ ] when the user clicks the "validate submission" button, the state of the button would change to the animated loader icon + the label "Validating Submission"
<img width="270" alt="Screen Shot 2020-08-18 at 1 35 00 PM" src="https://user-images.githubusercontent.com/18424138/90546311-de86c500-e157-11ea-8fcb-34151db889ad.png">

See buttons in zeplin: https://zpl.io/2p96NXQ

**Comment by kcullion** [comment]
@rosibaj I thought we avoided changing the word on the loader for a reason? Can't recall exactly but I do like the idea of changing that word to give user feedback depending on their action.

**Comment by rosibaj** [comment]
@kcullion i think Christinas main feeback here is that its not 100% clear to the user that the page is actually working on validations (instead of a button freezing). 

Maybe its not a word on the button, but something else to indicate that?

**Comment by kcullion** [comment]
Oh sorry, I though it was the dna loader you were talking about. Maybe we do the dna loader instead of the button text changing, which is not as obvious

**Comment by kcullion** [comment]
@rosibaj I updated this ticket with some mocks. Can you have a look to see if it's what you're looking for?

**Comment by kcullion** [comment]
@ciaranschutte and I discussed this, we are going to make both buttons (white or purple) have a consistent "working on it" style. So the copy and icon are dark purple #523785...and the background is medium grey #DCDDE1
![image (65)](https://user-images.githubusercontent.com/18424138/114571684-da5a6b00-9c44-11eb-8511-c0c92a8ebf5d.png)

**Comment by ciaranschutte** [comment]
dev tested: :heavy_check_mark:

**Comment by rosibaj** [comment]
Verified on QA wqhile testing dictionary uploads. looks great thank you @ciaranschutte !

**Comment by rosibaj** [comment]
@ciaranschutte or @joneubank can i get a version number on this ticket to move it forward please?
