### ISSUE TITLE
Update logout behavior for public pages.

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1485]
- Logout from a public page, you get redirected to the homepage

# Expected behavior 
Logout from a public page should behave the same as login (i.e redirected to the same page)

**Comment by ciaranschutte** [comment]
tested in dev, looks good

**Comment by rosibaj** [comment]
Tested May 18, 2021  9:03 pm
- loggin and went to file repository page. logged out and was rediretcted to logged out version of the file repository page
- logged in and went to the contact page.  logged out and was redirected after logout to the contact page. 

Looks great thank you very much @ciaranschutte !
