### ISSUE TITLE
Toast when a program is created

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#149]
Create a Toast Manager 

- close after a period of time
- global array of toast data
- toasts the toast
- Use the toaster to show the create programs success message

Implement the toast manager in the context of the **program creation**
- [ ] User clicks create program 
- [ ] The program is created. 
- [ ] The user is navigated to the program list page, and the newly created program is in the list.
- [ ] A Success toast appears at the top of the page that says:
`<Program.ShortName> was successfully created!`, where the program shortname is dynamically defined to be the program that was just created.
![Screen Shot 2019-07-30 at 11 26 56 AM](https://user-images.githubusercontent.com/18424138/62144367-aba92f00-b2bf-11e9-87c0-4a0db65282cb.png)

**Program edit** (doesn't navigate away from the page):
- [ ] If the user makes a change, and saves it - there is no indication that it has worked. Expected behaviour: 
- User makes change
- Presses Save button
- Save button disables and page scrolls up (or reloads the page)
- Success toast appears that indicates changes have been saved. "Your changes have been saved."
<img width="449" alt="Screen Shot 2019-07-18 at 10 52 01 AM" src="https://user-images.githubusercontent.com/18424138/61467737-24b49800-a94a-11e9-8218-b53f6b4e60fb.png">

**Comment by rosibaj** [comment]
Testing results:
* Created ROSI-CA and ROSY-CA.  As far as i can tell, they created correctly, but did not get the correct toast.  Will add more details once auth deplopy is worked out.

**Comment by hlminh2000** [comment]
@rosibaj back-end is fixed so looks like this is something wrong with the UI. I'm picking this up again :)

**Comment by rosibaj** [comment]
Cannot successfully create a program.

Video of Issue:
https://drive.google.com/file/d/1wtwV_TITJtqm9rbqN2HxyBqDMRwF0-wO/view
![image (5)](https://user-images.githubusercontent.com/15824252/63614541-535d0880-c5b1-11e9-8c4c-3fcc77cebdc9.png)


@hlminh2000 I cannot have this pass on QA at the moment bc i cannot actually see a program successfully created (issues above)
