### ISSUE TITLE
File Repository: Add selected file number to interface and button dropdown

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1490]
**Step 1: File repo has been queried. No files have been selected**
Zeplin: https://zpl.io/beE6pdq
- [ ] The query filters affect the stats and charts
- [ ] Nothing is added to table file counter
- [ ] A blue label, "All files" appears in the download button dropdown (this is not a button, just an indication of what the user is downloading)
<img width="1191" alt="2020-05-28_1508" src="https://user-images.githubusercontent.com/18424138/83182963-236d0380-a0f5-11ea-9d16-768caa47fa44.png">

**Step 2: The user selects 4 files from this queried list.**
Zeplin: https://zpl.io/ang54Zn
- [ ] The query filters affect the stats and charts, but the file selection does not
- [ ] A blue label,  "(# files selected)" shows up in the table file counter
- [ ] A blue label, "# files selected" appears in the download button dropdown (this is not a button, just an indication of what the user is downloading)
<img width="1192" alt="2020-05-28_1507" src="https://user-images.githubusercontent.com/18424138/83182916-12bc8d80-a0f5-11ea-84ed-d4f4f200ab84.png">

**Step 3: The user selects ALL files from this queried list.**
Zeplin: https://zpl.io/br59Qo5
- [ ] The query filters affect the stats and charts, but the file selection does not
- [ ] A blue label, "(All files selected)" shows up in the table file counter
- [ ] A blue label, "All files" appears in the download button dropdown (this is not a button, just an indication of what the user is downloading)
<img width="1197" alt="2020-05-28_1511" src="https://user-images.githubusercontent.com/18424138/83183262-88c0f480-a0f5-11ea-83c4-0da59144f3b3.png">

**Please note:** the selection for the table also has a light blue background for the selected row. I did not include that in the mockups as it's very time consuming. But please leave the blue background for selection!

**Comment by kcullion** [comment]
@rosibaj I finished the mocks for this ticket. Please review and re-assign as you wish.

**Comment by rosibaj** [comment]
@wajiha-oicr looks great!! thank you!!

**Comment by kcullion** [comment]
looks great @wajiha-oicr !
