### ISSUE TITLE
Replace maintenance graphic

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1500]
We are going to replace the graphic on the maintenance pages with this one. Ask Kim for svg

<img width="405" alt="Screen Shot 2020-05-28 at 9 32 03 AM" src="https://user-images.githubusercontent.com/18424138/83147883-3caa8b80-a0c6-11ea-9872-74f1a1554329.png">

**Comment by hlminh2000** [comment]
static deploy has been updated at https://argo-maintenance.netlify.app/. Also updated the bundle on google drive for IT to grab ([same url posted before)](https://drive.google.com/open?id=1K-y53Os_6Dq3chB6-l9bp1hJYgyOcLX5)

**Comment by kcullion** [comment]
thanks @hlminh2000. Did you update this page too? https://platform-ui.qa.argo.cancercollaboratory.org/maintenance

**Comment by hlminh2000** [comment]
@kcullion We'll only be showing maintenance when there is some outage, during which time we have to assume no back-end is available, which means no functionality is available. I'm only leaving the `/maintenance` path in the app to simplify the build process, but end users are never presented with that path.

**Comment by rosibaj** [comment]
lgtm thanks @hlminh2000 !
