### ISSUE TITLE
Update Documentation links on Platform

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1506]
The documentation pages were put into folders, so we will have to update the following links:

**Homepage:**
- [x] How to Apply button: /docs/data-access/data-access
- [x] How to Download button: /docs/data-access/data-download
- [x] About our Workflows button: /docs/analysis-workflows/dna-pipeline
- [x] Publication Guidelines callout: /docs/data-access/publication-guidelines
- [x] Release Notes callout: /docs/release-notes/data-releases
- [x] Programmatic APIs callout: /docs/data-access/programmatic-apis
- [x] Data Submission callout: /docs/submission/submission-overview
- [x] QA site: I noticed the Documentation callout links to the production docs url and the footer links to the QA version of the doc site. Just want to make sure all of these links are using that environment variable @hlminh2000 set up.

**User Profile page**
- [x] HOW TO USE YOUR API TOKEN WITH ICGC ARGO TOOLS: /docs/data-access/data-download
- [x] Hide this "View Files" link for now (repo won't be in production)
<img width="643" alt="2020-05-28_1715" src="https://user-images.githubusercontent.com/18424138/83194537-cc702a00-a106-11ea-9f54-84df1d33082b.png">

- [x] When no DACO access, change the sentence to:` Learn more about the DACO application process, or apply for DACO approval.` and link "DACO application process" to: /docs/data-access/data-access  and "apply for DACO approval" links to: https://icgc.org/daco
<img width="753" alt="Screen Shot 2020-05-28 at 5 28 11 PM" src="https://user-images.githubusercontent.com/18424138/83195888-f6c2e700-a108-11ea-9386-f91be5d7a836.png">

**Contact page (left content links):**
- [x] title update...this should be "Accessing Controlled Data"
<img width="626" alt="2020-05-28_1643" src="https://user-images.githubusercontent.com/18424138/83191752-8add8000-a102-11ea-97f3-38989326d264.png">

- [x] "applying for access to controlled data" links to: /docs/data-access/data-access
- [x] How to download data: /docs/data-access/data-download
- [x] change `Score Client` to `score-client` 
- [x] hide "Troubleshooting data download" link for now, as we don't have that page and replace with: "User profile and API token" linking to: /docs/data-access/user-profile-and-api-token
- [x] under Submitting Data section, link "Get started" to /docs/submission/submission-overview
- [x] Register samples to: /docs/submission/registering-samples
- [x] Submit clinical data to: /docs/submission/submitting-clinical-data
- [x] Submit molecular data to: /docs/submission/submitting-molecular-data

**Program Services modal**
- [x] this links to /docs/data-access/data-access
<img width="734" alt="Screen Shot 2020-05-28 at 4 53 40 PM" src="https://user-images.githubusercontent.com/18424138/83192674-e0fef300-a103-11ea-9a9f-bd4c7f3573e8.png">

**Program Dashboard**
- [x] Title bar help link: /docs/submission/submitted-data
<img width="1216" alt="2020-05-28_1655" src="https://user-images.githubusercontent.com/18424138/83192955-4226c680-a104-11ea-8140-c239d83ecf08.png">

- [x] Completed Core Clinical Data card link: /docs/submission/submitting-clinical-data
- [x] Molecular Data Summary card link: /docs/submission/submitting-molecular-data
- [x] Donor Data Summary card link. Change the label of this link to "Read more about the donor data summary"
and make it link to: /docs/submission/submitted-data

**Registering Samples section**
- [x]  Title bar help link:/docs/submission/registering-samples
<img width="1385" alt="2020-05-28_1703" src="https://user-images.githubusercontent.com/18424138/83193686-764eb700-a105-11ea-9a23-dada2afefbf7.png">

**Submit Clinical Data section**
- [x]  Title bar help link: /docs/submission/submitting-clinical-data
<img width="1378" alt="2020-05-28_1705" src="https://user-images.githubusercontent.com/18424138/83193795-a1d1a180-a105-11ea-8ca1-b2d18e89bb68.png">

**Manage Program section**
- [x] Title bar help link: /docs/submission/managing-program-access
<img width="1361" alt="2020-05-28_1707" src="https://user-images.githubusercontent.com/18424138/83193953-da717b00-a105-11ea-9d12-ffa5b4088c4a.png">

**Welcome to program banner**
- [x] Change second sentence to `If you have any questions, please check out our documentation for help with data submission, data access and program management.`
- [x] data submission links to: /docs/submission/submission-overview
- [x] data access links to: /docs/data-access/data-access
- [x] program management links to: /docs/submission/managing-program-access

**Comment by ciaranschutte** [comment]
New folder structure has to be merged for these links to work
https://github.com/icgc-argo/argo-docs/commit/e32071e445f728c0c5c199404e75f6a394bdc161

**Comment by rosibaj** [comment]
@ciaranschutte folders should be merge with latest docs release!

**Comment by ciaranschutte** [comment]
@ciaranschutte use content branch as qa

**Comment by rosibaj** [comment]
@ciaranschutte one more spot:  
![image](https://user-images.githubusercontent.com/15824252/83694967-279e9280-a5c7-11ea-8220-a1b080ac3f5f.png)
 
Was this updated?

**Comment by kcullion** [comment]
@rosibaj @ciaranschutte I tested all the links and they all work! Thanks Ciaran!

I do notice that trailing slash gets added still....but I think it's ok since I fixed all the doc links to be absolute

**Comment by rosibaj** [comment]
also was not able to break anything! @hlminh2000 can we get moved to production please?

**Comment by rosibaj** [comment]
confirmed on production!
