### ISSUE TITLE
Add dictionary version number to UI links

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1510]
Change instruction number 1 in:

- [ ] Registering Samples
change wording to remove "the latest" and add version number instead:
`1. Download the registration template and format it using **Data Dictionary v48.0**.`
<img width="1231" alt="2020-05-29_1431" src="https://user-images.githubusercontent.com/18424138/83293079-3ba65680-a1b9-11ea-9d84-3260c6ce5afa.png">

- [ ] Submit Clinical Data
change wording to remove "the latest" and add version number instead:
`1. Download the clinical file templates and format them using **Data Dictionary v48.0**.`
<img width="1335" alt="2020-05-29_1428" src="https://user-images.githubusercontent.com/18424138/83292885-e5391800-a1b8-11ea-8470-0e9192049888.png">

**Comment by rosibaj** [comment]
@wajiha-oicr lgtm! thank you!
