### ISSUE TITLE
Implement File ID Search

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/platform-ui#1517]
Autocomplete search with all applicable fields in https://github.com/icgc-argo/platform-api/blob/develop/compose/file_centric/file_mapping.json

Dropdown will display `object_id`, `study_id` (`program_id`) and `file.name`
Integrate with Filters context.

**Comment by rosibaj** [comment]
Couple things:
- [ ] 1
![image](https://user-images.githubusercontent.com/15824252/84920652-705b4e80-b091-11ea-995c-3b545bd9ba0a.png)

- [ ] 2
![image](https://user-images.githubusercontent.com/15824252/84920692-80732e00-b091-11ea-9b08-0aedc0af8537.png)

**Comment by anncatton** [comment]
@rosibaj is the windows issue in Chrome?

**Comment by anncatton** [comment]
Also will include:
- case-insensitive search
- decrease search icon size
