### ISSUE TITLE
Optimize for SEO - page titles

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1537]
We can at least add a` <title>` tag for each page. If there's anything else that can be done with metadata, keywords etc - that would be nice.

For example - the docs site does a better job at showing what page the user is on:
<img width="1025" alt="2020-06-04_1016" src="https://user-images.githubusercontent.com/18424138/83768480-d638e680-a64c-11ea-9a7e-7431725b7ec9.png">

Suggestion for format, based on what page user is on:
ICGC ARGO | Homepage
ICGC ARGO | PACA-CA Dashboard
ICGC ARGO | PACA-CA Clinical Submission
ICGC ARGO | The Team

## Possible Implementation 
- helmet library

**Comment by rosibaj** [comment]
@wajiha-oicr can we get this merged for release?

**Comment by kcullion** [comment]
this looks good in staging @blabadi 

My only question for @wajiha-oicr is if this is dynamic? Like if we add a section, will the page title take care of itself?

I only ask because I noticed some of the titles don't match the section titles like "Profile" instead of "Profile and Tokens" or "Clinical Submission" instead of "Submit Clinical Data". But maybe it's not controlled by the menu titles

**Comment by wajiha-oicr** [comment]
> this looks good in staging @blabadi
> 
> My only question for @wajiha-oicr is if this is dynamic? Like if we add a section, will the page title take care of itself?
> 
> I only ask because I noticed some of the titles don't match the section titles like "Profile" instead of "Profile and Tokens" or "Clinical Submission" instead of "Submit Clinical Data". But maybe it's not controlled by the menu titles

To clarify your question, the page titles are added manually. Some details are pulled automatically (i.e. the program name), but the overall naming scheme is not.
