### ISSUE TITLE
Mobile Header: issue with cookie notice 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1543]
![image](https://user-images.githubusercontent.com/15824252/83807039-6cd2cb00-a680-11ea-802f-4ad76e612670.png)

**Comment by wajiha-oicr** [comment]
once the nav-bar is fully responsive, this issue should be fixed as a result

**Comment by wajiha-oicr** [comment]
@rosibaj I believe in QA this issue is fixed thanks to https://app.zenhub.com/workspace/o/icgc-argo/platform-ui/issues/57, but please test it ( private browsing window should do the trick) and let me know! !!

**Comment by wajiha-oicr** [comment]
Scratch my previous comment, something is still funky one very small phone screens!

**Comment by rosibaj** [comment]
@wajiha-oicr looks great on most major phone screens! wecan consider this resolved. thank you!
