### ISSUE TITLE
Static UI: Clinical Timeline: Treatment tab update

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1547]
Theres a couple changes to the way the treatment files are displayed on the donor page, to account for a treatment combining multiple treatment types and multiple drugs 
Zeplin: https://zpl.io/VY4OJBn

- [ ] 1. The treatment file fields will be displayed in two tables at the top
- [ ] 2. Each supplement file will have it's own table section. Eg. Chemo table
- [ ] 3. Eg. radiation table

<img width="1140" alt="2020-06-05_1410" src="https://user-images.githubusercontent.com/18424138/83909341-9b12e200-a736-11ea-9bef-9a366887c576.png">

**Comment by ciaranschutte** [comment]
is this page active? Can't seem to be find it.
currently using mock data, so want to make sure I'm using correct data @rosibaj

**Comment by rosibaj** [comment]
@ciaranschutte what do you mean active? this is only in storybook right now

**Comment by ciaranschutte** [comment]
@rosibaj answers my q ty

**Comment by ciaranschutte** [comment]
https://606b64bb5dc3a70007789574--argo-ui-storybook.netlify.app/?path=/story/components-pages-submission-system-donor-clinicaltimeline--basic

tested dev looks good
examples:
- 1 col with sample
- 1 col data
- 2 col data
- treatments (last treatment item)
