### ISSUE TITLE
Static UI: File entity page version 1

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1549]
Build the static cards for the simple version of the file entity page.
Zeplin: https://zpl.io/VYgdOOw

- [ ] 1. Download buttons: file button is disabled when logged out or when user doesn't have access to download it
- [ ] 2. File summary card
- [ ] 3. Data & Analysis info
- [ ] 4. Associated donors. Display tabs along the side if the file is associated to multiple donors, hide the entire tab component if the file is only associated to one donor (would just display donor table and associated samples and specimens)
- [ ] 4. links in the associated specimens and samples section will link to that donor page and scroll down to the clinical timeline card with that specimen tab active 
- [ ] 5. Downstream analysis files table

<img width="1402" alt="2020-06-05_1555" src="https://user-images.githubusercontent.com/18424138/83918066-f9938c80-a745-11ea-8df4-ad3b68d8c7d9.png">

**Comment by rosibaj** [comment]
@wajiha-oicr is there a storybook link for this?

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr is there a storybook link for this?

yes you can view it here! https://argo-ui-storybook.netlify.app/?path=/story/components-pages-file-entity--basic

**Comment by rosibaj** [comment]
just one small typo:
![image](https://user-images.githubusercontent.com/15824252/86612348-004c3400-bf7e-11ea-91b8-d51e061e15b9.png)

**Comment by rosibaj** [comment]
lgtm thanks @wajiha-oicr !
