### ISSUE TITLE
File repo - SQON feedback

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1558]
- [x] apply a min-height to the query bar so that there isn't a slight jump when filters get applied

- [x] first time applying query it gets funky blip/flash.  after that its fine
https://drive.google.com/file/d/1QgiAHZSyobBynmiVZc2dbutFLwqUFEpZ/view

- [x] when the min/max facets get used - the values don't persist in the facet panel, but they get applied to the sqon. The facet panel should show all filters the user has applied, these textfields should not be cleared.

**Comment by rosibaj** [comment]
lgtm thanks @anncatton !
