### ISSUE TITLE
🐛 Prevent submitting decimal commitment level

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-ui#1561]
## Describe the bug
The create program form doesn't let you submit zero directly, but its possible to submit 0 commitment level if you submit decimal.

## Steps To Reproduce
1. Go to `Manage Program`
2. Enter 0.1 into commitment level
3. Save
![image](https://user-images.githubusercontent.com/34698315/84198533-b1d87200-aa71-11ea-9652-8f29afd650ae.png)
4. Refresh and see how commitment level is now zero

Related to this, if there is no commitment level can get (NaN %) in all program:
![image](https://user-images.githubusercontent.com/34698315/84199464-3677c000-aa73-11ea-892e-624f6b0975e4.png)

This is probably also being saved in db too

## Expected behaviour
Probably don't want to able to submit zero for commitment level or if we do maybe we should just allow submitting zero...

**Comment by andricDu** [comment]
Verified functionality, moving into staging, and adding to release.

**Comment by andricDu** [comment]
Deployed to staging.

**Comment by andricDu** [comment]
Released and tested in prod.
