### ISSUE TITLE
Show invalid donor state in download table 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1569]
Zeplin: https://zpl.io/bLlr3BD

- [x] Invalid donor banner
- [ ] Error icon in the star column
- [x] Invalid donor count in the stats bar

![image](https://user-images.githubusercontent.com/15824252/84339826-4673ca80-ab6d-11ea-95c0-a08ad5e5cc40.png)

**Comment by wajiha-oicr** [comment]
what's the error report download button in the banner?

**Comment by wajiha-oicr** [comment]
while It's possible for me to be show the total number of invalid donors **could** via calculations from the frontend, that information seems like it should be coming from gateway just like the rest of the statistics. 

Doesn't seem like there's anything in place for that just yet from the current queries to the gateway. @hlminh2000 please correct me if I'm wrong. I'm thinking we should make a ticket to get that put in place first?

**Comment by rosibaj** [comment]
@wajiha-oicr  please remove the error report line for now (i iwll make a separate ticekt for that)!

**Comment by andricDu** [comment]
@rosibaj please advise on whether or not this will be tested through regular release flow.

**Comment by rosibaj** [comment]
@andricDu regular release flow.

**Comment by rosibaj** [comment]
lgtm thanks @wajiha-oicr
