### ISSUE TITLE
🐛 Blip on transitions in file repository

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1596]
1. when i open the file repo (first load) 
2. pick a facet
3. observe the weird flash before  the page loads with data 
4. this always happens the VERY first time i use afacet, and then sometimes when adding other facets
5. if i click clear, and picka new facet, no weird blip

## Expected Behaviour
Improve the transition state to have a smoother flow when picking a facet, like icgc or gdc

**Comment by hlminh2000** [comment]
need to remove the conditional rendering of the facets on facets loading state

**Comment by rosibaj** [comment]
👍 thanks @jaserud !
