### ISSUE TITLE
Homepage: hook up stats

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1597]
Hook up the homepage stats to the real numbers from the file repo:
![2020-06-15_1726.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/17b9b9ec-2358-490a-a5f9-3233efe66683)

------ 
- [ ] Hide Primary Site 
- [ ] Hook up the other three stats to the same queries available in the file repository
![image](https://user-images.githubusercontent.com/15824252/84712934-da5fe080-af37-11ea-80e0-d67a628a2add.png)

**Comment by hlminh2000** [comment]
@rosibaj Primary sites are not yet available, should just remove for now?

**Comment by rosibaj** [comment]
@hlminh2000 @kcullion I have finally had time to update this ticket :) Yes, @hlminh2000 please remove primary site for now.

**Comment by rosibaj** [comment]
lgtm thanks @jaserud
