### ISSUE TITLE
Improve tooltip behaviour for long facet names in File Repo

### ISSUE THREAD

**Issue by anncatton** [icgc-argo/platform-ui#1611]
The tooltip for facet option text overflow is currently activated on a fixed char length (28 chars), but this will break down when the doc_counts get larger. Can this be implemented so that the tooltip is activated when the text-overflow is triggered, and the doc_count labels can be allowed to expand as needed?

**Comment by rosibaj** [comment]
lgtm

**Comment by andricDu** [comment]
Released and tested in prod.
