### ISSUE TITLE
Quick search behaviour feedback

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1614]
Followup to: https://github.com/icgc-argo/platform-ui/issues/1517.  This ticket includes teh quicksearch feedback.

Couple of things:
- [ ] 1 - scroll bar issue
![image](https://user-images.githubusercontent.com/15824252/84920652-705b4e80-b091-11ea-995c-3b545bd9ba0a.png)

- [ ] 2 - focus issue
![image](https://user-images.githubusercontent.com/15824252/84920692-80732e00-b091-11ea-9b08-0aedc0af8537.png)

**Comment by rosibaj** [comment]
@anncatton windows 10/chrome is system

**Comment by anncatton** [comment]
Also will include:
- case-insensitive search
- decrease search icon size
