### ISSUE TITLE
🐛 url param states are double firing

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#1617]
## Describe the bug
This causes some complexity in state management. 

## Steps To Reproduce (for developers)
Log out the filters state according to `useUrlParamState.ts`, you'd see every change is triggered twice. Since this is a piece of code meant for and will be reused throughout the app, fixing this will help simplify usage in future. In https://github.com/icgc-argo/platform-ui/pull/1615 for example, we needed a workaround, so also go back and remove this workaround.

## Expected behaviour
State changes should only be triggered once.

**Comment by andricDu** [comment]
Released and tested in prod.
