### ISSUE TITLE
🐛 e2e: Edit program save button remains enabled

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/platform-ui#1619]
## Describe the bug

Editing a program commitment level in e2e is broken
`seedForm` data `commitmentDonors` is a `number`
input into form is a `string`
`isSameContent` is doing strict equality check and seeing it as different data causing the `Save` button to remain enabled

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to edit program
2. Click on commitment level
3. Click save
4. Save button will not disable

## Expected behaviour
Save button should be disabled on form submit as content has not been edited

**Comment by rosibaj** [comment]
lgtm thanks @wajiha-oicr !

**Comment by rosibaj** [comment]
verified on production
