### ISSUE TITLE
Update home page

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#1621]
1. Change "Clinical data **is** available" to "Clinical data **will be** available"

![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/bbee5518-5cab-4901-9c14-a4397316f584)

2. Update text 
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/9655a3fa-12fe-49c5-9b30-c29f0eb4d73d)

3. Update Announcement (text TBD)

**Comment by rosibaj** [comment]
lgtm thanks so muhc @jaserud !
