### ISSUE TITLE
✨ File Repo search dropdown shadow

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#1630]
quality of life improvements for the users' eyes :)
![Screen Shot 2020-06-18 at 6 01 56 PM](https://user-images.githubusercontent.com/11821106/85077578-a3d0d280-b190-11ea-82a4-4608b89167ff.png)
![Screen Shot 2020-06-18 at 6 07 01 PM](https://user-images.githubusercontent.com/11821106/85077579-a501ff80-b190-11ea-8d28-0ac0f2e7cb0d.png)

## Detailed Description
Just to add some contrast :)

## Possible Implementation
Just do it!

**Comment by rosibaj** [comment]
lgtm!! thanks so much @wajiha-oicr !
