### ISSUE TITLE
File repo: make facet selections more apparent 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1634]
Add a blue shade to make it clear that the moving facet values are the ones that are selected at the top of the list.

Zeplin: https://zpl.io/2jxn8AO

![Screen Shot 2020-06-19 at 10.21.29 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/06b64d9c-656a-4164-9b32-cbdbcc9cb236)

**Comment by kcullion** [comment]
This looks good to me @wajiha-oicr

@rosibaj now that I'm seeing this, do we need to add a "clear selection" button like ICGC has?
<img width="247" alt="2020-07-13_1346" src="https://user-images.githubusercontent.com/18424138/87336115-60f3e780-c50f-11ea-8c0c-c860a6ab8df8.png">

**Comment by rosibaj** [comment]
@kcullion i think it kind of conflicts with the search behaviour.  once that icon appears, you can no longer do searches!   If so, would maybe say a `clear all` at bottom?

**Comment by kcullion** [comment]
Yeah I was thinking it could either be one of these two places.
But maybe we just disable it at the bottom, and enable the link if any or all values are selected?

<img width="265" alt="2020-07-13_1358" src="https://user-images.githubusercontent.com/18424138/87337130-f93e9c00-c510-11ea-9d21-96a3accdb7a9.png">

**Comment by rosibaj** [comment]
i beleive if you select all, it becomes deselect all already...

**Comment by kcullion** [comment]
yeah, but that's only if you select all. if you just select like 3, we can have the clear all just stay there on screen instead of the select all changing to deselect all

**Comment by rosibaj** [comment]
@kcullion so you are saying
- if `select all` is used then all itmes aer selected and the `select all` link is disabled, `clear all` is enabled 
- if some facets are selected, `select all` is enabled and `clear all` is enabled
- if no facets selected, `select all` is enabled and `clear all` is disabled

**Comment by kcullion** [comment]
@rosibaj yep that's what I meant! :)

**Comment by rosibaj** [comment]
@kcullion so it sounds good, but im a little worried it might look crowded: 
![image](https://user-images.githubusercontent.com/15824252/87338530-56d3e800-c513-11ea-9a33-83db2a620f97.png)


what do you think?

**Comment by kcullion** [comment]
I don't think it's too crammed: https://zpl.io/2jxn8AO

We could always only show the clear all beside the select all when selections are made...
<img width="1088" alt="2020-07-13_1425" src="https://user-images.githubusercontent.com/18424138/87339678-f3e35080-c514-11ea-8e1b-08eb989ba620.png">

**Comment by rosibaj** [comment]
ok cool @kcullion can you make a backlog ticket for that?

**Comment by kcullion** [comment]
Sure....actually @rosibaj should this be part of the Canarie arranger fixes that would be across all arranger UIs? If so, should I add the ticket somewhere specific?

**Comment by rosibaj** [comment]
@kcullion for now, we need this ticket in platform if you want it here.  

in general, i think a lot of these UX fixes need to be ported back to arranger.  we need to make a list of those.

**Comment by kcullion** [comment]
Ok I'll make a platform ticket and add it to my "UX fixes for arranger" list
