### ISSUE TITLE
Update homepage announcement 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1641]
![image](https://user-images.githubusercontent.com/15824252/85164687-b4d22000-b232-11ea-8fe3-e3ae346d4286.png)

Announcement: June 19, 2020 - We are excited to announce the launch of the ICGC ARGO Data Platform, a major milestone following the[ ICGC 25K Data Portal](url). ARGO represents an international effort to advance cancer genomics through high-quality clinical and molecular data for international researchers.

- Clinical data submission is now open for registered programs.
- Data analyzed against GRCh38 is now available in the [File Repository.](url)
- ARGO [Data Dictionary 1.0](url), [Data Release 1.0,](url) and [Software Release 1.54.0/3.2.0](url) are now available.

links: 
 ICGC 25K Data Portal --. link to icgc data portal https://dcc.icgc.org/
File repository - whatever the production url is (/repository)
and all the release notes in last bullet
https://docs.icgc-argo.org/docs/release-notes/data-releases
https://docs.icgc-argo.org/docs/release-notes/software-releases
https://docs.icgc-argo.org/docs/release-notes/dictionary-releases

- [ ] also change release date to June 19, 2020
<img width="642" alt="2020-06-19_1524" src="https://user-images.githubusercontent.com/18424138/85173484-5496aa80-b241-11ea-9f7d-9a369321e00f.png">

**Comment by kcullion** [comment]
looks good Ann!
