### ISSUE TITLE
🐛 Fix mobile modal

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#1651]
## Describe the bug
Modals render incorrectly on mobile.
![104448752_323285602170683_2593602472020135021_n](https://user-images.githubusercontent.com/11821106/85182733-96325000-b257-11ea-8728-0e790c3eaf6d.jpg)

## Steps To Reproduce
Open any modal on mobile, see it render on a corner

**Comment by rosibaj** [comment]
lgtm in chrome tools!

**Comment by rosibaj** [comment]
verified on prod (Android; Razer 2)
