### ISSUE TITLE
User Profile UI: Program Access message display

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1657]
From Christina: On the profile page, won’t the membership table or no membership message look nicer in a box like the DACO message?

Implementation details:
- [ ] When user doesn't have access to any programs, display the message like this:
zeplin: https://zpl.io/b6zjpkj
<img width="708" alt="2020-06-22_1711" src="https://user-images.githubusercontent.com/18424138/85335710-6e3b2a80-b4ab-11ea-8eb9-546f3e4d1e3e.png">

- [ ] When user does have programs, just add a left and right border to the table.
zeplin: https://zpl.io/a8gpdqg
<img width="705" alt="2020-06-22_1707" src="https://user-images.githubusercontent.com/18424138/85335398-f240e280-b4aa-11ea-8139-55b7c3f9d01b.png">

**Comment by rosibaj** [comment]
lgtm thanks @anncatton !

**Comment by rosibaj** [comment]
verified on production
