### ISSUE TITLE
Site-wide Notification banners

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1666]
Banner Notification for system alerts . Example  https://www.breezythemes.com/products/alerts)

### Scope: Component creation, not integration into platform. 

Note: I had to use our darker brand colours for enough contrast with white text. For yellow I had to use dark text to be compliant  

- Each banner should be able to be configured as DISMISSABLE or NOT 
- The banner should be able to be applied without a full deploy 

- [ ] Info banner- this example shows if the banner has a title + more description
Zeplin: https://zpl.io/VQjRZK4
- [ ]  Error banner - this example shows if the banner just has a title
Zeplin: https://zpl.io/a8g9r0g
- [ ]  Warning banner - this example shows if the banner just has a title
Zeplin: https://zpl.io/aNgDrJn

<img width="1169" alt="Screen Shot 2020-06-24 at 2 12 44 PM" src="https://user-images.githubusercontent.com/18424138/85610236-d06b6b00-b624-11ea-918c-8a90ca424ddf.png">

**Comment by kcullion** [comment]
@rosibaj  please review

**Comment by rosibaj** [comment]
@kcullion lgtm

**Comment by anncatton** [comment]
Alert component expects api response:
`[{
  level: AlertLevel;
  title: string;
  message?: string;
  dismissable: boolean;
},
...]`
Type `AlertLevel` = `'error' | 'warning' | 'info'`

**Comment by anncatton** [comment]
Icons are being implemented with existing components, but we'll need new svgs from @kcullion to match zeplin designs (can't modify fill colour of inner symbols)

**Comment by rosibaj** [comment]
Follow-up api: https://github.com/icgc-argo/platform-api/issues/282

**Comment by rosibaj** [comment]
@anncatton is this in qa AND is it available in storybook?

**Comment by kcullion** [comment]
made a ticket for the svg update: https://github.com/icgc-argo/platform-ui/issues/1710

**Comment by kcullion** [comment]
@anncatton the content looks like it isn't a set distance from the icon, so on large screens it looks far away. Can you make this space a set width?
<img width="1199" alt="2020-07-13_1340" src="https://user-images.githubusercontent.com/18424138/87335568-86342600-c50e-11ea-9a8c-da021af47993.png">

**Comment by anncatton** [comment]
@kcullion @rosibaj is it ok to add the above fix to the #1710 ?

**Comment by kcullion** [comment]
Sure @anncatton I'll add to 1710
