### ISSUE TITLE
Submission Date - change from EST

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1680]
On Sample Registration and Clinical Submission - date of submission seems to be EST.  It should be either (1) UTC, or (2) better yet UTC translated to user’s local time but with the time zone spelled out.

- [ ] Verify what time is being recorded in the clinical database
- [ ] If not UTC, switch to UTC 
- [ ] One the front end, convert the registration/clinical submissions date to the user local time

![image](https://user-images.githubusercontent.com/15824252/109168202-9373ed00-774c-11eb-81fd-012473751741.png)

## Expected Behaviour 
Time should show in users local time

**Comment by rosibaj** [comment]
Tested March 08, 2021: 
- submitted data 
![image](https://user-images.githubusercontent.com/15824252/110388225-bf3a8100-8030-11eb-9590-61a42eb9c907.png)
- changed my computer time to Beirut 
![image](https://user-images.githubusercontent.com/15824252/110388314-e09b6d00-8030-11eb-81ec-8b00151b5195.png)
- 
![image](https://user-images.githubusercontent.com/15824252/110388371-fb6de180-8030-11eb-8fd4-f29481d6d976.png)

Thank you @samrichca for letting me know  - I have now confirmed on my machine that its i correctly showing according to local time.
