### ISSUE TITLE
Add form utils (validation) to contact page

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1700]
- adding the form util captures the data that is input 
- add the validations (required fields, and email validation)

**Comment by wajiha-oicr** [comment]
@rosibaj I think this is already complete? I used the form util and validations  to the contact-us form when I did the setup to gateway.

**Comment by rosibaj** [comment]
thanks @wajiha-oicr was going to ask about this one!!! closing as done then
