### ISSUE TITLE
Updates to site wide banners

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1710]
related to: https://github.com/icgc-argo/platform-ui/issues/1666

- [ ] The svgs are now in the zeplin links please replace with correct icons.

- Info banner- 
Zeplin: https://zpl.io/VQjRZK4
- Error banner - 
Zeplin: https://zpl.io/a8g9r0g
- Warning banner - 
Zeplin: https://zpl.io/aNgDrJn

- [ ] The content looks like it isn't a set distance from the icon, so on large screens it may appear far away from the icon. Can you make this space a set width?
<img width="1199" alt="2020-07-13_1340" src="https://user-images.githubusercontent.com/18424138/87335568-86342600-c50e-11ea-9a8c-da021af47993.png">

- [ ] Also can we make "Dismissible: yes / no" an option within the "knobs" for any of these banners, so it can be configured with or without that "x"?
<img width="866" alt="2020-07-13_1342" src="https://user-images.githubusercontent.com/18424138/87335753-c8f5fe00-c50e-11ea-9dfc-d140e5eba366.png">

**Comment by wajiha-oicr** [comment]
@kcullion is it possible for the svg icons to use masks? The exclamation point shape inside the triangle has a hard-coded colour, and adjusting its transparency reveals the background triangle behind it but not the actual background. 

Let me know if this is possible! If it's not, the alternative is to make several variants with the particular fill colour of the exclamation point hard-coded.

**Comment by wajiha-oicr** [comment]
moving this to code review with all changes except for icon changes

**Comment by kcullion** [comment]
@wajiha-oicr yes I can get you those icons. I'll send them over slack soon.

**Comment by rosibaj** [comment]
LGTM! thanks @wajiha-oicr !
