### ISSUE TITLE
Feedback: Platform home page should not have obvious dynamic/async loading of content

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/platform-ui#1732]
Its generally good practice to have any home page for a product to load as snappy as possible. Loading this from Europe or other higher latency situations is jarring as the page has a loader and then causes a shift in content on load. 

We chose to have the ability to do server-side rendering specifically to avoid these kind of situations, so we should really lean on that here. If the query does take a second to load which would block page render, then we should be caching data to speed up the render. 

![image](https://user-images.githubusercontent.com/6350043/89791617-8ade0100-daf1-11ea-8b73-9c83bdca13f8.png)

## possible implemention
the platform configuration is set up to do this, but we didnt turn it on ye t
use the existing setup to pre-load. 
remove the chikxxxxa-chug

**Comment by rosibaj** [comment]
@hlminh2000 @wajiha-oicr anyway we can get this released by planning?

**Comment by kcullion** [comment]
will need @andricDu to test from France
