### ISSUE TITLE
🐛 Clicking on Manage Programs a second time breaks display

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/platform-ui#1737]
## Describe the bug
 Clicking on Manage Programs a second time breaks display

## Steps To Reproduce
https://drive.google.com/file/d/1CG9U4sOJbxIT9sNCPjecisTQe2-aVsWM/view

![image](https://user-images.githubusercontent.com/15824252/91312968-d4ca1680-e782-11ea-94a7-7c4d7a6d3fe8.png)

URL parameters are not being passed on the second click

## Expected behaviour
- Manage program data to stay on screen
- Should also work for all clinical submission tabs 
- File repository should also be checked after fix as it has url parameters

**Comment by ciaranschutte** [comment]
@rosibaj required to save state of each page too?
 eg. if on `Manage Programs` => `Profile`, 
clicks on `Manage Program`, 
stays on `Profile` 

 or is normal page reload(state is lost) correct (like https://dcc.icgc.org/search)?

**Comment by rosibaj** [comment]
@ciaranschutte its better to save state.

**Comment by rosibaj** [comment]
@ciaranschutte looks great! i couldnt break it in testing! moving forward.

**Comment by rosibaj** [comment]
@ciaranschutte can i please get a version number added so that we can move this forward?

**Comment by rosibaj** [comment]
confirmed on prod
