### ISSUE TITLE
User Profile: Update to show full/associate membership

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1750]
**For the user roles: Program Admin and Data Submitter**

Please do the following:

- [x] Show the membership type for the programs in the membership table [Should be based on the MEMBERSHIP SCOPE on the JWT]

- [x] If a member is part of one or more full membership programs, assign them the "Full Membership" tag (even if they also belong to associate programs) 
Zeplin: https://zpl.io/bzr8Mkz
<img width="715" alt="2020-09-24_10-07-38" src="https://user-images.githubusercontent.com/18424138/94156373-08659280-fe4e-11ea-8895-48d774ea4bf8.png">

- [x] If a member is part of ONLY associate program(s), assign them the "Associate Membership" tag
Zeplin:https://zpl.io/V079EdQ
<img width="711" alt="2020-09-24_10-06-49" src="https://user-images.githubusercontent.com/18424138/94156496-229f7080-fe4e-11ea-93e1-cac394212dc1.png">

**For Program Collaborators**

- [x] show the program membership type in the table
- [x] don't assign or show a tag for them as they will not be able to view full or associate level files for other programs

**Comment by rosibaj** [comment]
@ciaranschutte any chace to get this to QA today?

**Comment by ciaranschutte** [comment]
@rosibaj yup just waiting on a code review, followed up/re-requested review

**Comment by rosibaj** [comment]
@ciaranschutte i dont see anything: 
![image](https://user-images.githubusercontent.com/15824252/95592789-1d7a1e00-0a17-11eb-9460-f3559ee3ee13.png)

**Comment by kcullion** [comment]
yeah I see the same...I see the new table column but not the blue tag in the top left

**Comment by rosibaj** [comment]
@ciaranschutte @kcullion the issue is a scope issuein ego, not a code issue 
![image](https://user-images.githubusercontent.com/15824252/95593542-d6d8f380-0a17-11eb-9c2a-a03fbefea261.png)


@ciaranschutte lgtm we need to fix program membership scopes in the platform in a different ticket
