### ISSUE TITLE
Add "Access" facet when logged in 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1764]
facet on left
 - feature flag on ui
- display value change; extend component to handle this

**Full member** 
Zeplin (shows tooltip open - which would show on hover of the ?): https://zpl.io/2jDelJx
They can filter on all stages to see what files they have access for each
<img width="640" alt="Screen Shot 2020-10-22 at 12 09 24 PM" src="https://user-images.githubusercontent.com/18424138/96900273-ea487d80-145f-11eb-8540-83e0153fb4a5.png">

**Associate member** 
Zeplin: https://zpl.io/br4jk83
They can filter on all stages except the files in the Full membership stage
<img width="342" alt="Screen Shot 2020-10-22 at 12 06 41 PM" src="https://user-images.githubusercontent.com/18424138/96899574-131c4300-145f-11eb-8e55-405b9d73e88d.png">

**Selected and Hover state for new facet:**
Zeplin: https://zpl.io/25LMg4J

![2020-10-22_12-15-15](https://user-images.githubusercontent.com/18424138/96900644-54612280-1460-11eb-96c6-9c0186b2b66f.png)

** NOTE: do not reorder the values on this facet only.

**Comment by ciaranschutte** [comment]
@ciaranschutte will need to integrate with https://github.com/icgc-argo/platform-api/issues/294

**Comment by rosibaj** [comment]
@ciaranschutte linked tickets!

**Comment by ciaranschutte** [comment]
@rosibaj need to do more work with @hlminh2000 to resolve local build issue with `platform-api`

**Comment by hlminh2000** [comment]
@ciaranschutte if you are able to get the tests to pass locally, I think we can turn off the unstable tests for now to move things forward, and revisit test stability later

**Comment by ciaranschutte** [comment]
@rosibaj not working in dev yet. I updated the feature flag yesterday. Looking into this now.

**Comment by rosibaj** [comment]
perfec thank you @ciaranschutte !

**Comment by ciaranschutte** [comment]
@rosibaj in QA. there seems to be an extra row in the Access Facet with no title. Also #files isn't matching with table.

**Comment by ciaranschutte** [comment]
![rosi](https://user-images.githubusercontent.com/1486054/105860495-a5326b00-5fbb-11eb-9c65-c0a649d53761.png)

**Comment by rosibaj** [comment]
@ciaranschutte can you please add a version to this ticket to indicate what version this change represents?

**Comment by rosibaj** [comment]
@ciaranschutte This all looks great for now!  I have some feedback on data/behavior testing, but the UI portions of this are well covered! thank you! As soon as we get a software version on this we can move to awaiting release!
