### ISSUE TITLE
🐛 Remove import of `next/link` from uikit

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#1777]
Minor but important thing to fix: currently there's some import of `next/link` in uikit. This shouldn't be there cause uikit should be usable in projects that are not on `next.js` at all.

More specifically, this is in the `AppBar` component.

**Comment by ciaranschutte** [comment]
@rosibaj in QA. Looks ok to me.

**Comment by rosibaj** [comment]
@ciaranschutte  can you please add a version to this ticket to indicate what version this change represents?

**Comment by rosibaj** [comment]
Tested on QA environment - 
- when i had access to a program as a data submitter, successfully landed on a program dashboard
- when i had no access to a program, successfully landed on user page.  
Thanks for the fix @ciaranschutte !!
