### ISSUE TITLE
Security Upgrade: FIx the errors. 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1788]
![image](https://user-images.githubusercontent.com/15824252/103788860-53767080-500d-11eb-9ad9-dfc41f3df7ee.png)

**Comment by ciaranschutte** [comment]
@rosibaj no dependabot alerts right now.... guessing this way fixes somewhere along the line. please verify when you have a minute just in case it's something weird with my github

**Comment by rosibaj** [comment]
@ciaranschutte it looks like someone else fixed this yesterday already!  You should have just taken credit :)
