### ISSUE TITLE
🐛 RDPC Redirect is wrong 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1789]
- Make sure you are not dcc admin
- make sure you are an RDPC user 

Click the program Services button on the plaform.  If logged in, you will be redirected to `/rdpc` or `/rdpc` will be added to the redirect after login.  this leads to a DNE page. 

https://github.com/icgc-argo/platform-ui/blob/e435ee3aa3b4a68f56dec05e9d5c41250a1c9352/global/utils/pages/index.tsx#L44

## Solution 
- Remove the RDPC page as it will ne be used currently or the near future
- check the code for `/rdpc` references. 
![image](https://user-images.githubusercontent.com/15824252/104619255-a5e20d80-565b-11eb-88d3-53978632840a.png)

**Comment by ciaranschutte** [comment]
@rosibaj DNE page.? do not enter?

**Comment by rosibaj** [comment]
@ciaranschutte Does Not Exist.... its a maths term that i probably should not have assumed everyone knows :)

**Comment by rosibaj** [comment]
@ciaranschutte can you please add a version to this ticket to indicate what version this change represents?

**Comment by rosibaj** [comment]
Tested on QA environment - 
- when i had access to a program as a data submitter, successfully landed on a program dashboard
- when i had no access to a program, successfully landed on user page.  
Thanks for the fix @ciaranschutte !!
