### ISSUE TITLE
🐛 User with no access should have a disabled token on user profile

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1794]
## Steps To Reproduce
1. Login to platform with a user with no access (No DACO access and does not belong to a program)
the user JWT looked like this: 
```
{
  "iat": 1610740810,
  "exp": 1610742610,
  "sub": "23f1d054-14d5-4443-9df0-8460193dffbc",
  "iss": "ego",
  "jti": "04c7ed72-df15-43b8-92c7-e1072b8dfa01",
  "context": {
    "scope": [
      "*.DENY"
    ],
    "user": {
      "name": "RBajari@oicr.on.ca",
      "email": "RBajari@oicr.on.ca",
      "status": "APPROVED",
      "firstName": "Rosi",
      "lastName": "Bajari",
      "createdAt": 1591120423904,
      "lastLogin": 1610740810624,
      "preferredLanguage": null,
      "type": "USER",
      "groups": []
    }
  },
  "aud": []
}
```
2. Generate a token.  It spins forever on ui: 
3. 
![image](https://user-images.githubusercontent.com/15824252/104773173-a2758180-5742-11eb-9c9b-306486d42b8c.png) 
4. these errors are observed:
```
{errors: [{message: "The 'Policy' entity with name '*' was not found", locations: [],…}], data: null,…}
data: null
errors: [{message: "The 'Policy' entity with name '*' was not found", locations: [],…}]
0: {message: "The 'Policy' entity with name '*' was not found", locations: [],…}
extensions: {timestamp: "2021-01-15T20:01:05.619+0000", status: 404, error: "Not Found",…}
locations: []
message: "The 'Policy' entity with name '*' was not found"
path: ["generateAccessKey"]
extensions: {tracing: {version: 1, startTime: "2021-01-15T20:01:05.382Z", endTime: "2021-01-15T20:01:05.629Z",…}}
tracing: {version: 1, startTime: "2021-01-15T20:01:05.382Z", endTime: "2021-01-15T20:01:05.629Z",…}
duration: 246992728
endTime: "2021-01-15T20:01:05.629Z"
execution: {,…}
startTime: "2021-01-15T20:01:05.382Z"
version: 1

```

## Expected behaviour

- [ ] Disable the "Generate" button
- [ ] Remove the "Expired" tag that shows up in the token field (this is what I saw as a basic user for the platform in production)
- [ ] For this use case only: modify the text of the orange warning banner to be the following:

`You do not have permission to generate an API token to download controlled data.  Learn more about how to apply for access to ICGC Controlled Data. `

- [ ] Link "how to apply for access to ICGC Controlled Data" to https://docs.icgc-argo.org/docs/data-access/data-access. Note, this link will change when DACO is released, so use the **global links file**.

![image](https://user-images.githubusercontent.com/18424138/122990493-fe87a600-d371-11eb-86d1-20aff2cbaced.png)

**Comment by akachru-github** [comment]
Under what conditions should we be allowed to generate an API token? Does the user only need to be DACO approved?

**Comment by kcullion** [comment]
@demariadaniel @joneubank, Brandon set up his account and got DCC admin access in QA. This is a screenshot of his profile page - looks like he can't ever regenerate a token. This is confusing to me, I'm not sure I quite understand this token and when users should be able to access it.
![image (92)](https://user-images.githubusercontent.com/18424138/152236357-4d9157df-0725-4e5b-8ea3-760a199c15e7.png)

**Comment by joneubank** [comment]
Just looks like the logic on this is incorrect, needs to give them the ability to regenerate a token. The rule is simple: everyone should have access unless they have no scopes.

**Comment by demariadaniel** [comment]
Thanks, logic is clear, that's not how the component was working previously, so the first time through I was hesitant to make major changes.

Question though, previously we were disabling this feature when the user is not Daco Approved. Your description makes it sound like that is not the case. Should a user be able to generate a new token if they are not Daco Approved?

**Comment by demariadaniel** [comment]
@joneubank PR w/ updated logic to check scopes, just advise if I should remove `isDacoApproved` as well, it's an easy update

https://github.com/icgc-argo/platform-ui/pull/2193
