### ISSUE TITLE
Access Facet - QA Feedback 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1801]
Followup to #1764 - UI and Behaviour Feedback 

- [x] Access facet should be the FIRST facet below search 
![image](https://user-images.githubusercontent.com/15824252/105872710-b2098b80-5fc8-11eb-9cd0-7818fb4c6b90.png)

- [x] The actual facet values are not... formatted in a pretty way.  We should fix the display of these values: 
- [ ] ![image](https://user-images.githubusercontent.com/15824252/105873620-ac607580-5fc9-11eb-80b7-bd33f5375c99.png)
- [x] keep this order of facet values (so it's not based on file #) 
![image (60)](https://user-images.githubusercontent.com/18424138/106051511-8795fc00-60b6-11eb-96de-bc337afb3ca4.png)

**Comment by rosibaj** [comment]
Tested feb 11
- cannot accedd file repository unless logged in 
- facet itself looks fine, but need to fix ^

**Comment by ciaranschutte** [comment]
@rosibaj bug fix in 1.86.1  can create new ticket if you like

**Comment by rosibaj** [comment]
@ciaranschutte no just the versino label on this one is fine!
