### ISSUE TITLE
🐛 First login leads to 404 - Redirect issue?

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1802]
## Describe the bug
First login results in a 404 page.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Start with an account wiht no access.  Give them Data Collaborator access.
2. Go to Qa mailhog (https://mailhog.qa.argo.cancercollaboratory.org/) and accept the invitation. 
3. go through the invitation process.
4. One the correct login is complete, this happen:
5. 
![image](https://user-images.githubusercontent.com/15824252/105875514-e2065e00-5fcb-11eb-9a79-05d58908ca50.png)
6. If i refresh the page, the error goes away and it loads fine. 

## Expected behaviour
It should land and load on the program dashboard correctly with no refresh.

**Comment by rosibaj** [comment]
This ticket was released without QA.  Since the code connected to this ticket was released, I will be closing it. this bug will be reopened in a new ticket.

**Comment by ciaranschutte** [comment]
@rosibaj I can't replicate this. I checked with @kcullion just now too and it sounds like it's ok. can't replicate.

**Comment by ciaranschutte** [comment]
https://github.com/icgc-argo/roadmap/issues/778

**Comment by kcullion** [comment]
I tested this on QA - as dcc admin I invited my program member email address (belonging to other programs) to a new program. I went through mailhog to accept invitation and joined the program. When I logged in it took me to that new program dashboard with the welcome banner. Worked as expected!
