### ISSUE TITLE
System alerts not updating

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#1815]
System alerts won’t update with newly added/removed banners during a session. An API request to fetch system alerts should be made when users navigate from one page to another.

Implementation suggestions:

- make the request in the root of the application on render (or somewhere else with the same frequency/triggers)
- pass the banners down as a prop (using context may be overly complex here)
- this needs to be separated from prefetched+cached requests at root level because the request will be made multiple times per session

**Comment by rosibaj** [comment]
Discussed in planning - We don't need this level of availability on the banners, as we already do have a maintenance page in the event of a large maintenance.
