### ISSUE TITLE
Update the Calculations on Dashboard Header

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1818]
![image](https://user-images.githubusercontent.com/15824252/107652229-5983f080-6c4e-11eb-9918-f32511862d51.png)

**Comment by samrichca** [comment]
this progress bar is currently `registered donors / committed donors`

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/b1be9f04-57f7-450c-b164-1791cd8b56a1)

**Comment by samrichca** [comment]
closing, not an issue
