### ISSUE TITLE
🐛 "Resend Invitation" button not functioning

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/platform-ui#1821]
## Describe the bug
The "Resend Invitation" button does not work in the "Manage Program" section of the ARGO Platform
## Steps To Reproduce
** **UPDATE**: User confirmed she received the invitation email even though the below error happens **
- Was using Chrome browser
- Go to https://platform.icgc-argo.org/submission/program/MUTO-INTL/manage?activeTab=users
- Was trying to resend invitation for one of the users (Laura)
- When clicking on the "Resend Invitation" button, nothing happens:
![screenshot_1](https://user-images.githubusercontent.com/4992044/107666824-ed5cb900-6c5c-11eb-840f-aacf9ce5560f.png)

- The above pop-up does not go away. You have to click on the "X" to remove it. 
- A few seconds later, an error message pops up (`An error occurred while sending the invite`):
![screenshot_2](https://user-images.githubusercontent.com/4992044/107666974-2006b180-6c5d-11eb-9de2-53ea9abcf80c.png)

- User confirmed she received the invitation email despite the above error. She said she logged in and created her account, but there are now two duplicate entries in the the "Manage Program" - one that says "Approved", and the other that still says "Pending invitation":
![duplicate_entries](https://user-images.githubusercontent.com/4992044/107672078-83471280-6c62-11eb-82da-934da52da9c2.png)

- I also can't edit a user (all fields are grayed out when I click on `Edit User`)

**Comment by ciaranschutte** [comment]
having trouble recreating this.
Will check if there is anything weird about the user object on Monday

**Comment by akachru-github** [comment]
Tested today and looks to be resolved!
