### ISSUE TITLE
News Update: Homepage

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1826]
Update the announcement blurb on the homepage:
> **Announcements:** 
>**March 01, 2021:** The 17th Scientific Workshop & 4th ARGO Virtual Meeting Plenary Session is open to public for [registration](https://www.icgc-argo.org/page/128/17th-icgc-scientific-workshop).  ARGO updates from the Data Coordination Centre and the Secretariat will be presented, as well as oral and poster presentations from participating ARGO programs and technological development teams. 
>**October 23, 2020:** - We are excited to announce Data Release 2.0 on the ICGC ARGO Data Platform, including additional data for PACA-CA, OCCAMS-GB, and two newly released programs LUCA-KR and PTC-SA.
**New Features:** 
You can now compare changes in released ARGO Data Dictionary versions in the Dictionary Viewer. Data Dictionary version 1.2 has been released. Click the “Compare With” button to see the latest updates.
>
>ARGO Data Dictionary 1.5, Data Release 2.0 and Software Release 1.86.1 - API 3.13.2 are now available.

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj 

- removed the list format at the bottom of announcements. what's the point of 1 item list? looks odd
- updated "New Features" text content to reference Data Dictionary version 1.5 instead of 1.2


if any of these should be reverted please let me know

**Comment by ciaranschutte** [comment]
![Uploading announement.png…]()

**Comment by kcullion** [comment]
@ciaranschutte can you reupload the screenshot? the link seems to be broken

**Comment by ciaranschutte** [comment]
![announement](https://user-images.githubusercontent.com/1486054/109200271-66383680-776e-11eb-8bbc-3fc5de8b7a9e.png)

**Comment by rosibaj** [comment]
@ciaranschutte looks great! changes are 👌 !

**Comment by kcullion** [comment]
Looks good to me!

- [ ]  I would just add "the" before public
- [ ] and maybe technology development teams instead of technological?
- [ ] typo: "additional"
- [ ] and instead of  Click the “Compare With” button to see the latest updates. maybe
 `Click the “Compare With” button to see compare different versions of the dictionary`.

@rosibaj thoughts?

**Comment by ciaranschutte** [comment]
dev ok

**Comment by rosibaj** [comment]
tested on QA - looks great thanks @ciaranschutte ! Can i get a version number on this ticket please?

**Comment by rosibaj** [comment]
confirmed on prod release
