### ISSUE TITLE
Update tab color to blue 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1827]
![image](https://user-images.githubusercontent.com/15824252/108106867-83795080-705c-11eb-8ee6-de0ceb8a3c00.png)

You can see the text and active border colour on this mockup with the "Pending Program QC" item. (ignore the icon and count for now)
Zeplin: https://zpl.io/br9gqz1

**Comment by ciaranschutte** [comment]
@kcullion Does the top header need updates too? eg. Program Services active is green

**Comment by kcullion** [comment]
@ciaranschutte good question, never thought of that. Let's just leave that for now as it would mean updating RDPC too and I think the green stands out nicely on the dark blue.

**Comment by ciaranschutte** [comment]
@kcullion sounds good thank you

**Comment by ciaranschutte** [comment]
dev ok

**Comment by rosibaj** [comment]
tested on QA looks great! @ciaranschutte can i please get a version number on this ticekt?

**Comment by rosibaj** [comment]
confirmed on prod release.
