### ISSUE TITLE
Chart UI: General Improvements

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1835]
- [x] Move title to line chart component (as a child element)
- [x] Make all control bar text the same size (12px)
- [x] Add "# donors" to Y axis
- [x] Reduce padding between the chart and the edges of the card
- [x] Make Y axis labels right-aligned
- [x] Add chart to molecular card
- [x] Committed donors line

**Comment by samrichca** [comment]
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/263e1529-df79-478a-8ff4-e7b49e793196)

**Comment by rosibaj** [comment]
looks great thanks @samrichca !
