### ISSUE TITLE
ARGO Team page updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1843]
- [ ] Please add the following team members under software engineering (alpha order by first name) - see screenshot
- Rakesh Mistry
- Sam Rich
- Yelizar Alturmessov

- [ ] And move Minh, Rob and Wajiha to alumni (make this list alpha by first name too)
<img width="1297" alt="2021-03-02_17-00-50" src="https://user-images.githubusercontent.com/18424138/109721091-e4367c00-7b78-11eb-86e3-69acf8b8a0bb.png">

**Comment by rosibaj** [comment]
looks excellent, thank you @samrichca !

**Comment by rosibaj** [comment]
confirmed on production release
