### ISSUE TITLE
🐛 Fix the width of the edit user modal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1844]
## Describe the bug
The `edit user` modal is using a smaller width. Please make it the same as the `add user` modal width

## Steps To Reproduce
1. Go to a `Manage Program` for DASH-CA, for example
2. Click on the pencil icon for Rosi's data submitter user
3. The modal is very squished:
<img width="847" alt="2021-03-02_16-34-41" src="https://user-images.githubusercontent.com/18424138/109826408-c3b60280-7c08-11eb-8e9d-682625693ab5.png">

## Expected behaviour
Please use the same width as the add users modal:
![image](https://user-images.githubusercontent.com/18424138/109826495-d7f9ff80-7c08-11eb-9575-f0098ceccb4f.png)

**Comment by ciaranschutte** [comment]
I had trouble recreating this on `develop`

**Comment by rosibaj** [comment]
@ciaranschutte i still see this on the qa env: 
![image](https://user-images.githubusercontent.com/15824252/110387589-d036c280-802f-11eb-939e-3141848b9bfc.png)

**Comment by ciaranschutte** [comment]
I see... I've left some comments on Sam's PR

**Comment by rosibaj** [comment]
lgtm on QA thanks @samrichca and @ciaranschutte !

**Comment by rosibaj** [comment]
verified on production with OCCAMS-GB user
