### ISSUE TITLE
Donor Dashboard Table - sort on updated date column

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1845]
The table may already be sorted by default on this updated date column. But please indicate that with the blue bar on top of this column, like this:

<img width="1349" alt="2021-03-03_10-13-04" src="https://user-images.githubusercontent.com/18424138/109826829-30c99800-7c09-11eb-8a00-eb44535c3a7d.png">

**Comment by ciaranschutte** [comment]
dev:ok

**Comment by rosibaj** [comment]
Confirmed on QA to be soriting correctly! LGTM thanks @ciaranschutte !

**Comment by rosibaj** [comment]
verified on production
