### ISSUE TITLE
Align the 2 banners

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#1852]
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/d3c541bd-47be-4517-b34a-34856235ff07)

- [x] Align the 2 banners
- [x] For the first banner, add a full stop (period)  to the end of "please review our Privacy Policy"

**Comment by ciaranschutte** [comment]
dev:ok
looks a little odd because the "X" is out of line with the "OK"
@rosibaj @kcullion should we align the "OK", "X" and the initials or it ok?
![r](https://user-images.githubusercontent.com/1486054/111488606-c8ea7580-870f-11eb-85a8-788e9c65211c.png)

**Comment by rosibaj** [comment]
@ciaranschutte hmm i agree, looks odd.  can you try the alignment?

**Comment by ciaranschutte** [comment]
Aligning them is an improvement. 
Logged in
![r2](https://user-images.githubusercontent.com/1486054/111523166-55f1f680-8731-11eb-9897-09cf0e857778.png)

Not logged in
![r](https://user-images.githubusercontent.com/1486054/111523182-5c806e00-8731-11eb-8328-e871ac5cdfe3.png)

**Comment by rosibaj** [comment]
@ciaranschutte LGTM! alignment is much better

**Comment by rosibaj** [comment]
looks great thanks @ciaranschutte !
