### ISSUE TITLE
Add File Entity Page to Platform. 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1855]
- [x] Create the File page Routing in the Platform 
- [x] Link from the Object Id column on the File repository to the entity page
![image](https://user-images.githubusercontent.com/15824252/110807019-9db7e000-8250-11eb-9178-15206bcd8606.png)

- [x] Integrate the components of the page into the platform. The UI has been built already  in storybook: https://argo-ui-storybook.netlify.app/?path=/story/components-pages-file-entity--basic
Zeplin: https://zpl.io/VYgdOOw

**Comment by ciaranschutte** [comment]
is this still part of the `File Repository`?
If so it should have a similar url to the submission eg. `repository/program/file`
also `File Repository` in the navbar should remain in selected state

**Comment by rosibaj** [comment]
@ciaranschutte no its not part of the file repository. Donrs/Programs/Files should be their own entity, like so: 

`https://platform.icgc-argo.org/file/FI12533` would be the URL path to resolve.

**Comment by ciaranschutte** [comment]
FileID
```
file {
    hits(filters: $filters) {
      total
      edges {
        node {
          analysis {
            experiment {
              experimental_strategy
              platform
            }
            
            workflow {
              workflow_name
              workflow_version
          
            }
            analysis_type
            analysis_version
            variant_class
          }
          ```
data analysis [data type, genome build, software, workflowType: get(entity, 'analysis.workflow') ]

**Comment by rosibaj** [comment]
@ciaranschutte i said fileID, but we don't have that yet so you can use `objectID`

**Comment by rosibaj** [comment]
@ciaranschutte any chance to getting this to QA today?

**Comment by ciaranschutte** [comment]
Which users can see the page? 
Which users can download a file?

**Comment by ciaranschutte** [comment]
needs dev / qa env update

**Comment by rosibaj** [comment]
@ciaranschutte looks good a couple things:
- [ ] field updates
![image](https://user-images.githubusercontent.com/15824252/114932374-6915e600-9e05-11eb-90aa-cd056c09934a.png)

**Comment by ciaranschutte** [comment]
@rosibaj @joneubank Do we have `program_shortcode` available from gateway? 
I only see short code in the queries.

I believe it should be added to the `file` query as it only has the shortname displayed here already and needs to remain an unauthenticated endpoint for file repo.

**Comment by joneubank** [comment]
right now we only have this in the program service, it is not available to query by the UI. We should put some thought into how we want to make this kind of program specific info available in more places.

**Comment by rosibaj** [comment]
ok @ciaranschutte you can just leave it showing the study-id/shortcode as it is showing now for that feeedback then.
