### ISSUE TITLE
Donor Entity: Summary card

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1862]
## Goal
Set up the summary card using dummy data. The fields will come from:

- sample_registration.tsv
- donor.tsv
- primary_diagnosis.tsv (just cancer_type_code)
- program services - probably connected to this ticket, to make certain program data available publically: https://github.com/icgc-argo/platform-api/issues/508 

You can also reference the latest data dictionary to see how the fields are written: https://docs.icgc-argo.org/dictionary
Started in storybook: https://argo-ui-storybook.netlify.app/?path=/story/components-pages-submission-system-donor-donordatatable--basic

## Gender = Female or Other
Zeplin: https://zpl.io/2937nPY
![image](https://user-images.githubusercontent.com/18424138/143513580-a8cf91f0-bc69-431f-a420-90fd02f5b150.png)

- [x] Show all fields from the mockup
- [x] Split the fields up into two columns with ~half the fields in each column 
- [x] 1. Show the Program full name followed by the Program_ID in brackets. The full name may need to come from program services. This would link to the file repository, filtered on this Program_ID.
- [x] 2. First pass at this you can show the cancer_type_code from the primary_diagnosis.tsv (like the male example below). Feature request to come (API ticket: https://github.com/icgc-argo/platform-api/issues/504
) will be to transform this into a string to be mapped out in https://wiki.oicr.on.ca/display/icgcargotech/ICD-10+API
- [x] 3. Fields like these will eventually need to display units, just bring in the values for now.
- [x] 4. Genetic disorders can have multiple values, display these comma separated
 5. The `--` has been generalized to: https://github.com/icgc-argo/platform-ui/issues/2111

## Gender = Male
Zeplin: https://zpl.io/agExWwA
![image](https://user-images.githubusercontent.com/18424138/143513691-6e4e81cb-0374-41f7-b0d1-9f7f37921681.png)

- [x] The `N/A` has been generalized to: https://github.com/icgc-argo/platform-ui/issues/2111
- [x] Hide the following fields for male donors, and rebalance the table fields numbers:
- menopause_status
- age_at_menarche
- number_of_pregnancies
- number_of_children
- hrt_type
- hrt_duration
- contraception_type
- contraception_duration

**Comment by akachru-github** [comment]
Clinical API should be updated with the logic to provide a value like "NA". Business logic should not be added to the FE to interpret a return like "NULL" for example. @joneubank , @mistryrn , @demariadaniel  to connect on this to agree how this will work.

**Comment by kcullion** [comment]
donor page is correctly hidden on staging
