### ISSUE TITLE
Add a commas to make large numbers easier to read

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1908]
In the File repo, the large file numbers don't have commas, can we add them to make the numbers easier to read

![image (66)](https://user-images.githubusercontent.com/18424138/117348624-6c3a4a00-ae78-11eb-9eda-7221d589e116.png)

Also noticed this on the dashboard:
![image](https://user-images.githubusercontent.com/18424138/117349679-ace69300-ae79-11eb-981c-a7414735bfc5.png)

All programs table
![image](https://user-images.githubusercontent.com/18424138/117351129-59754480-ae7b-11eb-8e14-8c69b7b36409.png)

**Comment by kcullion** [comment]
you found so many more! Thanks @samrichca ! this looks good

**Comment by rosibaj** [comment]
looks great thank you @samrichca !

**Comment by rosibaj** [comment]
confirmed on production.
