### ISSUE TITLE
🐛 Cannot load private files pages 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1984]
1. login to QA platform.
2. From the file repository, click on a link in the table of a restricted file. 
3. The file page loads with an error: 
https://drive.google.com/file/d/13W0-9CVZHOopMqVqMUylihMOOtT1q6r5/view
![image](https://user-images.githubusercontent.com/15824252/124190378-28d31500-da90-11eb-86ec-925b6475be00.png)

**Comment by joneubank** [comment]
Note that file pages are behind a feature flag and are not enabled in prod/staging.

**Comment by rosibaj** [comment]
@joneubank is there a version to attach to this ticket?

**Comment by rosibaj** [comment]
Tested Jun 12, 2021 

Can  load private file pages without data crash now.
