### ISSUE TITLE
Downloaded items (TSV/Manifest) are not taking access filters into account 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1988]
- login as an access restricted user
- fakerosifortesting@gmail.com in this case; user is only a Data Submitter to ROSI-RU, Associate access inherited from this
- from the file repository table, with `no` filter applied, click `Download > manifest` and see that the manifest downloads with 5600 rows (plus header) so 5599 files 
- this is NOT taking into account the users restricted access, and is downloading a list of all files. 
- you can see in the screenshot below the Data Submitter/ Associate member sees 1567 files, but got a manifest of all files. this is the case for the Table TSV as well. 
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/62f1e6b5-51c1-465e-910b-2b5192002d6d)

- you can see in the screenshot below the DCC member sees all 5599 files 
![image](https://user-images.githubusercontent.com/15824252/124195572-b9155800-da98-11eb-954d-0ff63d2115b0.png)

**Comment by joneubank** [comment]
Access filters working now.

Found an issue (might be new) where the TSV download has a UUID as the name instead of the filename provided by the gateway. This problem doesn't seem to occur for the manifest. Might want a ticket for that.

**Comment by joneubank** [comment]
Just for record keeping purposes... the gateway was applying filters but the UI was not passing the JWT header, it passes your credentials to the backend now.

**Comment by joneubank** [comment]
The filename issue is actually a server side concern - We need to specify which response headers are safe in our CORS middleware. I am redeploying the gateway with a CORS exception for the `content-disposition` header which will contain the filename details.

**Comment by rosibaj** [comment]
so @joneubank no additional ticket needed then?

**Comment by joneubank** [comment]
yeup, no ticket needed now.

**Comment by rosibaj** [comment]
Tested Jul 12, 2021
- when logged in as DCC saw the complete file set and multiple queried with the correct dataset in downloaded files
-  logged in as the `fakerosi` profile and saw only the correct limited dataset when i downloaded my files with no query
-  logged in as the `fakerosi` profile and saw only the correct limited dataset when i downloaded my files with a query applied
looks great thank you @joneubank
