### ISSUE TITLE
Logging out still shows private data on the file repository and entity pages

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1989]
## Bug
- After logout, the file repository did not refresh the data
- this means in this state "private" data is still visible, which would be inappropriate on a shared computer space. Can still access private entity pages too.
- on refresh the page loads correctly to just public data
Video: https://watch.screencastify.com/v/vpFBpCeVrit1Gb0X6wEK

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/18a06848-128d-45d7-b956-63bd1baa756b)

## Steps to reproduce

1. Log in as a program member or DCC admin
2. Apply one of the "private' filters, like "Full member access"
3. I can access these entity pages when logged in, as expected
4. Log out
5. I stay on the file repository page, with the full member access filter still applied. I can see all of the private files still but some links lead to 404 pages.
6. I need to refresh the page in order to lose access to these files.

## Expected Behaviour first pass
- [ ] The private files should not be available when logged out. 
- [ ] If the user is logged in and selects any filters, then they log out, the page should refresh and all filters should be cleared from the facet panel and sqon.
- [ ] The table should refresh too and the user should not be able to access private entity pages when logged out.

## Future possibility (not in scope of this ticket)
In the future we could change it to only clear the private filters that have been applied, and leave any public filters applied on logout - this is how ICGC 25K works (but then it does not have private filters)

**Comment by akachru-github** [comment]
Suggestions: 
- On logout, wipe all filters
OR
- Wipe only private filters (filters not available to the public)

Which is easier?

**Comment by akachru-github** [comment]
Don't need to change the filters at all, just needs a refresh to be able to show the appropriate data.

**Comment by kcullion** [comment]
> Suggestions:
> 
> * On logout, wipe all filters
>   OR
> * Wipe only private filters (filters not available to the public)
> 
> Which is easier?

Talked to @demariadaniel over slack - Dec 23. He will look into both but we can start with clearing all filters from the facet panel and sqon - which is easier

**Comment by kcullion** [comment]
tested in QA: 
- when I go to a private entity page when logged in, then log out - it becomes a 404 page because it's not a public page
- when I'm logged in and apply any filters, including the private access tier filters, then I log out , the file repo is refreshed with now filters applied and all of the private ids are gone.

this looks good, thanks @demariadaniel

**Comment by kcullion** [comment]
this is working as expected in staging
