### ISSUE TITLE
🐛 Facet text runs under count bubble in sidebar

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/platform-ui#1999]
## Describe the bug
In the file repo sidebar, when a facet value text is long, it runs underneath the bubble indicating the number of files in this option. See the `Xenograph - ...` and `Metastatic tumour - ...` options in this screenshot:
<img width="264" alt="Screen Shot 2021-07-14 at 11 20 57 AM" src="https://user-images.githubusercontent.com/8339820/125648213-93ed1d48-b6ee-4825-9836-b3315e874234.png">

We should update the related UI Kit components to render this in a nicer way. Discuss with Kim/Rosi if we want to abbreviate the value (Long text cut here...) that is shown long on hover, or if it should wrap to a second line. There may be other options, but either way we shouldn't be rendering over the text like we do now.

## Steps To Reproduce
Currently visible in prod file repo.

If the data changes, modify a file in the file-centric index you are developing against to have one a very long (like 255 chars) length value for one of the facet properties (specimen type, for example).

## Expected behaviour
UI Kit sidebar facets do not render text under additional elements. Full text values can be read (either through hover or line wrap, needs confirmation).

**Comment by rosibaj** [comment]
confirmed in production
