### ISSUE TITLE
🐛 Log-in from File Page fails and redirects to 404

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/platform-ui#2004]
## Describe the bug

When an anonymous user is on a file page, then logs in, the log in fails and the user is redirected to a broken URL. The problem appears to be with something appended to the URL during the redirect process and failure to store the JWT in local storage

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to file repository as anonymous user, click on a file in the table to navigate to file entity page.
2. From this file page, log in
3. After login you will shown a 404 and not be logged in.

Example broken URL: 

## Expected behaviour
User should be logged in and returned to the file page.

**Comment by joneubank** [comment]
@kcullion do we have an epic around refactoring login/refresh tokens? This can be lumped in with that planned work since this isnt worth fixing until we get the new system in place.

**Comment by akachru-github** [comment]
related to https://github.com/icgc-argo/roadmap/issues/779.

**Comment by kcullion** [comment]
This is working in QA now. Thanks @samrichca !

**Comment by kcullion** [comment]
this is working as expected in staging
