### ISSUE TITLE
Connect stats bar to the refactored stats query that reflects the active filters in the table

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-ui#2021]
![image.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/02ac7c3d-28d0-434e-84f1-d8624d57b345)
- In the above screenshot, notice that the stats bar shows 10 donors while the table shows only 1. This is because a filter has been applied to the "Donor" column.
- A new query is being generated for the stats bar such that it will reflect all filterable columns.
- This ticket is to capture the work required to update the stats bar UI once the updated query work is completed. 

- [x] update existing filters to also use the combined query 
- [x] search for any pieces searching for the split piece

**Comment by rosibaj** [comment]
@mistryrn Looks great!

**Comment by rosibaj** [comment]
Confirmed on production deploy
