### ISSUE TITLE
🐛 Clicking backspace in filter closes the modal (dashboard table)

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2027]
## Describe the bug
https://drive.google.com/file/d/1eXfRYaHp4LX2DunIDREK52hmrAmD3o1Q/view

## Steps To Reproduce
Watch the video (with audio on) 
## Expected behaviour
Backspace should not close the filter.

**Comment by mistryrn** [comment]
A fix for this has been implemented in https://github.com/icgc-argo/platform-ui/pull/2025 , will update this ticket as soon as that is merged and deployed.

**Comment by rosibaj** [comment]
confirmed in production release spet 02, 2021
