### ISSUE TITLE
Feature Request - Spinner/Loading Indicator when waiting for download files to complete

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/platform-ui#2032]
When downloading TSV or manifest from the file repository, it can take a while for the file to be generated (10-30 seconds for ~25k files). While this is taking place on the server, there is no indication on the UI that any action is taking place. An indicator (little spinner over the button maybe) to indicate an action is occurring would ease the user's mind and prevent duplicate requests.

## Detailed Description
1. Go to File Repository
2. Click Download -> TSV
3. Wait
4. File downloads

During the waiting in step 3 there is no indication that your download is being compiled, simply appears as though the request failed or wasn't submitted. Need an indicator

## Possible Implementation
- Change the icon to the spinner icon but keep the label of the button
- if not part of ui kit, make it part of ui kit

**Comment by demariadaniel** [comment]
Create follow up ticket to add to UI kit after UI-kit is removed from platform
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2095

**Comment by kcullion** [comment]
@demariadaniel I made a UI kit ticket for us to look at eventually making this behaviour standard in the platform, once the ui kit upgrades are done. Please add any more details that I may have missed https://github.com/icgc-argo/uikit/issues/12

**Comment by kcullion** [comment]
@demariadaniel this looks great! will be a nice indication for the user. thanks!
