### ISSUE TITLE
Resolve security alerts 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2036]
![image](https://user-images.githubusercontent.com/15824252/132384721-ba11eb29-54c7-41e2-a459-2607927b5bb3.png)

**Comment by mistryrn** [comment]
All issues other than the major version upgrade of Next.js have been resolved.

Next.js upgrade has been moved to a separate ticket: https://github.com/icgc-argo/platform-ui/issues/2080
