### ISSUE TITLE
UI Donor Dashboard Table - Implement Legend

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2042]
Zeplin mockup: https://zpl.io/VYMWxML
(Some of the icons could be in the UI kit/could be added to the UI kit)

- [x] the number on the far left is the total donors in the table
- [x] show the label always, but show 0 if none exist for that item
- [x] when the table is filtered, these numbers will update to reflect the statuses in the table
- [x] implement the right alerts for now, but hide within the UI

![image](https://user-images.githubusercontent.com/18424138/132533628-ad33b60b-a127-4f31-afbc-a53fc1fdd5e1.png)

**Comment by kcullion** [comment]
@mistryrn @b-f-chan 
As mentioned in demo, the concept of "Invalid donors" isn't correct anymore. 
So the invalid donor count in the far right of the legend should not be there. Rakesh can you remove that count for now from the legend? 

Brandon, can me, you and @hknahal meet about this invalid donor stuff and confirm this is still correct, which is what Christina, Rosi and I discussed last...

1. If the dictionary changes, with new required fields added - we won't mark the released donors that already have clinical data submitted as "invalid" anymore. So if a donor is released with 100% of the required clinical data and then that clinical completeness changes with dictionary updates, we will just warn the data submitter that they need to provide some values for certain fields. And we will not remove them from being released.
2. if this is correct, we can work on a ticket to remove the invalid donor stuff from the current donor dashboard table.

![image](https://user-images.githubusercontent.com/18424138/138332415-54a3a2af-928e-43d0-bf97-35be09478a80.png)

**Comment by mistryrn** [comment]
Above feedback has been addressed in https://github.com/icgc-argo/platform-ui/pull/2097 , I'll let you know when it is merged and testable!

**Comment by kcullion** [comment]
Clicked around the DCC admin dashboards on staging, and this is working!
