### ISSUE TITLE
Connect Dashboard Filters to new aggregates

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2046]
- [x] Connect new aggregate api filters to the UI

**Comment by rosibaj** [comment]
@mistryrn can i get a version on this ticket?

**Comment by kcullion** [comment]
had a look at the aggregates in the filter dropdowns for many programs and it seems to be working correctly in staging: ![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/55a2be3c-6733-4452-a7f2-6c7aeeafc5e7)
