### ISSUE TITLE
Update the clinical file download endpoint to make sure it excludes registration 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2047]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/c2aa7f24-a5bd-49fd-b27a-c7a9dc864403)

**Comment by kcullion** [comment]
tested in staging Nov 9. When I download the clinical template files from a program on staging, I get a zip folder that excludes the sample_registration file. So this seems to be working on staging platform!
![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/ac7bee35-472c-43e0-9c92-7fad2edc5dab)
