### ISSUE TITLE
Add Open Access Filtering Column to UI 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2063]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/2fe6ccdb-079a-4591-ace4-7409c1345a82)
- We will have a separate column named "Open Filtering" under "DNA-SEQ PIPELINE" which will show the jobs running status in real time. 
- This will also include adding the filtering to UI for this new column, which will be the same as the other dna-seq filters

API tickets: https://github.com/icgc-argo/donor-submission-aggregator/issues/219
https://github.com/icgc-argo/platform-api/issues/490

**Comment by mistryrn** [comment]
After a chat with Kim and Linda, it was decided to label this column `Open Access VF` as a shortened form of the full workflow name `Open Access Variant Filtering`.

**Comment by kcullion** [comment]
I see this column in QA and the filtering works too. thanks @mistryrn !
![image](https://user-images.githubusercontent.com/18424138/146210081-ffce33d8-7f56-4b3c-9536-632d87cd4d7e.png)

**Comment by kcullion** [comment]
moving this ticket to awaiting release since the UI features are working as expected in QA, the issues are more data based right now.

**Comment by kcullion** [comment]
The Open access column is working on the program dashboard in staging
