### ISSUE TITLE
Investigate why platform refresh does not work

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#2083]
- `/api` is forgotten ?
- using string concatenation instead of a url joiner
- constants file?

**Comment by samrichca** [comment]
Unable to reproduce - refresh tokens work in isolation for me, and I think the issues in normal usage are due to having multiple sessions/tabs. Gonna go ahead with other token tickets.

**Comment by samrichca** [comment]
Updated the wiki re: why refresh tokens don't work
