### ISSUE TITLE
🐛 Donor filter search only working for some programs: QA and staging

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2101]
## Describe the bug
On **QA and staging**, when I copy and paste an id in this filter (for some programs), I get "no data" returned.
![image](https://user-images.githubusercontent.com/18424138/140997885-be072f36-a4b1-4ed4-af17-76a5ea471a5e.png)

Also: Hardeep tested all the programs in Prod, and they all filtered by donor id correctly.

## Steps To Reproduce
Most programs on staging aren't working, but these two I find are filtering properly:
https://platform.staging.icgc-argo.org/submission/program/MUTO-INTL/dashboard
https://platform.staging.icgc-argo.org/submission/program/TEST-INTL/dashboard

## Expected behaviour
This filter should work for all programs

**Comment by akachru-github** [comment]
This looks to have been an indexing issue. Affected programs were reindexed and the filter is working as expected now.
