### ISSUE TITLE
Show pretty file ID on the UI and entity URL

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2109]
## File Repository

- [ ] Add File ID column as the first column that displays the "pretty" file id. That will be the link to the file entity page, instead of the object ID. 
- [ ] Add the File ID to both file downloads (Manifest and Table TSV)
- [ ] File entity page: change the url to reference the file ID rather than object ID
- [ ] File entity page also contains "File ID" in the table that will also need to be populated. 

![image](https://user-images.githubusercontent.com/18424138/143489398-55545457-92b1-425a-8a91-87bdb2224344.png)

## File Entity page
![image](https://user-images.githubusercontent.com/18424138/143489640-668fc8ab-4175-49ed-b5bb-c29ed0a39f2a.png)

**Comment by kcullion** [comment]
This looks good @demariadaniel !
Didn't specify in ticket, but can you just make the default order on the File ID column, in descending order (so the newer files come to the front). And show that it's sorted on that column, it's built into the table component I think to show that blue bar on the column its sorted on.

![image](https://user-images.githubusercontent.com/18424138/151851488-9655286c-6fd6-4e31-b87a-ce619c00cb0c.png)

**Comment by kcullion** [comment]
Also @demariadaniel is it an easy fix to make the "table tsv" download have the same column order, from left to right, as the file repo table in the UI?

**Comment by demariadaniel** [comment]
@kcullion Yes actually it looks like that can be done pretty easily

**Comment by kcullion** [comment]
Great, thanks for looking into that @demariadaniel . Please add that as part of the feedback for this ticket :)

**Comment by kcullion** [comment]
As per slack discussion with Dan and Linda, we will leave the sort order as is and fix that after the release, as it's a bigger fix than we anticipated. 

From Dan:
```
OK so issue with sorting by file id, technically FL999 > FL1000 -- files above 999 are getting pushed to the back of the line, because of a quirk of how JavaScript works.
I can order the File IDs such that it starts at 999 and descending for now. Do we want that?
Getting it so file ids >999 display first is going to require extra logic on the API.
```
API ticket for this: https://github.com/icgc-argo/platform-api/issues/521

**Comment by kcullion** [comment]
I see the table download now has the columns in the right order in QA. Thanks so much Dan!

**Comment by kcullion** [comment]
this is working as expected in staging. I see the file id in the table tsv download and not the manifest so that's correct!
