### ISSUE TITLE
File Repository: when log out should refresh so the private files and filters are not accessible

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2116]
See this video: https://watch.screencastify.com/v/vpFBpCeVrit1Gb0X6wEK

1. Log in as a program member or DCC admin
2. Apply one of the "private' filters, like "Full member access"
3. I can access these entity pages when logged in, as expected
4. Log out
5. I stay on the file repository page, with the full member access filter still applied. I can see all of the private files still but some links lead to 404 pages.
6. I need to refresh the page in order to lose access to these files.

## Expected Behaviour

- [ ] If the user is logged in and selects any private filters (the yellow shaded facets), then they log out, the page should refresh and the filters removed so that I can't access the private filters and files.
- [ ] If the user is logged in and filters that are public (like data type), they should stay applied when logging out (mimics dcc.icgc.org)

**Comment by kcullion** [comment]
@akachru-github @joneubank 

@samrichca  found this - putting it in the next sprint as I'm not sure if this is an issue on staging or production right now.

**Comment by samrichca** [comment]
applies to File Entity & File Repository

**Comment by kcullion** [comment]
Merged some of these details with this ticket. Just noticed this was a known bug
https://github.com/icgc-argo/platform-ui/issues/1989
