### ISSUE TITLE
Split up authprovider into auth & data providers

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-ui#2123]
- Auth provider handling auth and data fetching
- Split this up into an auth provider and data provider, should work more like a redux action

**Comment by akachru-github** [comment]
Work don e a feature brach. Will leave in Dev Testing until we figure out a strategy for making this available for testing

**Comment by b-f-chan** [comment]
@samrichca to check what's been merged, then close whatever tickets relevant

**Comment by samrichca** [comment]
Closing. Some work on this epic is on the branch `feat/jwt-refresh`.
