### ISSUE TITLE
reduce redundancy between app.tsx & authcontextprovider

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-ui#2124]
- app.tsx handling things that the auth provider should handle
- app.tsx should instantiate and pass down to the auth provider, and should not duplicate functionality
  - contains duped functions form auth provider and login page
  - app.tsx > auth > data > root (handle path and data protection) > page layout

**Comment by samrichca** [comment]
scope update: remove server-side auth & handle page auth client-side. otherwise, maintain functionality for now.

**Comment by samrichca** [comment]
Closing. Some work on this epic is on the branch `feat/jwt-refresh`.
