### ISSUE TITLE
Make logging out secure

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-ui#2125]
- Ensure this is covered by https://github.com/icgc-argo/platform-ui/issues/2124
- Ego does not have a logout endpoint.

**Comment by samrichca** [comment]
we need a logout endpoint from ego and we need to detect logout events in other tabs/sessions.

**Comment by samrichca** [comment]
Closing. Some work on this epic is on the branch `feat/jwt-refresh`.
