### ISSUE TITLE
Donor entity: Clinical Timeline - Specimen

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2127]
## Goal
Set up the specimen tab and data tables with the correct field rules.
Every donor will eventually have at least one Normal/tumour pair.
**Clinical files**: specimen.tsv and some sample information from sample_registration.tsv

## Timeline Details
- [x] 1. The specimen days along the timeline will show the value in the `specimen_acquisition_interval` field
- [x] 2. This could have been set up in the styling ticket, but show a test tube icon for Specimen.

## General Data Details
- [x] 3. The tab includes the event label `SPECIMEN`, `Specimen ID` (ARGO pretty id), and the `tumour_normal_designation` field (from the associated sample registration file).
- [x] 4. The Specimen Files button will link to the file repository, filtered on this donor ID and specimenID (so will show all files related to this specimen).

## If tumour_normal_designation = tumour (this field is in sample_registration file)
Zeplin: https://zpl.io/an8vJRY
- [x] 5. Show all files related to the specimen file for tumours, split into two ~equal tables.
- [x] 6. `Pathological TNM Category` - combine the three fields submitted: `pathological_t_category`, `pathological_n_category`, `pathological_m_category`, into one string. So the value will look something like: `T0N0M0`. 
- [x] 7 `Specimen Acquisition Interval` - display the units: days.
- [x] 8 **Samples from this Specimen** - Display a table that shows each sample that is associated with this specimen. The title will display the count of those samples.
- [x] 9. List the experimental strategies that this sample went though (from files index??).
- [x] 10. List the workflow names that this sample went through (from files index??). Can we make this wrap onto multiple lines?
- [x] 11. The **Available Files** shows the number of files that exist in the file repository for this sample, the link will link to the file repository, filtered on this donor ID and sample ID.

![image](https://user-images.githubusercontent.com/18424138/144673485-9165470a-ebaa-427c-89bb-91937a93668a.png)

## If tumour_normal_designation = normal (this field is in sample_registration file)
Zeplin: https://zpl.io/bo7EQqE
All of the above applies except:
- [x] Hide all of the fields that only pertain to tumours: 
- pathological_tumour_staging_system
- Pathological TNM Category
- pathological_stage_group
- tumour_histological_type
- reference_pathology_confirmed
- tumour_grading_system
- tumour_grade
- percent_tumour_cells
- percent_proliferating_cells
- percent_inflammatory_tissue
- percent_stromal_cells
- percent_necrosis
![image](https://user-images.githubusercontent.com/18424138/144674406-a677372e-ac92-4c23-95cf-70a33fedbe9f.png)

**Comment by kcullion** [comment]
@demariadaniel as mentioned over slack, there are some changes regarding the ids.
![image](https://user-images.githubusercontent.com/18424138/160921098-875f7a19-8cd6-4e0e-8803-af9c43398e12.png)

**Comment by kcullion** [comment]
@demariadaniel as discussed over slack - we just need to make some changes to the fields shown. We will just show the argo pretty ids in the UI for specimen and samples (both normal and tumour).
We will also add a column for matched sample id and eventually use what Jaser did here: https://github.com/icgc-argo/song-search/issues/67

![image](https://user-images.githubusercontent.com/18424138/160929374-5bdb1f99-7516-4726-8a03-7e71dcbf6ec5.png)

**Comment by kcullion** [comment]
@demariadaniel please make the following changes

- [ ] For normal specimen, the fields should be as shown here:
![image](https://user-images.githubusercontent.com/18424138/163249012-fcf908f8-9629-4104-8f2a-66530aa901d2.png)

- [ ] For tumour specimen can you make sure the fields are as shown here:
![image](https://user-images.githubusercontent.com/18424138/163249748-3b2c47b6-59ee-4a1e-89fb-6446088160da.png)

**Comment by b-f-chan** [comment]
@kcullion to test

**Comment by kcullion** [comment]
Just had a question for @demariadaniel 
I noticed that normal and tumour aren’t using the same samples table? the sample type should be the 3rd column
![image (95)](https://user-images.githubusercontent.com/18424138/164722797-e0792d76-2e6f-45c5-9b68-916ac6acbead.png)

**Comment by kcullion** [comment]
Just moved this to awaiting release so it will go in with the I release. 
The small fix that's left to do has been copied to this ticket: https://github.com/icgc-argo/platform-ui/issues/2290 
This feature is hidden so it's not a priority for the release

**Comment by kcullion** [comment]
correctly hidden on staging
