### ISSUE TITLE
File Repo: implement tabs for facet panel

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2156]
**THIS SHOULD BE BEHIND A FEATURE FLAG**

## Goal
When the clinical data is indexed in the file repository, we want to display the facets in two tabbed panels, similar to: https://dcc.icgc.org/repositories
In this ticket, we will set up the tabs and arrange the facets that currently do exist in the file repository.

![image](https://user-images.githubusercontent.com/18424138/149182001-42ee7ed6-627c-4961-88ca-e10e1311f067.png)

## Expected outcomes
- [ ] Tabs are styled as per mockup, and working to switch facet list

Active and default tabs shown: Zeplin: https://zpl.io/VkL7x8G
Hover state just needs to be on the default state tab (not the active) seen here on the File Filters tab (just change background colour to #F2F2F8)
![image](https://user-images.githubusercontent.com/18424138/149184239-19b94541-5584-41a9-b904-44a5fa8e9bac.png)

Note these tabs look a bit different than the ones that exist in storybook right now - those are not noticeable enough: https://argo-ui-storybook.netlify.app/?path=/story/uikit-tabs--basic
You could use these as a starting point and make a "rounded tabs" component (they could be tabs we want to reuse in the future)

### Clinical Filters tab
- [ ] For now, the clinical tabs can show the facets that exist in the current file repository (we will hook the rest up in this ticket:https://github.com/icgc-argo/platform-ui/issues/2158)
`Program ID`
`Specimen Type`
`Specimen Tissue Source`
Note: they should be open facets by default - they appear closed in the mockup just to make it easier for design purposes.
![image](https://user-images.githubusercontent.com/18424138/149193219-de230044-ce1b-4df1-8220-63e1667fe508.png)

## File Filters tab
- [ ] All of these facets currently exist in the file repository - you can display them in the file filters tab as shown in in the mockup. Again, all facets should be open by default
Zeplin: https://zpl.io/bAPD0Kp

## Access Tier facet
- [ ] when a program member or dcc admin are logged in, sometimes an access tier facet is displayed. This will display in both clinical and file filter tabs, below the search facet, as shown in: https://zpl.io/bAPD0Kp
![image](https://user-images.githubusercontent.com/18424138/149188084-19626daf-f1fc-401e-a90c-0cf85e0ec8d1.png)

**Comment by demariadaniel** [comment]
@kcullion In addition to Access Tier does release state display on both tabs?

**Comment by kcullion** [comment]
this is looking good, thanks @demariadaniel !
Will move this to awaiting release and put my feedback into this ticket: https://github.com/icgc-argo/platform-ui/issues/2186

**Comment by kcullion** [comment]
this is hidden in staging...that's the extent of the testing I can do here.
