### ISSUE TITLE
File Repo: new Search by Donor ID facet that returns donors

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2159]
**THIS SHOULD BE BEHIND THE FEATURE FLAG** 
NOTE: this may need an API ticket, please investigate and if so, let us know
See ICGC facet panel for search box examples: https://dcc.icgc.org/repositories

## Goal
To split out the Search by Donor ID into a new component that is displayed in the clinical filters tab. This will allow the user to search by donor id/submitter donor id, return a list of matching donors, then to choose a donor and access all files for them.

## Expected Outcomes
- [x] Placeholder for this search box `e.g. DO35083, PCSI_0103...` 
- [x] with an info bubble that states: `Enter a Donor ID or Submitter Donor ID.`
NOTE: Ignore the "Upload a list of IDS" button for now - this is a future feature to be speced out (so don't display the button yet).
![image](https://user-images.githubusercontent.com/18424138/150192127-6e16651b-7897-409a-8b64-99260eef78dd.png)

- [x] When the user enters a donor_id or a submitter_donor_id, return a list of up to 5 donors that match the input.
The result should have the format:
```
donor_id (submitter_donor_id)
primary_site
```
Shown in Zeplin: https://zpl.io/a8dopjJ
![image](https://user-images.githubusercontent.com/18424138/150192282-48a20aba-de00-471b-bb9f-f974f12a8021.png)

## Selecting a donor result
As the mockup below shows, when the user chooses a donor result from this list:

- [x] 1. The donor_id is added above the search box with the ability to remove it. 
- [x] 2. The donor_id is added to the sqon as shown in mockup
- [x] 3. The file list and charts are filtered **on that donor_id - showing all of the files that exist for that donor**
- [x] 4. The user can still add multiple ids in this search box, which also get added to the sqon and above the search box (like you fixed for the file search)
 
![image](https://user-images.githubusercontent.com/18424138/150206757-ce654d55-7c32-4604-8dba-cac6e03cd4ba.png)

 
 ## Current Search box should now just search file ID and object id
 
- [x] Remove the ability to search by donor id/submitter donor id in the current searchbox, it will now just search by file id and object id
- [x] change the title to "Search by File ID" 

- [x] Placeholder for this search box `e.g. FL13796, 009f4750-e167...` 
- [x] with an info bubble that states: `Enter a File ID or Object ID.`
![image](https://user-images.githubusercontent.com/18424138/150197473-aabfc160-d719-4447-9795-fa55850fbc1c.png)

**Comment by kcullion** [comment]
Thanks @demariadaniel  here's some feedback

- [ ] when typing in `DO` I should still see 5 suggested results in the dropdown, like the file search does:
![image](https://user-images.githubusercontent.com/18424138/155789224-4eb970c0-ea03-4fd4-a9c2-325f69a05342.png)

- [ ] The donor search and file search should be independent of eachother. in the above example, if I switch to the file facet tab - I see the same thing I typed in to the donor search. This should not activate the file search box
![image](https://user-images.githubusercontent.com/18424138/155790021-39d85dd8-3d3d-48db-ace9-751df74f91d5.png)

**Comment by demariadaniel** [comment]
* Unable to reproduce `?` icon position issue, may only be an issue on larger monitors.

* Unable to display Program ID & Primary Site in Search Results menu w/ current queries, will need to wait for Donor Centric API

* Search Result menu currently displays Donor ID or File ID of matching search results, even if the search query matches the Object ID or Submitter Donor ID. 

If we want to display the property which matches the search term we should create another ticket (i.e. display Donor Submitter ID when searching 'PCSI'). This also depends on Donor Centric API to work properly for Donor Search.

**Comment by kcullion** [comment]
@hknahal @lindaxiang this use case has come up a lot: **As a data user, I am interested in seeing all the files for one donor.**

Can you please test the Donor search box that Dan has been working on in the QA file repository and see if it meets your needs? Thanks!

**Comment by hknahal** [comment]
@kcullion @demariadaniel I tested the Donor Search box in QA and it looks good!

**Comment by lindaxiang** [comment]
Thanks @kcullion , I tested upon with all the feedback you gave last time and all work well. Thanks a lot to @demariadaniel for the great job!

**Comment by kcullion** [comment]
Thanks for testing @hknahal and @lindaxiang ! Will move this ticket to awaiting release. Yay @demariadaniel !

**Comment by kcullion** [comment]
hidden as expected in staging
