### ISSUE TITLE
Add Tabs and RNA Table 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2176]
## Requirement
Add 2 new tabs and RNA columns to the donor dashboard table and hook up the data.
![Screen Shot 2022-03-16 at 4 30 01 PM](https://user-images.githubusercontent.com/8744047/158685425-c71daed5-aa2b-4117-a474-f116dcc49065.png)

1. Add a DNA tab and name it `DNA-SEQ`
- The tab should be above the `DNA-SEQ PIPELINE` header. 
- When clicking on DNA tab, the pipeline table section displays DNA columns
- rename `Samples` column (currently is under CLINICAl DATA STATUS header) to `Registered Samples`, and move it under `DNA-SEQ PIPELINE`. 
Mocks: Mocks:  https://projects.invisionapp.com/share/YS12DZ7RJ7KV#/screens/464268841_07a-Dashboard-DNA-tab

2. Add a RNA tab and name it `RNA-SEQ`
- The tab should be above the `RNA - SEQ PIPELINE` header.
- When clicking on RNA tab, the pipeline table section displays RNA columns
- Add a new table with these 3 columns: `Registered Samples`, `Raw Reads`, `Alignment` under `RNA-SEQ PIPELINE` header.
Mocks:   https://projects.invisionapp.com/share/MW12DZ8YYS3V#/screens/464269495_08a-Dashboard-RNA-tab

3. tab styling is the same as the file repo facet panel tabs but with a new background colour for each active state. The hover state is on the non-active grey tab, when the user hovers this non-active tab, change to this background-colour: #F2F2F8 (not in a mockup).
![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/f64f2498-8449-4c9d-980a-8830481d60b1)

4. For DNA - modify the error state styling (from red font to black font and apply the light pink shading to the cell).   Note: this was implemented as a pipe delimitate values in one cell - could talk to Sam for background on why it was done like this
![image](https://user-images.githubusercontent.com/18424138/159534462-5ffec74a-64c5-4796-a72f-59c192d2aa44.png)

**Comment by b-f-chan** [comment]
Independent of backend, this UI work can be started, candidate for @samrichca

**Comment by b-f-chan** [comment]
Candidate for @samrichca, can do styling and layout, but data part blocked by API

**Comment by lindaxiang** [comment]
The new RNA table and tabs look great!

**Comment by edsu7** [comment]
DNA-seq tab, RNA-seq tab, and error cells looks good to me

**Comment by Buwujiu** [comment]
Tested in QA, no issue, moving to awaiting release.
