### ISSUE TITLE
🐛 Items in `Analysis Tools` on file page are not correctly concatenated

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/platform-ui#2178]
## Describe the bug
Field `Analysis Tools` on the file page is an array which could contain more than one item. Currently,  Items in `Analysis Tools` on file page are not correctly concatenated.
![image](https://user-images.githubusercontent.com/18424138/151259327-97928364-65e2-4ddd-b063-a0134794ea89.png)

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/file/FL12097
2. `Analysis Tools` is showing as a string: `BWA-MEMbiobambam2:bammarkduplicates2`
3. However the field in platform api is an array 

<img width="592" alt="Screen Shot 2022-01-26 at 5 17 56 PM" src="https://user-images.githubusercontent.com/7522294/151257556-fbd76200-9779-463a-bd87-d5874a8e0846.png">

## Expected behaviour
Concatenate the items in the field `Analysis Tools` with `,' and a whitespace. 
```
BWA-MEM, biobambam2:bammarkduplicates2
```

**Comment by kcullion** [comment]
I see the comma on the page with multiple analysis tools. Thanks Dan!

**Comment by kcullion** [comment]
I see that multiple analysis tools have a comma separating them in staging. Eg. https://platform.staging.icgc-argo.org/file/FL33437
