### ISSUE TITLE
Add RNA-Seq Raw Reads and Alignment to Molecular Data Chart

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2198]
## Requirements
Add a new section `RNA-SEQ PIPELINE` to the existing molecular data summary chart on the donor dashboard. 

![Screen Shot 2022-02-09 at 12.10.22 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/c033d66a-b9c5-4fb8-a63e-4529db467b00)

Mockup: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/61f08926dda35ea78092421d

- the default should display all checks
- RNA should only plot tumour samples.

**Comment by b-f-chan** [comment]
Candidate for @samrichca, can do styling & layout, but data blocked by API

**Comment by samrichca** [comment]
Here's what it looks like with mock data ![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/ecc70f45-e114-4ebc-9ff0-810c64c36e30)

**Comment by lindaxiang** [comment]
@Buwujiu 
New section "RNA-SEQ PIPELINE" is added to the chart and checkbox is working properly

comment:
Noticed that when numbers are small, the numbers showing on the chart are not accurate? maybe it is an existing issue?
![Screen Shot 2022-11-11 at 10 18 20 AM](https://user-images.githubusercontent.com/7522294/201370858-bc730611-9c59-4d39-bd76-37c5cb5612c4.png)

**Comment by Buwujiu** [comment]
Yes @lindaxiang it's an existing issue, we should find time to address this.

**Comment by edsu7** [comment]
Successful test:
- `RNA-Seq pipeline` section in chart works
- Populating with `Alignment` and `raw reads` for RNA also works.

Side note:
- Noticed numbers are slight off in the graph for DNA though
- (Test-QA) Alignment totals >8 compared to graph
![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/5185c549-cefd-41b0-b9fb-3bb979c9f53f)
- (TEST-PR) According to graph Mutect (red) == Open Access (blue) when dashboard summary shows 4 vs 2 respectively
![image.png](https://images.zenhubusercontent.com/620bd7ddfcce5ea2de2e0d01/88f0893c-703a-435b-a874-b1e4a22f840f)

**Comment by Buwujiu** [comment]
Found issues in qa: https://github.com/icgc-argo/platform-ui/issues/2457.
Moving this to awaiting release.
