### ISSUE TITLE
Investigation - Invite user flow - Join Program   🐛 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/platform-ui#2215]
## Describe the bug

Join program is not working properly in DEV / QA / Staging / **Prod**
This could be a release blocker.
## Steps To Reproduce

1. invite a user to join program
 
2. go to mail hog and click join program https://mailhog.dev.argo.cancercollaboratory.org/

3. click login with google 

![image](https://user-images.githubusercontent.com/8655252/156599992-685295bf-b3f9-427f-9126-d637efc761ca.png)

5. Google login and account selection is not showing

- I tested with incognito mode and it worked properly 
- I tested the redirect_uri with normal login and it worked properly
## Expected behaviour
Login account selection similar to login button should show.

**Comment by blabadi** [comment]
played a little bit with this, and found that if I copy the login with google url from invitation page to the platform main page the button works for some reason. will send videos on slack

**Comment by blabadi** [comment]
I have confirmed the flow works in chrome incognito mode. google cookies seem to be causing the issue in normal mode
![image](https://user-images.githubusercontent.com/8655252/159750271-887f68a5-50d5-4e3b-aefa-3d52586af570.png)

I have no explanation for why copying the link to platform home page works though, and why it doesn't work outside incognito, that still needs investigation

**Comment by akachru-github** [comment]
This is happening in production, so is not related to the new version of Ego. 
This looks to be an existing bug in prod that has been around for a bit.

**Comment by b-f-chan** [comment]
@samrichca to complete this bug before moving onto RNA-Seq

**Comment by samrichca** [comment]
This issue is partially due to the button and partially due to Ego not prompting the user to select an account.

Additional ticket: https://github.com/overture-stack/ego/issues/645

**Comment by blabadi** [comment]
not resolved yet, after updating the ego url to prompt users for account issue still happening on the platform UI
![image](https://user-images.githubusercontent.com/8655252/171476247-681f3453-fa70-490e-9e6a-02d4ab8b6ebd.png)

**Comment by b-f-chan** [comment]
Tested successfully using both Chrome and Firefox in QA:

- Logged in as Program Admin, invited 2 users to LUCA-KR as Submitters
- In Chrome for one user and Firefox for second user:
    - Logged into MailHog on QA
    - Clicked Join Program
    - Selected Login with Google
    - Successfully redirected to Google auth
    - Authenticated with Google, successfully redirected to Join Program page
    - Filled in details, then was successfully redirected to Program Dashboard

This ticket can be moved into Awaiting Release

**Comment by kcullion** [comment]
Tested in prod by inviting myself to TEST-INTL and tried logging in in chrome and firefox..and it allowed me to. Great job!
