### ISSUE TITLE
File Entity: Enable `Sequencing Reads Properties` Section

### ISSUE THREAD

**Issue by mistryrn** [icgc-argo/platform-ui#2219]
Once the `metrics` data is available in the API, enable the `Sequencing Reads Properties` section of the File Entity page for files with `Data Type === Aligned Reads`.

From https://github.com/icgc-argo/platform-ui/issues/2105 :

![image](https://user-images.githubusercontent.com/3392776/156844492-e1e1b0e8-8482-4a78-8991-a8f95477b076.png)

## Sequencing Read Properties

- [ ] 5. `When Data Type = Aligned Reads`, show this new card at the bottom of the page that will show the quality of the BAM file to the user. This includes pulling in the following values from the song payload (metrics object)

```
"metrics": {
"total_reads": 2177190124
"paired_reads": 2177190124,
"pairs_on_different_chromosomes": 28108737,
"average_insert_size": 309.5,
"average_length": 100,
}

```

**Comment by kcullion** [comment]
thanks @mistryrn! Leaving in QA for:
- fixing spacing in between metrics
- testing that all aligned reads have metrics - noticed some don't like: https://platform-ui.qa.argo.cancercollaboratory.org/file/FL12097

**Comment by kcullion** [comment]
From a UI standpoint, this card looks great! 
We can further test the actual data in relation to this ticket: https://github.com/icgc-argo/platform-api/issues/506

**Comment by b-f-chan** [comment]
Note: @lindaxiang might need to help with staging + prod test

**Comment by lindaxiang** [comment]
@kcullion @mistryrn Just spot checked a couple of sequencing reads file entity page, the metrics are all correctly showing there. Thanks for the great job!
