### ISSUE TITLE
File Entity page: doc links update for new RNA workflows

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2240]
For the file entity page, we added links for `Workflow Name` and `Workflow Version`

- [x] confirm with @lindaxiang the workflow version links should work as expected with the new RNA workflows
- [ ] once documentation pages are set up, we need to add a new link for the RNA Alignment docs

![image](https://user-images.githubusercontent.com/18424138/158200014-149cafff-93d7-455b-841f-927f28f1f405.png)

**Comment by lindaxiang** [comment]
@Buwujiu , 
`Workflow Name` will link to `https://docs.icgc-argo.org/docs/analysis-workflows/rna-alignment` in future but the page currently does not exist yet.
`Workflow Version` should link to a tag dynamically based on the value in `workflow version`, this is the same as all the other workflows. E.g: https://github.com/icgc-argo-workflows/rna-seq-alignment/releases/tag/0.1.1

**Comment by lindaxiang** [comment]
@Buwujiu 
For RNAseq, there are two other fields which need to be updated on the page.
- `Genome Build`: `GRCh38_Verily_v1` (link to `https://console.cloud.google.com/storage/browser/genomics-public-data/references/GRCh38_Verily`)
- `Genome Annotation`: `GENCODE v40` (link to `https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/gencode.v40.chr_patch_hapl_scaff.annotation.gtf.gz`)

**Comment by Buwujiu** [comment]
Links for Genome Build and Genome Annotation #2495
