### ISSUE TITLE
Donor Entity: Page + card styling feedback and bugs

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2242]
Feedback on the donor entity page will be collected here:

## General
- [x] Layout-wise - can you make the spacing between the cards equal?
- [x] On the desktop view it possible to dynamically make the heights of the summary and available files card equal, no matter what's inside?
![image](https://user-images.githubusercontent.com/18424138/158252215-903871e3-2453-452c-a5cd-b4adf01c2e5c.png)

- [x] Header: just missed the link to the Data Dictionary (which will open this page in a new tab: https://docs.icgc-argo.org/dictionary)
![image](https://user-images.githubusercontent.com/18424138/158456517-3d2d17e6-12a2-42e2-b116-882e07f21b6d.png)

- [x] **Summary card**: sometimes there's no space in between the table. there should always be this consistent spacing in between the tables in a card/clinical timeline
![image](https://user-images.githubusercontent.com/18424138/158262304-c25d6fe0-47b6-4e0a-8124-076ad15773be.png)

## Clinical timeline
- [x] I found a weird crash - if you remove all of the filters on the clinical timeline it crashes the page and goes back to the homepage. We should show the Vital status tab and "no data found" message (sorry - I said to remove this in this ticket - but I think this is the correct message:https://github.com/icgc-argo/platform-ui/issues/2119). 
- [x] ![image](https://user-images.githubusercontent.com/18424138/158254125-cb9576e7-82f7-4fcd-aa50-0727f2d0824f.png)

- [x] If go to the donor page, and look at the right-margin for the container, when refreshing the page, the container width grows to span the entire card:
![image](https://user-images.githubusercontent.com/18424138/158263099-1b81475e-fd7d-4913-aa87-b353c0af5adb.png)

- [x] The timeline buttons feel strange without a hover state...can you implement a consistent grey background (#F2F2F8) when the user hover overs any of the non-active buttons? 
![image](https://user-images.githubusercontent.com/18424138/158462936-fcf326e3-28e9-485e-a11c-cf4bdf925dfa.png)

- [x] Top align the vertical timeline label instead of center. It will get lost especially when the user filters on data type. (see screenshot below)
- [x] The timeline card height is a bit tall. Can we try to set a smaller min-height and have it be able to grow based on the content?
![image](https://user-images.githubusercontent.com/18424138/158465546-26f8a5ea-0935-4102-b21b-44e227f555b6.png)

- [x] For the specimen tabs - the first table just gets an extra left indent that the other tables don't get
![image](https://user-images.githubusercontent.com/18424138/158467429-c015f679-843b-4222-a44e-3a7f618bf101.png)

- [x] For values that span more than one line, can we show the full value instead of `...`? just for now at least until we see the real data coming through and what happens. In this case I think it's important to show all the treatments listed here
![image](https://user-images.githubusercontent.com/18424138/158468415-9b9ad3d8-aab4-499f-ae5c-d37129ba6b5d.png)

- [x] would it be painful to always have the circle + number of days + age tag (if exist) all be vertically centered within the timeline button? right now they show up at different parts of the button 
![image](https://user-images.githubusercontent.com/18424138/158468736-afc39902-d8b1-440d-8374-c8344ef6f62b.png)

**Comment by kcullion** [comment]
Great job @demariadaniel ! Sorry I'm going to be picky here - just notice a few things so I will put this ticket back in progress

- [ ] I still see the spacing between tables increase when refreshing the page. The clinical timeline card also sometimes has padding-right and sometimes doesn't on refresh. Let me know if you want to hop on a call to see what I mean.
![image](https://user-images.githubusercontent.com/18424138/159790659-201a349f-fa77-46e6-a0ae-7ae35682c6d1.png)

- [ ] perhaps related to this item above - there's a grey background with part of the clinical timeline background happening 
![image](https://user-images.githubusercontent.com/18424138/159791080-8467fa1d-899a-4681-9a77-f2e1358a6d80.png)

- [ ] Can you make it always show all of the data tables in each timeline tab? Specifically this specimen tab. I didn't notice there was a scrollbar here so I missed the bottom tables
![image](https://user-images.githubusercontent.com/18424138/159791257-21152d29-e380-4b8b-b3b6-04e0b541de4e.png)

- [ ] Thanks for centering the timeline dots! Would it be ok to also lineup the days/age items with this dot? Right now, especially the bottom item, it's sort of falling off the line
![image](https://user-images.githubusercontent.com/18424138/159791745-98d9f68b-58a2-4ab6-88ab-64af2867105a.png)

**Comment by kcullion** [comment]
carried over the outstanding styling fixes to this ticket to revisit later https://github.com/icgc-argo/platform-ui/issues/2273

**Comment by demariadaniel** [comment]
Centred timeline elements fixed in: https://github.com/icgc-argo/platform-ui/pull/2277

**Comment by kcullion** [comment]
I see the timeline age/dots are showing up in the right place on the tab. Thanks for your hard work on this @demariadaniel ! moving the ticket

**Comment by b-f-chan** [comment]
@demariadaniel please tag with version

**Comment by kcullion** [comment]
hidden as expected in staging...moving along
