### ISSUE TITLE
Update DNA Sample & raw reads filters

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2245]
## Requirement
1. Update donor dashboard UI existing DNA table filters to match new design. 
![Screen Shot 2022-03-15 at 5.22.02 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/13050b0b-512d-4c10-a0cd-36375bd81cbc)

2. update filter criteria names for DNA `Raw Reads` and `Registered Samples` columns: 
Mocks: https://projects.invisionapp.com/share/NV12DZ8V7E2T#/screens/464269494_07c-Dashboard-DNA-Filters

3. update filter box titles to `DNA Registration Status` and `DNA Raw Reads Status`

4. Filters behaviour stay the same as they do now, and there is no styling change. 
5. When filter checkboxes are checked, dashboard table should update accordingly, 
For samples:
  - When filtered on T or N not registered, any donor with tumour or normal cell being 0 shall show in the table.
  - When filtered on T and N registered, any donor that has at least one tumour and at least 1 normal shall show in the table. 
  - When filtered on No samples registered, donors with 0 tumour and 0 normal samples shall show in the table.
For raw reads:
  - When filtered on T N matched pair submitted, any donor that has at least 1 matching N/T raw reads pair shall show in the table.
  - When filtered on T | N matched pair not submitted, any donor that does not have any matching N/T raw reads pair shall show in the table.
 - when filtered on "No data submitted" the donors with 0 N and 0 T shall show in the table.

Complete filter rules can be found in wiki, refer to `DNA Pipeline - Raw Reads` and `DNA Registered Samples` rows in:
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

Examples available at:
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.4DNAFilterResultsExamples

## Exit Criteria 
1. When I click on DNA - SEQ Registered Samples filter icon, samples filter should pop up.
2. When i click on DNA - SEQ Raw Reads filter icon, raw reads filter should pop up.
3. Filters stying is not changed.
9. When I check filter checkboxes, the entire table should display filtered columns accordingly.

**Comment by b-f-chan** [comment]
Candidate for @samrichca

**Comment by lindaxiang** [comment]
@Buwujiu The filters name and behaviours look correct to me.

**Comment by lindaxiang** [comment]
@Buwujiu one additional thought but low priority, is it possible to add info of the filters the user has chosen (similar as what we've implemented on the platform). Because I found many times I literally forgot what I've selected. :-)

**Comment by edsu7** [comment]
Pop up boxes for both `Samples registered` and `Raw Reads` work accordingly. Filters for both are working.

Followed up on a problem regarding `Raw reads` not filtering on `DATA-CA` but that's b/c `matchedSubmitterSampleId` was missing for those samples.

**Comment by Buwujiu** [comment]
Tested in QA, no issue, moving to awaiting release.
