### ISSUE TITLE
Implement RNA SEQ Table Filters

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2246]
## Requirement
1. Implement dashboard UI RNA SEQ table filters for these columns: `Registered Samples`, `Raw Reads`, `Alignment`.

![Screen Shot 2022-03-16 at 4 21 19 PM](https://user-images.githubusercontent.com/8744047/158683727-1cf8fa34-ff97-4d0f-bdd5-0205e3cc2b44.png)

- Mocks: https://projects.invisionapp.com/share/5M12GJVD8PZA#/screens/464884946_08c-Dashboard-RNA-Filters

2. filter box titles are: `RNA Registration Status` , `RNA Raw Reads Status`, `Alignment Status`.
3. When filter checkboxes are selected, the entire table should update based on the filter rules:
- For samples:
When filtered on Samples registered, any donor that has at least one tumour or 1 normal RNA sample shall show in the table.
When filtered on No samples registered, any donor with 0 tumour and 0 normal RNA sample shall show in the table.

- For raw reads:
When filtered on T N matched pair submitted, any donor that has at least 1 matching N/T raw reads pair shall show in the table.
When filtered on T | N matched pair not submitted, any donor that does not have any matching N/T raw reads pair shall show in the table.
when filtered on "No data submitted" the donors with 0 N and 0 T shall show in the table.

- For Alignment:
Complete: table shall show donors with completed workflow runs.
In Progress: table shall show donors with in progress workflow runs.
Failed: table shall show donors with failed workflow runs.
no Data: table shall show donors with no workflow runs.

For complete rules, refer to `RNA Registered Samples ` , `RNA Pipeline - Raw Reads`, `RNA Pipeline -Alignment` columns: 
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

4. Styling is the same as DNA filters.

## Exit Criteria
- When I click on RNA SEQ registered sample column filter icon, the filter should pop up.
- When I click on RNA SEQ Raw Reads column filter icon, the filter should pop up.
- When I click on RNA SEQ Alignment Status column filter icon, the filter should pop up.
- When I select filter checkboxes, the entire table columns should update. 
- Filter styling is the same as DNA filters.

**Comment by lindaxiang** [comment]
@Buwujiu The filters name and behaviours work properly to me.

**Comment by edsu7** [comment]
All four filter boxes appear and work accordingly.

However filtering isn't behaving. See doc for examples: 
https://docs.google.com/document/d/1caBzw6aCxaTH60MXMhQKrLXMWGT96bmt-BBsYXoyE2A/edit?usp=sharing

**Comment by Buwujiu** [comment]
made a feedback ticket: https://github.com/icgc-argo/platform-ui/issues/2460
Moving to awaiting release.
