### ISSUE TITLE
Implement Tooltip for DNA Pipeline

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2247]
## Requirement
1. Implement tooltips and change text colour to red for DNA `Registered Samples` and `Raw Reads` cells, when table counts fail to meet standards.
![Screen Shot 2022-03-16 at 4 00 46 PM](https://user-images.githubusercontent.com/8744047/158679892-14a46be2-6890-41c5-8692-b2ebcd3ca9ac.png)

2. Rules for displaying Raw Reads tooltip: 
  Two checks are in place to decide if a cell has error(red text):

 - if the donor has a matching T N pair
 - if the number of raw read is >= the number of registered samples
    The first check takes precedence. 

    If the first condition is false, display tooltip with message: "At least one T | N matched pair is required" AND change both 
    cells' text colour to red.

   if the first condition is true, proceed to check the second condition. If the second condition is false, display tooltip with 
   message: "Expecting # of tumour(or normal) reads" AND change text colour to red.

3. Rules for displaying Registered Samples tooltip:
 - When a cell value is 0, display tool tip with message: "At least 1 normal is required" for normal cells, and the text colour is red.
 - when a cell value is 0, display tooltip with message "At least 1 tumour is required" for tumour cells and the text colour is red.

Complete specs are here: https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.2TableDownloadSpecifications 
and section 4.3 shows examples.

- Mocks: https://projects.invisionapp.com/share/WP12DZ8RXKAY#/screens/464268842_07b-Dashboard-DNA-tooltips

**Comment by b-f-chan** [comment]
Candidate for @samrichca

**Comment by samrichca** [comment]
Talk to Bioinfo to get a program in dev/QA with molecular data

**Comment by samrichca** [comment]
Closing because we need to change our approach.

- JS-driven tooltips don't work with our tables. They flicker, probably due to conflicts between different hover events.
- CSS-driven tooltips don't work because they get cut off.
- I found examples of working tooltips in later versions of React Table. We're not ready to do that upgrade.
- Suggested solution: Change UX of error handling.
