### ISSUE TITLE
[UI+ Data Hookup] Submitted Data: Donor tab customizations and Clinical Core Completeness table

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2259]
## Goal
UI for the fixed clinical core completion table in the donor tab.
Also this tab will always be enabled, even if there is no clinical data submitted, so we will need a "no data" state for when just samples have been registered.

## Donor tab: Clinical Core Completeness table - Fixed
Zeplin: https://zpl.io/noPOpdv

- [x] 1. Similar to the Program Dashboard donor table, add the extra header row 
- [x] 2. Add the tooltip that describes what is required for clinical core completion
- [x] 3. Add the table that displays the `donor_id` and the numbers of records submitted for each core file type
- [x] 4. Fix this table, using a darker border line to show that, so the user just horizontally scrolls the submitted clinical data table columns.
- [x] Hook up the data for this table - so each donor will display the count of files that have been submitted with the correct colour shading

![image](https://user-images.githubusercontent.com/18424138/160153672-ca215173-3b20-4aac-8f2a-196a34ce44dc.png)

## Other tabs:  Donor id table - fixed
Zeplin: https://zpl.io/RMBrxMn

- [x] For all other file types (other than donor) - just show the donor_id fixed part
- [x] The extra header row in #1 above does not show in these tables
![image](https://user-images.githubusercontent.com/18424138/160154234-fda19e0f-3db6-4e1f-81e0-cccf0e521949.png)

## Donor tab: no data state

Zeplin: https://zpl.io/L48jPgQ

- [x] 1. The donor tab will always be the first enabled and what the user lands on
- [x] 2. If no donor.tsv data has been submitted, show this no data state
- [x] 3.  If no donor.tsv data has been submitted, disable the `Donor Data` download button
![image](https://user-images.githubusercontent.com/18424138/160153100-38ba34ef-c966-422e-946f-fa5244332c80.png)

## Extra fixes that Dan fixed in this ticket - for Testing
- [x] In some programs, there's an error reported on disabled tabs - this should never be the case because this means no data has been submitted for this file
![image](https://user-images.githubusercontent.com/18424138/172665065-79957f0f-f988-471a-a0c2-e628945a1b08.png)

- [ ] As discussed on slack: specimens that are just registered (i.e have no specimen file data submitted) should not show up in specimens tab (just in sample_registration tab) https://oicr-icgc.slack.com/archives/CGS75HFSB/p1654629768263419

- Examples: these specimens should only be in sample registration since no specimen data was submitted for them: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?tab=specimens
- https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/APGI-AU/clinical-data?tab=specimens

![image](https://user-images.githubusercontent.com/18424138/172667014-9aa571ac-0816-4afa-b74f-963dfae3e587.png)

- [ ] I notice the DNA loaders are positioned in top left corder of the component. If possible, let's move to center like other sections (was hard to catch a screenshot of this)
![image](https://user-images.githubusercontent.com/18424138/172706813-d23ce01c-df48-442d-9575-f474f870386b.png)

**Comment by demariadaniel** [comment]
PR https://github.com/icgc-argo/platform-ui/pull/2329

**Comment by kcullion** [comment]
Made a ticket for fixing the loaders here (can wait until the end): https://github.com/icgc-argo/platform-ui/issues/2352

Also consolidating feedback here: https://github.com/icgc-argo/platform-ui/issues/2350
