### ISSUE TITLE
[UI] Build reusable modal for Filtering by a list of ids

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2261]
## Goal
Build the static UI for reusable modal that will be used by the user to provide a list of ids to filter a table on.

## Default state

Zeplin: https://zpl.io/B1omB60
![image](https://user-images.githubusercontent.com/18424138/160192953-de53e7ef-644e-4340-aae8-f99219c27061.png)

- [x] When the user clicks on the "List" button beside the search by donor id box, it will launch this modal.

- [x] 1. The modal uses the same structure/styling as ones that already exist. Eg. https://argo-ui-storybook.netlify.app/?path=/story/uikit-modal--basic
- [x] 2. Interactive element: a text area component where the user can provide a list of ids, that are new line or comma separated, refer to this example in https://dcc.icgc.org/repositories 
![Screen Shot 2022-08-30 at 6 12 26 PM](https://user-images.githubusercontent.com/8744047/187552928-ab01190d-6f9c-4f23-90ea-c9262598b547.png)

The modal text area behaviour should be the same as this: 
![Screen Shot 2022-08-30 at 6 14 27 PM](https://user-images.githubusercontent.com/8744047/187553086-5fd80bfa-df22-4af0-86b8-d2f78de4e609.png)

- [x] 3. File upload component 
Might not have actual examples in argo. Refer to the previous screenshot of https://dcc.icgc.org/repositories
- [x] 4. modal actions - by default the "View results" button should be disabled until the user interacts with the text area or uploads a file that has matching IDs. The cancel button (and X) should behave as usual - closes modal without affecting the screen.

## File uploaded
Zeplin: https://zpl.io/XYZLPEx
![image](https://user-images.githubusercontent.com/18424138/160194286-6e5fac9b-2720-4081-9710-71fb892897c1.png)

- [x] 5. When user uploads a file, the "browse" button goes back as it is so they can upload a new file to overwrite the old uploaded file
- [x] 6. An id match summary shows which ids match the submitted donors and which aren't in the system yet
- [x] 7. The view results button is enabled to be hooked up to the results to show the data for the matching ids like: https://zpl.io/ll48jy5, the completion of this depends on the submitted data filters.

**Comment by sifavahora** [comment]
Making Couple of changes to the design for improved UX: 

1. Changing **input/display format** for donor ids/submitter donor ids from **separated by newline** to **separated by comma**
2. Changing the text for file upload from `Or Chose a **txt** file to upload` to `Or Chose a file to upload` 

Additionally:
Items 6 and 7  require the search results query working, which is covered in #2269 + #543

**Comment by Buwujiu** [comment]
@daniel-cy-lu Tested in QA, modal works as expected! Great work! 
Minor feedback on text:![Screen Shot 2022-12-06 at 1.18.00 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/8a67efba-f6d9-4a19-b150-2b2033ad7be7)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by lindaxiang** [comment]
For `MUTO-INTL` project, when I input the following list with `PD47027` and `DO250546` are the same donor
```
DO250551, PD46993, PD47027, DO250540, DO250546
```
The output is
![Screen Shot 2023-01-17 at 11 24 51 AM](https://user-images.githubusercontent.com/7522294/212955203-2d006ca6-e1cb-472c-9672-7660a3ebbc87.png)

I have no idea which ID does not match, but that seems not correct. Did I play the inputs too much. :-)
