### ISSUE TITLE
[Data Hookup] Hook up API table sort

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2265]
Hook up the UI the sorting that API set up  - we can use this for testing if it already works.

Related API ticket: https://github.com/icgc-argo/platform-api/issues/539

## Expected Outcomes

- [x] 1. If there are rows with invalid clinical data, those would sort to the top of each table.
- [x] 2. Otherwise, default sort is by clinically incomplete donors, to show submitters what to action on first. So if possible, the donors that have the most missing data will be at the top

![image](https://user-images.githubusercontent.com/18424138/160690033-d072d028-ca38-4409-88a5-cb50d32ce904.png)

So a more realistic mockup of the sort order by clinical completeness is this:
![image](https://user-images.githubusercontent.com/18424138/177397349-21b97aa8-2ace-49a1-8677-2fa30023ba62.png)

**Comment by Buwujiu** [comment]
Need to move it to service side, Dan to decide.

**Comment by Buwujiu** [comment]
@demariadaniel Tested in qa, found 1 issue: in ALEXIS-INTL, if I click on DO, the table sorts, but if click on other columns, like PD and FO, table doesn’t sort. However, if I click on DO first then PD, the table sorts. https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-INTL/clinical-data?tab=donor
