### ISSUE TITLE
[UI+ Data Hookup] Aggregated error banner for dictionary inconsistencies with submitted data

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2267]
## Goal
When the data dictionary is updated, if submitted data is already submitted for a donor becomes invalid, we want to show submitters that they need to fix these donors. For example: a permissible value is removed, a new required file is added, a new core field is added)

To do: Build the UI for the invalid donor aggregated banner, and hook up so that the correct errors are being aggregated.

Related API ticket: https://github.com/icgc-argo/platform-api/issues/542 

## Aggregated Banner
Mockup: https://zpl.io/5EknRN3
- [x] Build the Banner - the UI for this banner already exists within the clinical submission area, it can be reused.
- [x] 1. The title will dynamically show the # rows that have errors (shown in mockups there are 10 donors that have invalid clinical data).
- [x] 2. The explanation and instructions have two links. The first will link to the most recent version of the dictionary (global constant, DOCS_DICTIONARY_PAGE) and the second will link to that program's "Submit Clinical Data" section (for example: /submission/program/PACA-CA/clinical-submission?tab=donor)
- [x] 3. Instead of listing each donor with the same type of error, this new banner will aggregate the # donors with that type of error. This first type of error is if a value was specified in an older version of the dictionary, but is no longer permissible.
- [x] 4. the second type of error is a new core field that is added, that we would like to collect from programs that submitted against an older set of core fields. Related to this, a new required file could also be added (eg. new surgery file would be required if a donor has treatment_type = surgery) 

Note from Hardeep: These are the only types of errors we'd expect due to validation script changes or a new core field  (or file) being added. We'd only add a new core field if necessary, but there's always a possibility we may need to initially since we're only starting to get ARGO clinical submissions and we may find a new requirement for it. But we can anticipate validation script changes as we may encounter clinical data that needs to be validated correctly.

![image](https://user-images.githubusercontent.com/18424138/171196184-aff3d05f-b86b-41fc-a68c-5170a9f7f8ca.png)

(5, 6 and 7 moved to this ticket: https://github.com/icgc-argo/platform-ui/issues/2320)

**Comment by b-f-chan** [comment]
Split up into 2 tickets, separate for banner vs side bar stuff

**Comment by demariadaniel** [comment]
PR https://github.com/icgc-argo/platform-ui/pull/2341

**Comment by kcullion** [comment]
moving this to awaiting release....made two feedback tickets to track data inconsistencies and UI fixes related to this ticket
https://github.com/icgc-argo/platform-ui/issues/2350
https://github.com/icgc-argo/platform-ui/issues/2355

**Comment by daniel-cy-lu** [comment]
In the second task of this ticket, I found to keep it consistent, instead of using the hard coded dictionary website address, use the global constant that is set up already, `DOCS_DICTIONARY_PAGE`.
