### ISSUE TITLE
[Data Hookup] Submitted data: quick filters

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2268]
Make the quick filters items work:

- [x] 1. Show all donors - always takes the user back to the full submitted data section
- [x] 2.Show invalid donors - this item should only show if there are invalid donors (i.e there is some submitted data that doesn't comply with the most recent dictionary). When it's available it will filter the section to only show the tables with invalid rows: like https://zpl.io/r17Y8gD
- [x] 3. Show clinically complete donors - this will filter submitted data for all donors that are clinically complete
- [x] 4. Show clinically incomplete donors - this will filter submitted data for all donors that are clinically incomplete
- [x] 5. The title can sometimes say "donor_id" (if filtered on a specific donor), or "# donors" if filtered on multiple donors like in: https://zpl.io/ll48jy5

![image](https://user-images.githubusercontent.com/18424138/160695228-ab85dfb0-f4a9-46ba-a7b8-b6b3dba32525.png)

**Comment by demariadaniel** [comment]
'# of Donors' title state to be handled in #2269 https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2269

Current branch updates title to display 'All Donors', 'Invalid Donors', 'Clinically Complete Donors' or 'Clinically Incomplete Donors'

**Comment by Buwujiu** [comment]
@demariadaniel Tested in QA on DATA-CA. 
When filtered on "incomplete donors", example: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?tab=donor,  for donors such as DO263260, DO263256, they have all green check marks on all clinical core entities, this means they are core complete. However, they show up when quick filter is set to "incomplete donors". It's likely that the calculation of `coreCompletionPercentage` in clinical api is off. Will create another ticket to investigate. 

Other than this, the filter is working as expected.
