### ISSUE TITLE
[Data Hookup] Submitted data: Make the search by donor/submitter donor id  work

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2269]
## Goal
Hook up the Search by donor id/submitted donor id component. 

Related API ticket: https://github.com/icgc-argo/platform-api/issues/543 

## Expected Outcomes

**User types an id**
Mockup:https://zpl.io/XYDgAmM 
This is similar to the search in the file repo
- [x] 1. A user can enter a donor id or submitter donor id 
- [x] 2. The x icon will clear what they have typed 
- [x] 3. A list of matched results shows up, like in file repo
![image](https://user-images.githubusercontent.com/18424138/160696824-12ba6f9d-8568-4019-be33-e72e55be2151.png)

**If what they type does not match an id that has data submitted**
- [x] Show the "No results found" message like we do in the file repo
![image](https://user-images.githubusercontent.com/18424138/160697091-9cb820a5-3079-42f1-83da-bda3ae705903.png)

**If user selects a matching id from results dropdown**
Mockup: https://zpl.io/O0MNPj8

- [x] 1. The submitted data and file list filters to only the data submitted for this donor id
- [x] 2. The title changes to "Clinical data for: donor_id"
- [x] 3. A clear filters link shows, when the user clicks on it it goes back to All donors view
- [x] 4. The donor id also gets saved within the search box to prevent the user from adding another id in here (they can use the list feature for multiple ids). The user can also clear this search by clicking on the "x " icon of this search box

![image](https://user-images.githubusercontent.com/18424138/160697249-a2724ae7-32fc-44d6-9f0d-c5fd9f844444.png)

**Comment by lindaxiang** [comment]
Test and work
- filtering by donorId or submitterDonorId works
- A list of matched results shows up, like in file repo
- Title `clinical data for : DONOR_X` showing correctly when one donor provided
- donorID saved to search box
- `clear Filters` working

Does Not work
- `X` icon clears search bar but does not clear the filtered results (Is this expected?), it says All Donors but apparently it only shows the filtered results
- Show the "No results found" message like we do in the file repo, however when you search for the second time, "No results found" does not trigger
- After searching with one donorId, the Quick Filters do not work properly
- LIST button does not work for me

**Comment by Buwujiu** [comment]
Made a feedback ticket: icgc-argo/platform-ui#2440.
This will remain in QA until 2240 is resolved.
