### ISSUE TITLE
[Data Hookup] Submitted data: make the Filter by id list modal work

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2270]
## Goal
Add queries and make the Filter by id work in the modal - reusable component.
zeplin: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/623cb824547d0bbbcffcd5ac

UI ticket: https://github.com/icgc-argo/platform-ui/issues/2261
![Screen Shot 2022-09-06 at 4 32 16 PM](https://user-images.githubusercontent.com/8744047/188732493-46ce4d06-7422-4dd0-8f30-3819472fbaf2.png)

The completion of this ticket depends on
- https://github.com/icgc-argo/platform-ui/issues/2261

## Expected Behaviour:
- When enter a list of donor ids in the text area, there should be a section below the text area showing the matched and not matched donor ids. Refer to zeplin mockup. 
- When I click on "view results" button, I should be taken to the submitted data page where the donor Ids that I just searched are displayed on the page.

**Comment by daniel-cy-lu** [comment]
The match count also count duplicates as one. For example  "DO250444" is a matched donor_id on the "HNAHAL-CA" program. When entering "DO250444" twice in the filter in the above program, the match count will show as "1"

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!
