### ISSUE TITLE
[Data Hookup] Submitted data: hookup the data download buttons

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2271]
Hook up the download buttons

Related API ticket: https://github.com/icgc-argo/platform-api/issues/544

- [ ] 1. The "Clinical Data" download button should download all of the data that exists for this program, based on the donors that are filtered currently. eg. If all donors, download all data. If the user has filtered on one donor, download all clinical data just for that one donor. 
- [ ] 1. Download format for this button is similar to the "All clinical data" button on the program dashboard (the user should get a folder of all tsvs that have data associated to them).
- [ ] 2. Each file type tab also has a download. This will downland just that tsv file with all the data shown (based on the filters they have chosen too) 

![image](https://user-images.githubusercontent.com/18424138/160698938-93ba5b47-b752-42ec-940a-e893120495db.png)

**Comment by edsu7** [comment]
Downloading all clinical data or by clinical entity page works in most cases, however experiencing some weirdness with `DATA-CA`

|Samples|Able to execute Download all clinical| Able to execute Download Sample_registration|
|--|--|--|
|All|True|False|
|Complete Donors|False|False|
|[135 donors](https://github.com/icgc-argo/platform-ui/files/9924534/exampleA.txt)|False|False|
|[Above query minus (DO262719,DO262723)](https://github.com/icgc-argo/platform-ui/files/9924548/exampleB.txt)|False|True|

**Comment by hknahal** [comment]
Download buttons work in most cases, except a few times when switching between filters:

Example 1: 
When filter is set to `Show Invalid Donors` and click on download `Clinical Data` button, it downloads all clinical data, even though there are no invalid donors:
![downloads_all_data_show_invalid_donors_filter](https://user-images.githubusercontent.com/4992044/201167237-3f1dbfd8-fc9a-44c1-98f8-f5a299ae7984.png)

Example 2:
Set filter to `Show Complete Donors`
Switch to "Primary Diagnosis" tab
Click on download `Clinical Data` button or download `Primary Diagnosis Data` button, but it shows `Download Error` box:
![show_complete_donors_filter_download_error](https://user-images.githubusercontent.com/4992044/201168180-dbd7382b-82f7-4d8e-b7de-d13760950eb9.png)

**Comment by Buwujiu** [comment]
needs feedback work, Issues are logged in https://github.com/icgc-argo/platform-ui/issues/2440, moving to awaiting release.
