### ISSUE TITLE
Donor Entity: Specimen tab - small fix

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2290]
Just a small fix from this ticket; https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2127

I noticed that normal and tumour aren’t using the same samples table? the sample type should be the 3rd column
![image (95)](https://user-images.githubusercontent.com/18424138/164722797-e0792d76-2e6f-45c5-9b68-916ac6acbead.png)

**Comment by demariadaniel** [comment]
This ticket can be closed, Donor Entity is not hooked up to real data and this is a side effect of using fake data.

One JSON entry has 'sample_type' as the first field and one entry has it as the 3rd, resulting in different tables. Our real records from the DB should be consistent.

**Comment by Buwujiu** [comment]
Will close it since it's a result of fake data.
