### ISSUE TITLE
Dependency upgrades, part 1

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2299]
This issue covers:
- Next 9 to 10
- Dependencies that need to be upgraded in order for React 17 support
- Removing un(der)used dependencies
- Upgrading & removing only the dependencies that don't require significant debugging and refactoring
- Assessing and planning upgrades

**Comment by samrichca** [comment]
https://github.com/icgc-argo/platform-ui/pull/2305

**Comment by b-f-chan** [comment]
@samrichca has smoke tested should be sufficient, just haven't done release to QA yet
