### ISSUE TITLE
Migrate to @apollo/client & update GraphQL libs

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2301]
Currently we use many Apollo-related libraries that have been combined into apollo/client 3. We need to migrate to apollo/client 3 to support React 17+ and Next 11+.

Upgrading the packages is straightforward and well documented but results in errors that pop up in smoke-testing and require refactoring. They come up one at a time so I don't know how many there are or how complex they are to fix.

https://github.com/apollographql/react-apollo
https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/

---

# Updates

## June 2

- react-apollo: not used, remove
- migrate the following to Apollo 3:
  - apollo-cache-inmemory
  - apollo-client
  - apollo-link-http
  - apollo/react-hooks
- apollo-upload-client: check for API changes after Apollo 3 upgrade

## June 8

Adding GraphQL updates to scope & increasing story points because our graphql library version was insufficient for Apollo 3.

**Comment by b-f-chan** [comment]
Reviewed, change to approach required

**Comment by samrichca** [comment]
https://github.com/icgc-argo/platform-ui/pull/2342
