### ISSUE TITLE
Updates cleanup

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2307]
Updated scope:

- update Babel libraries
- do any updates still remaining

---

After we upgrade to the latest versions of Next, React, and Webpack, we should make sure Babel is configured to suit our needs (TBD)

See core-js readme https://www.npmjs.com/package/core-js

**Comment by b-f-chan** [comment]
Might get covered in the Next 10 -> 12 upgrades, but not sure yet.  Our core-js version is deprecated.  But let's do this at the end, because it may be covered.  Probably have to update, but lower priority for now.

**Comment by b-f-chan** [comment]
This ticket may be postponed or cancelled, Next has pivoted to SWC, which we won't do now since Babel still working.  @samrichca to leave this config alone, and create ticket in Q4 to move to SWC - Can close this ticket after.

**Comment by samrichca** [comment]
Updated ticket: will update Babel libraries as much as possible and check if there's any outstanding dependency upgrades needed.

migrate to SWC in Q4

**Comment by samrichca** [comment]
- tried to migrate to SWC but it's missing the optional chaining plugin we use in Babel. revisit in Q4
- removed libraries already included in Next
- removed libraries that aren't used
- no remaining critical vulns
- remaining high vulns & deprecations can't be resolved. re-audit in Q4.
