### ISSUE TITLE
Upgrade React 16 to 17

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2308]
- Upgrade React 16 to 17
- Try to make react-table use React 17

**Comment by b-f-chan** [comment]
Scope here is NOT to upgrade REACT table, we will use a small hack to make REACT table cooperate - @samrichca to advise!

**Comment by samrichca** [comment]
Tried this and it worked smoothly. Downgrading to 1 point

**Comment by samrichca** [comment]
https://github.com/icgc-argo/platform-ui/pull/2357
