### ISSUE TITLE
Upgrade Next 10 to 11, Webpack 4 to 5

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2309]
Upgrade Next 10 to 11, which requires Webpack 5

**Comment by b-f-chan** [comment]
Question @samrichca - There's also a ticket to upgrade Next from 11 to 12, does this need to be done sequentially or can you skip from 10 to 12?  @samrichca to advise

**Comment by b-f-chan** [comment]
Team decision --> Hold back Epic #2208 from Loki to ensure we have enough time to test thoroughly

**Comment by b-f-chan** [comment]
Some remaining issues need to be resolved, moving back to In Progress --> Need to change how we import images and various error pages

**Comment by samrichca** [comment]
https://github.com/icgc-argo/platform-ui/pull/2360
