### ISSUE TITLE
Update sqon-builder

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2314]
Update sqon-builder from 1 to 2.

- `.has()` becomes `.in()`
- remove `.build()`
- Types need to be updated for functions using the results of sqon-builder
- There may be additional API changes

**Comment by b-f-chan** [comment]
This suggestion was from @joneubank, may be more "nice-to-have" since it's out of date - confirm with Jon when he's back.  Lower priority.
