### ISSUE TITLE
[UI] Submitted data: Change the way invalid clinical data is displayed on the dashboard

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2315]
## Goal
It is very confusing when donors become invalid for a program, because of dictionary changes. Program members just see an error banner with an invalid icon in the donor table file release status column (confusing spot) and are not told what to fix. We will make some changes to the dashboard to help make this more clear.

Related donor aggregator ticket: https://github.com/icgc-argo/donor-submission-aggregator/issues/274

## What to change
This is what's currently implemented on the dashboard. Let's do the following
- [x] 1. Keep the first banner but change the text to
`The clinical submission you have in progress is invalid`
`[Version link] was released and has made your in progress clinical submission invalid. See the details in your clinical workspace.`
- [x] 2. Remove the error icons from the "file release status" column. We will communicate this error in a new alerts column (see below)
@Buwujiu looked into this. Right now we are checking if `validWithCurrentDictionary == false, then display alert, otherwise releaseStatus`. So we would now just always show releaseStatus, and move the other logic to the alerts column
- [x] 3. Remove this banner. We will build a more descriptive banner within the Submitted Data Section
![image](https://user-images.githubusercontent.com/18424138/171480968-ea5991dd-ec61-463e-84f3-bce7b69cb465.png)

## New Expected Outcomes
New mockup: Zeplin: https://zpl.io/GEkxJl9

- [x] 4. Change the label of the metric from
`# Invalid donors` to `# require clinical updates`
![image](https://user-images.githubusercontent.com/18424138/171481340-760b40b4-f51e-4f4f-932c-2a7d103c531f.png)
- [x] 5. Add a new column in the table called "Alerts" for now this will just show the donors that have errors in their submitted clinical data. If there are no errors, this column will be blank.
- [x] 6. The donor id should link to the `Submitted data section` filtered on that donor. So it will land on the donor tab and show all of the clinical data that has been submitted for this donor. This depends on https://github.com/icgc-argo/platform-ui/issues/2269
- [x] 7. The "update clinical" links in the alert column should link to the **first section in the submitted data section that has the errors for that donor. ** Eg. If only a permissible value was removed in the specimen file, and the donor has that permissible value - this link would open the `submitted data section` on the specimen tab. 
** NOTE: This will be done in this ticket: https://github.com/icgc-argo/platform-ui/issues/2387  **

![image](https://user-images.githubusercontent.com/18424138/171481964-93c57e4c-4a95-4a3c-9b15-05fe7228f026.png)
**NOTE: you will see bulk selection checkboxes and bulk actions, as well as the clear filters button move locations and change behaviour a bit. This is outlined in a future ticket and is not priority at this time**: https://github.com/icgc-argo/platform-ui/issues/2321

## Alert filter
New mockup: Zeplin (with alerts filter open): https://zpl.io/vMgmZRP
- [x] 8. Build and hook up the column filter for the new alerts column. For now there is just one type of alert: `requires clinical updates`. When the user filters on this, the table will return just the donors that require clinical data fixes
- [x] When the user filters on "no alerts" they return all the donors where this column has no value 
![image](https://user-images.githubusercontent.com/18424138/171688084-0d405ce0-8886-4d4f-bf7e-2365050292d4.png)

**Comment by Buwujiu** [comment]
@Buwujiu To see if all API is ready for this.

**Comment by Buwujiu** [comment]
@Buwujiu todo: remove point 7 to ticket 2387.

**Comment by edsu7** [comment]
Successful tests:
- Warning banner on dictionary change in `ROSI-RU`
- alerts column links to first instance of error in submitted data view filtered according to donor in `ROSI-RU`
- filter by alerts works in `TEST-QA`

Failed tests:
- alerts column links to submitted data view filtered by donor in `ROSI-RU`
- alerts column does not show `DATA-CA` despite `treatment` errors

**Comment by Buwujiu** [comment]
Logged an issue in #2440 , rest of the items passed test in qa. Moving to awaiting release.

**Comment by lindaxiang** [comment]
Observations on ROSI-RU
- The donor id link to the Submitted data section filtered on that donor. But it does NOT land on the donor tab, but on other tabs.
- The "update clinical" in the alert column does NOT link to the **first section in the submitted data section that has the errors for that donor**
- `Radiation` has alert however it shows `No Data Found` in ROSI-RU

DATA-CA
- When the user filters on "Require Clinical Updates" , and select `Show 100 rows`, it returns `Something went wrong`.
