### ISSUE TITLE
[UI+ Data Hookup] Invalid clinical data in table and sidebar alerts

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/platform-ui#2320]
## Goal
To finish off showing to the data submitter that they have errors in their submitted data, and what those errors are.

Related UI ticket; https://github.com/icgc-argo/platform-ui/issues/2267
Related API ticket: https://github.com/icgc-argo/platform-api/issues/542

## Table and sidebar

- [x] 5. The fields that have errors  should be shaded red
- [x] 6. This could have been done elsewhere, but the file types that have invalid data should show the red alert icon in the sidebar
**Things to check for (may have been done in previous ticket)**
- [x] If a donor does not have a data file submitted, make sure the tab is disabled (and this should never have an error icon because there's no data submitted for that type)
- [x] If the file has an error due to dictionary discrepancy, the error icon should show in the tab

## Program section sidebar

- [x] 7. Like we do for the Clinical submission and sample registration sections, if this section has an error (invalid donors to fix) show the error icon beside the "Submitted Data" item

![image](https://user-images.githubusercontent.com/18424138/171196184-aff3d05f-b86b-41fc-a68c-5170a9f7f8ca.png)

**Comment by demariadaniel** [comment]
PR https://github.com/icgc-argo/platform-ui/pull/2344
