### ISSUE TITLE
Donor Entity: Age_at_diagnosis would never be submitted as >90

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2349]
I was incorrect in some listed items in this ticket: https://github.com/icgc-argo/platform-ui/issues/2126

I clarified with @hknahal and the submitters have to submit age_at_diagnosis = 90 for anything over 90 or they will get this error: 
`Value is out of permissible range, value must be > 0 and <= 90.`

Dan may have implemented logic for the following from #2126 ticket. 
 4. For donors over 90, we will need to display as age: >=90

So if so, please just show the age as 90 like any other age. 
Zeplin: https://zpl.io/agExWwA
![image](https://user-images.githubusercontent.com/18424138/176716088-40167866-8b83-4da1-b7cb-3d7676985b1d.png)

**Comment by Buwujiu** [comment]
This is ready for implementation.

**Comment by Buwujiu** [comment]
Can't test since all donor entity page is fake data.

**Comment by Buwujiu** [comment]
Tested in QA, closing.
