### ISSUE TITLE
Submitted Data: Feedback on error display, clinical completeness

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2350]
The following is feedback related to these tickets (and other found bugs):
https://github.com/icgc-argo/platform-ui/issues/2259
https://github.com/icgc-argo/platform-ui/issues/2267
https://github.com/icgc-argo/platform-api/issues/542
https://github.com/icgc-argo/platform-ui/issues/2320

Note: I tested dev and QA to get a good range of types of errors/data that would show up

## Feedback -  Error banner and UI fixes
- [x] The title of the aggregated error banner should be: `# error(s) found in [file_name] data` for example:`10 error(s) found in donor data`. Zeplin: https://zpl.io/5EknRN3
![image](https://user-images.githubusercontent.com/18424138/176743126-dbbd5fe2-97b6-4781-8888-196ec6ff7949.png)

- [x] I don't think there's anything for Dan to do here, but made a ticket for a clearer description for `UNREGOGNIZED_FIELD` type: https://github.com/icgc-argo/argo-clinical/issues/789

- [x] The banner links need to be fixed. The first link should show the **latest dictionary version, and open in a new window** (so shouldn't be static). I'm not sure if that's just because this example is in dev, but the latest dictionary version is 1.14. A banner like this shows in the Submit clinical data section, so you can copy how it get's the correct version number. see https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/KIM2-GB/clinical-submission?tab=treatment
![image](https://user-images.githubusercontent.com/18424138/176744094-d1711ce8-ca98-4f2d-9a6b-a13cbc9ad8e8.png)

- [x] The second link in the above screenshot, should link to that program's "Submit Clinical Data" section (open in the same window is good, since it's an internal link). Right now the link goes to a 404, as there's a weird object reference in the URL
![image](https://user-images.githubusercontent.com/18424138/177565834-12aaa4f8-66f6-4018-882e-23747e7628d1.png)

- [x] As discussed in demo, let's change this header to `# Affected Records`, since it's not always unique donors
![image](https://user-images.githubusercontent.com/18424138/176745817-cf8c197d-1c9b-4da5-a574-dcc7eadb32a1.png)

- [x] As discussed with Hardeep over slack, the Error_Value isn't the most helpful for data submitters, let's remove this column from the banner.

- [x] For blank values, let's just display blank cells. I'm confused at why some are showing `--` and some are blank. Let's keep it as blanks because that’s how the table preview looks in the “submit clinical data” section when displaying values that aren’t provided
![image](https://user-images.githubusercontent.com/18424138/176749168-fa777d81-912d-4a54-99ef-06be54b75568.png)

- [x] For the donor tab, can you left justify the "Submitted Donor Data" table title so it's visible without the need to scroll horizontallly?
![image](https://user-images.githubusercontent.com/18424138/177570271-2c9e0fca-a526-4b53-8538-09cd615ae77b.png)

## No data state
- [x] When there's no data at all submitted for a program (not even registered samples), just show the "No data Found" icon and message in this tab.
For eg, this: https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/ANNC-CA/clinical-data?tab=donor
Should look more like this (my fault, I did not specify this):
![image](https://user-images.githubusercontent.com/18424138/176753820-cb2ed5ab-2900-47e6-a54c-3055e94b3ff5.png)

## Feedback for Clinical Core Completeness table

- [x] On DEV and QA, when I hover over the ? icon for the clinical core completeness description, the tooltip flashes on and off. This seems to be on first load and then after navigating to other tabs it stays on. See Video: https://watch.screencastify.com/v/ZtoGzQZKAJxCiyDWa3uC

**Comment by Buwujiu** [comment]
Regarding this inconsistency: 
```
The banner links need to be fixed. The first link should show the latest dictionary version, and open in a new window (so shouldn't be static). I'm not sure if that's just because this example is in dev, but the latest dictionary version is 1.14. A banner like this shows in the Submit clinical data section, so you can copy how it get's the correct version number. see https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/KIM2-GB/clinical-submission?tab=treatment
```
This is not an issue, because the dictionaries in DEV and QA are for testing purpose, they do not reflect the same dictionary version in prod. For the submitted data page, just make sure the dictionary version is the same as clinical submission page. @daniel-cy-lu

**Comment by daniel-cy-lu** [comment]
For the last checkbox regarding flashing description when hovering over ? icons, the video link is down. I was able to find the ? icon in DEV and QA, and it works well. I tried to replicate the issue during first load and the description show up fine each time.

**Comment by Buwujiu** [comment]
Tested in QA, all working as expected, thank you! @daniel-cy-lu
