### ISSUE TITLE
Submitted Data: make loader consistent with other sections

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2352]
Can you make the loader behaviour in the `Submitted Data` section consistent with what happens in the `Submit Clinical Data` section. Where the page dims and you see the loader in the middle of the screen. 

currently there is a page loader and table level loader happening like this
<img width="1070" alt="Screen Shot 2022-07-06 at 10 44 42 AM" src="https://user-images.githubusercontent.com/18424138/177580964-f38335e4-3f2e-4a73-99c9-73d6fa09dba6.png">
<img width="1062" alt="Screen Shot 2022-07-06 at 10 43 20 AM" src="https://user-images.githubusercontent.com/18424138/177581237-34900dd3-68c3-4426-a0b6-c8162c68539d.png">

**Comment by Buwujiu** [comment]
Tested in QA, loader is working as expected, thanks @daniel-cy-lu !
