### ISSUE TITLE
Submitted Data: Feedback - Data inconsistencies 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2355]
The following is feedback related to these tickets what was released in QA and looking at the data that's coming through for each program. 

Note: I tested dev and QA to get a good range of types of errors/data that would show up

## Data specific inconsistencies

- [x] I noticed the donor_id does not include the `DO` part in the submitted data section, but it does on the dashboard and in the file repo. I think we should keep it consistent here and display the `DO` part
![image](https://user-images.githubusercontent.com/18424138/177844429-9971e6b8-caa2-4f15-9a54-766503da88f4.png)

- [x] For:https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/BASH-CA/clinical-data?tab=treatment
I would expect 2, 3, and 4 not to be errors, since `is_primary_treatment` is `no`.
Same thing is happening on QA: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=treatment
![image](https://user-images.githubusercontent.com/18424138/176747208-26c1740a-c35f-4b61-9c2a-011affb940d4.png)

- [x] For the same example above, it should just be the one value `Hemotological` that is shaded
Also happening on QA: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=treatment
![image](https://user-images.githubusercontent.com/18424138/176748696-b0ee2512-fa33-40bf-acb5-50f2ec470d26.png)

- [x] For this error type it says 8 records are affected but I count 10 shaded cells here
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=follow_up
![image](https://user-images.githubusercontent.com/18424138/177614621-daa8baad-3fba-4490-8641-b681fb03a5fe.png)

- [x] For this: `treatment_type` is a core, required field so I'm not sure how Alexis passed submission for these. Actually this value is missing consistently and should have a value, or should be showing an error.
https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?tab=treatment
Same thing is happening on QA: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=treatment
![image](https://user-images.githubusercontent.com/18424138/176750947-39517b96-a1d6-4303-b66a-3172feed4685.png)
This is another example where treatement_type is blank for all entries. That should show an error: https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/BASH-CA/clinical-data?tab=treatment

- [x] Some of the tables have "submitter_id" as the last column. Can you remove this because it's the same as "submitter_donor_id". (also don't want it to be part of the download).
Eg. https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=specimen
![image](https://user-images.githubusercontent.com/18424138/176774745-b442b364-123f-4417-bec7-3f1c945e7be0.png)

- [x] In this program, there are errors highlighted that aren't reported in the banner. 
https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/BASH-CA/clinical-data?tab=treatment
This field is actually within another file, so it's showing up in two tabs - it's reporting the error here: https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/BASH-CA/clinical-data?tab=radiation 
![image](https://user-images.githubusercontent.com/18424138/176775135-7c42fd8c-9c45-480d-bb9a-d7b85772ee30.png)

- [x] This donor seems to have donor data submitted - so the `DO` count here should be "1", not "0". Also looking at the submitted data for the other tabs too, that donor has more files submitted for the other data types too.
https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?tab=donor
![image](https://user-images.githubusercontent.com/18424138/176749684-284f6638-f5b5-48fe-8618-4cbea0b7245f.png)
Something strange may be happening here because the dashboard should be reporting clinical completeness too
![image](https://user-images.githubusercontent.com/18424138/177173882-3bf6ebd2-1dad-4fdc-a22e-291f4e0fd813.png)

## Tumour and Normal DNA specimen counts don's seem to be accurate.

- [x] In this example, I see the NS and TS boxes shaded as if they weren't submitted - but in the specimen tab there are actually files that have been submitted for a normal DNA and tumour DNA specimen. So these should be 1 and 1 (this donor is clinically complete on the dashboard too)
![image](https://user-images.githubusercontent.com/18424138/176777249-2ae19ad6-bf5f-4439-a8bb-dbf6ed27a6bc.png)

- [x] checked some of the counts in the completeness table and sometimes they aren't accurate. For example, with this program - donor 262480 has a tumour DNA specimen registered, but the count here is zero. 
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/KIMC-CA/clinical-data?tab=donor
![image](https://user-images.githubusercontent.com/18424138/177616026-7b8e76c6-d07b-4060-b883-94ec3b223e90.png)

- [x] Another example where a whole donor reports 0 for each file, but that donor id shows that there has been submitted data in the other tabs
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ROSI-RU/clinical-data?tab=donor
![image](https://user-images.githubusercontent.com/18424138/177638966-c88579d2-7b06-4f34-beb5-dcc60097427d.png)

## Test program DATA-CA (QA)
I tried registering samples and submitting the donor.tsv file and primary diagnosis files from the set of files Hardeep and Edmund are preparing: https://github.com/icgc-argo/roadmap/issues/904

- [x] The data shows up in this section, but some values are missing. I didn't check all fields but the ones I noticed are ones that are required fields (and I know are in the files I submitted), `primary_site` and `genetic_disorders` in the donor.tsv, and `presenting_symptoms` in the primary_diagnosis.tsv

![image](https://user-images.githubusercontent.com/18424138/177849627-a4e88d1b-e61a-4bcb-bbe3-d1db71b47d50.png)

**Comment by b-f-chan** [comment]
Will require some deep investigation to determine if these issues are in the data itself or in the interaction with the backend

**Comment by b-f-chan** [comment]
@hknahal to help with some of the investigation

**Comment by demariadaniel** [comment]
For checkboxes 2+3, there are several instances where cells are being marked as having an error when they should not be because the Migration Error data does not always tell which specific value is causing the error.

I've made the code as specific possible so we are only marking known error values, but not all error objects from the DB have an explicit key/value

Example screen shot attached, where we have 2 records from given Donor marked with an error
Migration Errors tells us this donor the 'line_of_treatment' field is invalid, and the error response says the erroneous value is `null`, so we mark the two records where 'line_of_treatment' is null with errors

![Screen Shot 2022-08-09 at 5.39.36 PM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/fea282e2-ecff-4e58-8300-ac6e6e6f98a8)

**Comment by Buwujiu** [comment]
@demariadaniel Found a few more similar issues as `treatment_type` missing. 
if you compare the data returned by clinical: clinical.qa.argo.cancercollaboratory.org
/clinical/program/ALEXIS-INTL/donor/DO262508 with what's In this program: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-INTL/clinical-data?tab=donor,
the array columns are missing on the submitted page.
- Donor
![Screen Shot 2022-08-17 at 12.24.42 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/17b938ad-76ab-4cad-8281-b4f8cef369ae)
- Surgery
![Screen Shot 2022-08-17 at 12.21.30 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/38c37248-ba8d-42c1-9de3-cb8b8dee8a29) 
- Primary Diagnosis
![Screen Shot 2022-08-17 at 12.23.28 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/dfbdf9cb-bceb-434a-b9d7-67ecd6198566)

**Comment by demariadaniel** [comment]
Thanks @Buwujiu, many of these are the result of the same bug where values are stored as arrays and we are expecting strings, I have a fix on the branch in progress

**Comment by demariadaniel** [comment]
Validated that DB does contain Donors with data submitted but completionStats of 0 in QA and code is just reflecting what's there

![Screen Shot 2022-08-18 at 10.47.35 AM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/3f6989e0-e3f8-4a30-a0c3-bb8fbf756ebd)

**Comment by demariadaniel** [comment]
Discussed w/ @Buwujiu on Slack, Issue w/ multiple errors getting marked + adding specific error values will require a follow up ticket

**Comment by Buwujiu** [comment]
Tested all inconsistencies in QA, everything looks great except with the error counting. Will log a new ticket for investigating. Can move this ticket to awaiting release.

**Comment by Buwujiu** [comment]
Created a new ticket https://github.com/icgc-argo/platform-ui/issues/2385 for further investigate error counting issues.
