### ISSUE TITLE
Bug: File Repo shows No Data when there's an error

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2365]
- Where: File Repository page, in the table
- Issue: When the GraphQL response has an error and data, the table displays "No Data"
- To do: Improve the display logic
  1. Show the data if there's an error and data
  2. Show an error if there's an error and no data
  3. Show No Data if there's no data and no error

Issue is found in Staging, QA

**Comment by samrichca** [comment]
"No Data" message is shown when a table entry has a null value. Try filtering on CRAM files to reproduce.

**Comment by Buwujiu** [comment]
Tested in QA, file repo is working as expected, thanks for the great work @samrichca !
