### ISSUE TITLE
🐛 Submitted Data Page Goes Blank When Changing Page Size

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2370]
## Describe the bug
in QA, APGI-AU submitted data - Donor page: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/APGI-AU/clinical-data?tab=donor
Page shows no data when changing page size from a smaller number to a larger number.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/APGI-AU/clinical-data?tab=donor
2. Select 50 rows, go to the last page, page 4
![Screen Shot 2022-08-17 at 10 18 41 AM](https://user-images.githubusercontent.com/8744047/185158866-660859cc-80e9-44fa-a204-4333aa4f2bb5.png)

4. page works fine
5. Switch to 100 rows
6. Page shows `No Data Found`
![Screen Shot 2022-08-17 at 10 21 53 AM](https://user-images.githubusercontent.com/8744047/185158832-605b0a43-5a5e-4c68-bb29-fe13a10a77a6.png)
7. If I click the `previous` button twice, it takes me the page 2 of page limit 100.

You can reproduce this issue by switching row number from a smaller number to a larger one, as long as the page number of the second selection doesn't exist, the page goes blank. 

## Expected behaviour
When I switch from 50 to 100 rows, I should be taken to the first page, not the default page number is 4 + page limit 100, which doesn't exist.

**Comment by daniel-cy-lu** [comment]
Issue fixed in another ticket/PR by Dan.

**Comment by sifavahora** [comment]
works as expected!
