### ISSUE TITLE
Make submitted data filterable with donor id url params

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2387]
## Detailed Description
Taken out from ticket https://github.com/icgc-argo/platform-ui/issues/2261 as it needs to be done separately.

In order to implement the `update clinical` links in the alert column in ticket 2315(see below mockup #7 ), we need to make submitted data filterable with donor id url params. 

![171481964-93c57e4c-4a95-4a3c-9b15-05fe7228f026.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/33097d0b-925d-4496-84a9-9963d0205b51)

## Expected behavior: 
- When click on the "update clinical" links on donor dashboard, users will be taken to the submitted data page where the page is filtered with the selected donor id. 

- The "update clinical" links in the alert column should link to the **first section in the submitted data section that has the errors for that donor. ** Eg. If only a permissible value was removed in the specimen file, and the donor has that permissible value - this link would open the submitted data section on the specimen tab.

**Comment by edsu7** [comment]
The following works:
- clicking "update clinical" on donor dashboard links to donorId filtered submitted data page
- linked submitted data page will reflect first instance out of multiple errors

Comments:
- Have to navigate back to dashboard to reset donorId filter view of "submitted data" page. Ideally reset button for the page/view?
- minor nitpick. DO262422's only error is in `biomarker`.
In the donor filter view, warnings are seen in both `biomarker` and `radiation`, with `radiation` being an empty view
Warnings reflect all submitted data not just current view
![Screen Shot 2022-11-10 at 3 48 22 PM](https://user-images.githubusercontent.com/22638361/201203393-c469fbd5-05c6-472b-9453-f585247346ba.png)
![Screen Shot 2022-11-10 at 3 48 14 PM](https://user-images.githubusercontent.com/22638361/201203394-9e6b69c1-21bb-4b18-9de6-26da7686ec6f.png)

**Comment by lindaxiang** [comment]
Have the same observation as what Edmund commented above.

Comments:
- when I click the "Update Clinical" URL for donor: DO259189 (DASH-5), it links to donorId filtered submitted data page correctly, but observed some odds which are showing in the screenshot:
![Screen Shot 2022-11-10 at 5 02 38 PM](https://user-images.githubusercontent.com/7522294/201216947-805f1b52-8d1c-4b5c-b3b3-3bc324fe0f54.png)
