### ISSUE TITLE
[Feedback] [Data Hookup] Submitted data: Make the search by donor/submitter donor id work

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/platform-ui#2415]
Reference - https://docs.google.com/document/d/1ZmhiHG4lHYYZk0LWiNlDjqP8lIy-qCItbT6npYUeux4/edit?usp=sharing

Current Behavior for filter:
1. for partial search - filtering by `do` returns  records for matched string with submitted_donor_id only (see 1.1 of attached doc)
2. for partial search - filter by `1c` returns records that match individual characters not string as a whole (see 1.2  of attached doc)
3. filter returns incorrect number of records `Showing 1 of n` doesnt match the number of records displayed in the result table (1.3) 
4. for unmatched id -  Filter results no matched found and `Showing 0 of 0` but there are numerous records displayed in the results table (1.4) 
5. anything following the leading digit filter results same count of rows  e.g: `2` and `2gggihf` (1.5)

Expected Behavior for filter:
- [x] for partial search - user should be able to search a donor id with the prefix `DO` case-insensitive
- [x]  for partial search - filter should return the records that match the whole string eg `1c`
- [x]  filter returns should display correct number of records in the `Showing 1 of n` section
- [x] for unmatched id - result table should display 0 records or no result table should not be displayed  
- [x] filter results should display correct number of rows and display correct records in the result table

**Comment by edsu7** [comment]
Successful tests:
- "DO" & "do" partial search returns all donors
- filtered returns displays correct number of records 
- filtered returns displays correct number of rows in table
- unmatched ID returns 0 donors and no rows

Results regarding filtering by partial strings
|Records|String|Comment|
|--|--|--|
|939|N/A||
|71|l||
|0|L||
|370|2||
|370 |l2||
|370|l,2||
|370|L2||
|370|L,2||
|0|2l|correct behaviour|
|0 |2L|correct behaviour|
|124|2,l||
|53|2,L|returning by inner join of `donorIds` matching "2" and "L" by `submitter_sample_id`|
|370|2l2|based on previous behaviours looks like its searching by right most integer string|
|0|2l2l|
|370|2l2l2|based on previous behaviours looks like its searching by right most integer string|

**Comment by Buwujiu** [comment]
Tested In QA, no issues found, moving to awaiting release.

**Comment by lindaxiang** [comment]
Some observations when test on DATA-CA
1. partial search
 - when search DO/do/Do/dO, all show `Clinical Data for: 20 Donors` on the left.
 - when search for a pattern like `DO2627`, also shows `Clinical Data for: 20 Donors` on the left.

2. search for `DO262720`, select the donor, and then click button `X`
- we'll still get 1 record, but show `Clinical Data for: All Donors` on the left 
- there's no way to get back all donors unless we go to other tabs (e.g, Dashboard, Register Samples, ....) and then come back.
