### ISSUE TITLE
[UI] Close search dropdown on Enter 

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/platform-ui#2416]
Current Behavior: 
The search dropdown doesn't close on `Enter`. It gives an impression of incomplete action. 
![image](https://user-images.githubusercontent.com/30519419/196835582-4438f97a-081f-4a6f-b78c-277710db2926.png)

Expected Behavior:
The search dropdown should close on `Enter`.

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected.
