### ISSUE TITLE
🐛  Surgery Tab doesn't display records

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/platform-ui#2417]
![image](https://user-images.githubusercontent.com/30519419/196836527-150355ab-92ee-47ba-a16a-0a394022c04d.png)

## Expected behaviour
Surgery tab should be clickable and should display records.

**Comment by demariadaniel** [comment]
Can we validate which programs/environments this is an issue on?

https://platform-ui.dev.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?tab=surgery

This url works for me on Dev using DATA-CA program and looks like correct Surgery data

**Comment by sifavahora** [comment]
The issue is on QA environment. 
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?donorId=&tab=donor
We can use the Program DATA-CA as an example program.

**Comment by Buwujiu** [comment]
Working in dev but not in qa, need more testing.

**Comment by demariadaniel** [comment]
KIMC-CA, DASH-CA, & ALEXIS-INTL all display the Surgery tab in QA as of Nov 3

If there are specific programs that are not displaying Surgery when they should we can narrow down the issue

Clinical Service is returning items where Donor -> Treatments -> Therapies -> TherapyType === 'surgery'
So if the submitted Surgery data is stored elsewhere on the Donor it would not be rendering properly

**Comment by Buwujiu** [comment]
Tested in QA on ALEXIS-CA, ALEXIS-INTL, HNAHAL-CA. Working as expected.

**Comment by lindaxiang** [comment]
Tested in QA for programs: DATA-CA. Working as expected.
