### ISSUE TITLE
Clear Submitted Data Cache when a "Register Sample/Submit Clinical Data" request is made 

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/platform-ui#2423]
## Detailed Description
Currently the system caches responses in the browser so it doesn't repeat them
but after the user submits new data (register samples or submitting clinical data) then the “submitted data” section changes.
The user is required to refresh the browser page to see the new data. 

## Possible Implementation
Clear Submitted Data cache when a Register Sample/Submit Clinical Data request is made

**Comment by Buwujiu** [comment]
same issue as #2431?

**Comment by Buwujiu** [comment]
Same issue as #2431, which is working as expected.
