### ISSUE TITLE
🐛 [UI] Broken UI for row count display 

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/platform-ui#2428]
![image](https://user-images.githubusercontent.com/30519419/199286431-637ef6ea-ae91-4c96-87b6-0356d49c1196.png)

Steps to reproduce the behaviour:
1. Go to 'https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?donorId=&tab=donor'
2. Click on 'show ## rows'

## Expected behaviour
![image](https://user-images.githubusercontent.com/30519419/199286711-af152475-fe4c-4890-9da5-ce379f8c6a15.png)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected.
