### ISSUE TITLE
Bug - Random "Hello" on Manage Program Page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2432]
## Steps to reproduce:
1. go to QA manage program page
2. there is a "Hello" next to Add User button. Make it go away

![Screen Shot 2022-11-02 at 12.45.36 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/2ca46514-af6c-4eaa-a83c-1811e2078d6a)

**Comment by Buwujiu** [comment]
Fixed already in UI kit! 
@daniel-cy-lu to link it to PR

**Comment by edsu7** [comment]
LGTM. Tested on staging platform across all experiments. No longer see `hello` in `manage program` pages.
