### ISSUE TITLE
Allow Updates on Sample Registration 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2434]
## Detailed Description
Currently on the platform, users can only register samples once, without having the chance to update the form once it's submitted. If users made mistakes, they have no way of correcting. For example, they may want to change the gender, sample type in sample registrations that have already been submitted. We want to add the ability to allow updates on sample registrations. 

API ticket is https://github.com/icgc-argo/argo-clinical/issues/839

## Possible Implementation
Since we already let users update other clinical entities, all they need to do is upload files again and the page enters an admin approval status where DCC admins get to review the changes. We want the same approach for sample registration update. 

## User Flow
1. Users login as data submitter, go to Register Samples
2. Register some samples
3. Users want to update these columns for the newly registered samples: gender, tumour_normal_designation, specimen_type
4. Users upload a new registration file, click on `REGISTER SAMPLES`, a modal similar to this should pop up:
![Screen Shot 2022-11-02 at 11 27 41 AM](https://user-images.githubusercontent.com/8744047/199784593-ee7bf958-2115-4eef-abbc-b1b24dafed7b.png)
Title should be : "Are you sure you want to register samples?"
could use the same warning: `The DCC will be notified of the following updates to previously released data and your submission will be locked until approval.` on the modal. 
No need to add a summary table. 
5. If users click on YES, they will go to the same sample registration page where a table detailing what records are updated is listed in the page. Similar to this:
![Screen Shot 2022-11-02 at 11 28 06 AM](https://user-images.githubusercontent.com/8744047/199785452-dd2c38e1-4993-4a34-8034-664362684789.png)
6. The submission should be locked at this point because it's in pending approval state. 
6. done. Now wait for dcc's approval.

TODO 
- discussion UI design with Patrick.
- Make a ticket for clinical

**Comment by patrickdsantos** [comment]
Hello! Here are the links to the updated pages:

Copy update for Register Samples page: https://zpl.io/awOeOLg
Update Registered Samples Pop-up: https://zpl.io/7wLe4Yj
Registered Samples, Pending Approval: https://zpl.io/5EMxqYJ
Validate Submission: https://zpl.io/2ZXEgAL

**Comment by samrichca** [comment]
Step 1: upload file with sample registration updates, see updates on table

1. https://github.com/icgc-argo/argo-clinical/issues/867
2. https://github.com/icgc-argo/platform-api/issues/634
3. https://github.com/icgc-argo/platform-ui/issues/2497

Future steps:
1. Click the register samples button & click OK in the modal. Show Pending Approval state to submitter & admin.
2. Approval (admin)
3. Re-open submission (submitter & admin)
4. Potential side effects of adding new endpoints and changing the data model for samples

**Comment by samrichca** [comment]
closing, more specific tickets were created for this epic.
