### ISSUE TITLE
Improve GraphQL error handling

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2437]
Add GraphQL error handling to Husky pre-push shell command, similar to type checking.

- Looking for a visible, hard check on GQL validations that prevents pushing commits with invalid GQL requests.
- `npm run type-check` causes Husky to fail correctly.
- `npm run graphql-codegen` returns successfully even when there's errors.
- Expected outcome: Husky should fail when GQL is invalid.

**Comment by Buwujiu** [comment]
Thanks @ciaranschutte for testing in QA! Works as expected, moving to awaiting release.
