### ISSUE TITLE
🐛 Issues with Submitted Data 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2440]
## Describe the bug
Feedback for these tickets:
- https://github.com/icgc-argo/platform-ui/issues/2269
- https://github.com/icgc-argo/platform-api/issues/543
- https://github.com/icgc-argo/platform-ui/issues/2271
- https://github.com/icgc-argo/platform-ui/issues/2387
- https://github.com/icgc-argo/platform-ui/issues/2315

## Issue 1
When an id is entered, click on the suggested id, table filters, however if I click on 'X', the table stays the same: 
https://www.screencast.com/t/Qge3BORrpd5

Expected: table should go back to showing all donors when filter is cleared.

## Issue 2
After Issue 1 happened, if I enter random text to the filter, the same donor Id would still show up:
https://www.screencast.com/t/InU8qEVQ

Expected: search suggestion should be empty.

## Issue 3 
in https://github.com/icgc-argo/platform-ui/issues/2271, please refer to comments: https://github.com/icgc-argo/platform-ui/issues/2271#issuecomment-1310661282

## Issue 4
refer to comments: 
https://github.com/icgc-argo/platform-ui/issues/2387#issuecomment-1310880433
https://github.com/icgc-argo/platform-ui/issues/2387#issuecomment-1310972077

## issue 5
dashboard alerts column does not show DATA-CA despite treatment errors, refer to
https://github.com/icgc-argo/platform-ui/issues/2315#issuecomment-1315917229

**Comment by demariadaniel** [comment]
Created PR https://github.com/icgc-argo/platform-ui/pull/2469
Two bugs in this ticket have been fixed elsewhere:

Missing Dashboard DATA-CA alerts - Fixed in QA
'List' button not opening modal - Working in Dev

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!
