### ISSUE TITLE
Donor Dashboard - DNA-SEQ Sample & Raw Reads Cell Error Display

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2448]
## Detailed Description
As the last part of RNA seq epic, we need to display errors on DNA table `Registered Samples` and `Raw Reads` columns. Since the initial design of using tooltip is not feasible, we have decided to use changing cell background color to indicate three types of potential errors.
![Screen Shot 2022-11-16 at 10 55 37 AM](https://user-images.githubusercontent.com/8744047/202229539-cd3b9358-d526-4c59-adbc-9ff7d227cb93.png)

## Task 1
Mockup:
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/636ea7765a70b932fabd4b14

For rules on what error to display, refer to `DNA Pipeline - Raw Reads ` and `DNA Registered Samples` in:
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

## Task 2
Please also investigate why the cell color is not filling the cell.

**Comment by samrichca** [comment]
previous UI ticket https://github.com/icgc-argo/platform-ui/issues/2247

**Comment by Buwujiu** [comment]
@samrichca to create a ticket in API.

**Comment by samrichca** [comment]
original errors are still there when feature flag is false
![image](https://user-images.githubusercontent.com/3540896/204051727-d4aed719-f771-4aff-8180-5db48743e260.png)

errors with matched pairs
![image](https://user-images.githubusercontent.com/3540896/204052087-81afaaa3-513c-4984-bfc7-13cf33b9ccc3.png)

![image](https://user-images.githubusercontent.com/3540896/204051915-af8e1065-e2db-459d-ae00-b08ea7587f57.png)

errors if I disable matched pairs
![image](https://user-images.githubusercontent.com/3540896/204052156-1b093ea0-c9ca-45f3-a52a-df373bfcc1ce.png) 
![image](https://user-images.githubusercontent.com/3540896/204052164-6a9a6410-75c7-49eb-81e8-c27f6c421d46.png)

**Comment by Buwujiu** [comment]
will test in DEMO-CA, which is currently having dashboard issues.

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
