### ISSUE TITLE
Feature Request - Add Missing Raw Reads Filters on Donor Dashboard

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2454]
## Detailed Description
Add 1 filter criteria on DNA Raw Read column, the text should be
"Missing raw reads"

![Screen Shot 2022-11-17 at 12 07 07 PM](https://user-images.githubusercontent.com/8744047/202511565-c217c303-37f6-4d36-8353-ca9f2270a25d.png)

**Comment by samrichca** [comment]
closing because these changes are addressed in this ticket https://github.com/icgc-argo/platform-ui/issues/2489
