### ISSUE TITLE
🐛 Pagination Issue On Donor Dashboard - DNA columns

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2456]
## Describe the bug
Pagination isn't working properly in qa donor dashboard DNA raw reads and sample columns.
Same issue found  when applying DNA Raw Reads filters.
## Steps To Reproduce
https://www.screencast.com/t/69uyyG7klQ1

## Expected behaviour
When `T or N not registered` filter is applied, page size = 100, there should only be 2 pages if total donors are 110.

**Comment by samrichca** [comment]
known issue - should be fixed in this PR, where pagination is reset after queries. https://github.com/icgc-argo/platform-ui/pull/2464

**Comment by Buwujiu** [comment]
@samrichca Tested in QA, when changing page size to 100, the page crushes, see the clip: https://www.screencast.com/t/LWGlpW2jGg0q

**Comment by Buwujiu** [comment]
Tested in QA on PACA-CA and OCCAMS-GB, working as expected.

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
