### ISSUE TITLE
🐛 Molecular Chart RNA Alignment and Raw Reads Issue

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2457]
## Describe the bug
![Screen Shot 2022-11-18 at 11 51 52 AM](https://user-images.githubusercontent.com/8744047/202759764-d4e1f570-2cc5-4d63-9ecf-effa111f05b9.png)

Same issue with Raw reads line, it's between 3 - 5, should be at 3.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/TCRB-CA/dashboard
2. Click on RNA Alignment in chart

## Expected behaviour
The line should plot at 3 donors for RNA alignments

**Comment by samrichca** [comment]
Improved positioning for Y coordinates & changed the Y axis labels so they have to be multiples of (number of horizontal guides).

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/31f7016a-4727-4efe-8376-288cfd8f9b33)
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/089e754f-2468-438e-84a8-ab2feeefcf4d)

**Comment by Buwujiu** [comment]
Tested in QA TCRB-CA, working as expected!

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
