### ISSUE TITLE
🐛 Program Dashboard showing incorrect number of "Registered Donors" for MUTO-INTL

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/platform-ui#2461]
## Describe the bug
The Program Dashboard is showing the incorrect number of "Registered Donors" for the Mutographs program (MUTO-INTL) in PROD. It should report 516 donors, but it shows 1,030 donors instead. It appears to be counting the number of registered samples rather than the number of registered donors.

## Steps To Reproduce
1. Click on "All Clinical Data" in https://platform.icgc-argo.org/submission/program/MUTO-INTL/dashboard and open downloaded "sample_registration.tsv" file. This shows 1,031 rows (same as the number we see in the "Registered Donors" section in the Program Dashboard), but there are actually only 516 registered donors.

![duplicated_registered_donors](https://user-images.githubusercontent.com/4992044/203126928-e8ef9b60-4fbd-41d9-a966-942b168302be.png)

This issue appears to affect only the MUTO-INTL program. The other programs in PROD have the correct number of registered donors.
Possibly related to https://github.com/icgc-argo/platform-ui/issues/2462?

**Comment by sifavahora** [comment]
Temporary fix in place. longterm fix in progress

**Comment by Buwujiu** [comment]
This is fixed by icgc-argo/donor-submission-aggregator#282.

**Comment by Buwujiu** [comment]
moving to awaiting release.
