### ISSUE TITLE
🐛 Program Dashboard table is showing duplicated donors for the MUTO-INTL program

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/platform-ui#2462]
## Describe the bug
The donors in the [MUTO-INTL Program Dashboard table](https://platform.icgc-argo.org/submission/program/MUTO-INTL/dashboard) are appearing twice:

![muto_duplicated_donors](https://user-images.githubusercontent.com/4992044/203128343-4e861afd-6a3c-4488-90f0-09bf60766324.png)

This issue is causing problems for the program while they upload molecular data because the information in the Program Dashboard is not accurate and they're not able to tell if their samples are getting uploaded correctly.

**Comment by hknahal** [comment]
Program Dashboard table (in PROD) no longer shows duplicated donors for MUTO-INTL. Each donor appears only once in the table:

![muto_donors](https://user-images.githubusercontent.com/4992044/204024648-93c63cea-c5f5-43ae-87d2-de8381c0a1a5.png)

**Comment by sifavahora** [comment]
temporary fix in place, long term fix in progress

**Comment by Buwujiu** [comment]
This is fixed by https://github.com/icgc-argo/donor-submission-aggregator/pull/282.

**Comment by Buwujiu** [comment]
moving to awaiting release.
