### ISSUE TITLE
Feature Request - Add Number Tooltip to Molecular and Core Clinical Chart

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2474]
## Detailed Description
Currently on donor dashboard molecuar and core clincial charts, there is no indication of how many donors are plotted on the charts when hovering over to the dots.
![Screen Shot 2022-11-25 at 12 43 13 PM](https://user-images.githubusercontent.com/8744047/204035182-11ae05b3-9fbe-4b51-901c-bef3b13a5026.png)
![Screen Shot 2022-11-25 at 12 44 50 PM](https://user-images.githubusercontent.com/8744047/204035183-ee44e37f-69e1-4d4b-b323-9c9061e15205.png)

It's difficult to see exact number of donors in the charts.

## Possible Implementation
Update UI to show a tooltip of donor number when hovering over to the dots.

**Comment by Buwujiu** [comment]
Investigate possible solutions with @patrickdsantos , instead of tooltips, what are the other ways to show data?

**Comment by joneubank** [comment]
![tooltips_exploration](https://user-images.githubusercontent.com/8339820/212360239-1f89302d-90cb-4c69-81b6-aa436051684e.png)
