### ISSUE TITLE
🐛 Page crashes when number of rows to show is greater than 20 in the MUTO-INTL Program Dashboard table

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/platform-ui#2477]
## Description
Page errors out when number of rows at the bottom of the table in the Program Dashboard for the MUTO-INTL program is clicked and a value larger than `20` is selected from the drop-down.

## Steps To Reproduce

1. Go to https://platform.icgc-argo.org/submission/program/MUTO-INTL/dashboard
2. Click on drop-down in "Select rows" at the bottom of the table.
3. Select a number greater than 20 (for example 100)
![muto_page_rows](https://user-images.githubusercontent.com/4992044/204057368-7f2031e4-1797-49a8-9aae-8a14e2cf3dc4.png)
5. The page briefly (for 1 second) shows a table and then returns this error screen
![error](https://user-images.githubusercontent.com/4992044/204057380-c60a73b3-c5e0-4400-9edf-1a7789aa3fc0.png)

### Notes:
- This error only happens for the MUTO-INTL program
- The error doesn't show if `5` or `10` rows are selected.

**Comment by Buwujiu** [comment]
Reproduced in QA on DATA-CA.
