### ISSUE TITLE
List Modal - Search Result Should Update When Table Changes

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2481]
## Detailed Description
On the submitted data page, the "clinical data for" in the search bar should be updated to show the number of matched donors when the results are filtered with the list modal.

## Steps to reproduce
https://watch.screencastify.com/v/LokJdaBGYjg6kjRNHI7j

## Expected Results
![Screen Shot 2022-12-08 at 11 23 54 AM](https://user-images.githubusercontent.com/8744047/206505453-91404f5c-ae5c-4dfb-a536-3492e97a8d1a.png)

**Comment by daniel-cy-lu** [comment]
@Buwujiu To make it consistent with the Search Bar keyword search, the "Clinical Data For" section will only display the specific donor id if there is one match in the filter modal. If there are more than one matches, it will display the number of matches instead. For example, if the filter modal has two matches, DO250481, and DO250480. The Clinical Data For will display "2 Donors".

**Comment by daniel-cy-lu** [comment]
This ticket's requirement is met by PR #2469. @Buwujiu @demariadaniel

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by lindaxiang** [comment]
@Buwujiu 
Test in `MUTO-INTL`, when wildcard search for `2505`, it has `52` records found in total, however the search result still shows `20 Donors`
<img width="1444" alt="Screen Shot 2023-01-18 at 2 03 53 PM" src="https://user-images.githubusercontent.com/7522294/213271616-3005cc9b-8924-4f1a-b25b-cbe99ba11652.png">

**Comment by Buwujiu** [comment]
> 2505

This is a different issue than the one logged in this ticket.

**Comment by hknahal** [comment]
Tested in Prod by searching for `DO234122, DO234100` in `PTC-SA` program. Working as expected!

![ptc-sa](https://github.com/icgc-argo/platform-ui/assets/4992044/8b285dbf-45e8-4711-9632-bf481d5546fa)
