### ISSUE TITLE
Jenkins: husky & git tags not working

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2483]
- When we deploy to QA, Jenkins makes a git tag.
- This includes a `git push` which triggers Husky pre-push, which fails because it can't find npm.
- Git tags are also not working since 2021

from @ciaranschutte:
> npm executable probably isn't part of the docker image used for that jenkins step, it's a docker image of docker, not a docker image of node (used in other steps where we use npm/node)

(clarification: `git push` is happening inside `container('docker') { git push }` which doesn't have access to node and can't execute npm scripts)

---

Notes:
- Do we need Jenkins to be checking types & GQL on QA builds? (Definitely no for the latter.)
- We do want type & GQL checks on local manual pushes
  - GQL check needs to work without VPN

**Comment by Buwujiu** [comment]
tested in QA, working as expected! Moving to awaiting release.

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
