### ISSUE TITLE
Donor Summary Table errors feedback

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2489]
- add DNA to missing samples & missing raw reads in the legend ("45 missing DNA samples" "10 missing DNA raw reads")
- prioritize matched pairs errors over raw reads errors in legend
  - if a donor has no matched pairs, then it doesn't have a raw reads error
- add filter for missing raw reads https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2454

**Comment by Buwujiu** [comment]
Will test after DEMO-CA dashboard issue is resolved.

**Comment by Buwujiu** [comment]
Tested in QA DEMO-CA, working as expected!

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
