### ISSUE TITLE
Show summary of new & updated samples

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2497]
1. User goes to Register Samples page
2. User uploads files with existing sample IDs
3. The Register Samples page should update to show the number of samples updated and which fields were updated, as well as new samples and errors. Updated sample styling is similar to updated clinical data.
4. The progress bar should show the "Register" step with an orange background and `...` text.

Requirements: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Sample+Registration+Updates+Specs

Mockup: (only look at the table) https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/636ea53684e57280ac5454d0

Use a feature flag & new sample registration API endpoints.

Original ticket: https://github.com/icgc-argo/platform-ui/issues/2434

**Comment by Buwujiu** [comment]
This is feature is not needed anymore, closing.
