### ISSUE TITLE
Refactor SQONView without recompose

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2508]
Refactor SQONView without recompose, because recompose is no longer supported and has a nested vulnerable dependency.

Additionally we have to use --legacy-peer-deps to install platform UI now because of recompose.

---

Update: try to refactor to typescript

**Comment by Buwujiu** [comment]
Tested the filter icons in file repo, working as usual.

**Comment by Buwujiu** [comment]
Tested in staging, filter icons working as expected!

**Comment by Buwujiu** [comment]
Tested in Prod, working as expected!
