### ISSUE TITLE
🐛 Edit Instruction Text in Filter Modal

### ISSUE THREAD

**Issue by daniel-cy-lu** [icgc-argo/platform-ui#2510]
Follow BA's review as in the screenshot.
<img width="634" alt="Screenshot 2022-12-13 at 3 51 26 PM" src="https://user-images.githubusercontent.com/79996555/207441039-fd2c9920-689d-44be-b310-3503df1482c0.png">

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected.
