### ISSUE TITLE
Make filter dropdown larger

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2515]
The dropdown box gets invisible scrollbars when there's a lot of text. Add height/width or CSS controls in Uikit and then update this component in platform UI.

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/da114e62-29b9-4ab9-8391-e70f437b1a8b)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!
