### ISSUE TITLE
Donor Dashboard Issues

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2518]
## TCRB-CA not showing correct donor counts
Steps to reproduce:
1. https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/TCRB-CA/dashboard
the total number of submitted donors is 10, see the submitted data page: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/TCRB-CA/clinical-data?donorId=&tab=donor
However the dashboard is showing only 5 donors.
2. Select a filter from DNA registered sample column, the total number of donors becomes 9:
 ![Screen Shot 2022-12-16 at 5.10.23 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/8aa908cd-be1b-4f0a-9735-1c85853722a9)
3. select RNA Raw reads - No data submitted filter, total number of donors becomes 7, expected is 3

![Screen Shot 2022-12-16 at 5.19.14 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/3389e568-d8a2-47f3-b8b7-41811caaf650)

When making the following query to argo gateway API:
```
query{
  programDonorSummary(
    programShortName: "TCRB-CA", 
  	first: 20,
  	offset: 0,
  	filters:  [ ] ) {
    entries {
      donorId
      submitterDonorId
      
    }
    stats {
      registeredDonorsCount
    }
  }
}
```
The return is total 5 donors:
```
{
  "data": {
    "programDonorSummary": {
      "entries": [
        {
          "donorId": "DO262497",
          "submitterDonorId": "donor2"
        },
        {
          "donorId": "DO262498",
          "submitterDonorId": "donor1"
        },
        {
          "donorId": "DO263267",
          "submitterDonorId": "test222"
        },
        {
          "donorId": "DO263268",
          "submitterDonorId": "test333"
        },
        {
          "donorId": "DO263270",
          "submitterDonorId": "test555"
        }
      ],
      "stats": {
        "registeredDonorsCount": 5
      }
    }
  }
}
```

**Comment by samrichca** [comment]
I believe this is fixed in https://github.com/icgc-argo/platform-api/pull/640

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by Buwujiu** [comment]
Since it's fixed in another ticket, will close this issue.
