### ISSUE TITLE
Update Simple tables to V8

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2532]
- Add react-table v6 & v8 to uikit
- Update the following tables in react-table v8 (replacing the Uikit SimpleTable component)
  - Donor Entity page
    - Clinical Timeline data (e.g. Primary Diagnosis)
    - Summary
    - Associated Donors
  - File Entity Page
    - Data & Analysis Information
    - File Summary

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!
