### ISSUE TITLE
🐛 Submitted Data Page - Core Complete Tooltip Flickers

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2540]
## Describe the bug
in QA - submitted data page, when mouse over the core complete tooltip, it flickers. 
https://www.screencast.com/t/aJtp2USaT1

## Possible Cause
Might be fixed if upgrade react table.
Park on this until table is done.

**Comment by joneubank** [comment]
can we please remove the pop up until we have a fix? That flickering is worse than no popup
