### ISSUE TITLE
🐛 Sort By Donor Id Not Working Properly

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2546]
## Describe the bug
In QA and Staging submitted data page, when sorting table by `donor_id`, the table doesn't sort properly, example:
https://www.screencast.com/t/UzJhCv8UruZZ

## Expected behaviour
When sorting by donor_id, the table should be sorted by either descending or ascending order.

**Comment by lindaxiang** [comment]
Tested in Prod. Working as expected.
