### ISSUE TITLE
Update Submitted Data Table Error Cell Highlight Logic

### ISSUE THREAD

**Issue by demariadaniel** [icgc-argo/platform-ui#2547]
Lectern Client is updated to include specific values in the Donor error objects.

Update Submitted Data Table to only highlight cells which match donor ID, field name **and** error value
Errors are found @ ClinicalData Query -> ClinicalErrors -> error.info.value

See [TODO at `components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx` line 494](https://github.com/icgc-argo/platform-ui/blob/df8c69034269b8d9bdea0c425f4d7a4b89e8529e/components/pages/submission-system/program-submitted-data/ClinicalEntityDataTable/index.tsx#L494)

This should reduce the number of cells highlighted; the table currently matches all cells w/ matching donor ID and field name

**Comment by Buwujiu** [comment]
@demariadaniel Hi! The follow up table doesn't have any highlighted cells, but there are errors in the table: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?tab=follow_up
Could you please take a look at it?

**Comment by Buwujiu** [comment]
the issue still exists in  https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?tab=follow_up, Dan will fix it as part of ticket #2535 . Moving back to in progress.

**Comment by Buwujiu** [comment]
@demariadaniel some cells are not highlighted: 
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?donorId=&tab=follow_up

![Screen Shot 2023-04-03 at 2 46 41 PM](https://user-images.githubusercontent.com/8744047/229599626-b28c44a7-cca1-4598-b624-64372877006c.png)

**Comment by lindaxiang** [comment]
Program: TEST-CA, 
1. table - Follow Up

<img width="1087" alt="Screenshot 2023-05-05 at 5 28 39 PM" src="https://user-images.githubusercontent.com/7522294/236573103-65ce7b1c-e14e-44c2-856e-5158507ff6c5.png">

2. table - Immunotherapy

<img width="1093" alt="Screenshot 2023-05-05 at 5 41 02 PM" src="https://user-images.githubusercontent.com/7522294/236573368-dcf9fc7d-2e5d-43a8-be4f-fd478b7e2653.png">

3. table - Treatment
There are more than one records for the same `submitter_treatment_id`, should this be reported and highlighted?
<img width="1095" alt="Screenshot 2023-05-05 at 6 22 02 PM" src="https://user-images.githubusercontent.com/7522294/236578123-d058ba06-0dac-4c60-af7a-ac17a7bda2be.png">

**Comment by lindaxiang** [comment]
Program: ALEXIS-INTL
table: Primary Diagnosis
- when `lymph_nodes_examined_status` field is 'No', they are NOT needed to be highlighted. 

<img width="1092" alt="Screenshot 2023-05-05 at 6 26 20 PM" src="https://user-images.githubusercontent.com/7522294/236578572-1484d3c9-aaec-426b-b6fb-fea0a9786f36.png">

**Comment by Buwujiu** [comment]
Testing failed in staging, above issues are reproducible in QA, logged issue: https://github.com/icgc-argo/platform-ui/issues/2653. Will move ticket forward.
