### ISSUE TITLE
Remove "Unmatched IDs" From List Filter Modal 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2549]
## Describe the bug
The Unmatched IDs field has been proven to give confusing results, especially if users filter by a mix of donor ids and submitter donor ids. Also the field does not add much value to the filter, let's remove it from the modal.

## Exit Criteria
1. Remove the Unmatched IDs field.
2. The Matched IDs field should return all matched ID, for example, if go to QA DATA-CA, Click on list filter, Enter `DO263260,DN478,DO1` to the search area, the matched IDs should return 2, since DO263260 and DN478 are both valid IDs.
![Screen Shot 2023-03-28 at 4.00.28 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/b0d657c4-6476-48a1-a4bb-2cfebe90980c)

**Comment by Buwujiu** [comment]
Tested in QA, found a few issues: 
1. in DATA-CA, 
  -  when entering "DO1111" into the list modal, page crashes. 
  -  when filter by "DO263260,DN478,DO1" , returns one correct ID but two incorrect IDs. see
  
![Screen Shot 2023-03-06 at 10 54 01 AM](https://user-images.githubusercontent.com/8744047/223162281-b4b8ab97-b039-422e-acad-04b89413e007.png)
2. MUTO-INTL
 - constantly get page crash errors when input in the list filter: Ooops, something went wrong. Could not finish the test

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!

**Comment by lindaxiang** [comment]
Tested in Prod, working as expected.
