### ISSUE TITLE
Update Submitted Data Error Title

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2550]
## Detailed Description
Why we want to update the title? 
- Use staging MUTO-INTL as example, there are 88 errors on donor page: https://platform.staging.icgc-argo.org/submission/program/MUTO-INTL/clinical-data?donorId=&tab=donor, if users select `invalid donors` from quick filter, the page now says `93 error(s) found in donor data`. Because the wording seems to suggest the number applies to all donor data, it makes users think that the total number of errors increased, which should no be possible. 

Change error report title to:
`** error(s) found on the current page of [] table.`
- insert corresponding clinical entity name in `[]`.
Example:
![Screen Shot 2023-01-18 at 10 44 01 AM](https://user-images.githubusercontent.com/8744047/213218515-7549233e-b7a6-43f3-886b-480498ee0ec7.png)

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!

**Comment by lindaxiang** [comment]
Tested in Prod, working as expected!
