### ISSUE TITLE
🐛 Quick Filter Failed to Return Complete Donors

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2553]
## Goal
note: This is originally a bug ticket.
**Updates:**
As discussed with Dan, we need to update the definition of core complete in both UI and API. 
Use this ticket to track API work needed for the update.

The ultimate Core Completion Rule:

- For specimens (20%), each registered specimen must have a corresponding clinical record. 
- Count the number of registered specimen 
- Count the number of specimen with clinical records
- Find the ratio of (specimen clinical records/ registered specimen) 
- a donor must have one T/N pair to complete the calculation

How to calculate the specimen core complete:
For a given donor, 
All submitted specimens records count for 20% of the total core complete.
All T submitted specimens records count for 10% of overall core complete
All N submitted specimens records count for 10% of overall core complete

The formula: 
(# of submitted T specimen / # registered T specimen ) * 10% 
+
(# of submitted N specimen/ # registered N specimen) * 10% 

Refer to note: https://docs.google.com/document/d/1U6rsm9f286FDJ_UQCHvDNPpafXk12V5F5s0IKOiZmBw/edit

## The original bug
In qa and staging submitted page, quick filter doesn't return complete donors. 

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/ALEXIS-CA/clinical-data?donorId=&tab=donor
2. Click on Filter by Complete Donors
3. Page is empty

## Expected behaviour
In QA ALEXIS-CA, when filter by complete donor, `DO250682 ` should display on the page.

**Comment by demariadaniel** [comment]
This is connected to coreCompletionPercentage: selecting 'Complete' filters by coreCompletionPercentage =  1, but in ALEXIS-CA donor #264720 has Specimen coreCompletion = 0, so coreCompletionPercentage is calculated as 0.8:

{
 "coreCompletion": {
  "donor": 1,
  "specimens": 0,
  "primaryDiagnosis": 1,
  "familyHistory": null,
  "followUps": 1,
  "treatments": 1,
  "normalSpecimens": 1,
  "tumourSpecimens": 1,
  "__typename": "CoreCompletionFields"
},
"coreCompletionDate": null,
"coreCompletionPercentage": 0.8,
"overriddenCoreCompletion": [],
"donorId": 264720,
"__typename": "CompletionStats"
}

This is either connected to coreCompletionPercentage calculation, an error in the record in the DB, or in calculation of normal/Tumour completion, which is done by clinical-submitted-data flow post-DB retrieval

**Comment by Buwujiu** [comment]
Use this ticket to track the coreCompletion re-calculation change in the clinical API.

**Comment by Buwujiu** [comment]
Quick filter is working as expected in QA.
