### ISSUE TITLE
🐛 Partial Search Only Returns Donor Data

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2554]
## Describe the bug
<img width="1456" alt="Screen Shot 2023-01-20 at 4 15 07 PM" src="https://user-images.githubusercontent.com/8744047/213806791-37700f95-48ee-400b-a020-82c7f0dda966.png">

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?donorId=&tab=donor
2. Click on submitted page
3. enter `272` into the id search bar
4. page shows 10 records in Donor tab, but sample registration tab is not clickable

## Expected behaviour
Other tabs should be clickable when partial searching IDs.

**Comment by demariadaniel** [comment]
This is likely a conflict between filtering by Donors specified in the SearchBar / URL and not correctly populating the EntityNames field in the front end Query

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.

**Comment by Buwujiu** [comment]
Tested in staging, working as expected.

**Comment by lindaxiang** [comment]
Tested in Prod, when entering characters in search box, it returns correct #records in the table, however 
1. On the left top corner, it is consistently showing `Clinical Data for: 20 Donors`, even when #records >20, 

<img width="1345" alt="Screenshot 2023-05-11 at 3 33 59 PM" src="https://github.com/icgc-argo/platform-ui/assets/7522294/9c80b3b5-c893-4d54-a039-5f1f7b41e04d">

2. it is showing correctly when #records <20
3. the partial search is in effect across the tables.

**Comment by Buwujiu** [comment]
> Tested in Prod, when entering characters in search box, it returns correct #records in the table, however
> 
> 1. On the left top corner, it is consistently showing `Clinical Data for: 20 Donors`, even when #records >20,
> 
> <img alt="Screenshot 2023-05-11 at 3 33 59 PM" width="1345" src="https://user-images.githubusercontent.com/7522294/237794432-9c80b3b5-c893-4d54-a039-5f1f7b41e04d.png">
> 2. it is showing correctly when #records <20
> 3. the partial search is in effect across the tables.

Thanks @lindaxiang for confirming, issue is logged in https://github.com/icgc-argo/platform-ui/issues/2652
