### ISSUE TITLE
Update Core Completion Table NS and TS Column 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2580]
## Detailed Description
Based on the core completion rule, a donor's specimens are core complete when:
- The # of submitted specimens is equal to the # of registered specimens in sample registration file
- Must have both T and N specimens submitted in specimen table

API part is done #2553

## Exit Criteria 
- [x] 1 . Update the NS and TS columns in the core completion table, 
   - show a green checkmark when the # of submitted specimens is equal to the # of registered specimens
   - show the actual number of submitted specimens when the # of submitted specimens is LESS than the # of registered specimens. Change the cell background to red in this case.
  
Example 1:
QA ALEXIS-CA
DO263277
Registered samples: 1N 1T
Submitted specimen: 0N 0T

UI Core completion table should be:
NS = 0 (red background)
TS = 0 (red background)

Example 2:
QA ALEXIS-CA
DO263278
Registered sample: 2N 1T
Submitted specimen: 1N 1T

The UI core complete table should look like this:

NS = 1 (promised 2 N, but submitted 1, so 1) red background
TS = complete (green check)
![Screen Shot 2023-02-23 at 12.05.53 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/3181ed54-bf5e-4a3d-845e-350276dfc8b0)

- [x] 2. update the NS and TS in tooltip text so it reads:
```
NS: all the submitted Normal DNA Specimen record
TS: all the submitted Tumour DNA Specimen record
```

**Comment by demariadaniel** [comment]
Clinical updates included in RC 1.76.0

**Comment by Buwujiu** [comment]
Filter by quick filters should work now in qa. Will test.

**Comment by Buwujiu** [comment]
DATA-CA DO262873 should be core complete. https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/DATA-CA/clinical-data?tab=donor&donorId=DO262873

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!

**Comment by Buwujiu** [comment]
Tested in prod, working as expected!
