### ISSUE TITLE
Wrap Up React Table Upgrades

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2628]
## Goal
Get a new version of UI kit out (with NO old table version)so someone can take over.
Finish code review, get the typing correct.
Will need 2 days to finish the task, projected to start on April. 10.

**Comment by Buwujiu** [comment]
will have a major version of UI kit published today.

**Comment by samrichca** [comment]
suggested enhancements
- change enableX to withX. I had both initially to avoid naming conflicts with react table, but now I think we can stick to withX.
- (optional depending on clinical entity data table development) add column pinning or expose resize API to support column pinning in clinical entity data table

**Comment by Buwujiu** [comment]
All the work in UI kit is done. UI kit is left to a stable version. 
Dev work is done.
TODO
1.  migrate the platform UI to use the new ui kit. 
2. DACO and argo docs also need to use the new ui kit.
