### ISSUE TITLE
Homepage Announcement Update

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2630]
1.  [x] Update DR notification to be "Data Release 6 - April, 2023"
![Screenshot 2023-04-03 at 10 28 30 AM](https://user-images.githubusercontent.com/7522294/229540399-e95567ab-aac2-4f37-a250-f31fc2cb2fdd.png)

- [ ] Add the following announcements to the homepage `Announcements`: 

**April 05 2023**: We are excited to announce [Data Release 6.0](https://docs.icgc-argo.org/docs/release-notes/data-releases#data-release-60) on the ICGC ARGO Data Platform, including the first release of a new RNA-Seq analysis workflow: [RNA Seq Alignment](https://docs.icgc-argo.org/docs/analysis-workflows/rna-alignment), available now for transcriptome sequencing data from Australian Pancreatic Cancer Initiative (APGI-AU).

**[INSERT RELEASE DATE] 2023**: We are excited to announce that two new features are now available on our platform: the Submitted Data Page and the Program Level Clinical Exception.

- [ ] Update the footer to make sure it's pointing to the latest versions:
![Screen Shot 2023-04-10 at 9 36 47 AM](https://user-images.githubusercontent.com/8744047/230911784-89d53dc1-2955-4c99-ab4b-2306d567612c.png)

-  [ ] Make sure the styling is consistent.

**Comment by Buwujiu** [comment]
Move back to in progress, we need to insert the latest release date when Phoenix release is complete.

**Comment by demariadaniel** [comment]
Updated in https://github.com/icgc-argo/platform-ui/pull/2648

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!

**Comment by Buwujiu** [comment]
Tested in prod, working as expected!
