### ISSUE TITLE
Change the Processing Regions To A Dropdown List

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2675]
## Detailed Description
As we are supporting multiple RDPCs, there will be other processing regions other than Canada. Change the single selection to a dropdown list.  
![Screenshot 2023-06-06 at 2 18 44 PM](https://github.com/icgc-argo/rdpc-ui/assets/8744047/2c5e489e-dfdc-471c-8de9-1642b539bab1)

No API change needed. 

## Exit Criteria
1. DCC admins should be able to select only ONE country from the Processing Regions list when creating a new program. 
2. Update text `Please indicate the region(s) where data can be processed` to `Please indicate the region where data can be processed`.
~~3. Add a hardcode list to the repo to include RDPC names.~~
3. List regions as listed in Platform API's program regions list

**Comment by ciaranschutte** [comment]
@Buwujiu @joneubank 
changed to dropdown with hardcoded list

hardcoded list needs to be valid, in sync, with program service as validation happens on the backend
didn't touch backend code as api change not needed - but if you have something else in mind let me know and I can make the necessary changes

**Comment by joneubank** [comment]
I think maybe the instruction to switch to hardcoded was a mistake on our part. We can still read the options from the api and thus keep them in sync. Sorry for the misdirection.

**Comment by Buwujiu** [comment]
Tested in QA, working as expected.
