### ISSUE TITLE
Add A Feature Flag For Submit Clinical Data Page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2680]
## Detailed Description
When the new submit clinical page is ready, add a feature flag to we can enable the new page in QA, but hide it in staging and prod.

**Comment by demariadaniel** [comment]
Enable Flag:
Dev: https://github.com/OICR/argo-infra/pull/945
QA: https://github.com/OICR/argo-infra/pull/950

Add Flag (disabled):
Staging: https://github.com/OICR/argo-infra/pull/952
Prod: https://github.com/OICR/argo-infra/pull/951/files
