### ISSUE TITLE
Mocks for Clinical Download for Files

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/platform-ui#2718]
## Detailed Description
Adding ability to download clinical data for the donors associated with files in the File Repository. We need to add the following features to the File Repository UI:

1. Ability to download Clinical Data associated with files
    a. all files in search result
    b. selected files
    c. optionally -> individual file, download action in table row
2. Filter search results to show only files with clinical data available
    a. could be facet filter -> may need tool tip to explain it
    b. could be a toggle on the file repo table, or a filter on the column representing clinical data 
    c. Need the query bar text when filter is applied

**Comment by patrickdsantos** [comment]
Mocks available here: https://www.figma.com/file/lwoNunjDi5yySlzn0fdBdx/ARGO-Download_Clinical_Data_Download?type=design&node-id=0%3A1&mode=design&t=p8Lkf3ehfuKEbncm-1

**Comment by patrickdsantos** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--314d83eb62acf1a3d11aa620f646068ace468dcb/ARGO-FilePage.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGxjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afdf4fc152d51cb96fd655cac80ddb8c4a32a5e6/ARGO-FileRepo-ClincialData.png)
