### ISSUE TITLE
Contact Page: Hook up form + confirmation messages

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#284]
**Behaviour:**
1. When the form is submitted by the user, the form itself should fade out within the card, with a loader on top (can we use the fake loader timing thing that @wajiha-oicr implemented? To make it seem like something is happening). 
2. After that time and when form is submitted, the form fades back on to the page, empty, and the confirmation toast appears from the usual location.

**Confirmation messages:**
1. When form is successfully submitted:

**Thank you!**
Your message has been sent. We'll get back to you with a response as soon as possible.

<img width="439" alt="Screen Shot 2020-03-26 at 2 03 11 PM" src="https://user-images.githubusercontent.com/18424138/77680610-97aaef80-6f6a-11ea-849b-022058c0c149.png">

2. When form fails to submit:

**Your message failed to send**
An error occurred while sending your message. Please try again.

![Screen Shot 2019-07-17 at 11 49 16 AM](https://user-images.githubusercontent.com/18424138/61390509-ee631400-a888-11e9-9f7f-d9cf51995947.png)

**Comment by rosibaj** [comment]
closing during grooming as this has been completed
