### ISSUE TITLE
Gateway Integration for User API Keys

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#299]
- [x] Add the ability to `retrieve` a users API Key to the gateway layer using the ego [listToken endpoint](https://ego.qa.argo.cancercollaboratory.org/api/swagger-ui.html#!/token-controller/listTokenUsingGET)
-- A user should only have one active API key at a time 
-- NOTE: if the list returns more than one API key, send an error back that says 
`An error has been found with your API key.  Please generate a new API key.`  
- [x] Add the ability `generate` API keyto the gateway layer using the ego [issueToken endpoint](https://ego.qa.argo.cancercollaboratory.org/api/swagger-ui.html#!/token-controller/issueTokenUsingPOST)

**Comment by ciaranschutte** [comment]
@rosibaj @joneubank @andricDu 
When we generate an API access key, what scopes should we generate with?

**Comment by rosibaj** [comment]
@ciaranschutte all available scopes for that user please.
