### ISSUE TITLE
Snapshot Data for Test Restore

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#304]
- [x] Yell at everyone to stop entering data for 5 minutes.
- [x] Clean up test data set 
(1) ---- from the list of programs in `program_service.progam_ego_groups` delete all groups in EGO that are not part of this list, except for the dcc-group where id=`b0471378-4f1c-45ef-975b-5521067f6524`
(2)--- Delete these Ego Users:
-- `01af4d4a-b165-454f-ad58-0c15b65b0344`
-- `02c2e2e4-def2-4d61-a1ca-15f237940993`
-- `a1f6203e-4320-4095-9ff1-edd64b903872`
-- `be7ad284-a722-46c5-a32b-a774b389f326`
-- `8184937e-ad85-4613-bd6b-ae5e0d2f33fd`
-- `bb14848d-a0da-4e69-bc5f-042bd13f89c3`
-- `c7c25340-7462-4f31-958f-c410d83b5064`
-- `fe8742e9-2803-4630-ad2c-563cd718db39`
-- `2619186f-308c-418a-8da5-40271dc01ac9`
-- `5c530cf3-3d5c-4ee0-89c4-a9bb36a813a4`
-- `0610a017-7d71-4ce7-9bbc-fe03c7c450fb`
-- `b4418576-8f31-4516-9dc8-fe190897142c`
-- `533c89f6-c323-4273-99aa-3e14d427a0f7`
-- `3fd48d62-9a0e-4702-bfa4-460ab1ac046b`
-- `9a62b52b-fd03-43fd-aa82-fbed80bf374e`

- [x] Create database snapshots of:
-- program service database
-- Ego database
- [x] Create SQL scripts that can be used to restore the snapshotted data with Jenkins
- [x] Integrate data wipe + restore at the end of each test run

**Comment by henro001** [comment]
Jenkins pipeline for sql snapshot and restores
https://jenkins.qa.cancercollaboratory.org/job/ARGO/job/devops/job/sql-snap/
