### ISSUE TITLE
Join Program Data Hookup 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#306]
- [x] When the form loads, get the <program.shortname> that is being joined to display on the page
- [x] The url in the email template needs to be adjusted to the correct URL for routing purposes
- [x] Need to get the information from the invite ID 
- Complete validations on form

**Comment by d8660091** [comment]
@rosibaj this one requires invitation details from program-service

**Comment by rosibaj** [comment]
@d8660091 I tried to join a program but was unsucessful:
![image](https://user-images.githubusercontent.com/15824252/63618313-bbafe800-c5b9-11e9-97ac-80ff2129f91f.png)

```
{
  "operationName": null,
  "variables": {
    "joinProgramInput": {
      "department": "a",
      "piLastName": "a",
      "piFirstName": "a",
      "invitationId": "a72504d9-37d4-410f-a026-2e359a31a8db",
      "institute": "rosi"
    }
  },
  "query": "mutation ($joinProgramInput: JoinProgramInput!) {\n  joinProgram(join: $joinProgramInput) {\n    inviteAcceptedAt\n    __typename\n  }\n}\n"
}
````

**Comment by rosibaj** [comment]
@d8660091 on second attempt i was redirected to this page:

![image](https://user-images.githubusercontent.com/15824252/63619350-632e1a00-c5bc-11e9-83a1-69301b640f89.png)
