### ISSUE TITLE
Standardize Form Implementation

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#307]
- [x] Form hook should be abstracted away. Apply it retroactively to forms that have not used it 
- [x] Data Provider + Validation & error hooks.   hooks hooks hooks. 
- [x] Add submission validation.

**Comment by joneubank** [comment]
We should ensure we have tests set up for all forms as an input to this work. That way, when done, we can assure ourselves nothing is broken...

**Comment by rosibaj** [comment]
@joneubank How long do you think the working group needs to be?

**Comment by rosibaj** [comment]
forms are looking good to me!  thanks @ciaranschutte !
