### ISSUE TITLE
Contact Page: New UI Layout

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#336]
The layout of the contact page has changes in order to fit the form on the page better, and to style the resource links a bit different than the documentation landing page. 

Implement:
- [x] 1. Left side with new list of headings, links and documentation button
- [x] 2. Revised content
- [x] 3. Form on the right side

Link guide:
- [x] "apply to ICGC DACO" links to: https://icgc.org/daco
- [x]  "applying for access to controlled data" links to https://docs.icgc-argo.org/docs/data-access
- [x] "How to download data" links to https://docs.icgc-argo.org/docs/data-download
- [x] "Troubleshooting data download" - page to be created

- [x] Submitting data "Get started" links to: https://docs.icgc-argo.org/docs/submission-overview
- [x] "register samples" links to: https://docs.icgc-argo.org/docs/registering-samples
- [x] "submit clinical data" links to: https://docs.icgc-argo.org/docs/submitting-clinical-data
- [x] "submit molecular data" links to: https://docs.icgc-argo.org/docs/submitting-molecular-data

- [x] More Documentation button links to: https://docs.icgc-argo.org/

Zeplin: https://zpl.io/anLYpPk
![Contact v2](https://user-images.githubusercontent.com/18424138/76893529-e23db500-6862-11ea-802a-c876a2394d0c.png)

**Note from Minh:** This page can be accessed at the `/contact`. Run `npm run dev` for local development

**Comment by kcullion** [comment]
@P-Saha some css updates so user can see more of the form on a smaller screen.

- [ ] footer does not need to be fixed to the bottom of the screen. It's ok if the user has to scroll down to see the footer (like the other pages such as privacy page)
- [ ] The form shouldn't be vertically centering on the page. have a fixed gap beween the top of the form and the header - and an equal gap on the left side for the content
- [ ] right align the send message button so it lines up with the right side of the form
- [ ] reduce space between the message box and the captcha 

<img width="1213" alt="Screen Shot 2020-03-23 at 4 54 17 PM" src="https://user-images.githubusercontent.com/18424138/77362411-40690d00-6d27-11ea-8a8c-571e7794e88f.png">

**Comment by kcullion** [comment]
@P-Saha the new subjects for the form dropdown are: 

Applying for Access to Controlled Data through DACO
Data Download
Data Submission
Data or Analysis Inquiry
Media or Collaboration Inquiry
Publication Inquiry
Other

**Comment by kcullion** [comment]
@P-Saha can you change "Data or Analysis Query" in the dropdown to "Data or Analysis Inquiry" to be consistent with the service desk topics.

@rosibaj this looks good to me on my laptop. Can you check your screen size?

**Comment by rosibaj** [comment]
lgtm thanks @P-Saha @kcullion !
