### ISSUE TITLE
Gateway Integration of registration endpoints 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#379]
The gateway needs to accept registration files. 

The clinical endpoints can be found here: 
https://github.com/icgc-argo/argo-clinical/blob/master/src/app.ts

@blabadi will have postman example in `argo-qa` environment.

**Comment by alekspejovic** [comment]
- Make sure that you interpret the error messages correctly according to these rules :

https://wiki.oicr.on.ca/display/icgcargotech/Clinical+Submission+Validation+Errors

**Comment by joneubank** [comment]
https://github.com/icgc-argo/platform-api/pull/7

**Comment by rosibaj** [comment]
will be merged today!
