### ISSUE TITLE
Convert Ego Secrets to Vault

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#381]
- Secrets for ego need to be added to Vault 
- add spring cloud dependency; needs to be integrated with the clinical secret grabbing
- orchestrate how to manage the secrets in vault for a java client

**Comment by andricDu** [comment]
@rosibaj currently blocked due to Vault not recovering from Kubernetes upgrade.

**Comment by andricDu** [comment]
No longer blocked as vault has been brought back online.

**Comment by andricDu** [comment]
Ego in overture is using vault. For ARGO the secret have been loaded into vault and Ego will be made to use them after the demo this week.
