### ISSUE TITLE
Access Token card Data Hookup

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#394]
- [x] Blank state
Zeplin: https://zpl.io/2v0e4Lr
<img width="700" alt="Screen Shot 2019-08-01 at 11 40 06 AM" src="https://user-images.githubusercontent.com/18424138/62307192-281f4780-b451-11e9-84a9-b0b4e395ae99.png">

- [x] Active state
Zeplin: https://zpl.io/VOdPJ0Y
<img width="703" alt="Screen Shot 2019-08-01 at 11 41 03 AM" src="https://user-images.githubusercontent.com/18424138/62307261-46854300-b451-11e9-9077-6b128d9ae339.png">

- [ ] Expired state
Zeplin: https://zpl.io/VQRBJl4
<img width="712" alt="Screen Shot 2019-08-01 at 11 44 40 AM" src="https://user-images.githubusercontent.com/18424138/62307545-cad7c600-b451-11e9-9b9c-19ef9aed1804.png">

- [x] Copied state. The button fades back to the active state after 5 seconds (and the Copied! label disappears)
Zeplin: https://zpl.io/blLEgB0
![Screen Shot 2019-08-01 at 2 44 19 PM](https://user-images.githubusercontent.com/18424138/62319188-6cb7dc80-b46b-11e9-9edc-f381f871d822.png)

- [x] Connect the gateway calls to the Access Token card (specs in wiki for behaviour)
https://wiki.oicr.on.ca/display/icgcargotech/User+Profile+and+Token+Manager#UserProfileandTokenManager-2.2AccessToken

**Comment by alekspejovic** [comment]
- In the case there is an error , use the expired state.

**Comment by rosibaj** [comment]
@ciaranschutte This is looking really good!! A couple small things:

- [ ] 1) You did the disabled state a bit different than the mockup, but we like this better!! Can you just remove the background "Generate a token" text so that the disabled state looks like this:
![image](https://user-images.githubusercontent.com/15824252/65064087-a5ddda80-d94d-11e9-8987-1b92373757a5.png)
- [ ] 2) When i copy the token, for some reason the height of the whole box increases just a bit, then jumps back to the smaller height: https://drive.google.com/file/d/1AAbs9MUQuwgTOhUYwWI4iSJBIKQb6IXE/view 
On animation, can you make sure the height of the box stays the same to prevent this jump?
- [ ] 3) When the card gets smaller, it gets a _bit_  jumbled 
![image](https://user-images.githubusercontent.com/15824252/65064448-79768e00-d94e-11e9-840e-714691d3aef3.png)
To prevent this, please cut off the UUID of the API-key instead of trying to wrap it.  Users can always click the copy button to access the API-key on small screens.
-

**Comment by rosibaj** [comment]
@ciaranschutte Changes look great!!!! Thank you!!
