### ISSUE TITLE
UI Component Library: Table Action bar

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#42]
The table action bar can contain multiple elements - based on the content of the table
- [ ] Result Count
- [ ] Search box

**No pagination:**
![Screen Shot 2019-06-06 at 11 29 24 AM](https://user-images.githubusercontent.com/18424138/59045626-68e25200-884e-11e9-930d-ad38375049ab.png)
- [ ] Just result count (# Results) 

**Pagination:**
![Screen Shot 2019-06-06 at 11 29 29 AM](https://user-images.githubusercontent.com/18424138/59045639-71d32380-884e-11e9-9074-ed40d5afbdc0.png)
- [ ] Row count based of the # of results per table "page" (eg. 1-20 of 100)

**Bulk actions:**
![Screen Shot 2019-06-06 at 11 29 37 AM](https://user-images.githubusercontent.com/18424138/59045657-7d264f00-884e-11e9-9576-4b7a056fa22c.png)

If the user can perform bulk actions on a select number of table rows, they will see bulk actions. If no rows are selected, they are disabled by default
- [ ] Bulk actions: icons with tooltip labels. Actions are specific to table

Zeplin:https://zpl.io/adzPEOR
See in page: https://zpl.io/aBRPxwA

**Related tickets:**
Table body: https://github.com/icgc-argo/argo-platform/issues/59
Table footer: https://github.com/icgc-argo/argo-platform/issues/60

**Comment by ciaranschutte** [comment]
@hlminh2000 I think you covered this ticket already?

**Comment by rosibaj** [comment]
Moving to backlog as we are not sure if needed - will be implemented in page context for now.

**Comment by rosibaj** [comment]
@kcullion do we still need this?

**Comment by kcullion** [comment]
@rosibaj maybe we can close it for now until we know what types of actions we need in the file repo/other complex tables.
