### ISSUE TITLE
Program management tab url dynamic update

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#428]
Currently the query string in url is not updating when the user is interacting with the tabs. We need to update the url client-side so it reflects user's visual state.

Implementation options:
1) built-in Next.js's Link component
2) explore react-router
3) simple side-effect using a url library (easiest)

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/63602489-8ee9d980-c595-11e9-8ee6-b9cec7e7027f.png)
![image](https://user-images.githubusercontent.com/15824252/63602500-94dfba80-c595-11e9-9e14-a75bc7d678db.png)

URL used: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/BC-POGP-CA/manage?tab=users
role: OICR Test User (Dcc)

Refresh does not fix

@hlminh2000 moving this one back to in progress as it is not working

**Comment by hlminh2000** [comment]
@rosibaj if there's no other issue can we close this ticket given we've found it to be a data issue? I think error handling should go on a different ticket :)

**Comment by rosibaj** [comment]
@hlminh2000 sure
