### ISSUE TITLE
Download Templates User Flow

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/platform-ui#442]
![image](https://user-images.githubusercontent.com/15824252/63964405-0374ba80-ca65-11e9-9527-624bb8661f3f.png)

As a data submitter, I need to download file templates, so that I can format my registration file accordingly.  The file templates will  be provided from argo-clinical needs to provide the latest version of the dictionary (which it receives from lecturn).

- [x] The file should download as a `TSV file` with the header row is populated with column headers for registration according to the latest version of the dictionary. 
-  [x] On click, downloads the file . 

Wiki page for more details: https://wiki.oicr.on.ca/display/icgcargotech/Sample+Registration

**Comment by rosibaj** [comment]
@d8660091 Thanks - tested and is working great!!!
