### ISSUE TITLE
User Flow - Upload for Registration File (Success or Error)

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/platform-ui#445]
- [x] click upload file button
- [x] send one file to gateway
- [x] get errors and return them on the UI based on error type 
If the upload is invalid, then 2 different kinds of error messages will show :

When file name is incorrect : https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d51d3f94718c6523501722c

Other errors :
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d42f044a80cee88548d210f
- [x] update the progress bar based on error or success
- [ ] If successful upload, then enable registration

Wiki page for detailed specs: https://wiki.oicr.on.ca/display/icgcargotech/Sample+Registration

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/platform-ui/issues/708

**Comment by rosibaj** [comment]
Upload works with errors and happy path so closing! Thanks @ciaranschutte !!!
