### ISSUE TITLE
Something went wrong error page

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#448]
## Steps to Reproduce
1. go to https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/WP-CPMP-US/manage?tab=users
1. see the page go blank

## Solutions
We need an error page for handling unknown client-side error to replace `"An error occurred on client"`

* The 500 page would (and should) only handle server-side issues so ideally we want a different design.
* To help with debugging, this should have a slot for showing error message.
* The header and main nav should still be visible.
* This page should be very rarely seen.

**Comment by kcullion** [comment]
@d8660091 here is the mockup for the error page:
https://zpl.io/a39qr9y

**Comment by d8660091** [comment]
@kcullion Got it. Thank you!

**Comment by kcullion** [comment]
@d8660091 can you use the typography components here - and the correct semantics. 
So 
<h1>Oops!</h1>
<h2>Something went wrong</h2>
<p>We are working on fixing the…</p>

**Comment by d8660091** [comment]
@kcullion will do
