### ISSUE TITLE
Static UI -  the  progress bar (upload/register) component

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/platform-ui#464]
- [x] Must include all the state changes, but not data tie ins
- [x] Storybook

Zeplin :
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d42f03051da1e88f6fd12a2

**Comment by ciaranschutte** [comment]
Suggestions:
- success color #00c79d change to #24dbb4 for consistency
- use our standard style of 'caption' with font-size: 11px, rather than font-size: 10px

**Comment by ciaranschutte** [comment]
@alekspejovic I went ahead with the above suggestions. They are small enough that we can quickly change if need be.

**Comment by rosibaj** [comment]
@ciaranschutte sounds good to me!

**Comment by rosibaj** [comment]
lgtm thanks @ciaranschutte
