### ISSUE TITLE
Static Ui - The instructions bar 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/platform-ui#465]
- [ ] Storybook
- [ ] Modelt he different states (Register Samples is only active in certain state)

**Comment by hlminh2000** [comment]
preview: https://deploy-preview-487--argo-ui-storybook.netlify.com/?path=/story/components-pages-submission-system-program-sample-registration-instructions--basic
note: the box will be part of the page layout

**Comment by rosibaj** [comment]
lgtm!  Thanks @hlminh2000 @ciaranschutte
