### ISSUE TITLE
No error when inputing an  invalid email into the "Add Users" box

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/platform-ui#482]
## Description
A user can be added with an incorrect email format. A toast pops up that the user was succesfully added, but they do not show up in the list of users. The email is "sent" in Mailhog:
![image.png](https://images.zenhubusercontent.com/5c92ad88777e5f767e488112/2b8c7832-d508-401f-963a-11258afe34c2)

## Expected Behavior
On the Add Users form, add a front end validation that requires an <text>@<text>.<domain> format.
![image](https://user-images.githubusercontent.com/15824252/63892801-76732800-c9b6-11e9-8782-8c82986ccad6.png)

**Comment by rosibaj** [comment]
use yup

**Comment by kcullion** [comment]
looks great @ciaranschutte
