### ISSUE TITLE
Maintenance page updates: copy and new illustration

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#541]
Please make the following changes to the maintenance static page:
Zeplin: https://zpl.io/blMklW5

- [ ] Implement copy "We'll be back up and running as quickly as possible. We appreciate your patience."
- [ ] Implement new illustration (see zeplin)

**Comment by kcullion** [comment]
@d8660091 can you use the typography components here - and the correct semantics.
So
[h1]Be Back Soon[/h1]
[h2]Down for Maintenance[/h2]
[p]We'll be back up and running…[/p]

**Comment by kcullion** [comment]
@ciaranschutte @hlminh2000 @d8660091 
Let's discuss how to continue implementing the typography component consistently.
https://argo-ui-storybook.netlify.com/?path=/story/uikit-typography--list

I see some of the styles are coming through on this page however we should always implement proper html semantics (headlines and paragraphs) and have them inherit the styles from this storybook component

Please fix:
- [ ] paragraphs (both should be p) - so they are inheriting the line-height from storybook
- [ ] put more space in between the headlines and the paragraphs 
- [ ] The same goes for all basic pages - like 404, 401, error, contact us, etc
![Screen Shot 2019-09-13 at 10 26 41 AM](https://user-images.githubusercontent.com/18424138/64870998-61330600-d612-11e9-8336-9482f7034d08.png)

**Comment by akachru-github** [comment]
Moving to DK12 as this has been reopened.
