### ISSUE TITLE
Issue with dropdown being hidden behind card

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#544]
At the bottom of a card, the dropdown is hidden behind the card.  I cannot select options from the dropdown. 

https://drive.google.com/file/d/1uUoRh1dlFsRuNqUwJh9-h-rvNIMHpZbn/view

## Expected Behavior
I can use the dropdown even at the bottom of the card.

**Comment by kcullion** [comment]
@d8660091 
Please mimic the behaviour from https://dcc.icgc.org/search
So the dropdown opens below the select box, but vertically centered on the selected item. 

So in ICGC dcc eg, if user goes from 10 to 25:
![Screen Shot 2019-09-09 at 3.09.16 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/a4815a2b-2cbd-43a4-934d-dfd9d1370d0e)

Then from 25 to 50:
![Screen Shot 2019-09-09 at 3.09.21 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/2b1cbde1-ce5c-48e4-b50f-5b00527d0c74)

**Comment by hlminh2000** [comment]
re-openned issue to address at base `Container` component.

**Comment by rosibaj** [comment]
tested and is working again so cloing
