### ISSUE TITLE
Performance Issue Observed in UI

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#561]
Performance: interactions that are slow:

- [ ] In all cases, if a page takes a while to load - we should see a blank page with the dna loader to show the user that something is happening
- [ ] 1. Click on `Submission`,  it takes a few seconds to display the main all program panel. 
- [ ] 2. Click on `All Programs` on the left side bar, it takes 5 seconds to display all programs. This is also slow when clicking the "All Programs" link from the User Profile page
![Screen Shot 2019-09-10 at 9 32 13 AM](https://user-images.githubusercontent.com/18424138/64618245-e36ec080-d3ad-11e9-94b2-405538ca3087.png)
- [ ] 3. Click on `Manage Programs` - the user table takes a while to load each time - should cache
- [ ] 4. `Logging in` - takes a while for the ddc admin main page to load (could be related to # 2 and  https://github.com/icgc-argo/platform-ui/issues/559. Basically any link that links back to this all programs page is slow. eg. when creating a program - canceling the form.

**Comment by kcullion** [comment]
The tables are still taking too long to load

- [ ] All Programs
- [ ] Program users

**Comment by akachru-github** [comment]
Moving to DK-12. This is now carryover.

**Comment by d8660091** [comment]
@andricDu @KevinFHartmann @rtisma @Buwujiu I suggest to add an user_program table in the program-service. This table stores the user's first name, last name, role and its corresponding program. When an user accept an invitation, besides updating ego, we add a row to this table. The same goes for removing an user. What do you think?
