### ISSUE TITLE
Sidebar: DCC Admin remember where the user clicks in the list

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#562]
When DCC Admin chooses a program at the bottom of the sidebar list, then chooses "Dashboard" - the page refreshes and that program is at the bottom of the list again.

- [x] Can that spot in the sidebar menu remain fixed so that DCC doesn't have to keep finding it in the sidebar to make a new sub-selection. (Similar to what happens when you click on a new program name, it just opens the program sections and remains fixed).

- [x] when a user uses the searchbox filter in the sidebar - and they make their program page selection, please keep this search term in the searchbox + the sidebar filtered on this term. They can use the "x" to remove the term and unfilter the sidebar

**Comment by d8660091** [comment]
I suggest not to do the scrolling remembering. There are two reasons. First, it's technically tricky to do so, the feature could be unstable even if I managed to do that. Second, it won't work well when the menu list changes between navigation. For example, when a user click all programs, and the previous opened menu is closed.

**Comment by rosibaj** [comment]
Tested - both points are working well.  Navigating through pages, i am able to keep my search terms and project context making it much easier to navigate!

**Comment by rosibaj** [comment]
@d8660091 this looks great!!! Thanks so much!!!

**Comment by kcullion** [comment]
looks great!
