### ISSUE TITLE
MOBILE UI Component Library: Main Navigation Bar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#57]
All of the states for the main navigation bar elements on a small screen:

- [ ] Logged out - with login button: https://zpl.io/2EgDB9n
- [ ] Logged out - with hamburger menu open (switches to close icon): https://zpl.io/VYpXj3J
- [ ] Logged in - default: (login button switches to initials icon, which is the user menu button): https://zpl.io/V0gpdKE
- [ ] Logged in - with hamburger menu open (switches to close icon): https://zpl.io/a3j9Nml
- [ ] Logged in - with user menu open (switches to close icon): https://zpl.io/VYvrJ3w
- [ ] Dropdown item - default: https://zpl.io/VYvrJ3w
- [ ] Dropdown item - active: https://zpl.io/VYvrJ3w

Relates to: https://github.com/icgc-argo/argo-platform/issues/36

Logged out: get login button and public menu (hamburger)
<img width="730" alt="Screen Shot 2020-06-23 at 12 49 50 PM" src="https://user-images.githubusercontent.com/18424138/85431825-11de1680-b550-11ea-820b-85d35e021098.png">

Logged in: get the public menu and user menu
<img width="1110" alt="Screen Shot 2020-06-23 at 12 49 38 PM" src="https://user-images.githubusercontent.com/18424138/85431817-0f7bbc80-b550-11ea-8edf-af12c1ea91df.png">

**Comment by ciaranschutte** [comment]
@kcullion What color should the hover be for the mobile menu items? The standard one is very hard to read because it's on white background. What do you think?

![hover](https://user-images.githubusercontent.com/1486054/88098689-2d950680-cb68-11ea-9021-1c737588cf02.png)

**Comment by kcullion** [comment]
@ciaranschutte ...let's use: #0774d3 
(So same as active state font-colour but no background colour change)

**Comment by rosibaj** [comment]
lgtm thanks @wajiha-oicr !
