### ISSUE TITLE
🐛 Create a Program Form error messages bugs

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#570]
I noticed the following when creating a program:

- [ ] Do we need this error?
![Screen Shot 2019-09-10 at 9 36 22 AM](https://user-images.githubusercontent.com/18424138/64618899-24b3a000-d3af-11e9-94a3-3895e8fed97d.png)
Because when I fix my name and add an uppercase letter as the first letter, I get the next error. I think this second error would be enough the first time
![Screen Shot 2019-09-10 at 9 36 38 AM](https://user-images.githubusercontent.com/18424138/64618938-3bf28d80-d3af-11e9-9ea3-11d87c186f54.png)

- [ ] When I didn't specify processing regions I get this error, which is not human readable. It should be the "Please fill in the Processing Regions" right?
![Screen Shot 2019-09-10 at 9 38 01 AM](https://user-images.githubusercontent.com/18424138/64618972-49a81300-d3af-11e9-9820-54b1aa735bdd.png)
 
- [ ] When I don't put in a commitment level I get this error, which is not human readable. It should be "Please fill in Commitment level"
![Screen Shot 2019-09-10 at 9 38 28 AM](https://user-images.githubusercontent.com/18424138/64619053-6f351c80-d3af-11e9-93a1-f53d2f448c7b.png)

- [x] When I correct all of my errors, even specify processing regions, the processing regions error didn't disappear - but the create button was enabled. When I click create I get an error:
![Screen Shot 2019-09-10 at 9 38 59 AM](https://user-images.githubusercontent.com/18424138/64619178-a0155180-d3af-11e9-8b59-777e8639dfe3.png)

**Comment by rosibaj** [comment]
will be covered in #662
