### ISSUE TITLE
🐛 Join program brings user to a blank page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#572]
Expected Behaviour:
When user gets an invitation email, fills in user information, clicks on join now button, user should be redirected to program page showing he or she is now a joined user.

Actual Behaviour:
When user gets an invitation email, fills in user information, clicks on join now button, pages goes blank.
![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/630e1b9f-e4bf-47c6-9af9-ea4e78e164aa)

Steps to reproduce:
1. Go to program page, click on `ADD USER`, provide a valid email address, click send.
2. Go to mailhog, open the invitation, fill in the form, click on `join now`.
3. page goes blank.

**Comment by andricDu** [comment]
I cannot reproduce this in dev. Also I can't see in the code how this would happen without an error toaster.

**Comment by andricDu** [comment]
The correct Ego version was not deployed to QA and as such the request to update the ego JWT was returning a 404. Ego 2.6.0 was deploy and it resolved the reported issue.

However, the code here: https://github.com/icgc-argo/platform-ui/blob/develop/components/pages/submission-system/join/index.js#L56 is wrong and was the true reason for why the page went blank and locked up the browser. The promise does not handle the error and therefore is not handled by the catch. 

Issue has been created: https://github.com/icgc-argo/platform-ui/issues/599
