### ISSUE TITLE
🐛 All Programs page: Typo

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#581]
Fix the spelling of "Membership" (it's Memebership)
<img width="217" alt="Screen Shot 2019-09-12 at 10 47 21 AM" src="https://user-images.githubusercontent.com/18424138/64798549-316ff980-d551-11e9-8230-9793394f3522.png">

**Comment by Buwujiu** [comment]
Tested in QA, works as expected, closing the ticket.
