### ISSUE TITLE
Typography title fix

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#582]
Related to this ticket: https://github.com/icgc-argo/platform-ui/issues/337
I just found one case where the typography didn't get updated to the new style - as it's not using the typography component. 

When you are in any program section - the title (breadcrumb) should be 26px, not 30px.
![Screen Shot 2019-09-12 at 9 50 17 AM](https://user-images.githubusercontent.com/18424138/64805844-fb864180-d55f-11e9-8540-2358c388db24.png)

**Comment by d8660091** [comment]
@kcullion Do we need to change
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5cb87f892069be0a3e1f10bd
 as well?

**Comment by kcullion** [comment]
Yes @d8660091, sorry I haven't updated that mockup in a while, so there are some things that have changed. I'll try to update it at some point with the new font sizes
