### ISSUE TITLE
🐛 Users table - actions column tooltip blocking button actions

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#584]
Step to reproduce:
1. choose a program with only one user, example: ALEKS3-CA, click on manage program, go to users tab
2. move cursor to `Actions` column, notice how cursor's tooltip blocks button actions

Expected behaviour:
when there is only one row under users tab, action buttons should be clickable. The tooltip should always be displayed above or below the mouse cursor so the item is clickable

Actual behaviour:
when there is only one row under users tab, actions buttons are not clickable.
![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/cfe77464-48ca-4e2a-a05c-7ef9a0b6fe84)

**Comment by rosibaj** [comment]
Tested - the tooltip now show correctly to the left of the users mouse and actions are clickable.  thanks for the fix @hlminh2000 !
