### ISSUE TITLE
Edit Program Profile: feedback when saving changes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#585]
When making updates to the program profile information there is no feedback to tell the user that the updates were saved

**Expected behaviour:**

- [x] Show a toast that confirms the profile changes have been saved

Title: Success!
Content: Your changes have been saved.

**Comment by rosibaj** [comment]
@d8660091 Can you please a period at the end of the sentence?
![image](https://user-images.githubusercontent.com/15824252/66083048-83e17c00-e539-11e9-9a61-aead4384f6e7.png)

**Comment by rosibaj** [comment]
@d8660091 moving back to in progress until we get ^ fixed!

**Comment by rosibaj** [comment]
fixed - thanks @d8660091 !
