### ISSUE TITLE
UI Component: Table: top-align the content

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#592]
- [ ] Top align the content in the row to improve readability (not vertically centered, so align-items:normal)
![Screen Shot 2019-09-13 at 10 05 20 AM](https://user-images.githubusercontent.com/18424138/64868824-17e0b780-d60e-11e9-9090-2d0edd19b0e2.png)

- [ ] When a row spans just one line (so all items have only one data element in the row) - vertically center the data in the row (align-items:center). Otherwise, the actions column will determine the height of the row because the icons are tall, and the other content will look like there's more bottom padding than top.

So the table will be like:
![Screen Shot 2019-09-17 at 11 30 38 AM](https://user-images.githubusercontent.com/18424138/65056412-cbafb300-d93e-11e9-9f89-ebc400706d84.png)

**Comment by rosibaj** [comment]
lgtm thanks @wajiha-oicr !!!
