### ISSUE TITLE
🐛 Create a Program Bug: Multiselects for Countries, Cancer types and primary sites

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#593]
For the form fields:Countries, Cancer Types, Primary Sites, the user should not be able to create their own value, but just select from the dropdown of options.

- [x] Right now I can type any value, press enter and it's added to the text field. I shouldn't be able to do that.
- [x] In this case too, the form is submittable because technically those fields aren't blank - but the program isn't successfully created. There is no indication of this. The form component should not allow this to happen in the first place
![Screen Shot 2019-09-13 at 11 15 02 AM](https://user-images.githubusercontent.com/18424138/64874049-4c597100-d618-11e9-9aa6-0204dc2b8555.png)

This is related to the Multiselect component (without allowNew checked off)

**Comment by rosibaj** [comment]
lgtm - i cannot get the tags from typing in random text anymore.  Thanks @d8660091 !!
