### ISSUE TITLE
Join the Program User flow: change to a wizard

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#594]
Please implement this flow instead of taking the user to the login page from the join email:
https://wiki.oicr.on.ca/display/icgcargotech/User+Registration#UserRegistration-2.1InvitationUIflow

1. User gets the email and clicks the "Join the Program" button.
2. User is taken to the Join the Program Wizard. This is different than the regular landing/login page. (URL: https://platform-ui.qa.argo.cancercollaboratory.org/join/<invitation_id>)
-- This page SHOULD NEVER have a logged in user.  This flow should force the user log in. 
-- Zeplin: https://zpl.io/2jW1Zem

Based on the status of this invitation there are different paths:

- [ ] 1 ) **Happy Path**: If the invitation is `PENDING`, then: 
-- show the pending state wizard page: https://zpl.io/2jW1Zem
-- When the user clicks "Login with Google", the Google login page is displayed in a popup on top of the wizard: https://zpl.io/2G1xn7J
-- A) If the user selects the right email address (the one connected to the invitation), they are taken to step 2 to fill out basic details:https://zpl.io/aRXymM0
-- After filling out the join form, they click "Join Now" and are directed to the program dashboard with a success banner:https://zpl.io/amWgDlm
-- B.) If the user selects the wrong email address (one that is NOT connected to the invitation), they are taken step 1 with an error displayed and are asked to try again with the correct email:https://zpl.io/aM1Md8N

- [ ] 2) **Happy-ish Path**:  If the invitation is `ACCEPTED`, then: 
-- show the accepted-state` wizard page with a warning: https://zpl.io/2ZXp0yl 
-- The wizard steps are greyed out in this case
-- When the user clicks Login, then they are taken to Google login popup.
-- if the user logs in, then they are taken to the expected redirect for their user type

- [ ] 3) **Sad Path**: 
IF the invitation is `EXPIRED` or `REVOKED` or `INVALID`, then: 
-- Show the `invalid-invitation` wizard page with error: https://zpl.io/aBZg190
-- The wizard steps are greyed out in this case
-- The user will need to contact their program admin to get a new invitation

## **Technical notes**:
- The `/join/<invitation-id>` page looks like the user is logged out (whether they are logged in/out when they arrive there.
- We need  to add an  endpoint to the that queries the status of an invitation.  The endpoint 
-- should take an `invitation_id`
-- return the `program-id` AND  status of an invitation (one of `PENDING`, `ACCEPTED`, `EXPIRED`, `REVOKED`, or `INVALID`. 
-- be open (no authorization required)

COVERED IN https://github.com/icgc-argo/program-service/issues/254
- We need  to add  a second endpoint to check if the logged in user matches the invite’s intended recipient

- Register a 2nd ego application for the login page 

- The current retrieve invite/join flow in program service is fine; we will keep the auth as is as private details are only returned once the user has logged in.

**Comment by christinayung** [comment]
I definitely find A confusing.  Instead of taking them to the general login page, could we take them to a different login page for users who are about to join the program?

**Comment by kcullion** [comment]
@christinayung I agree! I can design this different login page once confirmed with @joneubank and @rosibaj that this is doable :)

**Comment by kcullion** [comment]
@rosibaj @joneubank I updated this ticket to outline the flow we talked about yesterday. Please review and break up into other tickets if needed.

**Comment by rosibaj** [comment]
duplicate ticket of https://github.com/icgc-argo/platform-ui/issues/246

**Comment by rosibaj** [comment]
There was an open question about how best to implement this flow.  There are three options: 
1. Register two ego apps
2. Add a state url parameter to the ego login link, set the state parameter when redirect back to the frontend
3. Update Ego with redirect URI logic

After discussion in person, the best solution for ego long-term is to add the ability to define multiple redirect URIs.  We need to differentiate between domains and redirect URIs resulting in a change to the current `login` endpoints/flows.

-  We don't have time to do this implementation in Ego right now with ARGO priorities
- We will build technical specs for multiple multiple redirect URIs
- We will incorporate this into the Ego roadmap
- As its a breaking change, we will need to address that. 
- Once completed, we will adjust the ARGO implementation

For this ticket implementation for ARGO, the team decided:
- do not pursue changes to ego that we will have to overwrite with redirect URI implementation
-  we will **add second Ego Application** for the 2nd login redirect as the simplest implementation 
- we recognize that we will have to register three applications (one for each environment) for ARGO for now.  we are ok with this.

**Comment by rosibaj** [comment]
Tested on qa - Not working.  When i click the invite i get this: 
![image](https://user-images.githubusercontent.com/15824252/67602101-ecd8a000-f743-11e9-8aa4-de2a109d2fd9.png)

**Comment by rosibaj** [comment]
@d8660091  I tested again this morning - The email works, but i am still seeing these issues:
- [ ] 1)  ![image](https://user-images.githubusercontent.com/15824252/67680537-cee88680-f961-11e9-9951-d1ec2df4c836.png)
- [ ] 2) When i have seleted the wrong email address it should stay selected on step one, and there should also be a login button for me to retry.
![image](https://user-images.githubusercontent.com/15824252/67680705-25ee5b80-f962-11e9-8a6d-ea1b56cc3bcb.png)
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d9e262175a912308b80abd0
- [ ] 3) When there are errors on the input, the height enamically adjusts to fit the newly added content, causing some weird bumps as I type.  Can we please set a single height for the card that prevents these content bumps?
https://drive.google.com/file/d/13Z8Ug_anQKYP867sI4cQlAQzzUNBluEc/view
 - [ ] 4) I get a weird redirect that my invitation has expired before refirecting to the dashboard.  This should not happen. 
https://drive.google.com/file/d/1V07_ktCwoPh_hX95QhHyIGJA4psFIL-i/view 
- [ ] 5) Can we please update the text on Step 2 of the invitation to this:
![image](https://user-images.githubusercontent.com/15824252/67681225-45d24f00-f963-11e9-93e0-85eb440d3612.png)
- [ ] 6) Please correct the punctuation in these places:
![image](https://user-images.githubusercontent.com/15824252/67681112-0c99df00-f963-11e9-8766-880549e68db9.png)

**Comment by rosibaj** [comment]
One issues still: 
- [ ] 
![image](https://user-images.githubusercontent.com/15824252/67708763-15a2a480-f993-11e9-8940-73ccdeff6e12.png)

**Comment by rosibaj** [comment]
@d8660091 were you able to address this issue ^?
