### ISSUE TITLE
🐛 Add a User form: button enabling and spacing

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#595]
- [ ] Disable the diableing
- [ ] Please remove the space below the form:
![Screen Shot 2019-09-13 at 11 43 25 AM](https://user-images.githubusercontent.com/18424138/64875765-b9223a80-d61b-11e9-9999-0a278c94a5cd.png)

**Comment by rosibaj** [comment]
lgtm.  thanks @d8660091
