### ISSUE TITLE
Create Program with same Program Name toast needs text update

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#606]
To reproduce,
1. Find an existing program, and copy its Program Name.  eg. Mutographs Study (from MUT-FR).
2. Create a new program with Program Name: Mutographs Study, Short Name: TEST1-CA
3. Fill in the rest of the form, and click SAVE
4. Toaster comes up saying "something went wrong:
![image](https://user-images.githubusercontent.com/15824252/67691637-51c70c80-f975-11e9-85d7-0f628c46dcd8.png)
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/BC-POGP-CA/manage?tab=profile
5. Check list on the left panel.  TEST1-CA is not created

## Expected behavior: 
A error message saying that 
> Program Not Created
>  A program with the same Program Short Name already exists.  Please choose a new Program Short Name.

**Comment by rosibaj** [comment]
lgtm! Thank you @d8660091
