### ISSUE TITLE
Footer links have disappeared in the "Submission" sections

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#611]
Footer links aren't appearing in the submission pages but are on things like the profile/token page and login page.

This is the correct footer: 
![Screen Shot 2019-09-17 at 9 43 56 AM](https://user-images.githubusercontent.com/18424138/65047211-0c540000-d930-11e9-93fc-1b70fcf80f84.png)

Submission pages are showing this:
![image](https://user-images.githubusercontent.com/15824252/65056851-a3748400-d93f-11e9-984a-37520d436913.png)

- [x] Make sure the correct footer component is being used in all submission pages. 
- [x] In footer, link the contact link to the /contact page

**Comment by rosibaj** [comment]
lgtm thanks @d8660091
