### ISSUE TITLE
Sample Registration Static UI updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#613]
Make the following changes to the sample reg static:

- [x] Change the "New" star colour from green to purple. Zeplin: https://zpl.io/VDW9Woq

- [x] font sizes. the instructions and table legend/file info should be using the "data" font type (12px).

- [x] cut the file name off after 40 characters and append a "..." so the file info doesn't have to wrap onto two lines

- [x] minimize the space between the legend on the left and the file info on the right to 50px; in case the file info does need to wrap on very small screens. 

![Screen Shot 2019-09-25 at 11 17 14 AM](https://user-images.githubusercontent.com/18424138/65614676-0c827a00-df86-11e9-9ecd-ed499d7a3446.png)

- [x] Button with icon: this should have the same left and right padding as the button without icon (UI Component Library change):
![Screen Shot 2019-09-25 at 4 18 45 PM](https://user-images.githubusercontent.com/18424138/65636377-2afd6b00-dfb0-11e9-80c4-d4ebf0042feb.png)

**Comment by rosibaj** [comment]
tested! lgtm!
