### ISSUE TITLE
Audit form validation messages 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#615]
In the spirit of standardizing our error message delivery, create a matrix of our validation types and form of the message. No code delivery here.

From atuls comment:
@joneubank , @kcullion , does setting aside 30 mins this week to chat about this make sense?

**Comment by kcullion** [comment]
Sure @rosibaj, I can chat whenever

**Comment by rosibaj** [comment]
After discussion, we decided on this format for  messages: 
1. <field name> is a required field.
2. Please enter a valid email address.
3. Please enter a valid url.
4. <field name> must be greater than <value>.
5. <field name> must be less than <value>.
6. <field name> must be in between <value> and <value>.
7. <field name> must be at least <value> characters. 

It was also noted that the order of validations used matters - the required field validation should be the first validation 100% of the time for all required fields. 

Work will be tracked in #662
