### ISSUE TITLE
Change API-key expiry to 30 days 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#617]
Currently the API-key duration is set to 365 days. 

Please change this to 30 days. 

edit the config!

**Comment by blabadi** [comment]
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/a6caac93-0449-4fe6-baa0-438c0a54177c)

**Comment by blabadi** [comment]
this is not a vault change, we should avoid using vault for non secret configs since it's harder to keep track of who and what changed there vs using the argo-infra helm values that are tracked.

anyway ready for QA !

**Comment by rosibaj** [comment]
@blabadi noted - we discused that it was a vault config in planning.  i will change the description.

**Comment by kcullion** [comment]
Do we also have to change the frontend?
![Screen Shot 2019-11-20 at 10 12 05 AM](https://user-images.githubusercontent.com/18424138/69250748-420aa480-0b7e-11ea-90a8-39698283b3f7.png)

**Comment by rosibaj** [comment]
@kcullion if you regenerate your token, what does it say?

**Comment by kcullion** [comment]
@rosibaj it says 30:) ooops
