### ISSUE TITLE
Remove pagination on Program >> Manage>>Users tab

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#621]
The users table was supposed to be an infinite scroll table. 

There should be no pagination. 

![image](https://user-images.githubusercontent.com/15824252/65169078-d12afd00-da13-11e9-98e2-25628c437209.png)

**Comment by d8660091** [comment]
React Table doesn't support infinity scroll

**Comment by rosibaj** [comment]
@d8660091 
1) there shouldn't be that many users so this table definitely doesn't need pagination
2) The registration/clinical tables in the cards appear to scroll fine - perhaps we can just do what was done there?

 @hlminh2000 For infinite scrolling ( for later when there may be more rows) do you any ideas?

**Comment by d8660091** [comment]
One of the issues of infinite scrolling is that users will never see the footer

**Comment by rosibaj** [comment]
@d8660091 that sounds good!

**Comment by kcullion** [comment]
@d8660091 @rosibaj should we have that scrollbar worked into the table component? So that it goes to the bottom of the page and then gets a scrollbar?  Like on the programs page - the full page is scrollable - not the table

**Comment by rosibaj** [comment]
lgtm thanks @d8660091 !
