### ISSUE TITLE
Adjust tool tip in Manage Program

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#626]
- [ ] Adjust tooltip location there's only 1 administrator in the program.  Tool tip is currently covering the icon making it hard to click "edit user" and "remove user".  

![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/ab0bd530-e5fc-44fd-ad8d-6d6435f37705)

**Comment by rosibaj** [comment]
This has been fixed in DK Sprint 12 - Minh adjusted the tooltip location so that it appears to the left, no longer blocking the images. 

Closing as this is resolved.
