### ISSUE TITLE
Need better error reporting in Join Program

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#627]
* Join program was sent to abc@gmail.com
* But after clicking "Join Program", I logged in with def@gmail.com
* Error in the toaster was GraphQL error: 7 PERMISSION_DENIED.
- [ ] This error needs to be more explicit: "Please login with the Gmail or Gsuite account where you received the invitation to join the Program"
- [ ] The toaster disappeared too quickly.  Make it stay till it's dismissed. 

![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/672392e4-0f63-43dc-9200-71309ec19909)

**Comment by rosibaj** [comment]
Closing this as a new join program flow was implemented that should cover this scenario.
