### ISSUE TITLE
Program must have at least 1 administrator

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#628]
To ensure there is at least 1 administrator in a program
- [ ] On Manage Program, "Remove user" next to the only administrator should be disabled
- [ ] When editing the role of the only Administrator, the drop down for Data Submitter & Collaborator should be disabled
- [ ] Also should not be allowed to removed remove self

We decided to fix this from the front-end:
- [ ] disable the delete icon and have a tooltip on hover saying "A program must have at least one Program Administrator". 
- [ ] Disable the delete icon on a users own row.

These text instructions can also be in the edit form to explain why we won't give them the ability to change the user role.

**Comment by rosibaj** [comment]
Discussion in grooming - user the light solution to edit the UI to prevent this
- ensure at least 1 admin 
- don't remove yourself

**Comment by kcullion** [comment]
@rosibaj from a UI point of view - maybe we can disable the delete icon and have a tooltip on hover saying "A program must have at least one Program Administrator"

**Comment by wajiha-oicr** [comment]
@joneubank @hlminh2000 do either of you know if it's possible to add some unique identifier from [this query?](https://github.com/icgc-argo/platform-ui/blob/develop/components/pages/submission-system/program-management/PROGRAM_QUERY.gql ). 

If a user shouldn't be able to remove themselves, then what would be a reliable way of checking if the logged in user is the same as the one from the list of users? 

I figure I could match against the email from the current logged in user, but I'm wondering if that's sufficient enough. Thoughts?

**Comment by joneubank** [comment]
@wajiha-oicr email is a valid unique identifier for users in Argo. The best would be the user ID (`sub` field in JWT) but that isn't made available through the gateway/ProgramService.

SO: use email. That works.

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr email is a valid unique identifier for users in Argo. The best would be the user ID (`sub` field in JWT) but that isn't made available through the gateway/ProgramService.
> 
> SO: use email. That works.

Makes sense! Thanks Jon!

**Comment by kcullion** [comment]
@christinayung I had a look and this looks good in QA. Can you give one final test to see if it's what you wanted: https://github.com/icgc-argo/platform-ui/issues/628

**Comment by christinayung** [comment]
Tested.  Good to go

**Comment by kcullion** [comment]
tested in production, looks good to me

**Comment by rosibaj** [comment]
lgtm in prod!
