### ISSUE TITLE
Show "Program Admin" instead of "Program Member"

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#630]
I'm logged in as Program Administrator.  I would like to see that role in the top right corner. 

![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/2657d94f-6f1f-4efe-86cf-ef281bb50bb7)

**Comment by rosibaj** [comment]
Discussed on slack:

What role to we choose/when to show/ the logic to switch it around  when a user is a member of more than one program could be quite complex. 

We will not change this at this time!.
