### ISSUE TITLE
Create Program with existing Short Name appears successful

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#631]
To reproduce:
1. Create program with using Program Name: testing123, and an existing Short Name, eg. MUT-FR
2. Fill out the rest of the form, and click SAVE
3. Toaster says Program testing123 is successfully created.
4. Find MUT-FR on the left panel, and click Manage Program, go to Profile tab.  Data is from the first creation, not from the current creation.

Expected behavior: An error message saying that a program with the same Short Name already exists.

**Comment by rosibaj** [comment]
Resolved in https://github.com/icgc-argo/platform-ui/issues/606
