### ISSUE TITLE
Firefox doesn't prompt me to choose which gmail profile to login

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#632]
When using Chrome to login, I get prompted to choose from a list of goggle accounts: 
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/0774a4b8-8ffe-4ac6-a162-e03f6e0a9abe)

But with Firefox, I don't get this prompt and get automatically logged in with the same google account previously used.  So I don't get the option to switch between different user roles.

**Comment by rosibaj** [comment]
https://stackoverflow.com/questions/37711665/forcing-a-user-to-choose-an-account-via-google-oauth2 

https://stackoverflow.com/questions/14384354/force-google-account-chooser 
It appears that there are  some variables that can be applied to prompt the user to select acount types. 

@joneubank @andricDu Would this be applied at the ego level, or is it something that can be configured in any ego deployment?

**Comment by rosibaj** [comment]
Tested on Chrome and Firefox Windows 10

When i am signed into a single gmail, i am still prompted to login with another account! 

Thanks for the quick fix @andricDu!!!!
