### ISSUE TITLE
Join Program - Fix Institute names that overrun to next line

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#634]
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/e0caec63-5ea6-4976-bf4b-cb6f943a94b5)

- [ ] The longer values are wrapping to a second line and covering the next value

- [ ] The dropdown is being cut off at the bottom, so I can't see the 'New" item for the multi-select 

## Expected Behaviour

Let's wrap the values if they need to be on two lines, but the next value should appear below that wrapped value
 
![Screen Shot 2019-09-26 at 1 32 07 PM](https://user-images.githubusercontent.com/18424138/65711031-15487e00-e062-11e9-8a8e-21426accd429.png)

**Comment by rosibaj** [comment]
@kcullion Should we expand the size of this box a bit to help?  We can also just cut the institution off instead of wrapping to a second line.

**Comment by kcullion** [comment]
@rosibaj I think the width of the dropdown can be determined by the longest value (without having the values wrap to the next line). So it's okay if the dropdown extends outside of the form container - either width or height-wise. I've revised the ticket description to explain this

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/66082837-0584da00-e539-11e9-8570-5018f807005b.png)

Dropdown is hidden behind card.

**Comment by rosibaj** [comment]
@d8660091 moving back to in progress until we can get the dropdown un-hidden behind the card.

**Comment by rosibaj** [comment]
lgtm! Thanks @hlminh2000 and @d8660091!!
