### ISSUE TITLE
No Data Found: only show this state when there is no data returned

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#636]
- [x] On All Programs page, the "No data found" message and graphic shows up while the data is loading. This state should only be shown if there is no data returned in a table or a card
![Screen Shot 2019-09-19 at 10 08 02 AM](https://user-images.githubusercontent.com/18424138/65252011-3fc89300-dac6-11e9-94e3-8b3f55307aad.png)

- [x] This happens on the Manage Programs page when the users are loading. 
Expected behaviour: show dna loader, return data. (If no data returned, show no data found state
- [x] This also happens on the Registration pages - it should be the same there as well.

**Comment by rosibaj** [comment]
@d8660091 looks great! I have not been able to get this to happen so looks like its working great! Thank you!
