### ISSUE TITLE
Empty States: style updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#637]
Please make the following updates to the style of the messaging for the empty states

**Registration Empty state:**
- [x] Font colour should be color: #525767
- [x] Add a bit more spacing in between the lines (approx margin-bottom:10px on the top line)
- [x] Semantically, should these be "p" or "span" elements instead of divs?

![Screen Shot 2019-09-19 at 11 08 45 AM](https://user-images.githubusercontent.com/18424138/65256795-20cdff00-dace-11e9-877c-8ee23636cdd6.png)

**No Data Found state:**
- [x] Double check that the font is  color: #525767 (difficult to tell as it flashes on screen)
- [x] For consistency, change from "No Data Found" to "No data found."
mock:
![Screen Shot 2019-09-19 at 11 15 16 AM](https://user-images.githubusercontent.com/18424138/65257321-0ea09080-dacf-11e9-8929-9fd8ed731316.png)

**Comment by rosibaj** [comment]
maybe make a no data component for this

**Comment by rosibaj** [comment]
tested - font + display looks great.
