### ISSUE TITLE
Cannot user search bar in Firefox 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#646]
![image](https://user-images.githubusercontent.com/15824252/65437310-90efc400-ddf1-11e9-9cb0-890da3fd42f7.png)

## Expected Behaviour 
Searchbox on the submission area program list should work the same way it does in Chrome.

**Comment by d8660091** [comment]
cannot reproduce on firefox 69

**Comment by rosibaj** [comment]
@d8660091 im and i are able to reproduce
![image](https://user-images.githubusercontent.com/15824252/65441071-c4355180-ddf7-11e9-8dab-684c7d860612.png)

**Comment by d8660091** [comment]
Is there any error in the console?

**Comment by akachru-github** [comment]
Just FYI @d8660091 , this is for the next sprint, not the current one!

**Comment by d8660091** [comment]
My all two issues are blocked.

**Comment by rosibaj** [comment]
tested - i can now use the search box in firefox, on Windows.  lgtm. 

Thanks @d8660091 !!!

**Comment by rosibaj** [comment]
@d8660091 sorry i noticed one thing so reopening:

![image](https://user-images.githubusercontent.com/15824252/66431246-a405b500-e9e9-11e9-8177-081c8b8cae96.png)

When i type in text in firefox, the (x) button gets weirdly shifted

**Comment by d8660091** [comment]
@rosibaj I saw that one, I thought we could make a separate ticket for this.

**Comment by rosibaj** [comment]
ah ok @d8660091  - I will make another ticket for next sprint then :) 

https://github.com/icgc-argo/platform-ui/issues/738
