### ISSUE TITLE
User Flow - Upload for Clinical File(s)  (Success or Error) 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#652]
- [x] On click should open file browser, with option to select multiple files from computer and upload.
Note: The uploader should only accept TSV files.  Other file types should not be available in the selector as options.
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d8a1bc3f425c1029fdb62a0 
- [x] If the upload is cancelled, the box should close and the UI state does not change.  
- [x] If the upload is selected, then the the upload is completed. Errors/success should be presented based on the file types in the respective areas. 
1. Happy path when all files can upload: https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d81191b820762784af56395

1. Saddest Path: Everything is wrong  
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d8a638f46a638025cb4db5e

**Comment by hlminh2000** [comment]
points about clinical error has been moved to https://github.com/icgc-argo/platform-ui/issues/746 for better PR separation :)

**Comment by rosibaj** [comment]
@hlminh2000 There are a few UI issues noted in the Google doc, but overall the Upload is working and errors _are_ going to the correct tabs/notifications so i am going to close this ticket. 

Looking amazing :)
