### ISSUE TITLE
Unify Form messages 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#662]
1. [field name] is a required field.
1. Please enter a valid email address.
1. Please enter a valid url.
1. [field name] must be greater than [value].
1. [field name] must be less than [value].
1. [field name] must be in between [value] and [value].
1. [field name] must be at least [value] characters. 

In the platform-ui, these are the exact places that need to be adjusted (apart from unifying the text in the error messages): 
1. On the `Create a Program form`, the required error should always show first.
1. On the `Create a Program form`, remove the errors like this: `Cancer Types field must have at least 1 item`. and `Processing Regions field must have at least 1 item`. - that will be taken care of by the required error
1. On the `Join the program` form, the required message shows two different types, once just "this is a required field" then after pressing join now, they change to "field name is a required field" - these just need to be in the format of #1 above
![Screen Shot 2019-09-25 at 11 22 50 AM](https://user-images.githubusercontent.com/18424138/65615210-f9bc7500-df86-11e9-8bb6-567e2dc75ad2.png)
![Screen Shot 2019-09-25 at 11 22 37 AM](https://user-images.githubusercontent.com/18424138/65615266-1193f900-df87-11e9-82c7-db7aaa981bea.png)

**Comment by joneubank** [comment]
Probably not an issue, but we can't do `#6-between number values` out of the box. instead, we can use less than and more than in combination, so the message shown will be one of those at a time.

**Comment by kcullion** [comment]
Ok thanks @joneubank. Do you mean the message would be more like 
[field name] must be less than [value] and greater than [value].

**Comment by rosibaj** [comment]
@joneubank okay - i dont think we have any of those atm, but ill change the wiki specs for further implementations to reflect that.

**Comment by joneubank** [comment]
let say we have a field that has to be between 10 and 20. if they put `0` we would say `[field name] must be greater than 9` and if they put 50 we would say `[field name] must be less than 21`

These are the messages for `moreThan` and `lessThan` validations... we could also introduce `min` and `max` which for the above would read `[field name] must be at least 10` or `[field name] must be at most 20`

**Comment by kcullion** [comment]
I think that sounds good @joneubank (the first paragraph)

**Comment by rosibaj** [comment]
Tested on QA - Required messages are appearing firs ton all forms and the other validation messages are appearing as expected.  thanks @joneubank!!!
