### ISSUE TITLE
Misaligned headers in table

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#664]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/13b4f3d8-1ebb-40d5-97c2-108e55d9e567)

![image](https://user-images.githubusercontent.com/15824252/65611800-51f07880-df81-11e9-9d85-bf89284f1d2a.png)

## System Details
Chrome 
Version 76.0.3809.132 (Official Build) (64-bit) 
Windows 10

**Comment by ciaranschutte** [comment]
having trouble reproducing this: https://drive.google.com/file/d/18PnGHl3N1YHvIqvV6cMkBQfj8rpiZzUC/view

@rosibaj any steps to replicate? 
moving col headers?
specific resize of the browser?
navigating from a specific page?

**Comment by rosibaj** [comment]
Was able to reproduce on Browserstack - Windows 10 + latest chrome 
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/TEST-CA/sample-registration 

This is the exact page with the issue

**Comment by ciaranschutte** [comment]
happens due to overflow scrollbars

you can force scrollbar on .rt.th header and hide it in webkit setting the scrollbar color but this doesn't work for FF :(

**Comment by d8660091** [comment]
@rosibaj The most elegant way to do scrolling is to make the page scroll, instead of make the react-table scroll. Could we do that?

**Comment by rosibaj** [comment]
@d8660091 maybe you could show @kcullion and I an example before we decide?

**Comment by rosibaj** [comment]
@d8660091 This is starting to look good, but I'm noticing a few things that I think we need to talk about. For example:

- [ ] ![image](https://user-images.githubusercontent.com/15824252/66946880-df266a80-f01f-11e9-91a1-6e021e39efc2.png)
- [ ] ![image](https://user-images.githubusercontent.com/15824252/66947227-84414300-f020-11e9-98de-5dddcc5777c0.png) 

I scheduled a meeting for Friday so @kcullion and I can show some examples of table navigation to discuss as part of this!
