### ISSUE TITLE
Copy button misaligned

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/platform-ui#671]
In Chrome, at 75% zoom, the Copy button on the Profile page is misaligned.
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/58214fec-2ed2-475c-a305-c2c2d87def75)

**Comment by thesanjeevsharma** [comment]
Hello, Can I take this issue?

**Comment by rosibaj** [comment]
@thesanjeevsharma you can try this.  Ask  @hlminh2000 if you have issues :)

**Comment by rosibaj** [comment]
Happens for me at 110%
![image](https://user-images.githubusercontent.com/15824252/73404677-11529400-42c0-11ea-8fdb-c5fa0c4052c4.png)

**Comment by rosibaj** [comment]
this issue is no loger obsrved 
Windows - Chrome Version 88.0.4324.104 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/15824252/107567888-46244700-6bb4-11eb-83a2-7a0a989ca4af.png)
