### ISSUE TITLE
Sidebar+Footer layout changes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#687]
To make the sidebar look better - we have extended it to the bottom of the browser, which makes the collapsible panel look smoother: https://github.com/icgc-argo/platform-ui/issues/278

zeplin: https://zpl.io/awOeOLg

Please make the following changes:
- [x] extend the sidebar to the bottom of the browser
- [x] move the footer so it is below the content area
- [x] remove the drop shadow on the footer and add the grey border instead:  border-bottom: 1px solid rgb(220, 221, 225);
- [x] right align the footer links beside the OICR logo

![Screen Shot 2019-09-27 at 4 04 27 PM](https://user-images.githubusercontent.com/18424138/65798792-8f4f3480-e140-11e9-8015-77da49fa1c04.png)

**Comment by rosibaj** [comment]
note: #278 contains the collapse changed(the << seen in the bottom left)

**Comment by rosibaj** [comment]
@ciaranschutte Looks amazing!!!!! thanks so much!
