### ISSUE TITLE
🐛 Sidebar not updating after Create Program success

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/platform-ui#689]
## Describe the bug
After Create Program completes successfully, side bar does not update to include the new program. Navigating to all programs, success Toast,  and Program table are all working correctly.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to Create Program form http://localhost:8080/submission/program/create
2. Complete form without errors and submit
3. wait for page to navigate to all programs table
4. Observer the left hand sidebar menu does not update to include the new program

## Expected behaviour
The left hand sidebar should be updated with the current list of programs, including the one just created.

**Comment by rosibaj** [comment]
tested- able to successfully see teh newly created program in the left sidebar after creation.
