### ISSUE TITLE
Card height should be dynamic based on page size

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#706]
- specifically for registration & clinical pages
- if the table is longer than the page height, then the card should be the height of the table
![image](https://user-images.githubusercontent.com/15824252/66078879-e5e9b380-e530-11e9-9857-1757d57ac5e2.png)

**Comment by rosibaj** [comment]
- [ ] Windows 10 Machine, Chrome Version 77.0.3865.90 (Official Build) (64-bit) 
![image](https://user-images.githubusercontent.com/15824252/66398806-72222d80-e9ac-11e9-8009-221779af3ad0.png)

- [ ] @kcullion Mac has a few issues with the dynamic display:

**Comment by kcullion** [comment]
- [ ] The padding all around the content area should be equal, no matter what height or width the screen is.
![argo-content-padding](https://user-images.githubusercontent.com/18424138/66400046-be6e6d00-e9ae-11e9-9eb2-8c97d170c26b.jpg)
