### ISSUE TITLE
Registration section style fixes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#735]
- [x] the "File preview" title should be an h2 using the "subtitle2" typography style
- [x] Error table - there is a transparent bottom border on the table rows, so it appears to be pink like the background. Please use the same styles as the table component (so border-bottom:none;)
![Screen Shot 2019-10-08 at 1 04 34 PM](https://user-images.githubusercontent.com/18424138/66416651-46af3b00-e9cc-11e9-9e15-7216320624ea.png)

- [x] Just make this use the black text and semibold the details that are dynamic
![Screen Shot 2019-10-10 at 4 29 37 PM](https://user-images.githubusercontent.com/18424138/66603941-2d002600-eb7b-11e9-95b5-aaef695b9ee6.png)

see zeplin: https://zpl.io/VDW9Woq

**Comment by rosibaj** [comment]
@ciaranschutte LGTM!  the weird table optical illusion with the borders looks much better now! 
thank you!!
