### ISSUE TITLE
Join a Program Email: updates

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#742]
Please make the following changes to the join a program email:

- [x] Add the sentence about the expiry date/time. This should be dynamic: expires 5 business days after the invitation is sent

- [x] Please change the copy for the paragraph after the expiry date "Joining a program means you will have permission to access...". Correct copy is in zeplin: https://zpl.io/Vqv9gLm

- [x] Make "The ICGC ARGO Platform" a link to the platform, within the salutation 

![Screen Shot 2019-10-09 at 2 10 30 PM](https://user-images.githubusercontent.com/18424138/66508643-8430c880-ea9f-11e9-88f1-4bf7ea6a8ef3.png)

**Comment by rosibaj** [comment]
lgtm!  Thanks @d8660091 !!!
