### ISSUE TITLE
Mult-select Component: Style changes for when values wrap

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#743]
To make the wrapping values appear as one item, please make the following style changes for the values 
- [ ] Within the dropdown, use the "Data" typography style (font-size: 12px; line-height:16px)
(note: we do have a line-height ticket still to be done: https://github.com/icgc-argo/platform-ui/issues/619
- [ ] Increase the spacing between the values (padding-top and bottom: 10px)

See zeplin: https://zpl.io/adzPEOR

![Screen Shot 2019-10-09 at 4 29 57 PM](https://user-images.githubusercontent.com/18424138/66517951-1346dc00-eab2-11e9-911b-4ea024c91e91.png)

**Comment by rosibaj** [comment]
lgtm thanks @d8660091 !!!
