### ISSUE TITLE
📝 Update readme with dev commands

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#768]
Provide updated list of commonly used commands and description for each in the "Setup / Dev commands" section in readme.

## Detailed Description
Commands of interest:
- `npm run dev`: starts local dev server. (remove the reference to the custom server as we no longer have one.
- `npm run build`
- `npm run storybook`
- `npm run build-storybook`

**Comment by pruthvigh** [comment]
Hi, I can work on this.
