### ISSUE TITLE
User Flow: Sidebar Status Icons

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#779]
Register sample sidebar status icons isn't implemented
- [x] No registration in Progress
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d42efceffd0028848d676ca
- [ ] File failed to upload OR errors in file
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d51d3f94718c6523501722c
- [x] In progress (successful upload) 
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d42f03051da1e88f6fd12a2
~ Commit registration animation~
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d8113bdd3d60b4f4517f981
- [x] After registration completed, it cycles back to no icon
https://app.zeplin.io/project/5a69fad2bde6330a929157fd/screen/5d42f07c3e1b3088fc230ed7

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj the commit registration icon is messy to do just for the second it will be on screen. after talking with @hlminh2000 we think it might be best to leave it out

**Comment by ciaranschutte** [comment]
@hlminh2000 to show the error icon on invalid file there's some refactoring to do it right.
currently if there is an invalid file our api returns a `ClinicalRegistrationInvalid` type with the error.

I think we should just add this to the `clinicalRegistrationData`
we can then simplify the api logic and the side menu status will work just from reading the cache.

**Comment by kcullion** [comment]
@ciaranschutte do you mean the checkmark green icon? If so, that's fine

**Comment by ciaranschutte** [comment]
@kcullion yes - cool cool :)

**Comment by hlminh2000** [comment]
ok :) thanks @ciaranschutte! Adding `ClinicalRegistrationInvalid` to `clinicalRegistrationData` makes sense to me, that'd be consistent with submission as well and simplifies a lot of things.

**Comment by rosibaj** [comment]
@hlminh2000 @ciaranschutte sounds good- lets check with @joneubank re comments on changes

**Comment by rosibaj** [comment]
Error state moved tohttps://github.com/icgc-argo/platform-ui/issues/853

**Comment by rosibaj** [comment]
@ciaranschutte looks amazing!
