### ISSUE TITLE
Program Member Sidebar: should have My Programs item (uncollapsable)

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#788]
When logged in as a program member, the sidebar looks like this:
![Screen Shot 2019-10-23 at 9 42 18 AM](https://user-images.githubusercontent.com/18424138/67399070-ad5e5800-f579-11e9-8205-5956fcb328bc.png)

But I should see the My Programs item with icon, as the icon will stay when the sidebar is collapsable. This "My Programs" item doesn't need to be collapsable like with the DCC account, as the user wouldn't need to close this item
![Screen Shot 2019-10-23 at 9 45 43 AM](https://user-images.githubusercontent.com/18424138/67399321-0ded9500-f57a-11e9-91ca-3aae93c855e8.png)

Also, users of role `Collaborater` should not have access to see the `Register Samples` or `Submit clinical data` pages in the left side bar. 

![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/fc3db0bc-b15a-4975-b2bb-880277e1a1d8)
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/1df3d872-a269-4df3-8e68-1067e9124ee1)

**Comment by ciaranschutte** [comment]
Fixed collapsible here https://github.com/icgc-argo/platform-ui/pull/863 not deployed yet (Wed 5.30)

**Comment by rosibaj** [comment]
@ciaranschutte understand about #863 - otherwise this looks great so i will close. 

Thank you so much!!!!

**Comment by kcullion** [comment]
@rosibaj if the collaborator just sees the dashboard, should we hide the entire sidebar for them?

**Comment by rosibaj** [comment]
recording - discussed in planning.  we will not change this as its not urgent right now.
