### ISSUE TITLE
Clinical Submission: Tab to load after uploading files

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#790]
Different cases when uploading clinical files:

- [ ] When a user uploads 1 clinical file - open the corresponding tab with that file loaded

When a user uploads more than one clinical file at a time
- [ ] a. if there are one or more files with errors, load the first tab in the list that contains errors
- [ ] b. if there are no files with errors, load the first tab in the list for the corresponding uploaded files

**Comment by rosibaj** [comment]
@hlminh2000 this looks great! thank you!
