### ISSUE TITLE
Add reopen button for Data Submitters

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#794]
- [x] Add "Reopen Submission" button for data submitters & program admins: https://zpl.io/VK6R0ZR

- [x] Implement a reopen confirmation modal: https://zpl.io/29znpQB
![Screen Shot 2019-10-24 at 2 55 47 PM](https://user-images.githubusercontent.com/18424138/67516279-64d49680-f66e-11e9-8823-e724a3c652cb.png)

**Comment by hlminh2000** [comment]
this has been addressed as part of https://github.com/icgc-argo/platform-ui/issues/719

**Comment by rosibaj** [comment]
@hlminh2000
- [ ]  Can you please style the button as the link style for non-dcc members: 
![image](https://user-images.githubusercontent.com/15824252/68144959-b862a200-ff02-11e9-92df-862b4c5c806b.png)

**Comment by rosibaj** [comment]
looks great! thanks @hlminh2000 !!
