### ISSUE TITLE
Table Overflow Issues

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#799]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/f927ca06-11aa-45fb-b5f0-d56b8b16752f)

-

**Comment by rosibaj** [comment]
- [ ] develop a technical plan to deal with the table 
-- either upgrade 
-- switch components
- [ ] timebox to 2 days

**Comment by hlminh2000** [comment]
Fixing overflow issue turned out to be not bad so I went ahead and did it in PR. 
If the solution is good, I think we can discuss exploring new table implementation separately (could be now as there's still time in sprint).

**Comment by rosibaj** [comment]
@hlminh2000 this looks good for now!
