### ISSUE TITLE
Persist Apollo client through navigation and remove prefetch

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#803]
This will fix navigation mysteriously freezing:

Sometimes when navigating with any of the links in the side bar, the page mysteriously freezes. This is because it is trying to fetch the program listing for the new page's side bar before it redirects, and that can sometimes take a while. Persisting the Apollo client and removing prefetch will prevent this from happening.

Things to do:
- Put Apollo client in react state.
- Remove the prefetching from the program pages.
- Refetch program after program update.

**Comment by rosibaj** [comment]
havent seen any weird freezes! thanks @hlminh2000 !
