### ISSUE TITLE
Join a Program fixes

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#837]
- [x] please make the picture have the same rounded corners as the white container

- [x] Can you make the following updates to step 2:
![Screen Shot 2019-10-31 at 3 24 22 PM](https://user-images.githubusercontent.com/18424138/67979400-8abfe500-fbf2-11e9-9ad8-b92a39376218.png)

- [x] the department field should not be required
![Screen Shot 2019-10-31 at 3 25 52 PM](https://user-images.githubusercontent.com/18424138/67979546-e38f7d80-fbf2-11e9-9b76-19aef8eb7afb.png)

- [x] this notification should be dismissible 
![Screen Shot 2019-10-31 at 3 30 06 PM](https://user-images.githubusercontent.com/18424138/67979777-57ca2100-fbf3-11e9-9575-70b7d703dadb.png)

- [x] Change title to "This invitation has already been accepted"
- [x] Put a period after "Please log in to access your program."
![Screen Shot 2019-10-31 at 3 30 50 PM](https://user-images.githubusercontent.com/18424138/67979915-a24b9d80-fbf3-11e9-9f12-c9cf95f257e6.png)

**Comment by rosibaj** [comment]
I cannot join a program without filling in  department:
![image](https://user-images.githubusercontent.com/15824252/68145400-b3eab900-ff03-11e9-8d49-0092166e6c25.png)

This is the errors:
```
{"errors":[{"message":"Variable \"$joinProgramInput\" got invalid value { piFirstName: \"R\", piLastName: \"B\", invitationId: \"1b101422-6627-4128-8094-b3d33b4723f5\", institute: \"Al Maather\" }; Field department of required type String! was not provided.","locations":[{"line":1,"column":32}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Variable \"$joinProgramInput\" got invalid value { piFirstName: \"R\", piLastName: \"B\", invitationId: \"1b101422-6627-4128-8094-b3d33b4723f5\", institute: \"Al Maather\" }; Field department of required type String! was not provided.","","GraphQL request:1:32","1 | mutation JOIN_PROGRAM_MUTATION($joinProgramInput: JoinProgramInput!) {","  |                                ^","2 |   joinProgram(join: $joinProgramInput) {","    at /usr/src/node_modules/graphql/execution/values.js:116:15","    at coerceInputValueImpl (/usr/src/node_modules/graphql/utilities/coerceInputValue.js:99:11)","    at coerceInputValueImpl (/usr/src/node_modules/graphql/utilities/coerceInputValue.js:54:14)","    at coerceInputValue (/usr/src/node_modules/graphql/utilities/coerceInputValue.js:37:10)","    at _loop (/usr/src/node_modules/graphql/execution/values.js:109:69)","    at coerceVariableValues (/usr/src/node_modules/graphql/execution/values.js:121:16)","    at getVariableValues (/usr/src/node_modules/graphql/execution/values.js:48:19)","    at buildExecutionContext (/usr/src/node_modules/graphql/execution/execute.js:184:61)","    at executeImpl (/usr/src/node_modules/graphql/execution/execute.js:89:20)","    at Object.execute (/usr/src/node_modules/graphql/execution/execute.js:64:35)"]}}}]}
```

@kcullion suggested department should not be required, so Xu removed the red star in the ui
but it actually is required as joining is successful after filling it in. 

Wee should make this required/not-required based on what program-service is requiring atm.

**Comment by rosibaj** [comment]
This is working correctly now.  Thanks @hlminh2000 !!!
