### ISSUE TITLE
GDPR Compliance message

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#839]
Build the Cookies message. 

See specs here: https://wiki.oicr.on.ca/display/icgcargotech/GDPR+Complicance

Design in Zeplin: https://zpl.io/VY1gvXe

When the user clicks the "OK" button - the messages closes (animation slide up)
Privacy Policy links to: /privacy

**Comment by rosibaj** [comment]
tested - messages appears on first load and after all local storage/cookies are cleared. 

lgtm.  thanks @hlminh2000 !
