### ISSUE TITLE
Fix failing selenium tests

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#871]
- E2E testing is not passing 
- Tests need to be updated.

## Exit Criteria
- Jenkins dashboard is visible to the team 
- Identify problems after https://github.com/icgc-argo/program-service/issues/267 
- Ticket any issues identified

**Comment by hlminh2000** [comment]
a couple tickets resulting from this:
- https://github.com/icgc-argo/e2e-test/issues/13: Firefox tests are not working (could be a bug in dependency - `geckodriver`)
- https://github.com/icgc-argo/e2e-test/issues/14: The test always fails at the last confirmation of joining programs, even though the program is created successfully. We may also want to improve the user experience there with a loader to give user feedback.
- https://github.com/icgc-argo/platform-ui/issues/904 (more of a UX improvement to joining program)

**Comment by rosibaj** [comment]
@hlminh2000 regarding `cleaning up dev data` - I thought the tests would have a step to set, run, and reset data to an appropriate data set from snapshots.

Is that not happening?

**Comment by hlminh2000** [comment]
The nightly test pipeline is, but there is dirty data inserted by day-to-day Dev work too, plus local test runs. If we could have a way to apply QA data to Dev that'd work best.

**Comment by rosibaj** [comment]
@hlminh2000 should we just reset dev data to qa regularly, say once a week with a pipeline to do that?

**Comment by hlminh2000** [comment]
I think that make sense, but would like to decide with the team :)
either way, I think we should have the ability to do that whether automated or with a manual trigger
