### ISSUE TITLE
Vertical Tabs: min-height

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#876]
The vertical tab needs a min-height so the arrow doesn't look strange when there is no badge in the tab:
![Screen Shot 2019-11-08 at 11 27 20 AM](https://user-images.githubusercontent.com/18424138/68493643-d4c05080-021a-11ea-9708-6297e596dc4c.png)

**Comment by rosibaj** [comment]
this looks to be fixed! Thanks @ciaranschutte !!
