### ISSUE TITLE
Data Submitter: show update diffs on submission validation

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#877]
It would be helpful to see the updated diff rows shaded when a data submitter validates a submission. 

So like this: https://zpl.io/boPqBQG - where they see the updated value(s)- but we don't need to reorder the rows for them in this case.  

![Screen Shot 2019-11-08 at 2 15 29 PM](https://user-images.githubusercontent.com/18424138/68504380-db5ac200-0232-11ea-9057-5cd6eaff957e.png)

**Comment by rosibaj** [comment]
@wajiha-oicr looks great!
