### ISSUE TITLE
🐛 Users cannot generate tokens 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#878]
## Describe the bug
User cannot generate tokens - when they click the button it spins forever.
## Steps To Reproduce

Steps to reproduce the behaviour:
1. Login as a user with USER role:
![image](https://user-images.githubusercontent.com/15824252/68509800-d3ede580-023f-11ea-8bdd-9c4a81ff3c8b.png)
2. Go to the user profile page and click "Generate" to generate a token
3. The button will spin forever. Checking the console you can see this error: 
```
{
	"errors": [{
		"message": "403",
		"locations": [],
		"path": ["generateAccessKey"],
		"extensions": {
			"code": "UNAUTHENTICATED",
			"exception": {
				"stacktrace": ["AuthenticationError: 403", "    at _callee$ (/usr/src/utils/restUtils.js:12:13)", "    at tryCatch (/usr/src/node_modules/regenerator-runtime/runtime.js:65:40)", "    at Generator.invoke [as _invoke] (/usr/src/node_modules/regenerator-runtime/runtime.js:303:22)", "    at Generator.prototype.<computed> [as next] (/usr/src/node_modules/regenerator-runtime/runtime.js:117:21)", "    at asyncGeneratorStep (/usr/src/utils/restUtils.js:10:103)", "    at _next (/usr/src/utils/restUtils.js:12:194)", "    at /usr/src/utils/restUtils.js:12:364", "    at new Promise (<anonymous>)", "    at /usr/src/utils/restUtils.js:12:97", "    at restErrorResponseHandler (/usr/src/utils/restUtils.js:5:38)"]
			}
		}
	}],
	"data": null,
	"extensions": {
		"tracing": {
			"version": 1,
			"startTime": "2019-11-08T19:33:17.662Z",
			"endTime": "2019-11-08T19:33:17.699Z",
			"duration": 37322622,
			"execution": {
				"resolvers": [{
					"path": ["generateAccessKey"],
					"parentType": "Mutation",
					"fieldName": "generateAccessKey",
					"returnType": "AccessKeyResp!",
					"startOffset": 478552,
					"duration": 36821159
				}]
			}
		}
	}
}
```
## Expected behaviour
1. If there is an issue/error, then a general error toast should appear. the box should NOT spin forever. 
1. Users should be able to view their own tokens.  
1. Users should be able to generate a token for themselves.
1. Users should not be able to view/generate other users tokens. 
## Possible Solutions
It looks like the issue is authorization - only people who are `Role = ADMIN` in ego can generate their tokens.

**Comment by andricDu** [comment]
@rosibaj @hlminh2000 I cannot seem to reproduce this issue.

Using a non admin user:
```
{
  "id": "REDACTED",
  "name": "REDACTED",
  "email": "REDACTED",
  "status": "APPROVED",
  "firstName": "Dusan",
  "lastName": "Andric",
  "createdAt": "2019-12-02T16:05:12.606+0000",
  "lastLogin": "2019-12-02T16:05:12.616+0000",
  "preferredLanguage": null,
  "type": "USER",
  "groups": []
}
```
I am able to generate a token as that user:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer REDACTED' 'http://localhost:8081/o/api_key?user_id=REDACTED&scopes=portal.READ'

{
  "apiKey": "REDACTED",
  "scope": [
    "portal.READ"
  ],
  "exp": 31536000,
  "description": null
}
```

**Comment by andricDu** [comment]
User JWT is passed as a Bearer Token to the API Key endpoint using the POST HTTP method.

**Comment by rosibaj** [comment]
@andricDu I can replicate right now with this user on qa: `argo.programad@gmail.com`
- they are  user in ARGO QA with one program admin access
- i do not see atoken on the ui and it is spinning constantly
![image](https://user-images.githubusercontent.com/15824252/69975427-319ae800-14f5-11ea-95ec-d36fc4a65282.png)
![image](https://user-images.githubusercontent.com/15824252/69975444-3b245000-14f5-11ea-80bb-36c7afc72af1.png)
- i changed them to admin
![image](https://user-images.githubusercontent.com/15824252/69975485-4c6d5c80-14f5-11ea-8439-e7eddc89178c.png)
![image](https://user-images.githubusercontent.com/15824252/69975518-5c853c00-14f5-11ea-92e6-44e61d70e3a3.png)

![image](https://user-images.githubusercontent.com/15824252/69975564-7292fc80-14f5-11ea-832e-521344934f2e.png)

**Comment by hlminh2000** [comment]
I can take a look from gateway

**Comment by hlminh2000** [comment]
hmm I can't reproduce this problem on neither `dev` nor `qa`, but locally I am seeing it. Could be a problem with specific accounts? (appears to be something wrong with newly created account, as my local setup is a fresh start)

**Comment by rosibaj** [comment]
@hlminh2000 ive seen this with Linda, Kim, and the test account i replicated it with above

**Comment by hlminh2000** [comment]
nvm, my personal accounts are set up as ego admin, hence it's working. 
Anyways, we found that the errors are thrown during token the reading step rather than the creation step, which is working as intended. We can change the token listing to not require an admin account in ego :)

**Comment by andricDu** [comment]
Turns out users can generate their own tokens, but cannot list them.

**Comment by rosibaj** [comment]
Tested - with the new deploy and list changes I can both see and generate tokens as a USER.  Thanks @andricDu !!!!
