### ISSUE TITLE
Program Table: pencil icon should link to edit program

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#889]
Currently these both link to program users.

The pencil should open the edit program tab
![Screen Shot 2019-11-13 at 4 51 23 PM](https://user-images.githubusercontent.com/18424138/68808770-6e7f6780-0638-11ea-9e56-9885f4740050.png)

**Comment by rosibaj** [comment]
tested looks amaizng! thanks @ciaranschutte !!!!!
