### ISSUE TITLE
User menu item: active state

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#892]
When the user is on the Profile & Token page, the user menu item should be in it's active state
![Screen Shot 2019-11-14 at 10 01 17 AM](https://user-images.githubusercontent.com/18424138/68868573-c6b07b00-06c5-11ea-87a6-97949bcc29af.png)

**Comment by rosibaj** [comment]
state is now correctly highlighted when on user profile page!  Thanks @hlminh2000 !

**Comment by hlminh2000** [comment]
it's @ciaranschutte's magic ;)

**Comment by rosibaj** [comment]
😱 You just look so much alike i confused you :p Thanks @ciaranschutte !!!
