### ISSUE TITLE
Register Samples section: buttons broken

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#895]
Sometimes this user dropdown does not appear when clicking on the user name. And the templates and upload files buttons don't work.

I notice it when I'm in the register Samples section of a program, that doesn't have a 
 registration in progress but has the ... in the sidebar
![Screen Shot 2019-11-14 at 5 04 01 PM](https://user-images.githubusercontent.com/18424138/68899946-c71a3780-0700-11ea-9832-099c340b7ff9.png)

**Comment by ciaranschutte** [comment]
@kcullion looks like stale data issue. can't recreate. clearing old data seemed to solve it.
