### ISSUE TITLE
Error message for submission workspace

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#903]
Currently when I validate my submission, in this case I only have errors in my files
![Screen Shot 2019-11-18 at 3 19 14 PM](https://user-images.githubusercontent.com/18424138/69090719-0b664a00-0a17-11ea-99bb-235ec8db28c8.png)

But the instructions say: _Your submission cannot yet be signed off and sent to DCC. Please correct the following errors and reupload the corresponding files._

I think we should make this more general in case the submission doesn't need to be sent to DCC.

**Change to:** 
Your submission cannot yet be signed off. Please correct the following errors and reupload the corresponding files.

**Comment by rosibaj** [comment]
looks great thanks @jaserud !!
