### ISSUE TITLE
Loading state in program join form

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-ui#904]
When we click on "Join Now" in the form, nothing is indicating that something is happening. Let's add a loading screen to indicate this.

## Detailed Description
- Our local testing feels much faster than when it is run from the test because we are always operating from within the network. (could be why https://github.com/icgc-argo/e2e-test/issues/14 is happening)
- In the wild, it is likely to look more like the test because of network latency. Hence we want a loading screen so the UI doesn't appear frozen.
- Having a loading screen also helps us narrow on what is happening when looking at e2e test recordings.
- **Requirements:** 
  + some loading state must be visible
  + form must be disabled

## Possible Implementation
- option 1: full-screen loading state (let's follow what was done in clinical submission page)
- option 2: Button loading state + disabled form fields

**Comment by rosibaj** [comment]
@hlminh2000 @anncatton is this still valid? is it still happening since we updated the login flow?
