### ISSUE TITLE
Add Script Based Error Validations to Dictionary 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#905]
A donor should not be able to be recorded as Alive and also have the other two fields (cause_of_death and survival_time) filled out
-- cause_of_death dependant on vital_status
This submission would go through:
![Screen Shot 2019-11-18 at 3 49 31 PM](https://user-images.githubusercontent.com/18424138/69092736-0a371c00-0a1b-11ea-89ff-b9d9657f84f4.png)

**Comment by rosibaj** [comment]
This should be a script based validation - It has not been written yet. adjusting ticket to reflect need for script based items

**Comment by rosibaj** [comment]
Closing this as all scripts have been captured in https://github.com/icgc-argo/argo-dictionary/issues/28
