### ISSUE TITLE
Toaster when a clinical submission is successful

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#907]
- [ ] Implement a toaster when a clinical submission has been successfully signed off (i.e. does not require update approval)

Zeplin: https://zpl.io/aRXpjYe

![Screen Shot 2019-11-18 at 4 16 33 PM](https://user-images.githubusercontent.com/18424138/69094658-ce9e5100-0a1e-11ea-8fb2-a84a151f4c4d.png)

For confirmation when signing off a submission, it is not the case that the clinical data will be queued for the next release (that depends on molecular data too) Please make the following changes:

- [x] Confirmation for sign off with updates, change description to: The DCC will be notified of the following updates to previously released data and your submission will be locked until approval.
https://zpl.io/2ZXNGXl

- [x] Confirmation for sign off without updates, change description to: The following clinical data will be submitted.

https://zpl.io/29n08ZY

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/platform-ui/issues/938 

issue identified to fix her e
