### ISSUE TITLE
Welcome message: the dismiss doesn't work

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#911]
The welcome message has an "x" to dismiss it from the dashboard, but it doesn't actually close the banner.

![Screen Shot 2019-11-19 at 9.47.41 AM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/b27389dc-48e7-4d91-892d-baebf903465c)

**Comment by rosibaj** [comment]
much dismiss - the x works now!  Thanks @ciaranschutte !!!
