### ISSUE TITLE
🐛 Mismatch index in error report for UI and tsv

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-ui#914]
## Describe the bug
Index in error reports doesn't match the one presented in UI. This occurs for both sample_registration and clinical submission

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to clinical submission for a program
2. Upload file with known validate errors
3. Click validate and look at error report table in UI
4. download error report and look at report in tsv

In UI:
![image](https://user-images.githubusercontent.com/34698315/69161082-9ba89b80-0ab8-11ea-91a6-de0df9eeeb18.png)

In TSV:
![image](https://user-images.githubusercontent.com/34698315/69161195-c266d200-0ab8-11ea-913a-846e1235d1fe.png)

## Expected behaviour
Indexes should probably be the same. I think we should also consider where we make index start from 1 (in UI or Gateway or Clinical). I think Gateway is probably the easiest...

- [ ] TSV line number will be presented in the UI. We should be able to jump from row number in the UI to the original TSV.
- [ ] Line 1 is reserved for the header. Numbering will start at 2.
- [ ] Change column header from "Row #" => "Line #"

**Comment by akachru-github** [comment]
- TSV line number will be presented in the UI. We should be able to jump from row number in the UI to the original TSV. 
- Line 1 is reserved for the header. Numbering will start at 2.
- Change column header from "Row #" => "Line #"

**Comment by rosibaj** [comment]
lgtm!  Thanks @hlminh2000 !!

**Comment by hlminh2000** [comment]
we are missing the index increment in the tsv file

**Comment by rosibaj** [comment]
ui error message, table, and downloaded error report all now align on the same reported number.  Thanks @hlminh2000 !
