### ISSUE TITLE
User table: hook up the DACO Approved column of the user table

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#919]
- [x] Change the heading of this table column to "DACO Approved"

- [ ] Hook up the column with DACO approval status
![Screen Shot 2019-11-20 at 10 08 11 AM](https://user-images.githubusercontent.com/18424138/69250477-b98c0400-0b7d-11ea-8c96-040d33cee999.png)

Technical back-end spec: Program service needs to provide this information from ego using its application API token. The gateway will read this from program service and provide to UI.

**Comment by hlminh2000** [comment]
Program service needs to provide this information from ego using its application API token. The gateway will read this from program service and provide to UI.

**Comment by rosibaj** [comment]
@anncatton can you please update the implementation details in the ticket above based on the recent DACO policy changes?

**Comment by rosibaj** [comment]
i can  see the yes appearing correcrlt now!

![image](https://user-images.githubusercontent.com/15824252/77206449-61362600-6acd-11ea-9d00-7e981085f264.png)


lgtm thanks @jaserud !

**Comment by jaserud** [comment]
Note: The back end changes for this ticket were released in program service 1.2.0 and gateway 1.6.4. These will need to deployed along with UI version 1.9.7 for this to work in other env.

**Comment by rosibaj** [comment]
verified on prod RAWR-CA program - lgtm.
