### ISSUE TITLE
Remove: Clear on clinical submission  validation errors 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#924]
-  [ ] Remove the clear on validation errors.
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/009afecf-9327-4374-8c49-5f460ab04cdb)

**Comment by akachru-github** [comment]
After discussion, decided to remove the clear altogether.

**Comment by rosibaj** [comment]
Clear is removed!  Thanks @ciaranschutte !!!
