### ISSUE TITLE
Bug or old data? Sometimes the "Joined on" column isn't filled out

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#925]
Sometimes the user is approved but the joined on date isn't filled out
<img width="1431" alt="Screen Shot 2019-11-21 at 10 11 29 AM" src="https://user-images.githubusercontent.com/18424138/69350429-8ada6000-0c47-11ea-8dad-0f0a8f57724b.png">

**Comment by rosibaj** [comment]
@jaserud This happens when you did join, but were added directly in ego-ui. 

I dont think there is anything we can do here?

**Comment by rosibaj** [comment]
@jaserud Can you just check the logic for how "Approved" shows as text and make sure Program Service is not recording approves without join dates?  if that is hte case, i think we can close this.

**Comment by jaserud** [comment]
As you said, the only way I was able able to get `Approved` and no `Joined On` date was if I added the user to the group via Ego-UI...

**Comment by rosibaj** [comment]
thanks for confirming @jaserud !
