### ISSUE TITLE
UI changes for dictionary updates: invalid submission

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#927]
When the data dictionary is updated, active submissions will be scanned and marked as OK against the new schema or NOT OK against the new schema(s)

**If a submission is marked NOT OK, then we need to**

1. Show this **Notification banner** at the top of all program sections (except clinical submission section). 
- Content link goes to the dictionary landing page, 
- "View" button links to the clinical submission section and 
- "Dismiss" closes the banner (which will return when the page is reloaded)
![Screen Shot 2019-11-26 at 3 33 51 PM](https://user-images.githubusercontent.com/18424138/69670572-33caf580-1062-11ea-9cb2-3a2c50c6c53f.png)

Zeplin: https://zpl.io/agB9RoO

2. In the **clinical submission section**, the submission progress bar is set to an upload error. 
![Screen Shot 2019-11-29 at 2 29 47 PM](https://user-images.githubusercontent.com/18424138/69887401-b814b700-12b4-11ea-9c6a-02e190816346.png)

The general submission message describes why there are now errors: 
![Screen Shot 2019-11-29 at 2 28 57 PM](https://user-images.githubusercontent.com/18424138/69887394-acc18b80-12b4-11ea-936d-5005d9b07fa2.png)

Each file that has dictionary errors will display the errors in the tab in the usual file error format:
![Screen Shot 2019-11-26 at 2 02 52 PM](https://user-images.githubusercontent.com/18424138/69664058-95389780-1055-11ea-9304-8aeb7980c3d1.png)

Zeplin: https://zpl.io/bzRy487

**Comment by rosibaj** [comment]
note: might need to update the enum in the gateway for submission state

**Comment by rosibaj** [comment]
@jaserud @hlminh2000 can we get this deployed for QA?
