### ISSUE TITLE
Logo update: lighter blue in the "O"

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#928]
The secretariat requested we make the "O" in the logo read more like an O by making the blue lighter. 

make sure there is an alt tag as well. 

![Screen Shot 2019-11-26 at 3 59 25 PM](https://user-images.githubusercontent.com/18424138/69672277-c4570500-1065-11ea-8e3c-a0f2022d43c8.png)

Please find the new logo in this zeplin mock: https://zpl.io/bzRy487

**Comment by rosibaj** [comment]
@jaserud I do not see this update on the ui 
1) did it get deployed?  or 2) do i need to clear my cache somehow?

**Comment by jaserud** [comment]
weird, I can see it in QA try refreshing with `Ctrl+Shift+R`

**Comment by rosibaj** [comment]
hmm today i can see it!! Thanks @jaserud - looks great!
