### ISSUE TITLE
Integrate Ego Redirect URI

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#940]
- [ ] Upgrade to latest Ego with redirect URI changes: https://github.com/overture-stack/ego/releases/tag/2.9.1 
- [ ] Make the correct changes to register the correct redirect patterns in the app:
1. When a user logs in and has NO program access, take them to the user page.
1. When a user logs in and has role `DCC Admin`, take them to the program list page. 
1. When a user logs in and has any program role, take them to the dashboard first program in their list.
1. When a user is joining, take them to the join form.
1. When a user inputs a url, gets redirected to a login page, and then successfully logins in, take them to the originally input url. 

From Minh: There are two main flows to the login:
**1. User intends to go to a specific path `e.g /user`.** 
2. User logs in from `/` without a specific target path.
**flow number 1** is currently using localStorage to remember the target path through the ego flow, and rely on the `/logged-in` page to redirect user after they are logged in. This should be removed and instead, passed to Ego as the `redirect_uri`

**Comment by rosibaj** [comment]
I got this on login:
![image](https://user-images.githubusercontent.com/15824252/75454978-57912680-5944-11ea-9d4f-05e4c44e0846.png)

**Comment by kcullion** [comment]
@anncatton and I tested this in prod and it seems all good! @rosibaj we will leave in production column for you to do a final test when you're back

**Comment by rosibaj** [comment]
@anncatton i have been testing this the past few days and so far it looks good to me!  I think you had said there was one one issue with the join flow, but it looked correct to me.  is there another ticket to link here?

**Comment by anncatton** [comment]
Found one issue with redirect: https://github.com/icgc-argo/roadmap/issues/314
