### ISSUE TITLE
Static UI: Empty State 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#944]
- [ ] Create the empty state of the program dashboard
- [ ] Make sure it is responsive now. Horizontal card at the top can stack numbers as it flows. 
![Screen Shot 2019-12-09 at 3 15 11 PM](https://user-images.githubusercontent.com/18424138/70469259-b908ce00-1a96-11ea-99f7-7bb737992d38.png)

Zeplin: https://zpl.io/a7xW3DM

**Comment by wajiha-oicr** [comment]
Hi! Could I get some clarification on the location of the hyperlinks? I see the links that say:
"get started with clinical data submission"
"get started with molecular data submission" **>>assuming this one takes you to the "submit clinical data" tab ?**

Thanks!
"get started with data submission"

**Comment by rosibaj** [comment]
@wajiha-oicr these will lead to the docs site - the deploy is currently in progress, so you can point those links to : https://platform-ui.qa.argo.cancercollaboratory.org/ for now; we will update these later in this ticket #271

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr these will lead to the docs site - the deploy is currently in progress, so you can point those links to : https://platform-ui.qa.argo.cancercollaboratory.org/ for now; we will update these later in this ticket #271

Ah okay! Thanks for clarifying :)

**Comment by rosibaj** [comment]
tested on argo-qa env - this looks great!! thanks @wajiha-oicr !!!
