### ISSUE TITLE
Connect Program Workspace Status Card

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#945]
- [x] Empty State: https://zpl.io/a7xW3DM
![Screen Shot 2019-12-09 at 3 15 54 PM](https://user-images.githubusercontent.com/18424138/70469421-fbcaa600-1a96-11ea-9d56-c4c824b48f29.png)

- [x] Full State(s) show the status of the Register Samples/Clinical workspace.  This is the same progress bar as in the register/clinical submission pages. 
Zeplin: https://zpl.io/V4dd110
![Screen Shot 2019-12-09 at 3 17 07 PM](https://user-images.githubusercontent.com/18424138/70469431-fff6c380-1a96-11ea-8a00-76d854add3ac.png)

- [x] @hlminh2000: We should refactor the existing progress components in `/registration` and `/submission` out for reuse here.

**Comment by kcullion** [comment]
@P-Saha can you just make it so if there's room in the card, those links (Sample Registration, Clinical Submission) would span one line? My design showed a version of the card that wasn't too wide. 

But on my big screen there's room for those links to be on one line:
[Uploading... Screen Shot 2020-01-17 at 2.59.50 PM.png ]

**Comment by rosibaj** [comment]
tested on QA lgtm! thanks @P-Saha !!
