### ISSUE TITLE
🐛 Two users appear in table in manage program

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-ui#946]
## Describe the bug
Editing user invitation makes two users in the table, while it is in pending invitation... Deleting one invite deletes both

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go through `Add User` flow inside `Manage Program`
![image](https://user-images.githubusercontent.com/34698315/70092992-7f931700-15ed-11ea-89b9-85334fc59e37.png)

2. We see the user is pending invitation
![image](https://user-images.githubusercontent.com/34698315/70093077-a5b8b700-15ed-11ea-9ac6-f90b2083b7dc.png)

3. Edit the invitation from `Collaborator` to `Administrator`
![image](https://user-images.githubusercontent.com/34698315/70093127-c41eb280-15ed-11ea-8cab-f7bd48fdf694.png)

4. Watch and wonder as user has two invites
![image](https://user-images.githubusercontent.com/34698315/70093180-e1ec1780-15ed-11ea-90e0-f401b4614601.png)

## Expected behaviour
- When a user has not accepted an invitation (status = pending or expired), then a new invitation should be issued to that user 
- "edit" user should functions exactly the same as "resend email" when a role is updated on an non-accepted invitation.

**Comment by jaserud** [comment]
After further investigation, it looks like this bug occurs if the user being edited already belongs to any group in EGO. The `edit_gql_mutation` is an [`updateUser`](https://github.com/icgc-argo/program-service/blob/develop/src/main/java/org/icgc/argo/program_service/services/ProgramServiceFacade.java#L176)  call in program service. This updates the `Groups` the user is a part of in EGO,  so they actually get added to the group and that causes two users to show up (one from the invite and one for the user who is now part of the group). Not sure if this is a check/fix to be done in `UI`, `gateway` or `program-service`

**Comment by rosibaj** [comment]
tested on qa 
- adding the same user/editing the same user works as expected
- deleting a user

lgtm!  thanks @jaserud !!!!
