### ISSUE TITLE
UI + gatweway changes for dictionary updates: locked program workspace

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#965]
When the data dictionary is being updated, active submissions will locked so that submissions do not continue while a migration is happening. 

## Data Information 

When the submission system is "locked", the submission configuration is set to  `true`, and the following updates should be visible on the submission areas. 

This can be checked for the whole submission system:
![image](https://user-images.githubusercontent.com/15824252/70472976-1fddb580-1a9e-11ea-9f95-cf1afdc8f0a0.png)

This is ready in clinical, but also needs to be updated in gateway. 
## User Flow 
1. **Dashboard**: Zeplin: https://zpl.io/2ZBBxrl
- [x] Show this Notification banner at the top of each program dashboard. Content link goes to the dictionary landing page
- [x] The "register samples" and "submit clinical data" sections in the sidebar will show the lock icon
- [x] The "Program workspace status" card will show both submissions are locked
![Screen Shot 2019-12-09 at 3 02 56 PM](https://user-images.githubusercontent.com/18424138/70468398-05eba500-1a95-11ea-98af-c680a8abdadd.png)

2. Register Samples: Zeplin: https://zpl.io/a7xxZ7Y
- [x] Show the notification banner at top
- [x] Registration progress bar is locked
- [ ] Disable the following buttons: "Upload File", "Register Samples", "Clear"
![Screen Shot 2019-12-09 at 3 07 17 PM](https://user-images.githubusercontent.com/18424138/70468727-9c1fcb00-1a95-11ea-8071-3b409313bec8.png)

3. Clinical submission: Zeplin: https://zpl.io/aX11Wqg
- [x] Show the notification banner at top
- [x] Clinical progress bar is locked
- [x] Disable the following buttons: "Upload Files", "Validate Submission", "Sign Off Submission", "Clear Submission" and "Clear" for the table
![Screen Shot 2019-12-09 at 3 09 07 PM](https://user-images.githubusercontent.com/18424138/70468898-f4ef6380-1a95-11ea-9a54-ba99faa17ee2.png)

**Comment by rosibaj** [comment]
@jaserud some very small, tiny change here pls:
![image](https://user-images.githubusercontent.com/15824252/72564364-8d3eec00-387d-11ea-9f9e-be3d70f04ee3.png)

**Comment by rosibaj** [comment]
tested on qa - this is working perfectly! thanks @jaserud !!
