### ISSUE TITLE
Display all possible file headers in table, even when  user deleted headers from file 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/platform-ui#971]
## Describe the bug

the submission preview table doesn't show all fields in the schema

## Detailed Description

Kim & Rosi requested that we should display all schema fields in the submission table.
Instead of relying on parsing the first json object in submission response, use the schema fields api because clinical no longer fill all fields automatically if the user didn't submit them in their files.

## Possible Implementation

¯\_(ツ)_/¯

## Steps To Reproduce

Steps to reproduce the behaviour:
1. submit file
2. notice not all schema fields are there.

NOTE: Related to https://github.com/icgc-argo/platform-api/issues/122

**Comment by kcullion** [comment]
@rosibaj @blabadi, Rosi and I were discussing this. We feel it's working well as is. So if a user deletes non-required field headers, their file preview will just show the headers in their file. 

@rosibaj should we close this ticket?
